### ISSUE TITLE
tp

### ISSUE THREAD

**Issue by Punky69** [uEssentials/uEssentials#10]
you could add tpall and /tpa into plugin 
tpa ignore 
tpa autoaccept nick
/v all car_id 
/spawn zombie/mega

**Comment by Punky69** [comment]
btw Aliases for jump=j
spawnvehicle=sv
respawnzombies=rz
respawnanimals=ra
autoreload ar
autorepair avr
repair rh

**Comment by Punky69** [comment]
also add custom commands and massages on server

**Comment by Punky69** [comment]
in list of commands where are 
Command	Description	Aliases	Arguments add permissions so its easyer to set them up

**Comment by leonardosnt** [comment]
I'm making a separately module for Aliases

**Comment by Mikuzzzz** [comment]
@leonardosnt Will this include interacting with other plugins? like setting /bal to do /balance?

**Comment by leonardosnt** [comment]
@PandahutMiku yes

**Comment by leonardosnt** [comment]
tpa will be add soon....

And now, you can create any aliases 38869acba2a037c712d6e2053bd18ee5c1cb4db2
