### ISSUE TITLE
Memory leak detected.

### ISSUE THREAD

**Issue by WGSRangerWolf** [uEssentials/uEssentials#100]
> Time	Description (additional details on these messages)
> 08:24:03 PM	The application has been restarted (run #4).
> 08:24:02 PM	Run Statistics: 2016/02/21 19:24:47 - 2016/02/21 20:24:00 (59.2 minutes) CPU (Avg / Max): 26% / 31% Memory (Avg / Max): 313MB / 412MB
> Warning	08:24:02 PM	AlwaysUpService has detected that the application has stopped.
> 07:24:41 PM	The application has been restarted (run #3).
> 07:24:40 PM	Run Statistics: 2016/02/21 16:17:23 - 2016/02/21 19:24:33 (3.1 hours) CPU (Avg / Max): 26% / 31% Memory (Avg / Max): 354MB / 399MB
> Warning	07:24:40 PM	AlwaysUpService has detected that the application has stopped.
> 04:17:17 PM	The application has been restarted (run #2).
> 04:17:16 PM	Run Statistics: 2016/02/21 12:30:54 - 2016/02/21 16:17:10 (3.8 hours) CPU (Avg / Max): 26% / 31% Memory (Avg / Max): 374MB / 453MB
> Warning	04:17:16 PM	AlwaysUpService has detected that the application has stopped.
> 12:30:46 PM	The application has been started.
> 12:30:35 PM	The service has started.
> 12:26:56 PM	The service has stopped.
> 12:26:56 PM	The application has been stopped.
> 12:26:55 PM	Run Statistics: 2016/02/21 10:34:31 - 2016/02/21 12:26:53 (1.9 hours) CPU (Avg / Max): 26% / 37% Memory (Avg / Max): 325MB / 365MB
> 10:34:25 AM	The application has been restarted (run #2).
> 10:34:24 AM	Run Statistics: 2016/02/21 06:47:47 - 2016/02/21 10:34:22 (3.8 hours) CPU (Avg / Max): 25% / 30% Memory (Avg / Max): 317MB / 390MB
> Warning	10:34:24 AM	AlwaysUpService has detected that the application has stopped.
> 06:47:39 AM	The application has been started.
> 06:47:27 AM	The service has started (at boot).
> 06:45:05 AM	The service has stopped.
> 06:45:05 AM	The application has been stopped.
> 06:45:03 AM	Run Statistics: 2016/02/21 03:30:17 - 2016/02/21 06:44:58 (3.2 hours) CPU (Avg / Max): 25% / 28% Memory (Avg / Max): 301MB / 341MB
> 03:30:11 AM	The application has been restarted (run #7).
> 03:30:10 AM	Run-Day Statistics: 2016/02/21 00:00:01 - 2016/02/21 03:30:05 (3.5 hours) CPU (Avg / Max): 25% / 30% Memory (Avg / Max): 337MB / 380MB
> 03:30:10 AM	Run Statistics: 2016/02/20 23:44:13 - 2016/02/21 03:30:05 (3.8 hours) CPU (Avg / Max): 25% / 30% Memory (Avg / Max): 333MB / 380MB
> Warning	03:30:10 AM	AlwaysUpService has detected that the application has stopped.
> 12:00:01 AM	Run-Day Statistics: 2016/02/20 23:44:13 - 2016/02/20 23:59:55 (15.7 minutes) CPU (Avg / Max): 23% / 26% Memory (Avg / Max): 277MB / 291MB
> 
> Saturday 02/20/16
> 
> Time	Description (additional details on these messages)
> 11:44:07 PM	The application has been restarted (run #6).
> 11:44:06 PM	Run Statistics: 2016/02/20 21:15:04 - 2016/02/20 23:44:02 (2.5 hours) CPU (Avg / Max): 25% / 39% Memory (Avg / Max): 328MB / 365MB
> Warning	11:44:06 PM	AlwaysUpService has detected that the application has stopped.
> 09:14:58 PM	The application has been restarted (run #5).
> 09:14:57 PM	Run Statistics: 2016/02/20 17:58:12 - 2016/02/20 21:14:51 (3.3 hours) CPU (Avg / Max): 26% / 31% Memory (Avg / Max): 330MB / 388MB
> Warning	09:14:57 PM	AlwaysUpService has detected that the application has stopped.
> 05:58:07 PM	The application has been restarted (run #4).
> 05:58:06 PM	Run Statistics: 2016/02/20 17:47:32 - 2016/02/20 17:58:00 (10.5 minutes) CPU (Avg / Max): 25% / 28% Memory (Avg / Max): 317MB / 327MB
> Warning	05:58:06 PM	AlwaysUpService has detected that the application has stopped.
> 05:47:26 PM	The application has been restarted (run #3).
> 05:47:25 PM	Run Statistics: 2016/02/20 15:53:59 - 2016/02/20 17:47:23 (1.9 hours) CPU (Avg / Max): 28% / 34% Memory (Avg / Max): 361MB / 399MB
> Warning	05:47:25 PM	AlwaysUpService has detected that the application has stopped.
> 03:53:53 PM	The application has been restarted (run #2).
> 03:53:52 PM	Run Statistics: 2016/02/20 12:59:00 - 2016/02/20 15:53:46 (2.9 hours) CPU (Avg / Max): 28% / 35% Memory (Avg / Max): 371MB / 420MB
> Warning	03:53:52 PM	AlwaysUpService has detected that the application has stopped.
> 12:58:52 PM	The application has been started.
> 12:58:41 PM	The service has started.
> 12:58:34 PM	The service has stopped.
> 12:58:34 PM	The application has been stopped.
> 12:58:32 PM	Run Statistics: 2016/02/20 12:54:33 - 2016/02/20 12:58:28 (3.9 minutes) CPU (Avg / Max): 17% / 24% Memory (Avg / Max): 317MB / 327MB
> 12:54:25 PM	The application has been started.
> 12:54:14 PM	The service has started.
> 12:53:34 PM	The service has stopped.
> 12:53:34 PM	The application has been stopped.
> 12:53:33 PM	Run Statistics: 2016/02/20 10:34:42 - 2016/02/20 12:53:27 (2.3 hours) CPU (Avg / Max): 28% / 34% Memory (Avg / Max): 384MB / 446MB
> 10:34:35 AM	The application has been restarted (run #2).
> 10:34:34 AM	Run Statistics: 2016/02/20 06:47:58 - 2016/02/20 10:34:28 (3.8 hours) CPU (Avg / Max): 21% / 32% Memory (Avg / Max): 360MB / 432MB
> Warning	10:34:34 AM	AlwaysUpService has detected that the application has stopped.
> 06:47:50 AM	The application has been started.
> 06:47:38 AM	The service has started (at boot).
> 06:45:04 AM	The service has stopped.
> 06:45:04 AM	The application has been stopped.
> 06:45:03 AM	Run Statistics: 2016/02/20 05:14:50 - 2016/02/20 06:45:02 (1.5 hours) CPU (Avg / Max): 13% / 21% Memory (Avg / Max): 327MB / 347MB
> 05:14:44 AM	The application has been restarted (run #5).
> 05:14:43 AM	Run Statistics: 2016/02/20 01:28:25 - 2016/02/20 05:14:37 (3.8 hours) CPU (Avg / Max): 17% / 28% Memory (Avg / Max): 356MB / 397MB
> Warning	05:14:43 AM	AlwaysUpService has detected that the application has stopped.
> 01:28:19 AM	The application has been restarted (run #4).
> 01:28:18 AM	Run-Day Statistics: 2016/02/20 00:00:04 - 2016/02/20 01:28:16 (1.5 hours) CPU (Avg / Max): 30% / 34% Memory (Avg / Max): 512MB / 534MB
> 01:28:18 AM	Run Statistics: 2016/02/19 19:29:09 - 2016/02/20 01:28:16 (6.0 hours) CPU (Avg / Max): 29% / 35% Memory (Avg / Max): 440MB / 534MB
> Warning	01:28:18 AM	AlwaysUpService has detected that the application has stopped.
> 12:00:04 AM	Run-Day Statistics: 2016/02/19 19:29:09 - 2016/02/19 23:59:58 (4.5 hours) CPU (Avg / Max): 28% / 35% Memory (Avg / Max): 416MB / 494MB

removed u essentials and its the complete opposite.
i will attach my logs to here. I am labeling this as a high priority as this has caused some issues.
I really want to continue to use this mod but by the looks of it and the direction its going I wont be able to do it until you solve it.
Ill attach my logs from what my server has logged.

**Comment by WGSRangerWolf** [comment]
Sadousku is a Plugin developer and he found the memory leak. he is currently working on a FAQ bot that will answer questions. this can be found at http://saduskobot.cf/

**Comment by leonardosnt** [comment]
What http://saduskobot.cf/ It has to do with it? And probably you are using too much /rocket reload.

**Comment by WGSRangerWolf** [comment]
I havent been using rocket reload.

**Comment by WGSRangerWolf** [comment]
Leonardosnt I think You should add a debug command for situations like this. My server host wasnt to happy about the memory leak. If you add that command. I will be happy to use it on my server for you and give you all the errors. What the debug would do is test every single command.

**Comment by leonardosnt** [comment]
What debug command should do?

**Comment by WGSRangerWolf** [comment]
Debug. It checks the code while the server is running. finds any errors and logs them to a error.log folder which can help YOU Find bugs quicker. Rocket.LOG doesnt really log stuff needed. Its more of a command we run for you to read. vise versa

**Comment by WGSRangerWolf** [comment]
I have been using /back command publicly and some people use it. If you are gunna get to the bottom of the memory leak i would be more than happy to Wing it out with memory issues for you. I run a public server. can you link me your profile Steam 64ID I made a video explaining how. I will add ya when you give me the steam 64 id

**Comment by WGSRangerWolf** [comment]
my server gets roughly around 20-29 players. And at 29 -30 somehting which the server can handle everyone loose connection. i donno what the cause of this is. But yeah

**Comment by leonardosnt** [comment]
76561198144490276

**Comment by WGSRangerWolf** [comment]
added

**Comment by leonardosnt** [comment]
Tested in my test server, he use 250~350MB without any player/plugin

is only you having this problem...?

**Comment by WGSRangerWolf** [comment]
i donno. ill go ahead and pop it back in excited about the new update tho lol
