### ISSUE TITLE
Permissions with LPX

### ISSUE THREAD

**Issue by axiomaticTwist** [uEssentials/uEssentials#102]
Recently you added support with LPX, which I was happy about. When I installed the plugin and added all the permissions onto LPX, I discovered by my staff members that none of the new permissions worked. It pops up on their end "Command_no_permission" even though I added the permissions through LPX.

**Comment by leonardosnt** [comment]
Show your permissions.

**Comment by axiomaticTwist** [comment]
![image](https://cloud.githubusercontent.com/assets/15700084/13273370/c12035a2-da57-11e5-822b-86f03f786c04.png)

Can't seem to resolve the massive amounts of color.Blue permissions but that's arbitrary.

**Comment by leonardosnt** [comment]
I'm not seeing any uEssentials permission here, you have read the wiki??

https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference

**Comment by axiomaticTwist** [comment]
I've tried it with "essentials.command.ii" and "essentials.ii" for the /iteminfo command. Anything you can say to that?

**Comment by leonardosnt** [comment]
ii is an alias of iteminfo... use essentials.command.iteminfo
