### ISSUE TITLE
/warps always says no warps are defined.

### ISSUE THREAD

**Issue by Ejraiel** [uEssentials/uEssentials#106]
There **are** warps defined; I have permissions to use them, and using them in game (like /warp space) works fine.

I have "PerWarpPermission" set to false.

I also have the following permissions in an attempt to make this work:
essentials.*
essentials.command.*
essentials.command.warp
essentials.command.warps
essentials.warp
essentials.warp.*
essentials.warp.a
essentials.warp.b
essentials.warp.c
essentials.warps
essentials.warps.*

 
 
**Versions:**
Unturned 3.14.5.0 to 3.14.6.2
Rocket 789 to 795 (4.9.2.0)
uEssentials 1.1.2.1 to 1.1.3.0

**Comment by Punky69** [comment]
try disabling command and use warps plugin for now while problem is not solved btw warps plugin supports ueconomy
