### ISSUE TITLE
essentials.warp.* permission does not work.

### ISSUE THREAD

**Issue by Ejraiel** [uEssentials/uEssentials#107]
I'm still having to add every
_essentials.warp.a_
_essentials.warp.b_
_essentials.warp.c_
etc.

"PerWarpPermission" doesn't affect this either; I've tried with it set to both true and false.

I also tried adding _essentials.warps.*_, just in case.

 
 
**Versions:**
Unturned 3.14.5.0
Rocket 789 (4.9.2.0)
uEssentials 1.1.2.1

**Comment by leonardosnt** [comment]
#94 

Fixed in 3195f40da6e8af2610bc14f6a357bcbd1038da72

Will be added in next release.
