### ISSUE TITLE
essentials.kit.* permission does not work.

### ISSUE THREAD

**Issue by Ejraiel** [uEssentials/uEssentials#108]
Still having to add
_essentials.kit.a_
_essentials.kit.b_
_essentials.kit.c_
etc.

 
 
**Versions:**
Unturned 3.14.5.0
Rocket 789 (4.9.2.0)
uEssentials 1.1.2.1

**Comment by leonardosnt** [comment]
#94 

Fixed in 3195f40da6e8af2610bc14f6a357bcbd1038da72

Will be added in next release.
