### ISSUE TITLE
Using "/clear -a" or "/clear -v" clears vehicles that players are using.

### ISSUE THREAD

**Issue by Ejraiel** [uEssentials/uEssentials#110]
Needs to ignore vehicles with players in them.

 
 
**Versions:**
Unturned 3.14.5.0 to 3.14.6.2
Rocket 792 to 795 (4.9.2.0)
uEssentials 1.1.2.1 to 1.1.3.0

**Comment by leonardosnt** [comment]
I did that way.

**Comment by Ejraiel** [comment]
No way to fix this?

Not fun as a player when you're driving or flying and your game crashes. =[

**Comment by leonardosnt** [comment]
This is not a issue, if you clear all vehicles, it will kick player that is inside, it is to prevent server crash #29

**Comment by WGSRangerWolf** [comment]
It happens on a rare occasion

**Comment by Ejraiel** [comment]
I see.

It is an issue however.

Happens all the time on my creative server -- vehicles everywhere from people spawning them -- they need to be cleared to remove lag.

And players need to be able to play, not be kicked.

So; either this command needs to ignore vehicles that have players, or a new command needs to be made that only clears vehicles with no players in them.

**Comment by Ejraiel** [comment]
That would work.

Though personally, I'd rather "/clear" and "/clear v" ignore currently used vehicles, and something like "/clearall" or "/clear av" (All Vehicles) would kick players and clear their current vehicles; since I prioritize people not being kicked over clearing *all* vehicles. =]

 
 
**Like this:**
/clear: Clear items.  Clear unused vehicles.

/clear v:  Clear unused vehicles.
/clear av:  Clear ALL vehicles, and kick players that are using them.
/clear pv:  Clear ONLY vehicles that players are using, and kick them.
/clear i:  Clear items.

/clearall:  Clear items.  Clear ALL vehicles, and kick players that are using them.

**Comment by Ejraiel** [comment]
@leonardosnt Thank you for being so attentive and considerate. =]

**Comment by leonardosnt** [comment]
no problem: D
