### ISSUE TITLE
Server broadcasting private messages.

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#114]
When a player executes /home or /tpa (types it in chat) and moves, or tries to get a kit this pops up in my chat...

![2016-02-26_00001](https://cloud.githubusercontent.com/assets/1404955/13359272/57600d6c-dcc4-11e5-88cc-0ba8bc506242.jpg)

**Comment by Daniil1288** [comment]
Does this happen to me because I'm an admin? If so, how do I disable those annoying alerts?!

**Comment by leonardosnt** [comment]
someone have the same issue?

**Comment by Daniil1288** [comment]
This was before both updates... Both the unturned one and the uEssentials one. Going to try to see if it is still present... :)

**Comment by Daniil1288** [comment]
I think you fixed it somehow in the newest version of uEssentials... Thanks :D

Issue resolved, if I encounter the problem again I'll open this issue again.
