### ISSUE TITLE
Suggestion: autoclear.

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#116]
Is there currently a way to clear all items each X seconds/minutes/hours?

If not, will you please make a module called "autoclear" that will automatically execute /clear -i -v?

**Comment by Ejraiel** [comment]
:+1:

**Comment by Daniil1288** [comment]
Thanks for the support lol :+1:

**Comment by Ejraiel** [comment]
Hehe. I actually meant to add this suggestion, but got busy and forgot. =]

**Comment by leonardosnt** [comment]
#150
