### ISSUE TITLE
Permission Restructuring

### ISSUE THREAD

**Issue by Ejraiel** [uEssentials/uEssentials#119]
**Old:**
essentials.antispam.bypass
essentials.home.bypasscooldown
essentials.kits.bypasscooldown
essentials.warps.bypasscooldown
essentials.reload

**New:**
essentials.bypass.antispam
essentials.bypass.homecooldown
essentials.bypass.kitcooldown
essentials.bypass.warpcooldown
essentials.command.reload

**Cleanliness aside, this would allow for:**
essentials.bypass.*
essentials.command.*

 
 
**Versions:**
Unturned 3.14.6.2
Rocket 795 (4.9.2.0)
uEssentials 1.1.3.0

**Comment by Daniil1288** [comment]
We should also help poor Leo with lang_en.json translation, as English isn't his primary language... (https://github.com/uEssentials/uEssentials/blob/master/default/lang_en.json). It was partially fixed by someone, but that was, like, a month ago. I am way too lazy to download git so I can only open issues, though :P

**Comment by Ejraiel** [comment]
Consider it done! ;O

**Comment by leonardosnt** [comment]
@Daniil1288 You can edit online, and send a pull request.

**Comment by Daniil1288** [comment]
@leonardosnt really? Didn't know about that :O my english isn't perfect, though... I'll try, but don't expect me to get every translation perfectly :D

**Comment by leonardosnt** [comment]
Probably is better than "my", that is 80% google translate.

**Comment by Ejraiel** [comment]
Done! =D

https://github.com/uEssentials/uEssentials/pull/123

**Comment by leonardosnt** [comment]
essentials.command.X is only for commands.

essentials.reload is to allow tu use 'reload' option, in /ess.
