### ISSUE TITLE
Possible aliases (Itemfeature + examples)

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#121]
Would like some commands and arguments shortened.

-----------
From:

/if autoreload on/off OR /if autorepair on/off

TO:

/if ar on/off OR /if ar on/off

----------------------------------------------------
same with other commands...

Example:
/respawnanimals to /ra or /resa
/respawnzombies to /rz or /resz
/killzombies to /klz (maybe /kz?)

etc. etc.

**Comment by Ejraiel** [comment]
Even cooler -- a separate config file to allow us to create our own aliases, along with an /alias command. ;D

**Comment by Daniil1288** [comment]
welllll... that'd be awesome for sure!

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/issues/10#issuecomment-183488837

**Comment by Daniil1288** [comment]
good luck, then :)

**Comment by leonardosnt** [comment]
#150
