### ISSUE TITLE
OFF-TOPIC: Someone having issue when updating unturned?

### ISSUE THREAD

**Issue by leonardosnt** [uEssentials/uEssentials#122]
I cant update my unturned. It is saying "time out" or "corrupt data"

**Comment by Ejraiel** [comment]
Not for me. =\

**Comment by leonardosnt** [comment]
Damn D: I cant work on uEssentials because of that.

**Comment by Ejraiel** [comment]
Maybe try a reinstall?

Or right click Unturned in your library and go to "Properties", "Local Files", "Verify Integrity of Game Cache"?

If you want, I could also completely wipe my install, redownload it fresh and untouched, then zip and upload it to MEGA or wherever, lol.

**Comment by leonardosnt** [comment]
I already did it, and now i deleted all content, and it happens when i try do download.
And now, i don't have unturned here, and cant download D;


I would be very grateful.

**Comment by Daniil1288** [comment]
can you please provide a screenshot? I don't promise to fix anything, I just wanna take a look... lol

**Comment by WGSRangerWolf** [comment]
LEo message me on steam

**Comment by Ejraiel** [comment]
Wish I had a faster upload speed.

It'll be ready in a minute or two.

**Comment by Ejraiel** [comment]
https://mega.nz/#!HMMCEKLD!0NPAoT1dHmtIfps1W7vFPOhx5EHWrOwlULD67BbN8XI

**Comment by leonardosnt** [comment]
@Ejraiel Thanks

**Comment by Ejraiel** [comment]
=]
