### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#128]
So, I compiled the source using VS Express for Desktop (Windows 10), optimize code checked.
This error popped up two minutes after launching the server:

[2/27/2016 9:14:15 PM] [Info] [World] The FilthyBeast [The FilthyBeast]: "&kits"
[2/27/2016 9:14:19 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.PlayerInventory.askSwapItem (CSteamID steamID, Byte page_0, Byte x_0, Byte y_0, Byte page_1, Byte x_1, Byte y_1)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.Provider.receiveServer (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel)
SDG.Unturned.Provider.listenServer (Int32 channel)
SDG.Unturned.Provider.listen ()
SDG.Unturned.Provider.Update ()

Is this related to uEssentials and/or the /kits command somehow?... Not sure...

**Comment by Daniil1288** [comment]
Yep, seems to be the case here...

[2/27/2016 9:21:48 PM] [Info] [World] ConnectTvojTatko [Horčica Corben]: "/kits"
[2/27/2016 9:21:51 PM] [Info] [World] ConnectTvojTatko [Horčica Corben]: "/kit s tart"
[2/27/2016 9:21:53 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.PlayerInventory.askDragItem (CSteamID steamID, Byte page_0, Byte x_0, Byte y_0, Byte page_1, Byte x_1, Byte y_1)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.Provider.receiveServer (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel)
SDG.Unturned.Provider.listenServer (Int32 channel)
SDG.Unturned.Provider.listen ()
SDG.Unturned.Provider.Update ()

[2/27/2016 9:21:54 PM] [Info] [World] ConnectTvojTatko [Horčica Corben]: "/kit start"
[2/27/2016 9:21:56 PM] [Info] [World] ConnectTvojTatko [Horčica Corben]: "/kit map"
[2/27/2016 9:21:56 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.PlayerInventory.askSwapItem (CSteamID steamID, Byte page_0, Byte x_0, Byte y_0, Byte page_1, Byte x_1, Byte y_1)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.Provider.receiveServer (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel)
SDG.Unturned.Provider.listenServer (Int32 channel)
SDG.Unturned.Provider.listen ()
SDG.Unturned.Provider.Update ()

**Comment by Daniil1288** [comment]
got it, thank you

who needs to fix that bug, though? should I contact Nelson?

**Comment by leonardosnt** [comment]
"Is this related to uEssentials and/or the /kits command somehow?."

Nop

**Comment by Daniil1288** [comment]
lol... now I'm getting a console spam of AsncTCPSocket created, AsncTCPSocket destroyed and giant TPS drops (from 999 to 40-200)

![lolwutunturned](https://cloud.githubusercontent.com/assets/1404955/13374793/beb9c24c-dd9f-11e5-9bc4-f41efd1ebf82.png)

**Comment by Daniil1288** [comment]
any ideas would be appreciated :D

**Comment by Ejraiel** [comment]
@_@

I get chunks of those STEAMPS3 packets too, but not a huge spam like that...

**Comment by Daniil1288** [comment]
yeah, I THINK he has a bug tracker... going to try and find that

**Comment by Daniil1288** [comment]
two minutes ago my tps dropped to 3 and I couldn't even type in console... it recovered now, but only 28-150 tps, welp

**Comment by WGSRangerWolf** [comment]
Lmao. my server suffers from this when the server has to many people on there causing ping 650 :laughing: so what i do is just restart it
