### ISSUE TITLE
Suggestion: make /i support spaces

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#129]
Say, I want to spawn in a Military Nightvision.
If I execute /i nightvision, it gives me a civilian nightvision
If I try to execute /i military nightvision or /i military_nightvision - it doesn't work (No such player as nightvision or no such ID military_nightvision)

**Comment by visloom28vi** [comment]
type /i "military nightvision" (ammount)
 if it has spaces add "" around the word

**Comment by Daniil1288** [comment]
thanks! :)

**Comment by Daniil1288** [comment]
you should probably add that to the wiki, though, as I wasn't aware of that =)
