### ISSUE TITLE
command doesnt work

### ISSUE THREAD

**Issue by linyuzhe210** [uEssentials/uEssentials#13]
hey commands dont work on my default group even i input for example essential.command.back default group wiil get command_no permission.what do i wrong?please reply me soon .thx XD
(my english isnt very well please ignore it)

**Comment by leonardosnt** [comment]
The correct permission is essentials.command.<command_name> not essentials.<command_name>

**Comment by linyuzhe210** [comment]
ahhh..........are you sure？-。-it still doesnt work when i input essentials.command.back，im sure i restart the server.pleaseeeeeeeee help me i really love your plugin

**Comment by leonardosnt** [comment]
I will check

**Comment by leonardosnt** [comment]
Rocket broke my plugin again... i will fix it.

**Comment by odyss3y** [comment]
using essentials.command doesnt work, but using just the command does. i think this problem might be effecting kits as well. i cannot get kits to list using any option i can think of.

**Comment by leonardosnt** [comment]
@odyss3y When Rocket 'command system' was changed he's broke my 'command system'

**Comment by leonardosnt** [comment]
Rocket is an shit, freaky do not know maintain an api, every time that he update. all plugins break.

I will not fix it now, use just the name of command.

**Comment by odyss3y** [comment]
yeah im noticing a pattern. my users are frustrated that every update pretty much breaks most plugins and then we have to wait for updates. i appreciate your efforts leonardo. this is a great plugin and ive already switched over most of what i can to it.

**Comment by leonardosnt** [comment]
Fixed, i will upload new release soon.
