### ISSUE TITLE
Suggestion: admins can open locked doors

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#131]
I have a server but can't open doors placed by other players. Can I open them anyhow?...

**Comment by Ejraiel** [comment]
:+1:

**Comment by visloom28vi** [comment]
idk, but if this was somehow added that would be nice

**Comment by WGSRangerWolf** [comment]
Would love this! :+1:

**Comment by Daniil1288** [comment]
Fixed by using a plugin called Inspector from here: [https://imperialplugins.com/Products/ProductDetails?ProductID=26](url)

...only took me around two years :)
