### ISSUE TITLE
REQUEST: ENHANCEMENT OF /item command!

### ISSUE THREAD

**Issue by WGSRangerWolf** [uEssentials/uEssentials#132]
Can you have item command configurable to limit to what people can spawn in Lets say if someone wants to do /i all pizza 100   and everyone gets 100 pizzas, can we set a limit to what they can spawn in like /i pizza 10 and they can spawn 10 pizzas but no more than 10 if they do /i pizza 15 it wouldn't give them it. this would help reduce Item overflow on servers which makes the server crash.

and add a function where item all can be disabled. Thank ye

**Comment by Ejraiel** [comment]
:+1:

Great idea; people often spawn way too many items at once.

**Comment by Punky69** [comment]
just use command chatrate in server config and put like 3 sec they would not be abble to spam commands and its enugh to chat with people

**Comment by WGSRangerWolf** [comment]
@Punky69  So your telling me that doing chatrate 3 /i all pizza 200 will stop the overflow of pizzas?

**Comment by WGSRangerWolf** [comment]
This suggestion is primary based on how many pizzas a person can spawn while executing the command. Rocketmod has a command cool down..................

**Comment by WGSRangerWolf** [comment]
how do i configure it? @leonardosnt

**Comment by leonardosnt** [comment]
Config >> "ItemSpawnLimit": 10

**Comment by WGSRangerWolf** [comment]
@leonardosnt Can this be applied to administrators that are on the server aswell?
i have some administrators that like to get well "Drunk" and play and spawn alot of shit

**Comment by leonardosnt** [comment]
@WGSRangerWolf It is applied to everyone that dont have the ```essentials.bypass.itemlimit``` permission
