### ISSUE TITLE
Vanish Mode Unity error

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#134]
[2/29/2016 2:24:42 PM] [Error] NullReferenceException - UnityEngine.Component.GetComponent[UnturnedPlayerFeatures] ()
Rocket.Unturned.Player.UnturnedPlayer.get_VanishMode ()
Rocket.Unturned.Player.UnturnedPlayer.Teleport (Vector3 position, Single rotation)
Essentials.Api.Unturned.UPlayer.Teleport (Vector3 pos, Single rotation)
Essentials.Commands.CommandHome+<>c__DisplayClass2_1.<OnExecute>b__0 (Essentials.Api.Task.Task t)
Essentials.Api.Task.Tasks.FixedUpdate ()

[2/29/2016 2:24:42 PM] [Error] NullReferenceException - UnityEngine.Component.GetComponent[UnturnedPlayerFeatures] ()
Rocket.Unturned.Player.UnturnedPlayer.get_VanishMode ()
Rocket.Unturned.Player.UnturnedPlayer.Teleport (Vector3 position, Single rotation)
Essentials.Api.Unturned.UPlayer.Teleport (Vector3 pos, Single rotation)
Essentials.Commands.CommandHome+<>c__DisplayClass2_1.<OnExecute>b__0 (Essentials.Api.Task.Task t)
Essentials.Api.Task.Tasks.FixedUpdate ()

**Comment by Daniil1288** [comment]
This error appeared 3000+ times in the last 5h of my server running. Help?

**Comment by Daniil1288** [comment]
To prove that this is actually being spammed:

![uessentials_vanish](https://cloud.githubusercontent.com/assets/1404955/13402640/4333b8ec-df22-11e5-818e-0ec0f24610f4.png)

**Comment by Daniil1288** [comment]
What happened before the spam: (p0n4ik is an admin, he probably was in vanish)
[2/29/2016 6:52:24 PM] [Info] [World] p0n4ik [p0n4ik]: "/tp ira"
[2/29/2016 6:52:28 PM] [Error] NullReferenceException - UnityEngine.Component.GetComponent[UnturnedPlayerFeatures] ()
Rocket.Unturned.Player.UnturnedPlayer.get_VanishMode ()
Rocket.Unturned.Player.UnturnedPlayer.Teleport (Vector3 position, Single rotation)
Essentials.Api.Unturned.UPlayer.Teleport (Vector3 pos, Single rotation)
Essentials.Commands.CommandHome+<>c__DisplayClass2_1.<OnExecute>b__0 (Essentials.Api.Task.Task t)
Essentials.Api.Task.Tasks.FixedUpdate ()

**Comment by WGSRangerWolf** [comment]
This is due to more of a rocket issue.




*Have a amazing day,*

*Derrick McLean* (formaly known as waspgod, Rangerwolf)

**Comment by Daniil1288** [comment]
what can I do about it, though? it's making my server lag :(
@WGSRangerWolf

**Comment by WGSRangerWolf** [comment]
Have  you been doing /vanish recently?
