### ISSUE TITLE
Spy Mode

### ISSUE THREAD

**Issue by Gigavoltz** [uEssentials/uEssentials#137]
Can you please explain what spy mode does?

**Comment by leonardosnt** [comment]
""
There’s and answer higher – when you are in “spy” mode, you can see other’s tells
Ex: player A tells (command /tell) player B: admin is a sh*t.
Spy off – you see nothing
Spy on – you see (A to B): Admin is a sh*t.
""

~ NoAdo

**Comment by Gigavoltz** [comment]
Thank you!

**Comment by leonardosnt** [comment]
No problems :D

If you like this project do not forget to leave your star :D

**Comment by Daniil1288** [comment]
A random suggestion!

Can you make so that when /spy is on, I can see everything that other people are doing, just like in the console? (for example, I don't just see /tell, but also /home /kit start /warp /kits; etc.)

**Comment by Gigavoltz** [comment]
owners can see all that in console

**Comment by Daniil1288** [comment]
yeah, but for debug reasons I'd like to see that in my chat, too... It wouldn't be too hard to implement, so I could at least know that when people say "/kit <kit_name> doesn't work!!" they actually typed in /kit <kit_name> and not /kits <kit_name>.
