### ISSUE TITLE
kits.json Autocomplete Error (please disable autocomplete, or make it a Config option!)

### ISSUE THREAD

**Issue by Ejraiel** [uEssentials/uEssentials#138]
When an item in kits.json has no "Durability" entry, the server creates one.

When it creates that entry, it makes the durability 0 instead of 100.

**Before:** _(What I personally put in the file, by hand.)_
 {
  "Name": "Dragon",
  "Cooldown": 0,
  "ResetCooldownWhenDie": true,
  "Items": [
   {"Id": 132,
    "FireMode": "AUTO",
    "Barrel": {"AttachmentId": 7},
    "Tactical": {"AttachmentId": 151},
    "Grip": {"AttachmentId": 8},
    "Sight": {"AttachmentId": 118},
    "Magazine": {"AttachmentId": 133},
    "Ammo": 100,
   },
  ],
 },

**After:** _(What the server changed the file to, probably when "/kit dragon" was used.)_
 {
  "Name": "Dragon",
  "Items": [
   {
    "FireMode": "AUTO",
    "Ammo": 100,
    "Barrel": {
     "AttachmentId": 7,
     "Durability": 0
    },
    "Sight": {
     "AttachmentId": 118,
     "Durability": 0
    },
    "Grip": {
     "AttachmentId": 8,
     "Durability": 0
    },
    "Tactical": {
     "AttachmentId": 151,
     "Durability": 0
    },
    "Magazine": {
     "AttachmentId": 133,
     "Durability": 0
    },
    "Id": 132,
    "Durability": 100,
    "Amount": 1
   }
  ],
  "Cooldown": 0,
  "ResetCooldownWhenDie": true
 },

It would be nice if the server didn't edit previous entries at all -- I like my kits more human readable, and not filled with extra entries that aren't needed.

**Please disable this autocomplete, or add a Config option to disable it.**

 
 
_Versions:_
Unturned 3.14.6.2
Rocket 795 (4.9.2.0)
uEssentials 1.1.4.0

**Comment by leonardosnt** [comment]
I will It's done by JsonSerializer and i will not rewrite it.

**Comment by leonardosnt** [comment]
Use /createkit and /editkit (will be added)

**Comment by Ejraiel** [comment]
Any way to change it's default of 0 Durability to 100 Durability?

I've been saving my original file (kits[Ej].json) and copy/pasting onto the used one (kits.json) so I have my human readable kits for easy editing.

So it doesn't matter too much that it expands my kits with extra lines, but I don't like it setting all Durability to 0.
