### ISSUE TITLE
Ammo and magazine

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [uEssentials/uEssentials#14]
Faced with such a question in the whales ammunition and stores specified not only the number but somehow the number of rounds that is in them. For example in 4 stores only 4 rounds...since when you spawn all the magazines were full?

**Comment by leonardosnt** [comment]
Sorry but I not understand your question.

**Comment by ZSHADOWWOLF** [comment]
I make 4 zubekanov magazine (In kit)...rounds 4 all magazines. Need 35 (Full) How make it?

**Comment by leonardosnt** [comment]
Can you send me your kits file?

**Comment by ZSHADOWWOLF** [comment]
I need Full Magazines in kits...You Understand?

**Comment by leonardosnt** [comment]
Yes, but i'm busy now.

**Comment by Punky69** [comment]
add me on steam i will help you

**Comment by Punky69** [comment]
{
        "Id": 6,
        "Durability": 100,
        "Amount": 1
      }
 military magazine should be full

**Comment by leonardosnt** [comment]
I think i understand...

You are talking about that?

![](http://i.imgur.com/9xliAAK.png)

**Comment by ZSHADOWWOLF** [comment]
Yes this is Round. need fully Magazine

**Comment by leonardosnt** [comment]
I "fixed" it.

Now, to set Magazine "size" use "Ammo".

Example:

```json
  {
    "Id": 17,
    "Durability": 100,
    "Amount": 1,
    "Ammo": 99
  }
``` 

You will receive an Military Drum (17) with 99 "bullets".
