### ISSUE TITLE
Commands with "player|all" should be split into "command" and "commandall".

### ISSUE THREAD

**Issue by Ejraiel** [uEssentials/uEssentials#141]
As is, if a player is named "all", attempts to use those commands on the player will cause it to apply to all players instead of that one player.

**Comment by Daniil1288** [comment]
yeah, I noticed that, too... Would be really nice if Leo implemented such a thing

**Comment by leonardosnt** [comment]
Which commands?

**Comment by Daniil1288** [comment]
any command that has both "player" and "all" defined

taken from wiki:

freeze	Freeze an player/all	None	[player/all]
unfreeze	Unfreeze an player/all	None	[player/*]
item	None	i	[item] <amount> or [player|all] [item] [amount] (!!! that's probably the one that Ejraiel was talking about)

**Comment by Daniil1288** [comment]
basically, create commands called:
/unfreezeall
/freezeall
/itemall

already done:
/tpall
/kickall

**Comment by leonardosnt** [comment]
:+1:

**Comment by leonardosnt** [comment]
I will change "all" to "*" !!

**Comment by Daniil1288** [comment]
Nice! :+1:
