### ISSUE TITLE
Item spawning error with the new items.

### ISSUE THREAD

**Issue by persiafighter** [uEssentials/uEssentials#144]
So I tried spawning in the handcuffs with `/i handcuffs` and with `/i 1195` but I get the following error:

[Image because i'm too lazy to copy all the logs](http://i.imgur.com/Mk8wQLY.png)

**Comment by persiafighter** [comment]
@leonardosnt 
Just noticed right now, sorry for making this request without checking before.

**Comment by leonardosnt** [comment]
Use uEssentials /item, he is working fine http://prntscr.com/ab8qpk
