### ISSUE TITLE
Handcuff command? maybe ?!?!?

### ISSUE THREAD

**Issue by leonardosnt** [uEssentials/uEssentials#145]

**Comment by Daniil1288** [comment]
YES.

**Comment by leonardosnt** [comment]
:D

**Comment by Daniil1288** [comment]
xD :+1:

**Comment by ZSHADOWWOLF** [comment]
Yes admin command...add please! XDDDD

**Comment by WGSRangerWolf** [comment]
lol

**Comment by Ejraiel** [comment]
this made me laugh.

so did the thought of using /handcuffall.

**Comment by Ejraiel** [comment]
only thing is you'd have to force them to unequip weapons/tools...

not sure you could do that without a clientside mod?

**Comment by leonardosnt** [comment]
@Ejraiel i haven't found yet, i need to search more, but i have no time.

**Comment by Ejraiel** [comment]
=\
