### ISSUE TITLE
/tpa command

### ISSUE THREAD

**Issue by DrMasik** [uEssentials/uEssentials#146]
Is it possible to add /tpa <player_name> command?

**Comment by leonardosnt** [comment]
:+1:

**Comment by Daniil1288** [comment]
oh wow that escalated quickly xD

maybe I finally stop using Rocketmod_TPA which throws a bunch of errors and is outdated then?...

Leo do it pls =D

**Comment by WGSRangerWolf** [comment]
recently was updated
