### ISSUE TITLE
Writing /i "metal door" gives a metal doorframe

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#148]
You should probably make it so when we use /i "some item" it gives us exactly the item specified (in this case, "some item") and not "some itemsomething"

OR you could just do this:
IF /i "metal_door" = give metal door
if /i "metal door" = give metal doorframe

**Comment by Daniil1288** [comment]
why, thank you! :D :+1:

**Comment by leonardosnt** [comment]
Fixed, thanks for reporting it  :D

**Comment by leonardosnt** [comment]
@Daniil1288  :D
