### ISSUE TITLE
Config Documentation?

### ISSUE THREAD

**Issue by WGSRangerWolf** [uEssentials/uEssentials#15]
Can we have a Config Documentation please explaining how to edit properly.
Thanks.

**Comment by leonardosnt** [comment]
I will add soon...

If you dont know what the "property" do, say here and i will explain.

**Comment by waspkiller** [comment]
What does the disable command do? cause i am trying to disable some commands that is conflicting with a couple of my addons that is working

**Comment by leonardosnt** [comment]
He disable an command of this plugin.

Example:
```json
"DisabledCommands": [
    "kit",
    "kits",
    "and so on..."
]
```

**Comment by waspkiller** [comment]
Thanks!. trying to transistion to a plugin that is updated regularly.

**Comment by waspkiller** [comment]
Should update the commands refrence with the two new commands
/itemfeatures and /vehiclefeatures

**Comment by waspkiller** [comment]
How does updater work exaclty in the config

**Comment by leonardosnt** [comment]
@waspkiller If 'CheckUpdates' is false it will not check updates. If 'DownloadLatest' is false it will not download the [latest release](https://github.com/uEssentials/uEssentials/releases/tag/1.0.6.4) '-'

**Comment by waspkiller** [comment]
I made those true How do i make it update automatically then is there like a autoupdate command. or check?
if you add that command it would be awsome. if not and their is a command about  how do i reload the rocket

**Comment by leonardosnt** [comment]
It will check when plugin load.

**Comment by waspkiller** [comment]
Will /rocket reload mess it up?

**Comment by waspkiller** [comment]
Yep /rocket reload messes the plugin up
can you add a /version command?

**Comment by leonardosnt** [comment]
Yes, its hard to explain, /rocket reload doesn't reload assembly data...

Will need to replace manually.

**Comment by leonardosnt** [comment]
@waspkiller /ess info

**Comment by waspkiller** [comment]
Didnt know that then. Cause when i do /ess it shows me command etc etc

**Comment by waspkiller** [comment]
so if i restart my server the plugin will self update?

**Comment by leonardosnt** [comment]
@waspkiller "```Use /ess <commands/help/info/reload>```"

Nop, it will download latest version and will "put" in "updates/" folder.

I think that i will add an option for this.

**Comment by waspkiller** [comment]
Yeah that would be nice and convenient. im using your plugin and will plan on deleting plugins when i switch soley to your plugin cause My current rocketmod Setip is way to much plugins and downloads. If theres a way to Combine Feast mod into the essentials that would be GREAT! waiting on join/leave messsages and ill remove the Current join/leave messages that is On the Server for this.

**Comment by waspkiller** [comment]
when you add the /ckit command i will get rid of kits aswell :smile:

**Comment by WGSRangerWolf** [comment]
Closing as this isnt an issue nomore
