### ISSUE TITLE
Update wiki (Permissions)

### ISSUE THREAD

**Issue by leonardosnt** [uEssentials/uEssentials#152]
Old:
essentials.antispam.bypass
essentials.home.bypasscooldown
essentials.kits.bypasscooldown
essentials.warps.bypasscooldown

New:
essentials.bypass.antispam
essentials.bypass.homecooldown
essentials.bypass.kitcooldown
essentials.bypass.warpcooldown

#119

**Comment by WGSRangerWolf** [comment]
Closing as i have completed it.

**Comment by leonardosnt** [comment]
Thaanks :D
