### ISSUE TITLE
Poll doesn't display how many votes it got after it ended

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#155]
Basically this

![unturned_poll_broken](https://cloud.githubusercontent.com/assets/1404955/13549888/53469738-e321-11e5-9b0f-9b077337af72.png)

**Comment by WGSRangerWolf** [comment]
#72 Fixed

**Comment by Daniil1288** [comment]
is it really? don't see a commit there

**Comment by leonardosnt** [comment]
@WGSRangerWolf I just let the newest
