### ISSUE TITLE
leonardosnt steam broke again -_-

### ISSUE THREAD

**Issue by leonardosnt** [uEssentials/uEssentials#156]
For some reason my steam isnt updating, he say that i not connected with internet... this is happening after windows was updated...

I can't work on Essentials now ;(

**Comment by Daniil1288** [comment]
what windows are you using now

**Comment by leonardosnt** [comment]
10

**Comment by WGSRangerWolf** [comment]
post msconfig and dxdiag? and damnit leopnardosnt Stop running into fucking issues :P

**Comment by leonardosnt** [comment]
:laughing: 

msconfig?

dxdiag: http://prntscr.com/abp6wk ?

**Comment by WGSRangerWolf** [comment]
the only way i can think this will solve your issue is. a steam data is corrupted 2 Knowing microsoft dotnet and etc could be messed up. Try resetting your Spartan or whatever u call that shit browser that they use. If that doesn't work, Uninstall and reinstall steam

**Comment by WGSRangerWolf** [comment]
Oh lord i cant speak your language :cry:

**Comment by leonardosnt** [comment]
I already uninstalled steam, but now i cant reinstall '-'

Stea Log: http://pastebin.com/raw/xeeSbXqq

**Comment by WGSRangerWolf** [comment]
were you on windows 7 and upgraded to win 10?

**Comment by WGSRangerWolf** [comment]
try deleting manafest file located in C: \ Program Files (x86) \ Steam \ package \ steam_client_win32.installed

**Comment by leonardosnt** [comment]
Nop, the system just updated.

**Comment by leonardosnt** [comment]
Already did that.... i'll try again...

**Comment by WGSRangerWolf** [comment]
How many times did u uninstall it?

**Comment by leonardosnt** [comment]
Steam?

**Comment by WGSRangerWolf** [comment]
Yeah steam. how many

**Comment by leonardosnt** [comment]
http://pastebin.com/raw/NiQNsgVp

**Comment by leonardosnt** [comment]
idk, 5 !?!

**Comment by leonardosnt** [comment]
I think that is my wireless adapter ;( i'm not sure.

**Comment by WGSRangerWolf** [comment]
Hmmm this is a LONGSHOT but maybe just maybe.
http://download.cnet.com/IObit-Uninstaller/3000-2096_4-75161625.html?part=dl-&subj=dl&tag=button
Download this and install it to your desktop.
Uninstall using THE PROGRAM, and hit power scan delete what it says.

**Comment by WGSRangerWolf** [comment]
It appears the steam install is corrupted

**Comment by WGSRangerWolf** [comment]
Delete your installer for steam after you have done it.

**Comment by WGSRangerWolf** [comment]
Then re-download the package and reinstall. Then THINGS SHOULD BE OK

**Comment by leonardosnt** [comment]
I already did that also.

Im having issues with ssl when using google chrome...

**Comment by WGSRangerWolf** [comment]
www.firefox.com
install
try again
if google chrome is giving issues You might want to reset the browser
Remove google chrome as default browser. Weird but yeah

**Comment by leonardosnt** [comment]
Deleted installer, downloaded, installed.

3 hours trying a lot of things and nothing D:

**Comment by leonardosnt** [comment]
Nop, it happens with other browsers.

**Comment by leonardosnt** [comment]
damn ;(

**Comment by WGSRangerWolf** [comment]
this is crazy

**Comment by WGSRangerWolf** [comment]
Reset spartan?

**Comment by leonardosnt** [comment]
:laughing: Yeh :c

**Comment by leonardosnt** [comment]
spartan? browser?

**Comment by WGSRangerWolf** [comment]
Yeah internet explorer

**Comment by WGSRangerWolf** [comment]
There's a way i can look at your desktop and see what is really going on in there.
DId you update your drivers lately?

**Comment by leonardosnt** [comment]
I dont use '-'

The main problem is not with browser, is with steam updater...

**Comment by WGSRangerWolf** [comment]
@leonardosnt if u want me to i can download SteamSetup check for digital signature. And upload it to my mega.

**Comment by leonardosnt** [comment]
it would be great.

you are helping me too, thanks.

i will watch an movie now, i'm too tired, +3 hours trying to fix it and nothing...

thank you <3

**Comment by leonardosnt** [comment]
i'm too slow replying.

**Comment by leonardosnt** [comment]
i'm too slow replying.

**Comment by leonardosnt** [comment]
:laughing:

**Comment by leonardosnt** [comment]
sorry for "stealing" your time.

**Comment by WGSRangerWolf** [comment]
its ok
https://mega.nz/#!BYhjGCoY!sNyi6ZO81xYLV0fQ4vktu9lqb1VYPHbBcOGOnwoehg4

**Comment by leonardosnt** [comment]
The problem is when install, it install with no problems, but it cant download "steam" content.

My steam folder have only the Steam.exe and other things, he cannot donwload steam data.

**Comment by WGSRangerWolf** [comment]
Are u using any free firewall stuff? have u checked for viruses?

**Comment by leonardosnt** [comment]
Yes, i disabled the firewall, and .... nothing...

**Comment by WGSRangerWolf** [comment]
Uninstall with iorbit uninstaller.
Use the setup i given you. 
Fresh clean uninstall can fix alot of problems
Download and install ccleaner Run the registry and clean junk issue.

**Comment by leonardosnt** [comment]
the problem isnt with the installer '-'

**Comment by leonardosnt** [comment]
i already used cclear to do that.

**Comment by WGSRangerWolf** [comment]
Hmm very intresting

**Comment by WGSRangerWolf** [comment]
post a screeenshot of the current steam dir

**Comment by leonardosnt** [comment]
http://prntscr.com/abpl7z

**Comment by leonardosnt** [comment]
I'll eat now, and watch an movie ;\

Sorry for "stealing" your time. Thanks very much!!!!

**Comment by WGSRangerWolf** [comment]
lol i helped ya the bets i could.

**Comment by leonardosnt** [comment]
@WGSRangerWolf Yes, i know '-', i said thanks '-' <3

**Comment by JustOneMoreBlock** [comment]
https://support.steampowered.com/kb_article.php?ref=7549-MURQ-4431

or

https://forum.teksyndicate.com/t/steam-fatal-error-fixed/91783/12

or possibly:
https://forum.teksyndicate.com/t/steam-fatal-error-fixed/91783/34

or
http://steamcommunity.com/discussions/forum/1/492378265883796219/
"Problem is BT DNS blocking steam update, use google DNS 8.8.8.8"

Basically, you can either try and disable all your network adapters and then re-enable them. This will release and renew.

If that doesn't work you can try and disable IPv6 on your network adapters.

Do you have any VPNs or Proxies running as this can be an issue.

The last one would be try and change your DNS to Google DNS.

**Comment by leonardosnt** [comment]
Nothing

Nothing

Nothing

Nothing

Already tried that, i changed dns to 8.8.8.8, 8.8.4.4 and nothing...

Nothing

Nothing

No, i don't use proxy/vpn

And nothing :\


Thanks for trying D:


I think that it is an problem with my OS or my wireless adapter, because i having a lot of issues with another softwares/games.

**Comment by WGSRangerWolf** [comment]
System restore

**Comment by Daniil1288** [comment]
full windows reinstall pls.

**Comment by leonardosnt** [comment]
I will buy a "internet cable" tomorrow, i hope it works...if not, i'll reinstall windows

**Comment by Daniil1288** [comment]
well, if nothing else - just install teamviewer and ask someone else to provide access to their machine so you can continue working on your plugin on your friend's computer.

**Comment by leonardosnt** [comment]
I can work, but i cannot test that i did because i don't have unturned.

**Comment by WGSRangerWolf** [comment]
Leo i can test your unstable builds

**Comment by WGSRangerWolf** [comment]
i can upload my test server to mega for you

**Comment by leonardosnt** [comment]
Thanks, if i need i talk to you.

**Comment by leonardosnt** [comment]
Finalllyyyyyyyyy!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

http://answers.microsoft.com/en-us/windows/forum/windows_10-networking/ssl-certificate-errors-in-windows-10-browsers/3a495009-5c0c-4ecf-bb49-75de9c531237?auth=1

**Comment by Daniil1288** [comment]
nice :D

**Comment by leonardosnt** [comment]
Damn, now i cant download unturned again #122 T.T, i need to format my pc

**Comment by Daniil1288** [comment]
yeah, you should probably do it. the faster the better :+1:

**Comment by leonardosnt** [comment]
:laughing: :+1:

**Comment by leonardosnt** [comment]
@Daniil1288 Can you upload unturned again? I cannot download he :C

**Comment by WGSRangerWolf** [comment]
ill upload it

**Comment by WGSRangerWolf** [comment]
Uploading now Will add link

**Comment by WGSRangerWolf** [comment]
https://mega.nz/#!FFJGnaDK!j-f_q_oxCmv05QQ8EyvIKyFXLOw9xvphqlLK1B4ExO4

**Comment by leonardosnt** [comment]
Thaanks :D

**Comment by leonardosnt** [comment]
@WGSRangerWolf Can you send me latest unturned? Thanks.

**Comment by WGSRangerWolf** [comment]
Sure bud lol

**Comment by WGSRangerWolf** [comment]
@leonardosnt https://mega.nz/#!4VgkCbCJ!FPv6VSXVI-SqhyNENoq2qZ5ztcn7Brgzo5YXeuIl5Oo

**Comment by leonardosnt** [comment]
Thankss :D
