### ISSUE TITLE
Join/leave messages

### ISSUE THREAD

**Issue by waspkiller** [uEssentials/uEssentials#16]
Could we have this integrated with this or no?

**Comment by leonardosnt** [comment]
I had already added it, but i think i removed, i will add again soon :D

**Comment by waspkiller** [comment]
:dancer:

**Comment by waspkiller** [comment]
if i had the option to Give 10 stars in one time i seriously would yay one less program i gotta worrie about

**Comment by leonardosnt** [comment]
:laughing: 

Thanks
