### ISSUE TITLE
how would I disable a certain cmd like spawning items?

### ISSUE THREAD

**Issue by ServerOne** [uEssentials/uEssentials#165]
I'm trying to disable the spawning item cmd what would i put to disable this so i'm left with the rocket spawning cmd, please help thnx :+1:

**Comment by WGSRangerWolf** [comment]
```
"DisabledCommands": [
		"tpall",
		"kill",
		"boom"
	]
```
validate with www.jasonlint.com

**Comment by WGSRangerWolf** [comment]
well thats what i did for mine. You edit it in config.json

**Comment by WGSRangerWolf** [comment]
Close this when you fixed it
