### ISSUE TITLE
/god doesn't always work :( Can you please enhance it?

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#166]
Players keep killing me and my friends when:

1) We execute /god
2) We leave the server
3) We join the server
4) Players kill us (even if we type /god another time, it just won't work)

Suggestion: maybe let's improve /god and make it an uEssentials command?...

**Comment by Ejraiel** [comment]
See #178 =D

**Comment by Daniil1288** [comment]
@Ejraiel yuup, that's pretty much what I wanted to say :D

**Comment by WGSRangerWolf** [comment]
mentioned in a different topic closing this. 
#178
