### ISSUE TITLE
Implement: "Player was kicked for..." and "Player was banned for ... seconds for ..."

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#167]
I want my players to know if a cheater got banned, so it doesn't just say:

"Cheater has left the game"

but rather:

"Cheater was banned for 600 seconds for cheating" or "Cheater was permabanned"

Basically, I want this: "<nickname> was banned for <seconds> seconds/permabanned for <reason>"

**Comment by WGSRangerWolf** [comment]
Would have to have a Cheat detection method too but that would be too much on leo Adding it as a suggestion but im not saying this will happen

**Comment by Daniil1288** [comment]
nonononono, I'm not implying that I want an anticheat system implemented!

Currently, if I execute /ban <name>/<reason>/<duration> the command outputs "<name> has left the game" and I want that changed to "<name> was banned for <duration> seconds for <reason>" or "<name> was permabanned for <reason>" if I haven't specified the <duration>.

I think that that'd be a nice enhancement!

**Comment by Ejraiel** [comment]
Basically saying in chat when someone is kicked / banned that they were kicked / banned, rather than just left the game, with optional reason / info.

:+1:

**Comment by leonardosnt** [comment]
I will need add a new ban system...

**Comment by leonardosnt** [comment]
Wrong button...

**Comment by WGSRangerWolf** [comment]
Damn u leonard

**Comment by leonardosnt** [comment]
?

**Comment by leonardosnt** [comment]
#182
