### ISSUE TITLE
warp data

### ISSUE THREAD

**Issue by WGSRangerWolf** [uEssentials/uEssentials#168]
> ystem.ArgumentException: An element with the same key already exists in the dictionary.
>   at System.Collections.Generic.Dictionary`2[System.String,Essentials.InternalModules.Warp.Warp].Add (System.String key, Essentials.InternalModules.Warp.Warp value) [0x00000] in <filename unknown>:0
>   at Essentials.InternalModules.Warp.Data.WarpData+<>c__DisplayClass3_0.<Load>b__0 (Essentials.InternalModules.Warp.Warp kit) [0x00000] in <filename unknown>:0
>   at System.Collections.Generic.List`1[Essentials.InternalModules.Warp.Warp].ForEach (System.Action`1 action) [0x00000] in <filename unknown>:0
>   at Essentials.InternalModules.Warp.Data.WarpData.Load () [0x00000] in <filename unknown>:0
>   at Essentials.InternalModules.Warp.WarpManager.Load () [0x00000] in <filename unknown>:0
>   at Essentials.InternalModules.Warp.WarpModule.OnLoad () [0x00000] in <filename unknown>:0
>   at Essentials.Api.Module.EssModule.Load () [0x00000] in <filename unknown>:0
>   at Essentials.Api.Module.ModuleManager.LoadModule (Essentials.Api.Module.EssModule module) [0x00000] in <filename unknown>:0
>   at Essentials.Core.EssCore.<Load>b__51_9 (System.Type type) [0x00000] in <filename unknown>:0
>   at Essentials.Common.Extensions.ForEach[Type] (IEnumerable`1 enume, System.Action`1 act) [0x00000] in <filename unknown>:0
>   at Essentials.Core.EssCore.Load () [0x00000] in <filename unknown>:0
>   at Rocket.Core.Plugins.RocketPlugin.LoadPlugin () [0x00000] in <filename unknown>:0
>

**Comment by leonardosnt** [comment]
Probably you has modified this file manually...

**Comment by WGSRangerWolf** [comment]
nah that isn't it. /setwarp at certain areas and time causes issues.

**Comment by leonardosnt** [comment]
I will try to reproduce.
