### ISSUE TITLE
Ia ser legal com isso!

### ISSUE THREAD

**Issue by qwexvf** [uEssentials/uEssentials#169]
Ola. eu queria un système com IP Log come nome e steamid ia ser muto utio.

Poderia ser com mysql ou .txt alguma coisa!

**Comment by WGSRangerWolf** [comment]
bing translator to English OLA. I wanted un système eat Log name and IP steamid would be very utio.

Could be with mysql or .txt, anything!

**Comment by leonardosnt** [comment]
@WGSRangerWolf  I understood, thanks.

**Comment by WGSRangerWolf** [comment]
@leonardosnt i didnt.

**Comment by xyzdevdox** [comment]
@leonardosnt @WGSRangerWolf sorry about that.

i wonder if we have a support to log ip with username and steamid.
could be with mysql or  in .txt files.

pretty sure that with mysql is much easier.

Thanks.

**Comment by leonardosnt** [comment]
@xyzdevdox  I already understood.

**Comment by WGSRangerWolf** [comment]
@leonardosnt  yeah but i didnt :+1:

**Comment by leonardosnt** [comment]
@WGSRangerWolf you already said that.
