### ISSUE TITLE
Antispam bypass not working.

### ISSUE THREAD

**Issue by Ejraiel** [uEssentials/uEssentials#170]
Fast typing triggers the antispam even with both of these permissions:
essentials.bypass.*
essentials.bypass.antispam

 
 
_Versions:_
Unturned 3.14.7.2
Rocket 807 (4.9.3.0)
uEssentials 1.1.5.0

**Comment by leonardosnt** [comment]
You are using "wrong" permission, use old permissions, #119 

"essentials.bypass...." is not released yet.

**Comment by Ejraiel** [comment]
Ah. Thanks. Thought they were added to the plugin since the wiki has them.
