### ISSUE TITLE
Moderators not have permissions

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [uEssentials/uEssentials#171]
Why do I see yellow in the console that disabled commands like i,tp and other commands? And most importantly why I was prescribed them to moderators and they don't even use them why?

**Comment by leonardosnt** [comment]
You need to add the respective permissions...

essentials.command.tp
essentials.command.item
...

**Comment by ZSHADOWWOLF** [comment]
No thanks i Disabled in Config.Json This commands and we are worked
