### ISSUE TITLE
UGH!

### ISSUE THREAD

**Issue by WGSRangerWolf** [uEssentials/uEssentials#172]
ne.Component.GetComponent[UnturnedPlayerFeatures] ()
                              Rocket.Unturned.Player.UnturnedPlayer.get_VanishMode ()
     Rocket.Unturned.Player.UnturnedPlayer.Teleport (Vector3 position, Single rotation)
       Essentials.Api.Unturned.UPlayer.Teleport (Vector3 pos, Single rotation)
                                                                              Essentials.Commands.CommandHome+<>c__DisplayClass2_1.<OnExecute>b__0 (Essentials.Api.Task.Task t)
               Essentials.Api.Task.Tasks.FixedUpdate ()
                                                       NullReferenceException - UnityEngine.Component.GetComponent[UnturnedPlayerFeatures] ()
                                                             Rocket.Unturned.Player.UnturnedPlayer.get_VanishMode ()
                                    Rocket.Unturned.Player.UnturnedPlayer.Teleport (Vector3 position, Single rotation)
                                      Essentials.Api.Unturned.UPlayer.Teleport (Vector3 pos, Single rotation)
                             Essentials.Commands.CommandHome+<>c__DisplayClass2_1.<OnExecute>b__0 (Essentials.Api.Task.Task t)
                                              Essentials.Api.Task.Tasks.FixedUpdate ()
      NullReferenceException - UnityEngine.Component.GetComponent[UnturnedPlayerFeatures] ()
            Rocket.Unturned.Player.UnturnedPlayer.get_VanishMode ()
                                                                   Rocket.Unturned.Player.UnturnedPlayer.Teleport (Vector3 position, Single rotation)
                                                                     Essentials.Api.Unturned.UPlayer.Teleport (Vector3 pos, Single rotation)
                                                            Essentials.Commands.CommandHome+<>c__DisplayClass2_1.<OnExecute>b__0 (Essentials.Api.Task.Task t)
                                                                             Essentials.Api.Task.Tasks.FixedUpdate ()
                                     NullReferenceException - UnityEngine.Component.GetComponent[UnturnedPlayerFeatures] ()
                                           Rocket.Unturned.Player.UnturnedPlayer.get_VanishMode ()
                  Rocket.Unturned.Player.UnturnedPlayer.Teleport (Vector3 position, Single rotation)
                    Essentials.Api.Unturned.UPlayer.Teleport (Vector3 pos, Single rotation)
           Essentials.Commands.CommandHome+<>c__DisplayClass2_1.<OnExecute>b__0 (Essentials.Api.Task.Task t)
                            Essentials.Api.Task.Tasks.FixedUpdate ()
                                                                    NullReferenceException - UnityEngine.Component.GetComponent[UnturnedPlayerFeatures] ()
                                                                          Rocket.Unturned.Player.UnturnedPlayer.get_VanishMode ()
                                                 Rocket.Unturned.Player.UnturnedPlayer.Teleport (Vector3 position, Single rotation)
                                                   Essentials.Api.Unturned.UPlayer.Teleport (Vector3 pos, Single rotation)
                                          Essentials.Commands.CommandHome+<>c__DisplayClass2_1.<OnExecute>b__0 (Essentials.Api.Task.Task t)
                                                           Essentials.Api.Task.Tasks.FixedUpdate ()
                   NullReferenceException - UnityEngine.Component.GetComponent[UnturnedPlayerFeatures] ()
                         Rocket.Unturned.Player.UnturnedPlayer.get_VanishMode ()
                                                                               Rocket.Unturned.Player.UnturnedPlayer.Teleport (Vector3 position, Single rotation)
 Essentials.Api.Unturned.UPlayer.Teleport (Vector3 pos, Single rotation)
                                                                        Essentials.Commands.CommandHome+<>c__DisplayClass2_1.<OnExecute>b__0 (Essentials.Api.Task.Task t)
         Essentials.Api.Task.Tasks.FixedUpdate ()

**Comment by Ejraiel** [comment]
lol best issue title

it's like all my server console screenshots of various unturned / rocket bugs

**Comment by Daniil1288** [comment]
yeah, I've submitted the same issue 7 days prior to this one :)
https://github.com/uEssentials/uEssentials/issues/158

**Comment by Daniil1288** [comment]
STILL can't find what's causing it besides rocket and uessentials :(

**Comment by leonardosnt** [comment]
I found the problem... i ill fix.

**Comment by Daniil1288** [comment]
nice :+1:
took long enough ;)
