### ISSUE TITLE
Money in kits...

### ISSUE THREAD

**Issue by leonardosnt** [uEssentials/uEssentials#174]
Allow to give money in kits.

Add Kit cost?!?!

**Comment by Daniil1288** [comment]
...from this plugin: https://dev.rocketmod.net/?rplugin=kits

**Comment by leonardosnt** [comment]
@Daniil1288 what

**Comment by Daniil1288** [comment]
@leonardosnt that plugin already supports money, you could see how it works there :+1:

**Comment by leonardosnt** [comment]
@Daniil1288 I dont need, but thanks.

**Comment by leonardosnt** [comment]
Kit cost?!?!
