### ISSUE TITLE
Command Caller Issue

### ISSUE THREAD

**Issue by ClassyDestroyer** [uEssentials/uEssentials#175]
I have been having a problem between my staff. One of my staff members has a generic name, and another has his entire name inside his own.

Eg:
Staff 1 with a STEAM name of "Star"
Staff 2 with a STEAM name of "BlackStar-Slayer"

Staff 1 will run the command /tp someplayer
Staff 2 will be teleported to someplayer instead of Staff 1
And nothing happens to Staff 1

The same happens to other commands.
/suicide for example.

![ss 2016-03-13 at 07 05 21](https://cloud.githubusercontent.com/assets/14995258/13727650/ad38f686-e94e-11e5-90b7-33351e6eef47.png)

I use LIGHT if that might affect it in some way? But i don't think so.

**Comment by ClassyDestroyer** [comment]
I have been unable to replicate it. I don't know what caused it in the first place but i'll watch to see if it happens again.

**Comment by WGSRangerWolf** [comment]
I was able to duplicate this on numerous occasions. Leonardosnt if you want admin on my server so you can test out certain commands in live to verifiy issues. i can even supply you with telenet rcon for rocket for my server if need be

**Comment by WGSRangerWolf** [comment]
This is a verified bug as i have been able to duplicate this.
lets say i wanted to tp to a person. like seaotter for an example
On some occasions it would send me to seattle.

**Comment by leonardosnt** [comment]
@WGSRangerWolf I dont have fixed my pc yet...

**Comment by leonardosnt** [comment]
Idk if is possible, but, is the same steam id?

**Comment by WGSRangerWolf** [comment]
this is not possible as each person has a unique steam id.

**Comment by leonardosnt** [comment]
@WGSRangerWolf Nooo, you don't have understood... maybe he is using 2 unturned accounts with one steam account.

**Comment by WGSRangerWolf** [comment]
@leonardosnt STILL it doesnt matter it is not possible to use 2 unturned accounts with steam
STEAM ID is a unique id. and that id is an account......

**Comment by leonardosnt** [comment]
@WGSRangerWolf That's what I wanted to know ...

**Comment by WGSRangerWolf** [comment]
@leonardosnt Glad i cleared things up then.

**Comment by WGSRangerWolf** [comment]
This bug is a rare bug. Remove high priority and add low priority as you will need more data in order to look into it.
This bug is time consuming and can be easily override d by simply changing their name.
When i find another issue i will post information here.

**Comment by WGSRangerWolf** [comment]
@leonardosnt This does not affect plugin functionallity

**Comment by WGSRangerWolf** [comment]
@leonardosnt Can you release what you have now? Been waiting for the current up to date fixes

**Comment by leonardosnt** [comment]
@WGSRangerWolf :+1:

**Comment by Daniil1288** [comment]
still not fixed? :P
