### ISSUE TITLE
The "Automatic" Abilities -- Item & Vehicle Features -- Restructured command, & new permissions!

### ISSUE THREAD

**Issue by Ejraiel** [uEssentials/uEssentials#177]
**Old Commands:**
`/itemfeatures [autoreload|autorepair] [on|off]`
`/vehiclefeatures [autorefuel|autorepair] [on|off]`

 
 
**New Command:**
`/auto <item | vehicle | itemreload | itemrepair | vehiclerefuel | vehiclerepair> <on|off>`
_(if "itemreload" / etc. is omitted, it would apply to all features.)_
_(if on/off is omitted, it would toggle the current state.)_

**Usage Examples:**
`/auto` -- Toggles itemreload, itemrepair, vehiclerefuel, and vehiclerepair.
`/auto on` -- Turns all on.
`/auto off` -- Turns all off.
`/auto item` -- Toggles itemreload and itemrepair.
`/auto item on` -- Turns itemreload and itemrepair on.
`/auto vehicle off` -- Turns vehiclerefuel and vehiclerepair off.
_Etc._ :smiley:

 
 
**New Permissions:**
`essentials.auto.*`
`essentials.auto.item.*`
`essentials.auto.item.reload`
`essentials.auto.item.repair`
`essentials.auto.vehicle.*`
`essentials.auto.vehicle.refuel`
`essentials.auto.vehicle.repair`

**Comment by leonardosnt** [comment]
Too complex for users.
