### ISSUE TITLE
Pc broken t.t

### ISSUE THREAD

**Issue by leonardosnt** [uEssentials/uEssentials#179]
My windows has broken, 2 days ago... i think that i will install a new windows today, i'm not sure...

Just explaining why i'm not working on uEssentials in last days ..

**Comment by WGSRangerWolf** [comment]
Windows 7

**Comment by Ejraiel** [comment]
ah ;\

and as pretty as 7 can be, i'd go with 8.1 for performance / usability ;P

**Comment by WGSRangerWolf** [comment]
Screw windows 8

**Comment by Ejraiel** [comment]
lol.

UI wise i much prefer 10, but i hate the forced updates, so...  =\

**Comment by Daniil1288** [comment]
@Ejraiel yeah I'm using 10 on my main (this) pc too, but I don't like Microsoft collecting my data, still :(

**Comment by WGSRangerWolf** [comment]
I use windows 7 and i have a flat border lol.

**Comment by WGSRangerWolf** [comment]
https://i.gyazo.com/f1e5c0008d9c1820206bef0930f2ef18.png

**Comment by leonardosnt** [comment]
I have installed Windows 7, and upgraded to Windows 10 because i love Windows 10...

Now i am Installing drivers...

**Comment by leonardosnt** [comment]
I don't care...

Windows 7 is cool, i like, but it's old.

**Comment by WGSRangerWolf** [comment]
Old is better than new stuff. I have learned this by experiences. and i will stay with windows 7 until it dies.

**Comment by leonardosnt** [comment]
Haha, ok, i like new stuffs, i like the Windows 10 UI, i really love Windows 10 UI.

**Comment by WGSRangerWolf** [comment]
@leonardosnt https://i.gyazo.com/f1e5c0008d9c1820206bef0930f2ef18.png :3

**Comment by leonardosnt** [comment]
Everything working fine again, finally...



Except that i will need download my programs again T.T
