### ISSUE TITLE
Command Logger?

### ISSUE THREAD

**Issue by WGSRangerWolf** [uEssentials/uEssentials#18]
Looking at rocket logs is quite dreadful and i was wondering if There can be a plugin where all commands are executed are logged. A much cleaner version. I have amateur admins and i am trying to teach them. Could this be possible?

**Comment by waspkiller** [comment]
Would have time and date
and if there was a issue it would log chat messages

**Comment by leonardosnt** [comment]
Cool, i will make an separately module for this.

**Comment by waspkiller** [comment]
Can it have a function where if someone executes a command that isnt allowed to be used they get booted? I am trying to restrict some abusive Commands.

**Comment by leonardosnt** [comment]
I did not understand this "get booted"

**Comment by leonardosnt** [comment]
Ah, ok.

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials.LogCommands/releases

**Comment by Daniil1288** [comment]
will be testing this out, thanks @leonardosnt

**Comment by Daniil1288** [comment]
works nicely, thank you very much! @leonardosnt :+1:
