### ISSUE TITLE
Wiki locked to uEssentials group members only?

### ISSUE THREAD

**Issue by Ejraiel** [uEssentials/uEssentials#181]
I'd like to edit / update:

Main
FAQ
Command Reference
Permission Reference

**Comment by WGSRangerWolf** [comment]
i could do that




*Have a amazing day,*

*Derrick McLean* (formaly known as waspgod, Rangerwolf)

**Comment by WGSRangerWolf** [comment]
@Ejraiel @leonardosnt needs to add you as a collaborator or you could give me a document of it being updated such as drive.google.com

**Comment by leonardosnt** [comment]
I will check it when i fix my pc...

**Comment by WGSRangerWolf** [comment]
i was able to edit the wiki and etc. if you give me what you want to change
i can change it or if Leonardo want's to add you as a collaborator, he can
do so.




*Have a amazing day,*

*Derrick McLean* (formaly known as waspgod, Rangerwolf)

**Comment by leonardosnt** [comment]
@Ejraiel I have added you as collaborator, now you can help on issues, ...

**Comment by Ejraiel** [comment]
Awesome. =]
