### ISSUE TITLE
Odd console output from "/ess commands 1"?

### ISSUE THREAD

**Issue by Ejraiel** [uEssentials/uEssentials#185]
![uh lol wtf](https://cloud.githubusercontent.com/assets/17344624/13791989/e51fd088-eaac-11e5-9879-061a9c573017.png)

**Comment by Daniil1288** [comment]
can confirm, I've found that a long time ago but thought that it had a meaning

**Comment by WGSRangerWolf** [comment]
Can confirm

**Comment by leonardosnt** [comment]
Damn, i forgot to close....

1aec83aa304fe0d5fffb74b22ccb179c81af95a9
