### ISSUE TITLE
Kits can be spawned on other players with the `essentials.command.dropkit` permission.

### ISSUE THREAD

**Issue by Ejraiel** [uEssentials/uEssentials#187]
Is there no `essentials.command.dropkit.others` permission?

**Comment by leonardosnt** [comment]
Nop

**Comment by leonardosnt** [comment]
dropkit is for admins, or console. normal players cau use /kit.

**Comment by leonardosnt** [comment]
I see no need to add it.

**Comment by Ejraiel** [comment]
Completion, to account for any possible use.

Other similar commands have the same ability, so it makes sense.

As for a usage example, I run a creative server, and there would be cases where it would be more useful to drop a kit rather than partly fill your inventory; such as with building materials when people are making a base.

**Comment by leonardosnt** [comment]
essentials.command.dropkit.other

**Comment by leonardosnt** [comment]
Add on wiki plz...
