### ISSUE TITLE
Chat tags?

### ISSUE THREAD

**Issue by WGSRangerWolf** [uEssentials/uEssentials#19]
I seriously want this to happen.
I have a moderator group and I would like to have [MOD] Every time they chat.
Can be configurable by permission base.

**Comment by leonardosnt** [comment]
I don't know if this is possible, i will check.

**Comment by waspkiller** [comment]
Alright :D

**Comment by waspkiller** [comment]
so chat tags is possible?

**Comment by leonardosnt** [comment]
I dont know

**Comment by leonardosnt** [comment]
I don't know how say it.

"I have not verified yet"

My english is :-1::-1::-1::-1::-1:

**Comment by waspkiller** [comment]
Its alright man i can read broken language just fine :D

**Comment by leonardosnt** [comment]
lmao

**Comment by Mikuzzzz** [comment]
It's possible. http://i.imgur.com/8wYPOh1.jpg Not going to release code though :p

**Comment by leonardosnt** [comment]
I will find out... :laughing: :laughing:

**Comment by Mikuzzzz** [comment]
It took weeks to code and make it work with colors. Lol though, good luck.

**Comment by leonardosnt** [comment]
wow '-'

So, my way is more easy.

onPlayerChated
{
     message = "[tag]" + playername + bla bla
}

**Comment by waspkiller** [comment]
OMg yes add it add it

**Comment by waspkiller** [comment]
But you have to grab the group too. talking to Mikuzzz

**Comment by leonardosnt** [comment]
@waspkiller its easy

**Comment by leonardosnt** [comment]
#1
