### ISSUE TITLE
STORM IS COMMING

### ISSUE THREAD

**Issue by WGSRangerWolf** [uEssentials/uEssentials#198]
When storm is comming, uessentials will annouce it.

**Comment by leonardosnt** [comment]
what

**Comment by leonardosnt** [comment]
rain not worked for me T.T

**Comment by WGSRangerWolf** [comment]
its working on my server
do /storm while ingame

**Comment by leonardosnt** [comment]
I think that this thing is not helpful to add directly in uEssentials. If you want i can made an module for that.
