### ISSUE TITLE
remove clear v

### ISSUE THREAD

**Issue by WGSRangerWolf** [uEssentials/uEssentials#199]
since clear ev has been implemented. remove v command which causes crashes

**Comment by leonardosnt** [comment]
Just don't use that

**Comment by WGSRangerWolf** [comment]
Yeah well i have admins who perfer to type clear v than ev

**Comment by leonardosnt** [comment]
ev isn't implemented.

I cant remove the command because of your admins.

**Comment by leonardosnt** [comment]
ev implemented!
