### ISSUE TITLE
Command createkit

### ISSUE THREAD

**Issue by leonardosnt** [uEssentials/uEssentials#2]
Create kit w/ player inv contents

**Comment by odyss3y** [comment]
this is a great idea

**Comment by Punky69** [comment]
this would make so easyer to create kits!
mybe you could use /ckit name
i think plugin should somehow scan players inventory and put it in file

**Comment by waspkiller** [comment]
Yeah thats a good idea.

**Comment by ZSHADOWWOLF** [comment]
Thats Awesome!
