### ISSUE TITLE
Global ResetCooldownWhenDie kits

### ISSUE THREAD

**Issue by WGSRangerWolf** [uEssentials/uEssentials#203]
Add in config.json
ResetCooldownWhenDie false/true

**Comment by leonardosnt** [comment]
why?

**Comment by WGSRangerWolf** [comment]
Does /ckit still has the cooldown t or f?

**Comment by leonardosnt** [comment]
```/kit [name] <cooldown>``` ??

**Comment by WGSRangerWolf** [comment]
/kit [name] <cooldown> <cooldown reset t f>
