### ISSUE TITLE
:D

### ISSUE THREAD

**Issue by leonardosnt** [uEssentials/uEssentials#206]
In 2 days uEssentials metrics has "recorded" 336 servers and 30.078 UNIQUE FUCKING players...

**Comment by WGSRangerWolf** [comment]
:+1:

**Comment by WGSRangerWolf** [comment]
and man you have been busy

**Comment by leonardosnt** [comment]
@WGSRangerWolf :+1:

**Comment by WGSRangerWolf** [comment]
upgraded uessentials on my server. 1 nire server

**Comment by JustOneMoreBlock** [comment]
Well, once I add uEssentials. I get 200~ average concurrent on my servers. :P

JPH :)

**Comment by leonardosnt** [comment]
03/28/15:
- 1013 servers
- 143.577 players

**Comment by Daniil1288** [comment]
welp that's... quite the bit :O

**Comment by leonardosnt** [comment]
:smile:

**Comment by WGSRangerWolf** [comment]
is there a command where i can see the metrics ingame?

**Comment by leonardosnt** [comment]
@WGSRangerWolf nop.

**Comment by WGSRangerWolf** [comment]
darn

**Comment by leonardosnt** [comment]
04/29/15:
- 2692 Servers
- 448.355 players (Unique)

**Comment by Daniil1288** [comment]
welp, that escalated quickly enough :D
