### ISSUE TITLE
i cant get kit permissions work

### ISSUE THREAD

**Issue by fisteranton50** [uEssentials/uEssentials#207]
<Id>mod</Id>
      <DisplayName>mod</DisplayName>
      <Color>#8904B1</Color>
      <Members>
        <Member>76561198205701567</Member>
        <Member>76561198272546037</Member>
        <Member>76561198072149955</Member>
        <Member>76561198141072296</Member>
      </Members>
      <Commands>
        <Command Cooldown="3000">essentials.command.kit.mod</Command>
        <Command Cooldown="3000">essentials.command.kit.donater</Command>
        <Command>p</Command>
        <Command Cooldown="500">v</Command>
        <Command Cooldown="300">heal</Command>
        <Command Cooldown="500">essentials.command.item</Command>
        <Command>tpa</Command>
        <Command>tpa.send</Command>
        <Command>tpa.accept</Command>
        <Command>tpa.deny</Command>
        <Command>compass</Command>
        <Command>rocket</Command>
      </Commands>
    </Group>
    <Group>

why does it not work?

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference
