### ISSUE TITLE
Lagging w/cars

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#208]
So, with the last unturned update my server goes down to 3 tps and kicks all players.

I only need to know one thing:
Can I somehow make the server autoexecute /clear v (and possibly /clear i) every once in awhile, like, say, 30 minutes?

**Comment by WGSRangerWolf** [comment]
i dont have an issue with that. and this has been mentioned a thousand times.

**Comment by leonardosnt** [comment]
f628803f5d757686db851f09bd776fa8ade44e9f

**Comment by Daniil1288** [comment]
thank yoouuu! :+1:

**Comment by leonardosnt** [comment]
:D
