### ISSUE TITLE
Idk what im doing wrong

### ISSUE THREAD

**Issue by daseki** [uEssentials/uEssentials#21]
http://pastebin.com/0iMximtB half the commands work. half dont. is there a limit on how lines i can have. It tells me "command_no_permission" i re-read over it many times. a couple commands that dont work are spy, jump, ascend, descend, autoreload and item/i. the rest that i actually use work. It's probably some little thing that im missing

**Comment by leonardosnt** [comment]
Remove

       <Command>ascend</Command>
        <Command>descend</Command>
        <Command>item</Command>

just leave the "essentials.command.\<cmd_name\>"

**Comment by waspkiller** [comment]
I was just about to say that. Lol

**Comment by daseki** [comment]
i just tried that and no change. im probably just being slow right now,

**Comment by daseki** [comment]
everything works on admin/owner but not in the actual group.

**Comment by waspkiller** [comment]
Daseki
This is my setup and it works for me
`<Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Color>grey</Color>
      <Members />
      <Commands>
        <Command>p</Command>
        <Command>motd.default</Command>
        <Command>compass</Command>
        <Command>rocket</Command>
        <Command>warp</Command>
        <Command>reward</Command>
        <Command>balance</Command>
        <Command>home</Command>
        <Command>rules</Command>
        <Command>deathmessage</Command>
        <Command>kits</Command>
        <Command>kit.food</Command>
        <Command>kit.starter</Command>
        <Command>kit.House</Command>
        <Command>kit.timber</Command>
        <Command>kit.maplestrike</Command>
        <Command>kit.grizzly</Command>
        <Command>tpa</Command>
        <Command>tpa.send</Command>
        <Command>tpa.accept</Command>
        <Command>warps</Command>
       ** <Command>essentials.command.ping</Command>**
      </Commands>`

**Comment by daseki** [comment]
thats exactly what i have. the ping works for me but others ones dont. there is nothing different between the writings. im just very confused and frustrated that i cant figure this out.

**Comment by waspkiller** [comment]
What ones are you trying to figure out?

**Comment by waspkiller** [comment]
heres my Permissions
http://pastebin.com/Xw2YcDMp

**Comment by daseki** [comment]
ok i found out that these commands dont work but in the pastebin i posted they are written the same. spy, ascend, descend, autoreload, autorepair, and item/i. 
http://pastebin.com/sLC6gtuD
they should all work from what im looking at.

**Comment by waspkiller** [comment]
@daseki 
```
<Command>essentials.command.vehiclefeatures</Command>
<Command>essentials.command.itemfeatures</Command>
```

**Comment by daseki** [comment]
i tried replacing the autorepair/auto refuel with those commands and vice versa. Nothing seems to work. This thing just doesn't like me.

**Comment by waspkiller** [comment]
Ive added those. asking people if it works. if not all comamnds that dont work Make a new issue so they can be catagorized as a bug

**Comment by leonardosnt** [comment]
The permission is JUST 'essentials.command.<command_NAME> just name, not aliases'

Ex

```xml
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Color>white</Color>
      <Members />
      <Commands>
        <Command>p</Command>
        <Command>essentials.command.back</Command>
        <Command>essentials.command.kits</Command>
        <Command>essentials.command.kit</Command>
        <Command>essentials.kit.default</Command>
        <Command>rocket</Command>
      </Commands>
    </Group>
```

https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference
https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference
