### ISSUE TITLE
Is this related to uEssentials?

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#212]
Happened with Int16, happens with Int32. Hm.

[3/27/2016 12:00:43 AM] [Info] [World] Fook [Fook]: "/kit start"
[3/27/2016 12:00:44 AM] [Error] ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index - System.Collections.Generic.List`1[SDG.Unturned.InventorySearch].get_Item (Int32 index)
SDG.Unturned.PlayerCrafting.askCraft (CSteamID steamID, UInt16 id, Byte index, Boolean force)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.Provider.receiveServer (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel)
SDG.Unturned.Provider.listenServer (Int32 channel)
SDG.Unturned.Provider.listen ()
SDG.Unturned.Provider.Update ()

**Comment by leonardosnt** [comment]
No, there is nothing related with uEssentials in stacktrace.

"When" it happens?"

**Comment by Daniil1288** [comment]
Welp, don't really know, but this error occurs really, really rarely

After someone tries to give something to oneself, possibly while teleporting. This player's log:
[3/27/2016 12:00:11 AM] [Info] [World] Fook [Fook]: "/tpa vega"
[3/27/2016 12:00:37 AM] [Info] [World] Fook [Fook]: "/tpa yo"
[3/27/2016 12:00:43 AM] [Info] [World] Fook [Fook]: "/kit start"
[3/27/2016 12:00:44 AM] [Error] ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index - System.Collections.Generic.List`1[SDG.Unturned.InventorySearch].get_Item (Int32 index)
SDG.Unturned.PlayerCrafting.askCraft (CSteamID steamID, UInt16 id, Byte index, Boolean force)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.Provider.receiveServer (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel)
SDG.Unturned.Provider.listenServer (Int32 channel)
SDG.Unturned.Provider.listen ()
SDG.Unturned.Provider.Update ()
[3/27/2016 12:00:52 AM] [Info] Fook moved x:160.651 y:62.25331(+24.03684) z:-447.6624 in the last second (0.1067581)
[3/27/2016 12:04:38 AM] [Info] Fook [Fook] bled to death!

**Comment by Daniil1288** [comment]
8 seconds after he moved, hm.

**Comment by Daniil1288** [comment]
[3/27/2016 12:12:12 AM] [Info] [World] VEGA[VEGA]: "/tpa accept"
[3/27/2016 12:12:12 AM] [Error] IndexOutOfRangeException: Array index is out of range. - SDG.Unturned.ResourceManager.getResourceSpawnpoint (Byte x, Byte y, UInt16 index)
SDG.Unturned.ResourceManager.getResource (Byte x, Byte y, UInt16 index)
SDG.Unturned.WalkingPlayerInputPacket.read (SDG.Unturned.SteamChannel channel)
SDG.Unturned.PlayerInput.askInput (CSteamID steamID)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.Provider.receiveServer (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel)
SDG.Unturned.Provider.listenServer (Int32 channel)
SDG.Unturned.Provider.listen ()
SDG.Unturned.Provider.Update ()

another one

**Comment by leonardosnt** [comment]
Well, this is a unturned bug.

**Comment by Daniil1288** [comment]
welp, thought that nelson'd fixed that with adding UInt32 :(
Should I close this, then?

**Comment by leonardosnt** [comment]
yep
