### ISSUE TITLE
Improve wiki (commands)

### ISSUE THREAD

**Issue by leonardosnt** [uEssentials/uEssentials#213]
Add help text for "complex" commands (e.g /item), examples etc...

Usages of /item
/i [item]
/i [item] [amount]
/i [player] [item]
/i * [item]
/i * [item] [amount]
/i [player] [item] [amount]

**Comment by WGSRangerWolf** [comment]
When i can get around to messing the wiki up for this i will do so :+1:

**Comment by WGSRangerWolf** [comment]
Going to start messing around with wiki now will close this when i am done

**Comment by WGSRangerWolf** [comment]
Someone beat me too it i think lol

**Comment by leonardosnt** [comment]
...?

**Comment by WGSRangerWolf** [comment]
have ejraiel proof read i just took this outta active issues for the sake of prioritizing i guess
