### ISSUE TITLE
Vanish Mode Unity error, yet again

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#215]
[3/27/2016 4:52:23 PM] [Error] NullReferenceException - UnityEngine.Component.GetComponent[UnturnedPlayerFeatures] ()
Rocket.Unturned.Player.UnturnedPlayer.get_VanishMode ()
Rocket.Unturned.Player.UnturnedPlayer.Teleport (Vector3 position, Single rotation)
Essentials.Api.Unturned.UPlayer.Teleport (Vector3 pos, Single rotation)
Essentials.Commands.CommandHome+<>c__DisplayClass2_0.<OnExecute>b__0 (Essentials.Api.Task.Task t)
Essentials.Api.Task.Tasks.FixedUpdate ()

984 hits in 1 file, crashing my server...

**Comment by leonardosnt** [comment]
#172
