### ISSUE TITLE
LIGHT support

### ISSUE THREAD

**Issue by ghost** [uEssentials/uEssentials#218]
Hello. I have a chat delay bug with Light
Example: typed something and after ~2.5 i will get response.
 (tested, bug is happening with Light installed only)

**Comment by leonardosnt** [comment]
I will try to reproduce, but i think that is not related with uEssentials.

**Comment by leonardosnt** [comment]
Nothing... here is working fine.

**Comment by WGSRangerWolf** [comment]
@Ghost your problem is related to latency issues
