### ISSUE TITLE
spam in console when player uses a command or chats

### ISSUE THREAD

**Issue by sharkbound** [uEssentials/uEssentials#22]
this is what it does - https://gyazo.com/60c27ae7385f3ed42006de19902d703f

i updated the plugin and rocket to latest version. this didnt happen until i update essentials to latest version. also that you type is determines what it spams

also whenever you do /vf autorefuel on|off it says "autoreload disabled and autoreload enabled"

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/releases/tag/1.0.6.1
https://github.com/uEssentials/uEssentials/releases/tag/1.0.6.1
https://github.com/uEssentials/uEssentials/releases/tag/1.0.6.1
