### ISSUE TITLE
How to stop players from pulling one of every kit?

### ISSUE THREAD

**Issue by ed8toastpc** [uEssentials/uEssentials#224]
Guests have permission to pull 4 different kits, but I just realized they can pull every kit right after another! The kits have cool downs for themselves but a player can still pull all four. How do I make it so they can only pull one kit once, per life?

**Comment by WGSRangerWolf** [comment]
Manuelly edit the kits.json file where it says cooldownresetondeath true Change that to false.

**Comment by ed8toastpc** [comment]
3 of the 4 are on false, but when a person logs in they can still immediately use ALL FOUR kits, and end up with the contents of ALL of the kits. I want to stop that. When you take one kit, I want that to be all you can have.

**Comment by leonardosnt** [comment]
I will add global cooldown, i forgot.

**Comment by ed8toastpc** [comment]
Right on. You can add a cooldown to the kit command in the permissions xml, but you can't make it reset on death like how you can in the kit.json. I have been messing with it and, yeah, I can't get the desired effect of ONE kit per life. It either is an obnoxious cooldown for all kits for extended period, or they can spam kits.

Thanks, yo.

**Comment by leonardosnt** [comment]
b5583f468092cfa5a96e56996dece72e8ad716e0
