### ISSUE TITLE
* permission bug

### ISSUE THREAD

**Issue by DubFriendsFriendlyFriend** [uEssentials/uEssentials#227]
Over on the Rocket github, there was this issue where the universal " * " permission stopped working. Some guy found out that the way to fix it was to downgrade uEssentials back into 1.1.7.0.

Is there possibly some sort of incompatibility between uEssentials and the latest Rocket?

Link to original issue: https://github.com/RocketMod/Rocket/issues/651

**Comment by Daniil1288** [comment]
huh, so my admins were right when they told me "/god doesn't work! write to the plugin developer that we want this fixed now!"... Shame I didn't listen to them at first.

**Comment by DubFriendsFriendlyFriend** [comment]
Well, you can stop them from going crazy either by just adminning normally or downgrading to 1.1.7.0 :P

**Comment by Daniil1288** [comment]
Weeellll, my admins aren't really /admin to be honest. More like moderators, they are limited in their abilities. The best of these "admins" get promoted to the actual admin rank, getting permissions to all the commands. :D
And I forget to /admin them sometimes, so, the file is the only thing that gives them access to all of the commands.

**Comment by DubFriendsFriendlyFriend** [comment]
yeah thought so

why else would you care about the * permission? O3O

**Comment by leonardosnt** [comment]
The new Rocket update are broken.
