### ISSUE TITLE
Run Task Once

### ISSUE THREAD

**Issue by AlxndrBo** [uEssentials/uEssentials#228]
I ask you to make a one-time start-up task with the timer from starting the server. For example, to add a flag RunOnce = true to the Timer.
"AutoCommands": {
    "Commands": [
      {
        "Timer": 1200,
        **"RunOnce": true,**
        "Commands": [
          "say first run once command",
	  "say second run once command"
        ]
      },
    ],
    "Enabled": true
  },

**Comment by AlxndrBo** [comment]
Wonderful plugin.
It has long wanted to be able to remove items. And then there's possible to kill a zombie, and the animals, removing vehicles. Super!
P.S. Sorry for my English. Not the native language.

**Comment by leonardosnt** [comment]
Thanks, then leave your star, i will be grateful.

**Comment by AlxndrBo** [comment]
You are gorgeous

**Comment by leonardosnt** [comment]
:laughing:
