### ISSUE TITLE
Couple of bugs

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#231]
Minor bugs:
- Antispam bypass doesn't work
- When you send a tpa request (/tpa player) it tells you:
player has sent you a tpa request, use '/tpa accept/deny'.
(even though YOU'RE the one who is sending a tpa request.)
and when someone tries to teleport to you it says vice verca:
You sent a tpa request to player, use '/tpa cancel' to cancel

BIG bug:
Players can't access kits. It tells them that there are NO kits available and that they have NO permission to spawn one in.
My permissions:
```
    <Group>
      <Id>default</Id>
      <DisplayName>Player</DisplayName>
      <Color>white</Color>
      <Members>
        <Member />
      </Members>
      <Permissions>
        <Permission>kits</Permission>
        <Permission>kit</Permission>
        <Permission>essentials.kit.home</Permission>
        <Permission>essentials.kit.start</Permission>
        <Permission>essentials.kit.bonus</Permission>
        <Permission>essentials.kit.map</Permission>
```
and other perms that don't matter for this situation
Help?

**Comment by Daniil1288** [comment]
for some reason, when I give the permission essentials.kit.* then everything works... But I don't want to give my players a permission for ALL the kits! How to solve this?

**Comment by Daniil1288** [comment]
OK so I just deleted admin kits, essentials.kit.* solved the big bug for me... But I want separate permissions for separate player groups. Leo, pls fix this bug.

**Comment by leonardosnt** [comment]
b98c543 fix kits & anti-spam

**Comment by Daniil1288** [comment]
thank you! :+1:

**Comment by leonardosnt** [comment]
Np

**Comment by Doobaa2000** [comment]
you dont have to use essentials.kit.* what i did with mine is essentials.command.kit.home then you do essentials.kit.home so you would have  <Permission>essentials.kit.home</Permission><Permission>essentials.command.kit.home</Permission> thats what i did and it worked

**Comment by leonardosnt** [comment]
@Doobaa2000 The correct permission is "essentials.kit.**kit name**"...
