### ISSUE TITLE
Bug with /clear ev

### ISSUE THREAD

**Issue by AlxndrBo** [uEssentials/uEssentials#232]
The problem with removing the vehicle. "/clear ev"
1. The corpses of machines are often removed only visually. A player may stand on them. Other players see that a character is hanging in the air. If relogin, the body of the machine will be seen again.
2. Often transport is not removed immediately. Delete parts of machines. Interestingly, some of the players no longer see the car, others continue to see. If relogin, the vehicle will be seen again.
3. It is not sure of the relationship. Command "/clear ev" influence on the change of day/night. Suddenly night falls. Some players will always see the day (even at night)

**Comment by leonardosnt** [comment]
`/clear ev` was removed.
