### ISSUE TITLE
Localisation (support any lang file. Etc lang_ru.json)

### ISSUE THREAD

**Issue by AlxndrBo** [uEssentials/uEssentials#233]
I tried to use the "Locale": "ru". I created lang_ru.json file. Start the server. Automatically empty lang_ru.tmp file was created. Errors in the console as an attachment. Please, add support lang_XX.json files for any XX. I'll send you the file lang_ru.json (now I use lang_en.json with my partial translation)
![localisation_err](https://cloud.githubusercontent.com/assets/17691265/14383138/be693e64-fd9b-11e5-9784-23609199d8ee.png)

**Comment by leonardosnt** [comment]
I'll fix.
