### ISSUE TITLE
Localization RU

### ISSUE THREAD

**Issue by AlxndrBo** [uEssentials/uEssentials#236]
Some are not translated. For example, minutes. Because changes in Russian words ending (2 minutes, 5 minutes). Everyone understands days hours minutes recording in English.
It should also be remembered that the console does not display Cyrillic. Therefore, some of the messages are better left untranslated. (Especially those that are not visible to the players)

[lang_ru.txt](https://github.com/uEssentials/uEssentials/files/210797/lang_ru.txt)

(Change txt to json)

**Comment by AlxndrBo** [comment]
Ах, да. По-русски ))
Кое-что не перевел. Например, минуты. Потому что окончания слов меняются во множественном числе. Я думаю, каждый русский поймет запись 1 day 3 hours 15 minutes ...
Также следует помнить, что в консоли кириллица отображается некорректно. (Хотя, можно поиграть с кодировками и сделать частичный перевод для консоли, частично для игроков. Не знаю, получится ли.) Поэтому некоторые сообщения лучше оставить на английском (особенно те, которые не видны игрокам)

**Comment by Daniil1288** [comment]
TL;DR:
Time can't be translated. Say, days/hours/minutes. @leonardosnt, pls fix

**Comment by Daniil1288** [comment]
@AlxndrBo, а вот насчет консоли идея хороша. Мне приходится лог держать открытым, чтоб видеть, что игроки пишут в чат. Так же сложно использовать команды say/broadcast, когда не знаешь, что написал уже.

**Comment by YuRaNnNzZZ** [comment]
Кракозябры вместо текста появляются из-за того, что Unturned использует ANSI (CP1252) в консоли вместо юникода. Пофиксить это может только Нельсон.
А по поводу времени - можно же использовать сокращения по типу `1 д. 3 ч. 15 мин.`, разве нет?

**Comment by AlxndrBo** [comment]
Да. В консоли одна кодировка, в игре другая. Это к Нельсону.
Сейчас попробую, будет ли работать, если в переводе использовать часть в ANSI (то, что хотим видеть в консоли), часть в Unicode (для игры)

**Comment by YuRaNnNzZZ** [comment]
Лично я вообще не парюсь по поводу кодировки - у меня консоль в скрине в одном окне, а лог через tail - в другом. (да и на винде через cygwin или msysgit tail работает замечательно)

**Comment by AlxndrBo** [comment]
Можно к RCON приконнектиться программой Putty и видеть все в правильной кодировке

**Comment by leonardosnt** [comment]
Thaaanks :D
