### ISSUE TITLE
Item Spawning / Loot Control

### ISSUE THREAD

**Issue by MortalMonkey** [uEssentials/uEssentials#237]
My ideas for loot control perfect for creative servers with vote rewards is to restrict players from spawning in a list of items but allow them to pick up the item or receive it in a reward bundle.

For example:

When player ABC enters  "**/i 4**" uEssentials displays a server message "**Eaglefire (004) is a reward item and cannot be spawned.**" or "**Eaglefire (004) cannot be spawned**".

Could this be achieved by adding a config that server owners can input item IDs players are restricted from spawning? -Thanks

**Comment by leonardosnt** [comment]
368e79f3e09697a822e6083336ad778b7af6f0a5
