### ISSUE TITLE
ahh......sir i have a problem

### ISSUE THREAD

**Issue by linyuzhe210** [uEssentials/uEssentials#24]
your plugin is very good but i just want to use my previous kits plugin because i dont use your new kits plugin very well，is there a way to be not cover my previous kits plugin？（my english isnt very well please ignore it）XD

**Comment by waspkiller** [comment]
Open config.json in uessentals
and add this

```
 "DisabledCommands": [
    "kit",
    "kits"
]

```
```
```
``

**Comment by leonardosnt** [comment]
@waspkiller Good answer!
