### ISSUE TITLE
/home error

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#240]
Maybe this guy just didn't claim his bed?...
![uesserror](https://cloud.githubusercontent.com/assets/1404955/14574409/36ed244a-0364-11e6-8566-040a7072d559.png)

**Comment by Daniil1288** [comment]
same happens with every command. /kits don't work for ordinary players, but they work for me for some reason...
(I'm /admin'd)

**Comment by Daniil1288** [comment]
![uesserror](https://cloud.githubusercontent.com/assets/1404955/14574528/dbf2d890-0364-11e6-9124-22b37cb1e210.png)

**Comment by leonardosnt** [comment]
i'll check.

**Comment by Daniil1288** [comment]
thank you for the quick response, leo!

**Comment by leonardosnt** [comment]
Np :)

**Comment by Daniil1288** [comment]
thank you, compiling now :+1:

**Comment by leonardosnt** [comment]
:smile:
