### ISSUE TITLE
/Rules and Death Messages

### ISSUE THREAD

**Issue by MortalMonkey** [uEssentials/uEssentials#241]
You are really creating a all-in-one plugin for Unturned server owners.  Those of us that use and understand your plugin love it! 

A few things I would like to see in this plugin is death messages with a config section like "AutoAnnouncer" and command so players can enter /rules to see a list of server rules.

I know other plugins offers these feature but like I said earlier,  All-in-One.   ;)

Thanks Leonardo

**Comment by leonardosnt** [comment]
I will add "text commands" e.g.

TextCommands.json
```json
[
  {
      "Name": "rules",
      "Text": [
          "Rule 1",
          "Rule 2"
      ]
  },
  {
       "Name": "serverfb",
       "Text": [ "www.facebook.com/serverfb" ]
  }
]
```

**Comment by MortalMonkey** [comment]
Works for me.  Thanks

**Comment by leonardosnt** [comment]
:D

**Comment by MortalMonkey** [comment]
Were you still looking for a test server to try pvp:on, pvp:off?  I can tell you that it works for me on my testing server.  Tried it out with a friend a couple days ago.

**Comment by leonardosnt** [comment]
No, i just wanted to know if it works.

Thanks for testing it, and sorry for my poor english.

**Comment by MortalMonkey** [comment]
It works and I will be using it on my Role-play servers for kill events.  A great addition to the pvp;on/pvp:off feature would be a schedule.  On day (0) for (7200) or 2 hours pvp will be on with a timer to the start of the kill event and the end.  

Your english is good ;)
