### ISSUE TITLE
How to enable Death Messages

### ISSUE THREAD

**Issue by MortalMonkey** [uEssentials/uEssentials#242]
I see you added death messages in the last update and posted the additions to the translation file but I do not see the option to enable the messages or the permission to add (If that is how its done).   Can you provide me with some information on implementing this feature.   

Thanks

**Comment by leonardosnt** [comment]
It is not released yet, but you can use my build, https://www.dropbox.com/s/640psrqtrxoalrv/uEssentials.dll?dl=0

**Comment by MortalMonkey** [comment]
Ah.  Thanks Leonardo

**Comment by Daniil1288** [comment]
@leonardosnt any way to disable them? I'm using an outdated translation (lang_ru.json) and it's been broadcasting "Error: translation not found for..." a lot. can't use the newest version

**Comment by leonardosnt** [comment]
@Daniil1288 No yet.

**Comment by leonardosnt** [comment]
@Daniil1288 57c7b076286bed318672ff626ee1888d6bbe5806 Not tested!!
