### ISSUE TITLE
uEssentials won't compile/won't load after the latest update

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#243]
Maybe it's rocket's fault, but my VS2015 says that "can't use blablabla because your .NET Framework is 4.0.0.0, but the project is using 2.0.0.0"

If I change it from 3.5 to 4.0 or anything higher in the settings, then my server can't load uEssentials. In fact, it doesn't even recognise its name.

What have I done wrong? I'm pretty sure I have .NET 3.5 installed... And before it compiled fine with 3.5...

**Comment by Daniil1288** [comment]
Experimental works fine, though. hm

**Comment by leonardosnt** [comment]
weird, i will check.

**Comment by leonardosnt** [comment]
Try again.

**Comment by Daniil1288** [comment]
works now, nice

**Comment by leonardosnt** [comment]
:+1:
