### ISSUE TITLE
[BUG REPORT] uEssentials AUTOREFUEL DONT WORK

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#244]
PT-BR 

O Plugin uEssentials quando uso o /refuel , ele altera a % de gasolina atual para 100% , porem quando a gente sai e entra novamente no carro ele da um bug e volta para a % antiga atual 

por favor teria como arrumar ? isso é muito útil :c

**Comment by leonardosnt** [comment]
Já corrigi esse problema, estará disponível na proxima release.
