### ISSUE TITLE
[BUG REPORT] uEssentials CLEAR EV

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#245]
PT-BR

Antigamente quando usava o comando /clearv era muito bom removia todos os carros no mesmo momento e sem dar bug , agora esse /clearev (novo) ele é muito ruim , as vezes ele da bug e não aparece nenhuma mensagem e também se o player tiver em um veiculo ele não é removido , e também tem veiculo que não é removido mesmo sem ter ninguém usando ele... 

por favor teria como arrumar ou voltar igual era antigamente ? :c

**Comment by leonardosnt** [comment]
Já foi reportado aqui #232

Aqui está funcionando normalmente, estou procurando o que está causando isso.
