### ISSUE TITLE
[SUGGESTION] LOSE SKILL FOR DEFAULT GROUP

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#246]
PT-BR

Da mesma forma que existe o essentials.keepskill.* que faz você não perder habilidade quando morre , seria possível fazer uma ao contrario , que faca perder todas habilidades upadas quando morrer ?

exemplo : essentials.loseskill.* 

queria poder adicionar isso ao meu servidor , para quem não é vip

**Comment by leonardosnt** [comment]
Basta colocar ```essentials.keepskill.0```
Isso indica que é pra salvar 0% das skills, ou seja, nada.

**Comment by leonardosnt** [comment]
Pra mais informações dê uma olhada na wiki https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference
