### ISSUE TITLE
AutoCommand MaxSkills on respawn

### ISSUE THREAD

**Issue by viperp12** [uEssentials/uEssentials#247]
nevermind.

**Comment by leonardosnt** [comment]
:Z

**Comment by viperp12** [comment]
Sorry, the post I made was not particularly helpful so I closed it and
removed it. I did not see a delete button.

**Comment by leonardosnt** [comment]
Ok

**Comment by viperp12** [comment]
Leonardo,

Good Afternoon! I have been having trouble doing the following things:
1. I'd like to set a player's keepskill to 90 when they log in
automatically, is that possible?
2. I would also like to set the tpa permissions for a player as a default.

Are those two things possible or would I have to set those permissions
every time they logged in?

Thank you,

**Comment by leonardosnt** [comment]
essentials.keepskill.90
essentials.command.tpa

**Comment by viperp12** [comment]
Thank you but doesn't that require me to authorize each player?

**Comment by leonardosnt** [comment]
Just add these permissions to group that you want.

**Comment by viperp12** [comment]
I'll try to add them to the default group. :) Thanks for your responses. I
develop in Unity, so this is pretty fun to see :).

**Comment by viperp12** [comment]
Adding it to the default group worked, thank you for your response.
Sometimes it is those little things that make it MUCH easier to work with.
:)

**Comment by leonardosnt** [comment]
:+1:

**Comment by viperp12** [comment]
Ok, it does not appear to be working now. I still have it in the Rocket
permissions set to essentials.command.tpa, but for some reason it says they
don't have permission.

**Comment by viperp12** [comment]
Nevermind, it's working again.

**Comment by viperp12** [comment]
Afternoon,

Do you know of a way, or is it already in Essentials to have vehicle
ownership?
