### ISSUE TITLE
Tpa??? Can you?

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [uEssentials/uEssentials#248]
Please Add Tpa. Previous authors completely forgot plugin and no longer update

**Comment by leonardosnt** [comment]
WHAT?

**Comment by ZSHADOWWOLF** [comment]
Russian?

**Comment by leonardosnt** [comment]
go on, i will try to translate.

**Comment by ZSHADOWWOLF** [comment]
Добавьте возможность телепорта между игроками. (Пример) https://dev.rocketmod.net/plugins/tpa-for-unturned/ Раньше использовался этот плагин,но авторы забили на него и больше не обновляют, а он перестал работать и теперь выдает ошибки

**Comment by leonardosnt** [comment]
/tpa already exists.

 https://github.com/uEssentials/uEssentials/issues/146

**Comment by ZSHADOWWOLF** [comment]
Тоесть ничего настраивать больше не нужно?

**Comment by leonardosnt** [comment]
Не понимаю.

**Comment by ZSHADOWWOLF** [comment]
Правила для гостей нужны?

**Comment by leonardosnt** [comment]
Я не понимаю, извините.

**Comment by ZSHADOWWOLF** [comment]
Permissions for players need it?

**Comment by leonardosnt** [comment]
Just essentials.command.tpa

**Comment by ZSHADOWWOLF** [comment]
Thanks - Спасибо

**Comment by leonardosnt** [comment]
:D
