### ISSUE TITLE
uEssentials Death Message Error

### ISSUE THREAD

**Issue by EremesGuile** [uEssentials/uEssentials#249]
I have an issue after the update. How do I disable this? Currently have sadosku Death Message plugins too.

uEssentials >> Broadcast: Lang: Key not found 'DEATH_WATER', report to an adminstrator.

**Comment by Daniil1288** [comment]
remove your lang_.json file, helped for me

**Comment by EremesGuile** [comment]
Ok now I have 2 Death Message. LOL!

**Comment by leonardosnt** [comment]
Update your translation file (translations/lang_*.json).

**Comment by EremesGuile** [comment]
Thanks! The problem solved. Now I'm using uEssentials Death Message. Awesome!

**Comment by leonardosnt** [comment]
@EremesGuile  :D
