### ISSUE TITLE
/time

### ISSUE THREAD

**Issue by WGSRangerWolf** [uEssentials/uEssentials#25]
time command.

**Comment by leonardosnt** [comment]
Unturned already have that.

/day
/night
/time X

**Comment by waspkiller** [comment]
I ment server system time command.. do/stime then for system time. lets say when you do /stime The command sees the computer time

**Comment by leonardosnt** [comment]
How would this be useful?

**Comment by waspkiller** [comment]
It would be useful to me due to our server restarts at a specific time
