### ISSUE TITLE
[Suggestion] Trade Item Option

### ISSUE THREAD

**Issue by EremesGuile** [uEssentials/uEssentials#250]
Is it possible in Unturned?

**Comment by leonardosnt** [comment]
Explain to me, how does it works?

**Comment by EremesGuile** [comment]
I don't know leonard That's why I ask. XD

IMHO, maybe its like TPA. Using /trade [playername], /trade accept, /trade deny with some limitation on the range rather than full map range. If its possible, A use /trade on B and B /trade accept. A trade interface (some sort like bag interface) will pop up with Confirm button for both A and B. For item transferring function I don't know. XD

**Comment by leonardosnt** [comment]
@EremesGuile With "buttons" or an user interface is not possible, but with commands is.

Sorry for my english, if you not understood, tell me.

**Comment by EremesGuile** [comment]
@leonardosnt I understand. Hehe. 
So it's a trade by text chat right. Is it hard? Need a workflow how does trade happen.
The interface is not possible? No floating bag interface can be spawn with simple button?

**Comment by leonardosnt** [comment]
No it's not hard, maybe I'll create a separate module for it.

And no, Unturned does not support.

**Comment by EremesGuile** [comment]
@leonardosnt Thank you! You are the best!
