### ISSUE TITLE
Premissions

### ISSUE THREAD

**Issue by lammas112** [uEssentials/uEssentials#252]
Hello i have this error in rocket premissions everything works like TPA etc but the kits are werid normal and vip players get error (you dont have premission for this kit) but in premissions i cleary put essentials.kit.name and still nothing only admin gets them
Help meh 
regards ed

**Comment by lammas112** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Color>white</Color>
      <Members />
      <Permissions>
        <Permission>p</Permission>
        <Permission>compass</Permission>
        <Permission>home</Permission>
        <Permission>rocket</Permission>
        <Permission>tpa</Permission>
        <Permission>tpa.send</Permission>
        <Permission>tpa.accept</Permission>
        <Permission>kits</Permission>
        <Permission>essentials.kit.Cowboy</Permission>
        <Permission>essentials.kit.Hunter</Permission>
        <Permission>essentials.kit.Starter</Permission>
      </Permissions>

**Comment by leonardosnt** [comment]
Try

```xml
<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Color>white</Color>
      <Members />
      <Permissions>
        <Permission>p</Permission>
        <Permission>compass</Permission>
        <Permission>home</Permission>
        <Permission>rocket</Permission>
        <Permission>tpa</Permission>
        <Permission>tpa.send</Permission>
        <Permission>tpa.accept</Permission>
        <Permission>essentials.command.kits</Permission>
        <Permission>essentials.command.kit</Permission>
        <Permission>essentials.kit.cowboy</Permission>
        <Permission>essentials.kit.hunter</Permission>
        <Permission>essentials.kit.starter</Permission>
      </Permissions>
```

**Comment by lammas112** [comment]
Works like butter :) thx keep up the good work :)

**Comment by leonardosnt** [comment]
:)
