### ISSUE TITLE
Lang Key not found 

### ISSUE THREAD

**Issue by Riddler76** [uEssentials/uEssentials#255]
Hi,
Have this error when player death 

Essentials >> Broadcast: Lang: Key not found 'DEATH_SUICIDE', report to an adminstrator.

**Comment by leonardosnt** [comment]
Update your translation file. translations/lang_en.json

You can just delete the translations/ folder, but if want to keep your old translations you need to update manually.

**Comment by Riddler76** [comment]
Ok, thanks for help :)
