### ISSUE TITLE
CONFIG /FREEZE PLAYER , NOT WORK

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#259]
Esta configuração do essentials (config.json) , não está funcionando.

Quando altero ela não tem efeito algum... 

line 5 and 6

"UnfreezeOnDeath": true
  "UnfreezeOnQuit": true

**Comment by leonardosnt** [comment]
Vai estar disponível na próxima atualização.

Se você gosta do meu projeto não se esquece de deixar sua estrela :D

**Comment by OldCash4u** [comment]
Seu plugin é maravilhoso merece muito mais que uma só estrela ^^
