### ISSUE TITLE
Kit not work

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [uEssentials/uEssentials#26]
I dont understand why this kit not work     
    "Name": "darmy",
    "Items": [
      {
        "Id": 1011,
        "Durability": 100,
        "Amount": 1
      },
      {
        "FireMode": "AUTO"
		"Id": 363,
        "Durability": 100,
        "Amount": 1
		"Ammo": 30
      },
	  {
        "Id": 121,
        "Durability": 100,
        "Amount": 1
      },
	  {
        "Id": 6,
        "Amount": 4
		"Ammo": 30
      },
	  {
        "Id": 1012,
        "Durability": 100,
        "Amount": 1
      },
	  {
        "Id": 148,
        "Durability": 100,
        "Amount": 1
      },
	  {
        "Id": 8,
        "Durability": 100,
        "Amount": 1
      },
	  {
        "Id": 151,
        "Durability": 100,
        "Amount": 2
      },
	  {
        "Id": 7,
        "Durability": 100,
        "Amount": 1
      },
	  {
        "Id": 333,
        "Durability": 100,
        "Amount": 1
      },
	  {
        "Id": 337,
        "Durability": 100,
        "Amount": 1
      },
	  {
        "Id": 80,
        "Durability": 100,
        "Amount": 6
      },
	  {
        "Id": 77,
        "Durability": 100,
        "Amount": 6
      },
	  {
        "FireMode": "AUTO"
		"Id": 99,
        "Durability": 100,
        "Amount": 1
		"Ammo": 20
      },
	  {
        "Id": 334,
        "Durability": 100,
        "Amount": 1
      },
	  {
        "Id": 1006,
        "Amount": 3
		"Ammo": 40
      },
	  {
        "Id": 1013,
        "Durability": 100,
        "Amount": 1
      },
	  {
        "Id": 253,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 111,
        "Durability": 100,
        "Amount": 1
      },
	  {
        "Id": 76,
        "Durability": 100,
        "Amount": 1
      },
	  {
        "Id": 394,
        "Durability": 100,
        "Amount": 9
      },
      {
        "Id": 395,
        "Durability": 100,
        "Amount": 3
      },
	  {
        "Id": 403,
        "Durability": 100,
        "Amount": 2
      },
      {
        "Id": 1010,
        "Durability": 100,
        "Amount": 1
      }

**Comment by leonardosnt** [comment]
What is happening?

**Comment by leonardosnt** [comment]
This is wrong, missing a lot of commas.

https://www.diffchecker.com/lu8lneua

```json
    "Items": [
    {
    "Id": 1011,
    "Durability": 100,
    "Amount": 1
    },
    {
    "FireMode": "AUTO",
    "Id": 363,
    "Durability": 100,
    "Amount": 1,
    "Ammo": 30
    },
    {
    "Id": 121,
    "Durability": 100,
    "Amount": 1
    },
    {
    "Id": 6,
    "Amount": 4,
    "Ammo": 30
    },
    {
    "Id": 1012,
    "Durability": 100,
    "Amount": 1
    },
    {
    "Id": 148,
    "Durability": 100,
    "Amount": 1
    },
    {
    "Id": 8,
    "Durability": 100,
    "Amount": 1
    },
    {
    "Id": 151,
    "Durability": 100,
    "Amount": 2
    },
    {
    "Id": 7,
    "Durability": 100,
    "Amount": 1
    },
    {
    "Id": 333,
    "Durability": 100,
    "Amount": 1
    },
    {
    "Id": 337,
    "Durability": 100,
    "Amount": 1
    },
    {
    "Id": 80,
    "Durability": 100,
    "Amount": 6
    },
    {
    "Id": 77,
    "Durability": 100,
    "Amount": 6
    },
    {
    "FireMode": "AUTO",
    "Id": 99,
    "Durability": 100,
    "Amount": 1,
    "Ammo": 20
    },
    {
    "Id": 334,
    "Durability": 100,
    "Amount": 1
    },
    {
    "Id": 1006,
    "Amount": 3,
    "Ammo": 40
    },
    {
    "Id": 1013,
    "Durability": 100,
    "Amount": 1
    },
    {
    "Id": 253,
    "Durability": 100,
    "Amount": 1
    },
    {
    "Id": 111,
    "Durability": 100,
    "Amount": 1
    },
    {
    "Id": 76,
    "Durability": 100,
    "Amount": 1
    },
    {
    "Id": 394,
    "Durability": 100,
    "Amount": 9
    },
    {
    "Id": 395,
    "Durability": 100,
    "Amount": 3
    },
    {
    "Id": 403,
    "Durability": 100,
    "Amount": 2
    },
    {
    "Id": 1010,
    "Durability": 100,
    "Amount": 1
    }
    ],
```

**Comment by leonardosnt** [comment]
Use this http://www.jsonschemavalidator.net/ to check if your kits are valid. it will show errors.

**Comment by leonardosnt** [comment]
![](http://i.imgur.com/teoyYPY.png)
