### ISSUE TITLE
[SUGGESTION] CONFIG COLOR IN PRIVATE MESSAGE

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#260]
Seria possível configurar uma cor em mensagens privadas ? 

na linha 3 e 4

"PrivateMessageFormat": "Recebido de [{0}] : {1}",
 "PrivateMessageFormat2": "Enviado a [{0}] : {1}",

**Comment by leonardosnt** [comment]
Sim, olha aqui https://raw.githubusercontent.com/uEssentials/uEssentials/master/default/lang_pt-br.json no inicio explica como fazer isso.

**Comment by OldCash4u** [comment]
eu sei que está explicando , mas essa mensagem privada , não fica em lang_pt-br.json , é localizada no config.json a onde tem efeito nulo colocar <blue> , etc 

não funciona nesse outro arquivo

**Comment by leonardosnt** [comment]
:+1:
