### ISSUE TITLE
[SUGGESTION] /REFUELGENERATOR <ALL>

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#261]
PT-BR

Da mesma forma que existe o /refuelvehicle <all> , seria possível existir um comando que colocaria gasolina nos geradores ?  obrigada , aguardo resposta ! 

exemplo : /refuelgenerator <all | radius> 

:)

**Comment by lammas112** [comment]
Would be good command especially for the huge gens ...

**Comment by leonardosnt** [comment]
#256
#417
