### ISSUE TITLE
[BUG REPORT] COLOR IN PRIVATE MESSAGE , NOT WORK

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#262]
A Configuração da cor desta mensagem não fica localizado em "translations" , ele fica na config.json do essentials , quando eu coloco exemplo <blue> ele não tem efeito algum... as cores só funciona nos arquivos de translations , o config não

**Comment by leonardosnt** [comment]
Você já reportou aqui #260

Vou corrigir assim que possível.
