### ISSUE TITLE
Issue with Linux (Lag player death)

### ISSUE THREAD

**Issue by Riddler76** [uEssentials/uEssentials#265]
Hi,

I have 2 dedicated server with Unturned server install on it.
On my windows server, i don't have problem.

On my linux server, when a player die, the server have a lag spike and disconnect some people.

I don't have error in console.

My plugin list 

- AutoShutdown2.dll
- FeexRanks.dll
- Kits.dll
- MessageAnnouncer.dll
- Votifier.dll
- ZaupUconomyEssentials.dll
- FeexHitman.dll
- GlobalBan.dll
- LPX.dll
- Uconomy.dll
- ZaupFeast.dll

And uEssential (Disable for moment)

**Comment by Riddler76** [comment]
I found the solution !

I have this problem on windows too.
Just disable unfreeze in config. 

  "UnfreezeOnDeath": false,
  "UnfreezeOnQuit": false,

**Comment by Riddler76** [comment]
Oh no is not the solution.

**Comment by Riddler76** [comment]
If you need video, exemple ... I can do it for you. Just say me what you need ;)

**Comment by leonardosnt** [comment]
@Riddler76 You seen any error in console? (When player dies)

**Comment by Riddler76** [comment]
Sometimes i have a message. I put one tooday.

**Comment by Riddler76** [comment]
http://screenshots.freeforfriends.fr/repository/RidShots/clipboard_2016-05-11_18-24-18.png

**Comment by leonardosnt** [comment]
Send me the full screenshot pls,
I need to check the stacktrace...

**Comment by Riddler76** [comment]
I send you tooday ;) Do you want a .log ?

**Comment by Riddler76** [comment]
http://screenshots.freeforfriends.fr/repository/RidShots/clipboard_2016-05-12_13-33-33.png

**Comment by Riddler76** [comment]
http://screenshots.freeforfriends.fr/repository/RidShots/Rocket.log

**Comment by YuRaNnNzZZ** [comment]
I had this problem too. For me it's `ZaupUconomyEssentials.dll` that kicks all players. The "lag spike" happens because this plugin connects to database each time if some event occurs (zombie killed, player died etc). I have removed all plugins that using MySQL and server not kicking anyone.
You may want to move your database to the machine that hosts your server, so plugins will reach it instantly and will not kick players.

**Comment by leonardosnt** [comment]
@YuRaNnNzZZ Ok, thanks.
