### ISSUE TITLE
Some commands and permissions not working.

### ISSUE THREAD

**Issue by EqlipseD** [uEssentials/uEssentials#268]
A few of my players are saying they are having issues with /home saying that it says they are moving when they are standing completely still.

TPA is also not working properly, I have my permissions setup perfectly fine and they were working before this update.

Also essentials.keepskill.* is not currently working as well.

**Comment by leonardosnt** [comment]
TPA permission was changed

Change `essentials.command.tpa` to `essentials.command.tpa.*`

See #263

**Comment by EqlipseD** [comment]
Alright so that fixes my TPA problem, thanks for that. /home is still not working along with keepskill. 

Thanks for the fast reply.

**Comment by leonardosnt** [comment]
:+1: 

Working On

**Comment by leonardosnt** [comment]
Change `essentials.keepskill.*` to `essentials.keepskill.100`

**Comment by leonardosnt** [comment]
essentials.keepskill.* is working fine too.

**Comment by EqlipseD** [comment]
My players are still having issues with the essentials.keepskill.* and essentials.keepskill.100. They are still losing their skills upon death.

**Comment by leonardosnt** [comment]
Ok, i will check again.
