### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by seliv2** [uEssentials/uEssentials#27]
Please add the ability to disable certain functions such as plug-in kit warp, they interfere with the other pre-configured plug-ins ( conflict )

**Comment by leonardosnt** [comment]
Config:

```json
"DisabledCommands": [
    "kits",
    "kit",
    "warp",
    "warps"
]
```

**Comment by seliv2** [comment]
Sorry, string no_permissions

**Comment by waspkiller** [comment]
What are you trying to do? Are you tring to disable some functions uessentials came with or are you trying to add permissions. there has been some conflicts on my current Stuff and i narrowed it down to the item command. here is my configuration for disabled commands.
```
"DisabledCommands": [
		"kit",
		"kits",
		"warps",
		"warp",
		"item"
	]
```

**Comment by waspkiller** [comment]
the item command had some weird conflicts with rocketmods default /i

**Comment by seliv2** [comment]
Sorry, i am have erorrs the coded config file :D. Verry Thanx

**Comment by leonardosnt** [comment]
@waspkiller Essentials /i replaces Rocket /i

He's an improved version of Rocket /i.
