### ISSUE TITLE
Error...Again

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [uEssentials/uEssentials#272]
Нужно обновление. Также после этого обновления включился ваш Death Message, хотя изначально прописано что он отключен! http://s018.radikal.ru/i507/1605/86/b4a1e92a8fe4.jpg

**Comment by Daniil1288** [comment]
как сказал наш cartman-2000 вот здесь https://github.com/RocketMod/Rocket.Unturned/pull/23#issuecomment-219202524, был убран ивент PlayerUpdatePosition из исходников рокетки, а значит, что отсюда тоже надо убрать все связанное с ним. Ну, по крайней мере мне это помогло. Вот длл с фиксом (внимание! не работает кулдаун на телепорт домой!): https://yadi.sk/d/u1on04CcrhgF5

**Comment by Riddler76** [comment]
Hey, i have same here.

I delete configuration. No solve :(

**Comment by EqlipseD** [comment]
Just relax guys, it has to be updated again.

**Comment by leonardosnt** [comment]
I'm updating now....

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/releases/tag/1.2.2.2

**Comment by Riddler76** [comment]
Nice ;)
