### ISSUE TITLE
WebConfig and WebKits

### ISSUE THREAD

**Issue by JustOneMoreBlock** [uEssentials/uEssentials#273]
Hello,

Currently, I’ve been trying to get WebConfig working globally across all my servers. However, I’m not sure if I’m misunderstanding something, or the system is not working.

You can find my config.json here;
https://justplayhere.com/unturned/public/uEssentials/config.json

```
  "WebConfig": {
    "Url": "https://justplayhere.com/unturned/public/uEssentials/config.json",
    "Enabled": true
  },
```

Enabled or not, the WebConfig doesn’t load at all from the Web Server.

First Solution
Make it load as intended. However, I’d rewrite the config like the following;

```
{
  "WebConfig": {
    "Url": "https://justplayhere.com/unturned/public/uEssentials/config.json",
    "Enabled": true
  }
}
```
Nothing else would be stored in the new config.js as you would be enabling the WebConfig, reloading uEesstions would reload the config.js from the Web.

Second Solution
Well, still make it load. However, possibly cache/write the config.js into the server folder of that location. Possibly, may have to check and make sure they’re no syntax errors and if so, disregard it and keep the original cached version.

Your WebKits systems work great too.
https://justplayhere.com/unturned/public/uEssentials/kits.json

The only question is, I was reading the Kits wiki, and I saw money on there. Is this for your Economy system or is there a way to integrate with Uconomy?

Kind Regards,
Cory

**Comment by leonardosnt** [comment]
I will check...

...

uEssentials does not have economy system yet, you can use Uconomy or ingame experience.

For Uconomy, just add he in your plugins.
For 'ingame experience' you need to enable it on config.json.
```
"Economy": {
  "UseXp": false,          <------- true
  "XpCurrency": "Xp",
  "UconomyCurrency": "$"
},
```

**Comment by leonardosnt** [comment]
I implemented new system for "web resources"...
