### ISSUE TITLE
[BUG REPORT] PERMISSION /ITEMINFO WORK PARTIALLY 

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#275]
PT-BR

A Permissão "iteminfo" do comando "/iteminfo ou /ii" está funcionando normalmente quando está com um item na mão , mas quando você não está segurando nada a onde deveria aparecer a mensagem da EMPTY_HANDS ele simplesmente diz que você não tem permissão.  

Ou seja a permissão só esta funcionando quando você está com algum item na mão , se você não estiver ele fala que não tem permissão.

**Comment by leonardosnt** [comment]
Aqui ta funcionando perfeitamente

![](http://i.imgur.com/KMyUvPZ.png)

**Comment by leonardosnt** [comment]
Vê se não é problema na tua tradução.

**Comment by OldCash4u** [comment]
Era sim , arrumei está funcionando normalmente. Obrigada !
