### ISSUE TITLE
[BUG REPORT]  RESTRICTION TPA NOT WORKING

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#276]
PT-BR

"CANNOT_TELEPORT_DRIVING" e "TPA_CANNOT_TELEPORT" , A onde deveria ser bloqueado o tpa quando alguém estiver em um veiculo ou aceitar , não funciona... 

E também não tem nenhuma configuração para ativar estas duas acoes ou desativar. 

Tem como ser arrumado ? :P

**Comment by leonardosnt** [comment]
Isso não é configurável, sempre deve estar ativado pois senão o jogador fica bugado.

**Comment by OldCash4u** [comment]
Sim deveria ficar ativado , mas não esta... Os jogadores estão ficando bugado aceitando e dando tpa em veículos !  Por favor , arruma :c

**Comment by leonardosnt** [comment]
Ta funcionando também

![](http://prntscr.com/b5q7s0)

Ele só manda essa mensagem quando você aceitar (caso esteja dentro de um veiculo);
