### ISSUE TITLE
[SUGGESTION] TURN / CLEAR V

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#277]
PT-BR

O /clear v era bem melhor que esse atual /clear ev que também é cheio de bugs

Seria possível a sua volta ? :c

**Comment by leonardosnt** [comment]
Ambos estão bugados, parece que o unturned não suporta muito bem um monte de pacotes sendo enviados ao mesmo tempo.

Eu ainda vou arrumar isso.
