### ISSUE TITLE
[SUGGESTION]  SET COMMAND MESSAGE /TPA

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#279]
PT-BR

Teria como configurar a mensagem de quando digita ./tpa ? Porque aparece "/tpa [plater/accept/denny/cancel]" , para ser configurado a gosto , com a intenção de facilitar o entendimento de novos jogadores dos comandos... e para quem não fala english também , eu procurei no arquivo de tradução e não tem nada para definir essa mensagem !  :c

**Comment by leonardosnt** [comment]
Isso fica no código, não tem como modificar, todos os comandos são assim.

Pode ser que eu coloque para ser configurado no `commands.json`

**Comment by OldCash4u** [comment]
Sim por favor , ja iria ajudar ! :+1:
