### ISSUE TITLE
These commands won't work no matter how i write it.

### ISSUE THREAD

**Issue by daseki** [uEssentials/uEssentials#28]
spy, ascend, descend, autoreload/autorepair or itemfeatures/vehiclefeatures don't work.
http://pastebin.com/nV2Ac2bg
I had my programmer friend take a look at it and he can't get it to work. i cleaned up my config so its easier to look at and just kept the essentials.command.<command_name> like the maker said to everything else BUT those work. 
I think they may just be bugged for groups cause they work for the admin/owner when i try them.

**Comment by leonardosnt** [comment]
I know that is causing it, i will fix it now.

**Comment by leonardosnt** [comment]
Fixed in e43e9f9210714b4340285ae8d9406f10be625382

Wait for release.

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/releases/tag/1.0.6.4

If you love this project, do not foget to leave your star :D
