### ISSUE TITLE
Poll Not working

### ISSUE THREAD

**Issue by iCuss** [uEssentials/uEssentials#280]
Basically the poll itself runs fine but when it closes it does not save anyone's votes that they did. Any way to fix?

**Comment by Alec123445** [comment]
I am having the same issue. Also it if you do /vote no it says you voted yes

**Comment by pepixiko** [comment]
cual son los permisos? me lo podeis decir por favor?

**Comment by pepixiko** [comment]
which are permissions? can you tell me please?

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference

**Comment by pepixiko** [comment]
http://pastebin.com/YYbgVb4j 
español: lo tengo asi y no lo se que hacer como activarlo, me dice dentro del juego que no tengo permisos
english: I have it well and do not know how to activate it, tells me ingame I have no permissions

**Comment by pepixiko** [comment]
leonard please help me https://github.com/uEssentials/uEssentials/issues/353
