### ISSUE TITLE
[SUGGESTION] CLEAN PERMISSION ONLY OWN INVENTORY

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#281]
PT-BR

Seria possível desenvolver uma permissão para o jogador limpar somente o inventario dele mesmo e não pode limpar o dos outros ? :c

Porque aquela permissão do clearinventory o /ci , ele pode limpar o dele e de quem ele quiser...

**Comment by leonardosnt** [comment]
Isso já existe, acho que você deveria dar uma olhada na wiki antes de criar sugestões.

O jogador só pode limpar o inventario de outro jogador caso ele tenha a permissão `essentials.command.clearinventory.other`

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki
