### ISSUE TITLE
[SUGGESTION] IN THE SAME COMMAND?

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#282]
PT-BR

Sera que é possível criar um comando para o itemfeatures & vehiclefeatures que ative e desative todas as funções dos dois juntos ao mesmo tempo ? Exemplo : /ifv all (on - off)

E também ativar todas funções dos dois individualmente ? Exemplo : /if all (on - off) & /vf all (on - off)

Também seria possível ativar eles para um certo jogador ? Exemplo : /ifv all (on - off) player 

Iria ser muito bacana se desse certo fazer isso , alem de facilitar a vida dos administradores ! :+1:  
Não sei se ficou muito confuso... ahuahua mas espero que você consiga me entender :3

**Comment by OldCash4u** [comment]
PT-BR

Já tem o /if all e o /vf all , agora só falta fazer o /ifv all , :D 
obrigado @leonardosnt  por já fazer grande parte s2

**Comment by leonardosnt** [comment]
Não vou adicionar o `/ifv all` pois acho redundante.

Em breve vou adicionar um sistema de aliases, ou vou adicionar argumentos no text_commands...
