### ISSUE TITLE
[SUGGESTION] SHOW OF STEAMID A PLAYER

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#283]
PT-BR

Teria alguma forma de criar um comando que desse para descobrir o steamid de um jogador online no servidor ? Exemplo : ./steamid player , Name : G15 - SteamID : 76561198132155279

Iria ser muito útil para descobrir o steamid de jogadores e poder adicionar em certos grupos como , MODERADOR , ADMINISTRADOR... sem tem que adicionar ele na steam :+1:

**Comment by leonardosnt** [comment]
O Rocket já tem esse comando, é `/investigate [jogador]`
