### ISSUE TITLE
[DOUBT] NO RESPONSE RECEIVED ?

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#284]
PT-BR

leonardosnt , Porque existem alguns tópicos antigos que nunca foi analisados ou respondidos  ? 

a 18 dias atras criei 2 tópicos de sugestão e até hoje nunca obtive nenhum resposta :c
foi o #261 e #258 > http://prnt.sc/b5r6l0

Os Administradores , Moderadores e Jogadores do meu servidor sempre perguntão sobre se houve alguma resposta sua ou noticia , sobre os tópicos criados , você é muito bom no trabalho que faz e que da progresso aos servidores de Unturned , eu imagino que deve dar trabalho e tudo mais... respeito ao máximo , você é bastante atencioso e dedicado ao que faz ! entendo o seu lado :+1: 

Gostaria muito de ter uma resposta para ser passado a eles. #thebestprogrammer

**Comment by leonardosnt** [comment]
Essas duas sugestões já foram criadas antes. #1, #256.

Eu to sem tempo para implementar...
