### ISSUE TITLE
[BUG REPORT] KEY ASCENDED FADING

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#285]
PT-BR

A "KEY ASCENDED" fica sumindo da configuração de tradução quando dou reload no essentials , e também quando reinicia o servidor...

Causando o erro http://prnt.sc/b5shl3 

Pensei que o problema era meu arquivo de tradução , testei com o original lang_pt-br que vem com o essentials e também não está funcionando , ela simplesmente fica sumindo do arquivo de tradução e depois da esse erro  :/

não está funcionando na lang_en e também lang_pt-br (não testei as outras línguas)

**Comment by leonardosnt** [comment]
Adicione

`"ASCENDED": "You ascended {0} 'meters'",`

no seu arquivo de tradução.
