### ISSUE TITLE
Hi, i've got an idea. coud you please make a system that limits players in each group ?

### ISSUE THREAD

**Issue by qwexvf** [uEssentials/uEssentials#288]
Hi, i've got an idea. coud you please make a system that limits players in each group ?

for example in my server, 24max of 16 are in one group sometimes they playing 1 vs 16 lol.

Its not funny i want to limits players for each group. thanks.

**Comment by leonardosnt** [comment]
Permissions group ?

**Comment by cellinho** [comment]
Sorry, no. the group managed by steam thing.
so with the group you can make your team in the game.

**Comment by leonardosnt** [comment]
I think this is a special thing, is not useful for everyone.
