### ISSUE TITLE
Safezones

### ISSUE THREAD

**Issue by MiffedLyric559** [uEssentials/uEssentials#289]
It would be so cool if you could add safezones.
So that you can do /safezone add (range) (flags)
You could have like different flags like nopvp or no build and no zombies and stuff like that.

And maybe some other cool futures

**Comment by MiffedLyric559** [comment]
Also if possible you could do so some commands only work in this and this safezone.

There should be a lot to configure in the configuration file

**Comment by leonardosnt** [comment]
https://dev.rocketmod.net/plugins/regions/
