### ISSUE TITLE
/p not work

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [uEssentials/uEssentials#291]
После обновления игры + сервера на новую версию команда перстала работать так как надо. Я не могу во время игры выдать игрокам права (Хотя до обновления все работало) При это никаких ошибок,ничего просто - Неверная команда

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/releases/tag/1.2.2.3

**Comment by ZSHADOWWOLF** [comment]
Not work. /p Tails Vip - Invalid parameter

**Comment by Daniil1288** [comment]
@ZSHADOWWOLF ээ... https://github.com/RocketMod/Rocket.Unturned/commit/80334ada4bd3ef3c5ae830c36189667d2607f270

**Comment by leonardosnt** [comment]
@ZSHADOWWOLF This is not related with uEssentails.
