### ISSUE TITLE
This is urgently!!!!!

### ISSUE THREAD

**Issue by cellinho** [uEssentials/uEssentials#292]
After the latest update any one has access to all commands. (including rocket commands)

Please check out and fix. 

Thanks.

**Comment by MrBlaszkNB** [comment]
Please fix this asap! D:

**Comment by leonardosnt** [comment]
Working perfectly here...

https://github.com/uEssentials/uEssentials/releases/tag/1.2.2.3

**Comment by MrBlaszkNB** [comment]
Permissions are working, but all players have access to all commands And
kits

**Comment by leonardosnt** [comment]
...

![](http://image.prntscr.com/image/f091d1e5f4eb454c8b8f23dbd672e525.png)
