### ISSUE TITLE
Anyone can has acces to command(/item,/vehicle)

### ISSUE THREAD

**Issue by root1k** [uEssentials/uEssentials#294]
After update everybody can use commands(/item,/vehicle,clearinventory,/clear,/itemfeatures,/tp and more).Commands /god,/vanish unavailable.http://imgur.com/3q5SwnA
P.S i am download this https://github.com/uEssentials/uEssentials/releases/tag/1.2.2.3
PLS, FIX IT.

**Comment by root1k** [comment]
And command permissions name group do not work from console.

**Comment by EremesGuile** [comment]
@leonardosnt

**Comment by Daniil1288** [comment]
@root1k that's actually a Rocket.Unturned change, it works, but not "/p name group", but "/p add name group" or something like that... look for Rocket.Unturned on github and find the commit that changed it.

**Comment by Daniil1288** [comment]
https://github.com/RocketMod/Rocket.Unturned/commit/80334ada4bd3ef3c5ae830c36189667d2607f270
^this one

**Comment by EremesGuile** [comment]
So how to fix it?

**Comment by leonardosnt** [comment]
Duplicated #293

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/issues/293#issuecomment-222310302
