### ISSUE TITLE
PERMISSION NOT WORKING , IF & VF !

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#297]
PT-BR

Quando dou a permissão essentials.command.itemfeatures e essentials.command.vehiclefeatures a pessoa consegue digitar o comando normalmente porem não consegue ativar e nem desativar... 

Aparece que ela não tem permissão quando digita /if autoreload on / on ... etc

 Como dou permissão de ativar e desativar o if e vf ?

**Comment by leonardosnt** [comment]
Você precisa especificar ``autorepair`` ou ``autoreload`` 

Ex:
``essentials.command.itemfeatures.autorepair``

O vehiclefeatures não precisa.

**Comment by OldCash4u** [comment]
adiciona isso na wikia , eu procurei la e não tinha achado :c

**Comment by leonardosnt** [comment]
Eu tinha esquecido de adicionar, já adicionei :D
