### ISSUE TITLE
uhh, my players cant use commands.

### ISSUE THREAD

**Issue by weespin** [uEssentials/uEssentials#298]
Hi, leo.
/home is not working( essentials.command.home)
/maxskills too ( essentials.command.maxskills)
Maybe another commands arent working.
Permissions from another plugins are working.
Using:LPX(https://github.com/IQbrod/Light_LPX)

**Comment by weespin** [comment]
Yep

**Comment by leonardosnt** [comment]
That is wrong, the permisson of `/tp` is `essentials.command.tp`

**Comment by weespin** [comment]
lol, i meaned /home xD
Its not working too. :3

**Comment by leonardosnt** [comment]
both /home and /maxskills are working perfectly.

**Comment by Daniil1288** [comment]
this one, I assume: https://github.com/lightphoenix2/LPX ? you can also download it from here: https://dev.rocketmod.net/plugins/light
People report the plugin as being broken, though... 
Someone fixed it here: https://github.com/IQbrod/Light_LPX , and that's the version that @weespin is using atm. You can get the dll from here: http://puu.sh/p9CiX/9438b05310.dll (INSECURE)

**Comment by leonardosnt** [comment]
@Daniil1288 Thx

**Comment by Daniil1288** [comment]
@leonardosnt np, :D

**Comment by weespin** [comment]
lel, plugin didnt created a home command in command text file 
/uEssentials/commands.txt

**Comment by weespin** [comment]
leo check maxskills permission.

**Comment by weespin** [comment]
Everything is working now.
