### ISSUE TITLE
Rocket changes...

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#299]
1)https://github.com/RocketMod/Rocket.Unturned/commit/d99e2b27a52b8c184cd818c08990d0338cc1e385
2)https://github.com/RocketMod/Rocket/commit/b276dae2aaa3033a989d4174f343097c479fcf65

----------------------------------------------------------------
1) Fixes HomeCommand.CancelWhenMove, most certainly.
2) Fixes all the problems related to /rocket reload. Consider improving /ess reload!

STILL WAITING ON THE .* PERMISSION FIX! INVESTIGATE THESE COMMITS: https://github.com/RocketMod/Rocket/commit/407e6abb4dec472b4bef7a96e0be7c9f4eae405e, https://github.com/RocketMod/Rocket/commit/3096e72039356439239871fe7912677bce52e2e7, https://github.com/RocketMod/Rocket/commit/566e9f90e9deccd19c6b08b920e2ce89152185cc!

**Comment by leonardosnt** [comment]
".* permission bug" is a Rocket bug and is not my priority now.

**Comment by Daniil1288** [comment]
alright, thank you! @leonardosnt
