### ISSUE TITLE
This Is A Suggestion.

### ISSUE THREAD

**Issue by Cooldude12251** [uEssentials/uEssentials#304]
Hello, i have a suggestion.

I see "uEssentials" has the "Refuelvehicles" On it, i was thinking how abort a refuel generators.
I don't know how you would do this, but i think it should be like this

                                       /refuelgenerator 10
So it would refuel generators in a range of 10, Or something like that

Also, Is their a ways you can make a "safezone" plugin but like it does not put them in god mode it just makes them not be able to die, But food water etc stills goes down?

                                                                   Thanks for your time.

                                                                           GoodBye

**Comment by leonardosnt** [comment]
#261
