### ISSUE TITLE
Why wont it work? 

### ISSUE THREAD

**Issue by NoireSan** [uEssentials/uEssentials#306]
Okay so i got this Gameservers unturned server right? And ive been trying to add perms for players if there anything wrong with this?
<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <DefaultGroup>vip</DefaultGroup>
  <Groups>
    <Group>
      <Id>vip</Id>
      <DisplayName>Default</DisplayName>
      <Color>FF9900</Color>
      <Members>
        <Member></Member>
      </Members>
      <ParentGroup>default</ParentGroup>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">tpa</Permission>
        <Permission Cooldown="0">home</Permission>
        <Permission Cooldown="0">tpa.accept</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>
No matter how many different ways i do it it wont work all that works is /p and /home not even compass works.

Thx for the help!

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference
