### ISSUE TITLE
Cannot give experience to other players

### ISSUE THREAD

**Issue by lammas112** [uEssentials/uEssentials#310]
I cannot give experience to other players it shows that i gave but they didnt recive (tested on 2 different pcs in different places) all suggestions are welcommed :)
regards ed

**Comment by vovan12361** [comment]
+

**Comment by Daniil1288** [comment]
same! @leonardosnt , pls fix?

**Comment by lammas112** [comment]
Also since i opened the issue ..... the * premission thing still doesnt work .... Just saying ...

**Comment by viperp12** [comment]
I have experienced this issue as well today.
