### ISSUE TITLE
Not working at all?

### ISSUE THREAD

**Issue by Falleno** [uEssentials/uEssentials#312]
It was all working fine till I downloaded the 922 version of rocket and now this plugin won't work. I tried re-uploading the dll file , it made the folder but no files inside

**Comment by JustOneMoreBlock** [comment]
Yeah, it's not loading the DLL.

http://pastebin.com/raw/uRHZaXfZ

**Comment by Invictumrex** [comment]
Yep, broken since update. Players aren't happy at all :+1:

**Comment by leonardosnt** [comment]
Fixed....

**Comment by Invictumrex** [comment]
You're a good man
