### ISSUE TITLE
Issue whit permission

### ISSUE THREAD

**Issue by xstonemetal** [uEssentials/uEssentials#313]
Hi leo, i have a problem whit permission, when i usse for example commands.keepskills,* or any commando whit " * " all player have permission for use all commmands 

this bug cause a great problem for me can u fix it pls?
pd: i update the spanish traslation i send via email

**Comment by leonardosnt** [comment]
This is a Rocket bug.

**Comment by xstonemetal** [comment]
i update the spanish translation

2016-06-12 17:06 GMT-04:00 Leonardo Santos <notifications@github.com>:
