### ISSUE TITLE
essentials.keepskill.* Does not appear to work for vip groups

### ISSUE THREAD

**Issue by viperp12** [uEssentials/uEssentials#319]
Despite vip having the parent group of default, and the keepskill.* present there it does not seem to apply to the admin.

I have successfully tested it multiple times on a non-admin, default group player several times, but for some reason, it will not work for my admin character. I get that it is easy to just max the skills, but that's not the point.

**Comment by viperp12** [comment]
Does this work for anyone else?

**Comment by viperp12** [comment]
Ok, so I am not sure how they are related, but it was this command that I had to remove from permissions in order for the rest of my kits, and other commands, and cooldowns to work properly.

**Comment by leonardosnt** [comment]
Don't use .* use

```
essentials.keepskill.overkill
essentials.keepskill.sharpshooter
essentials.keepskill.dexterity
essentials.keepskill.cardio
essentials.keepskill.exercise
essentials.keepskill.diving
essentials.keepskill.parkour
essentials.keepskill.sneakybeaky
essentials.keepskill.vitality
essentials.keepskill.immunity
essentials.keepskill.toughness
essentials.keepskill.strength
essentials.keepskill.warmblooded
essentials.keepskill.survival
essentials.keepskill.healing
essentials.keepskill.crafting
essentials.keepskill.outdoors
essentials.keepskill.cooking
essentials.keepskill.fishing
essentials.keepskill.agriculture
essentials.keepskill.mechanic
essentials.keepskill.engineer
```
Here is working fine.
