### ISSUE TITLE
uEssentials not loading

### ISSUE THREAD

**Issue by Alec123445** [uEssentials/uEssentials#325]
![image](https://cloud.githubusercontent.com/assets/18058634/16053859/5d021066-321f-11e6-85aa-e3957e357c5e.png)
i tried using other older builds and on other servers but on the other servers it doesnt even error.
Broke after using itemfeautres command

**Comment by leonardosnt** [comment]
Rocket version? (Build number)

**Comment by Alec123445** [comment]
oh yes ill make sure rockets updated.

**Comment by Alec123445** [comment]
v 4.9.5.0

**Comment by leonardosnt** [comment]
Update your Rocket...

**Comment by leonardosnt** [comment]
http://rocketmod.net/get-rocket

**Comment by Alec123445** [comment]
updated

**Comment by WGSRangerWolf** [comment]
is this issue still present?

**Comment by leonardosnt** [comment]
nop

**Comment by WGSRangerWolf** [comment]
Closed as issue is not present anymore
