### ISSUE TITLE
Weird error in console after people join

### ISSUE THREAD

**Issue by lammas112** [uEssentials/uEssentials#326]
Just no comment (facepalm)
Any suggestions (Log)= empty so i took a Screenshot :)
![capture](https://cloud.githubusercontent.com/assets/18724978/16056695/5b9c59a6-327f-11e6-946b-bd4168e7b521.PNG)

Thx for reading

**Comment by lammas112** [comment]
At loading 0 errors nothing ... just happens when people join ...

**Comment by leonardosnt** [comment]
This is not related with uEssentials.

**Comment by leonardosnt** [comment]
Probably your map/player data is corrupted.

**Comment by lammas112** [comment]
But rocket does not give any errors at all o.O and i can test without essentials
and make a server wipe

**Comment by lammas112** [comment]
wipe done...

**Comment by lammas112** [comment]
Request to close the map was bugged out....
Thx
