### ISSUE TITLE
/tpa instant

### ISSUE THREAD

**Issue by pepixiko** [uEssentials/uEssentials#327]
hi, i need your help my /tpa no have cooldown.
i have:
essentials.command.tpa.accept
essentials.command.tpa.send
essentials.command.tpa.cancel
essentials.command.tpa.deny
and
“Tpa”: {
“ExpireDelay”: 900,
“TeleportDelay”: 30
},

**Comment by leonardosnt** [comment]
Tpa for admins is instantly

**Comment by pepixiko** [comment]
and that it is, but it is for players

**Comment by pepixiko** [comment]
the permissions are those? or missing?

**Comment by pepixiko** [comment]
permissions which are tpa?
i have 
        <Permission Cooldown="900">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>

and it does not work

**Comment by leonardosnt** [comment]
essentials.command.tpa.accept	Allow use of /tpa accept.
  essentials.command.tpa.send	Allow use of /tpa send.
  essentials.command.tpa.cancel	Allow use of /tpa cancel.
  essentials.command.tpa.deny	Allow use of /tpa deny.

**Comment by pepixiko** [comment]
ok, in config:
   "Tpa": {
    "ExpireDelay": 100,
    "TeleportDelay": 30
  },

  "HomeCommand": {
    "Cooldown": 900,
    "Delay": 30,
    "CancelWhenMove": true
  },

I want the cooldown is the same as that of / home but instantly teleported if Cooldown: S

**Comment by pepixiko** [comment]
http://pastebin.com/KscVEjcV

**Comment by leonardosnt** [comment]
Delay is working fine.
