### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by viperp12** [uEssentials/uEssentials#328]
I have removed all essential kit permissions as a test, and players still have access to the /kits command, and all kits regardless. I know this use to work, and maybe I am missing something on the configuration.

**Comment by KamiBoku** [comment]
I have too your issue! I have try with this permissions :      
   
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="0">essentials.kit.Caçador</Permission>
        <Permission Cooldown="0">essentials.command.kit.Caçador</Permission>
        <Permission Cooldown="0">essentials.kit.Médico</Permission>
        <Permission Cooldown="0">essentials.command.kit.Médico</Permission>
        <Permission Cooldown="0">essentials.kit.Soldado</Permission>
        <Permission Cooldown="0">essentials.command.kit.Soldado</Permission>
        <Permission Cooldown="0">kit.Soldado</Permission>
        <Permission Cooldown="0">kits.Soldado</Permission>

And the people can write /kits and say "No exist some kits" and not working! 
Please fix this issue! Fast! I need this urgent!

**Comment by WGSRangerWolf** [comment]
https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference

**Comment by KamiBoku** [comment]
Bro i dont know , so i need your help! You can configure the my hastebin?
please?

**Comment by viperp12** [comment]
Check it out below, ALL kits are available to all players, and NONE of the cooldowns work anymore, even after a server restart and without the permissions being in place. The only way I can stop them from Spamming a kit is by removing it from the json completely or adding an xp cost.

I am going to reinstall my unturned server, hopefully that will correct it. 

<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Color>white</Color>
      <Members />
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.keepskill.*</Permission>
        <Permission Cooldown="900">heal</Permission>
        <Permission Cooldown="1800">essentials.command.home</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>vip</Id>
      <DisplayName>VIP</DisplayName>
      <Color>FF9900</Color>
      <Members>
        <Member>76561198016438091</Member>
      </Members>
      <ParentGroup>default</ParentGroup>
      <Permissions>
        <Permission Cooldown="0">effect</Permission>
        <Permission Cooldown="0">heal</Permission>
        <Permission Cooldown="30">v</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>


This is what it normally looks like:
<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Color>white</Color>
      <Members />
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="0">essentials.kit.standard</Permission>
        <Permission Cooldown="0">essentials.kit.survival</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.keepskill.*</Permission>
        <Permission Cooldown="900">heal</Permission>
        <Permission Cooldown="1800">essentials.command.home</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>vip</Id>
      <DisplayName>VIP</DisplayName>
      <Color>FF9900</Color>
      <Members>
        <Member>76561198016438091</Member>
      </Members>
      <ParentGroup>default</ParentGroup>
      <Permissions>
        <Permission Cooldown="0">effect</Permission>
        <Permission Cooldown="0">heal</Permission>
        <Permission Cooldown="30">v</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>

**Comment by viperp12** [comment]
OK! I figured it out!

essentials.keepskill.*

Basically I removed the above permission and everything started working again. In fact, all cooldowns started working again, and all permissions.

WOW! What a obtuse little command :+1:  I am sure it can be fixed. Thank you! I can live out that command for now.

**Comment by asdasd1** [comment]
can u help . my plugin already done for all 
but can u help me . when event players B send tpa to player  A . thats member A can accept request notif but stil cant accept that tpa . player A just have notification " You dont have any request" 
why thats
