### ISSUE TITLE
Permissions of Kits - Issue

### ISSUE THREAD

**Issue by KamiBoku** [uEssentials/uEssentials#329]
I have too your issue! I have try with this permissions :

    <Permission Cooldown="0">essentials.command.kits</Permission>
    <Permission Cooldown="0">essentials.command.kit</Permission>
    <Permission Cooldown="0">essentials.kit.Caçador</Permission>
    <Permission Cooldown="0">essentials.command.kit.Caçador</Permission>
    <Permission Cooldown="0">essentials.kit.Médico</Permission>
    <Permission Cooldown="0">essentials.command.kit.Médico</Permission>
    <Permission Cooldown="0">essentials.kit.Soldado</Permission>
    <Permission Cooldown="0">essentials.command.kit.Soldado</Permission>
    <Permission Cooldown="0">kit.Soldado</Permission>
    <Permission Cooldown="0">kits.Soldado</Permission>

And the people can write /kits and say "No exist some kits" and not working! 
Please fix this issue! Fast! I need this urgent!

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference

**Comment by leonardosnt** [comment]
Can you read the WIKI, plz???

**Comment by KamiBoku** [comment]
I read and i dont understand please add me on skype m.j199 and my name of
skype is: [̲̅D̲̅σ̲̅и̲̅σ̲̅]►ØɌĄŊǤĘƑØẌ™◄►🐺◄ for see the my configuration, i
dont understand!

**Comment by WGSRangerWolf** [comment]
Or you could post the cfg here

**Comment by KamiBoku** [comment]
See whats is wrong? http://hastebin.com/wugedukuge.xml

**Comment by leonardosnt** [comment]
/kit = `essentials.command.kit`
/kits = `essentials.command.kit`

For kits `essentials.kit.<kit name>`

**Comment by leonardosnt** [comment]
```
        <Permission Cooldown="120">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="0">essentials.kit.Caçador</Permission>
        <Permission Cooldown="0">essentials.command.kit.Caçador</Permission>                       // <<--- WRONG
        <Permission Cooldown="0">essentials.kit.Médico</Permission>
        <Permission Cooldown="0">essentials.command.kit.Médico</Permission>                       // <<--- WRONG
        <Permission Cooldown="0">essentials.kit.Soldado</Permission>
        <Permission Cooldown="0">essentials.command.kit.Soldado</Permission>                       // <<--- WRONG
        <Permission Cooldown="0">kit.Soldado</Permission>                       // <<--- WRONG
        <Permission Cooldown="0">kits.Soldado</Permission>                       // <<--- WRONG
```

**Comment by KamiBoku** [comment]
Not working bro!

**Comment by KamiBoku** [comment]
Add me on skype please and i will search my screen my skype is m.j1999 and
the name is [̲̅D̲̅σ̲̅и̲̅σ̲̅]►ØɌĄŊǤĘƑØẌ™◄►🐺◄

**Comment by WGSRangerWolf** [comment]
Wheres your commands list.

**Comment by leonardosnt** [comment]
Show me your kits.json.

**Comment by KamiBoku** [comment]
Bro i dont know , so i need your help! You can configure the my hastebin?
please?

**Comment by WGSRangerWolf** [comment]
those entry's should be inserted into your group Commands. theirs 2 different files. Find the one where you edit groups and commands and post it here

**Comment by KamiBoku** [comment]
http://hastebin.com/epuvucepud.cpp

**Comment by WGSRangerWolf** [comment]
would look like something like this
<command>rocket</command>

**Comment by WGSRangerWolf** [comment]
@leonardosnt hes putting the commands in the wrong area.

**Comment by KamiBoku** [comment]
sooo im am correct with this issues?

**Comment by leonardosnt** [comment]
@WGSRangerWolf But my permissions is working....

```xml
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">heal</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="0">essentials.kit.plane</Permission>
        <Permission Cooldown="0">essentials.kit.xp</Permission>
        <Permission Cooldown="0">essentials.kit.default2</Permission>
        <Permission Cooldown="0">essentials.kit.default</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.home</Permission>
        <Permission Cooldown="0">essentials.command.warps</Permission>
        <Permission Cooldown="0">essentials.command.maxskills</Permission>
        <Permission Cooldown="0">essentials.keepskill.40</Permission>
```

**Comment by WGSRangerWolf** [comment]
Will need to brush up on my rocketmod skills lol

**Comment by leonardosnt** [comment]
@KamiBoku Which version of Rocket you are using?

**Comment by KamiBoku** [comment]
Latest

**Comment by KamiBoku** [comment]
és portugues, porque o teu nome é portugues, e queria dizer que eu tenho um
ingles mau

**Comment by leonardosnt** [comment]
Ok.

Eu não sei o que pode estar acontecendo, aqui está funcionando perfeitamente.

Eu estou usando a versão mais recente do Rocket e do uEssentials...

:\

**Comment by KamiBoku** [comment]
Tens skype? É que assim puderia fazer partilha de ecra e ajudavas-me a resolver isto e não estou a entender nadinha mesmo.

**Comment by leonardosnt** [comment]
Não, faz tempo que não uso.

O que aparece quando você digita /kits ?

Quais outros plugins você está usando?

**Comment by KamiBoku** [comment]
Os plugins que eu tenho é seu! É o unico plugin que tenho no meu server, quando um player digita /kits diz "Nao ah nenhum kit disponivel "

**Comment by KamiBoku** [comment]
Pode me ajudar por favor?

**Comment by leonardosnt** [comment]
Tente apagar suas permissões atuais, ai só adicionar as que eu mostrei ali em cima...

**Comment by KamiBoku** [comment]
Pode organizar as minhas permissoes no Hastebin?
Por favor peço muito

**Comment by leonardosnt** [comment]
Tenta esse

```xml
<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Membro</DisplayName>
      <Color>white</Color>
      <Members />
      <Permissions>
        <Permission Cooldown="120">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="0">essentials.kit.Caçador</Permission>
        <Permission Cooldown="0">essentials.kit.Médico</Permission>
        <Permission Cooldown="0">essentials.kit.Soldado</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>vip</Id>
      <DisplayName>VIP</DisplayName>
      <Color>FF9900</Color>
      <Members>
        <Member>76561198097895742</Member>
      </Members>
      <ParentGroup>membro</ParentGroup>
      <Permissions>
        <Permission Cooldown="0">essentials.bypass.antispam</Permission>
        <Permission Cooldown="0">essentials.kit.Vip</Permission>
        <Permission Cooldown="0">essentials.command.home</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>
```

**Comment by KamiBoku** [comment]
Quando digito "/kits" diz "Não há nenhum kit disponivel" e quando digito "/kit" diz "Use /kit (kit_name)" e quando digito "/kit Soldado" diz "Você não tem acesso a esse kit"

**Comment by leonardosnt** [comment]
Cara aqui ta funcionando, eu não sei o que está acontecendo, tente baixar a versão experimental que eu arrumei um problema que tinha nos kits https://github.com/uEssentials/uEssentials/releases/tag/experimental

Tenho que sair agora.

**Comment by KamiBoku** [comment]
Hey Leonardo, i have updated the Rocket, and he not loading plugins. You
can update your plugin please?

2016-06-15 20:04 GMT+01:00 Leonardo Santos <notifications@github.com>:
