### ISSUE TITLE
Creating/deleting warps

### ISSUE THREAD

**Issue by DubFriendsFriendlyFriend** [uEssentials/uEssentials#33]
Remember that other issue with the extra "]"?

Well, when I deleted a warp the Warps.json recreated the error, putting the extra "]" back, thus again making the uEssentials unload itself.
http://i.imgur.com/enID5i7.png

I then deleted the "]", and the plugin works perfectly fine.

I added another random warp, and the extra "]" is back.

**Comment by DubFriendsFriendlyFriend** [comment]
It seems that using the command "rocket reload" or "rocket plugins reload uEssentials" also puts the extra "]" back.

**Comment by leonardosnt** [comment]
DONT use /rocket reload

**Comment by leonardosnt** [comment]
i will check

**Comment by leonardosnt** [comment]
Fixed.

If you love this project, do not foget to leave your star :D
