### ISSUE TITLE
Kit Issue

### ISSUE THREAD

**Issue by JustOneMoreBlock** [uEssentials/uEssentials#330]
Using Experimental Build to support #286 

A staff member executed:
`/kit DemoTeamCar`

Works fine. However, after a restart the kit_cooldowns.json file shows the following:

```
{
  "76561197972974462": {
    "Global": "0001-01-01T00:00:00"
  },
  "76561198066176197": {
    "Global": "0001-01-01T00:00:00"
  }
}
```

We are using WebKits:
https://justplayhere.com/unturned/public/uEssentials/kits.json

OR

```
  {
    "Name": "DemoTeamCar",
    "Items": [
      {
        "Vehicle": 93
      }
    ],
    "Cooldown": 0.0,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  },
```

Error in CONSOLE:
```
[Group] Doktor Krieger [Hanji Zo├½]: "/kit demoteamcar"
[uEssentials] System.NullReferenceException: Object reference not set to an inst
ance of an object
  at Essentials.NativeModules.Kit.Commands.CommandKit.OnExecute (ICommandSource
src, ICommandArgs args) [0x00000] in <filename unknown>:0
  at Essentials.Core.Command.CommandAdapter.Execute (IRocketPlayer caller, Syste
m.String[] args) [0x00000] in <filename unknown>:0
```

**Comment by pepixiko** [comment]
{
    "Name": "DemoTeamCar",
    "Items": [
      {
        "Vehicle": 93
      }
    ],
    "Cooldown": 0.0,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  }

( , ) delete

**Comment by JustOneMoreBlock** [comment]
@pepixiko That's not the issue.

```
  },
  {
    "Name": "DemoTeamCar",
    "Items": [
      {
        "Vehicle": 93
      }
    ],
    "Cooldown": 0.0,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "DemoTeamSigns",
    "Items": [
      {
        "Id": 1098,
        "Durability": 100,
        "Amount": 10
      }
    ],
    "Cooldown": 0.0,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  }
]
```

DemoTeamCar is secondary to the last and there is one more entry. Therefore, a , is required.

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/releases/download/experimental/uEssentials-experimental-2.zip

**Comment by JustOneMoreBlock** [comment]
This should be fine atm.

I did find an issue where my
 "Cooldown": 0.0,

.0 - May has broken the command and cause that error.

Either way, I'll let you know if it any more errors occurs and possibly pushes this to a released environment.

Been running Experimental Build 2 for about a day now.
