### ISSUE TITLE
UPDATE PLUGIN

### ISSUE THREAD

**Issue by KamiBoku** [uEssentials/uEssentials#332]
New version on ROCKET ! Please update!

**Comment by OldCash4u** [comment]
2

**Comment by jorea143** [comment]
Please update. Kits aren't working.

**Comment by KamiBoku** [comment]
Bro finally the plugin is working on new version

**Comment by BlackShape** [comment]
Yeah, Kits are broken :/

**Comment by JustOneMoreBlock** [comment]
The plugin is working fine using the Experimental Build. They're maybe some minor issues. However, it seems to be functional.

Kits are indeed broken, please wait patiently guys!

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/releases/tag/1.2.4.0
