### ISSUE TITLE
Put TPA with time for send and put with move cancel tpa.

### ISSUE THREAD

**Issue by KamiBoku** [uEssentials/uEssentials#333]
Put when you write /tpa and have cooldown, or when you write /tpa and you need be quiet for tpa when you move the tpa cancels
Sorry for bad english

**Comment by OldCash4u** [comment]
It would be nice there this :)

**Comment by pepixiko** [comment]
yes ,please!

**Comment by Toso10** [comment]
yes please!!!!!
