### ISSUE TITLE
[IMPROVEMENT] CANCELONMOVE

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#334]
PT-BR

Iria ser muito bom se existisse uma opção de configuração para cancelar pedido de teleporte do /home quando ativado o cancelonmove , de quando tomar dano cancelar o teleporte , ou morrer porque as vezes acaba teleportando e até bugando.

e também da mesma forma que existe o cancelonmove no /home , existir também no
/TPA e /WARP ... ? igual foi descrito no #333

**Comment by OldCash4u** [comment]
PT-BR

att , já no o cancelteleportwhenmove no warp , agora só falta no /tpa , @leonardosnt obrigado por já fazer uma parte , só falta a outra :D :+1:

**Comment by leonardosnt** [comment]
#478
