### ISSUE TITLE
[IMPROVEMENT] SHOW A MESSAGE TO NOT MOVE IN TELEPORTER

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#335]
PT-BR

Seria possível colocar uma mensagem quando o CancelWhenMove estiver ativado exemplo : "Você sera teletransportado para sua cama em breve. Não mova-se do seu local atual por {0} s!"

Teria como fazer isso por favor ? :3 os jogadores do meu servidor anda com duvida sobre isso , para eu não ter que ficar explicando toda hora

**Comment by KamiBoku** [comment]
PT-BR

É uma boa ideia ! Como nos tickets #333 e #334 . Por favor faça isso!

**Comment by leonardosnt** [comment]
Isso já existe. `"TELEPORT_DELAY": "Você será teleportado em {0}.",`
