### ISSUE TITLE
1 hour timer

### ISSUE THREAD

**Issue by symvizan** [uEssentials/uEssentials#336]
Hello!
On my server there is a 1 hour limit to any command to all players (including admins). So if I execute a command I have to wait an hour to be able to execute that command again. It doesnt affect commands which are in Rocket, and not uEssentials, like /god.
Please help!

**Comment by WGSRangerWolf** [comment]
`<Command cooldown=60>Random command</Command>`

**Comment by symvizan** [comment]
There is no command cooldown on any of them!

**Comment by symvizan** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Default</DisplayName>
      <Color>white</Color>
      <Members />
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">reward</Permission>
        <Permission Cooldown="0">balance</Permission>
        <Permission Cooldown="0">pay</Permission>
        <Permission Cooldown="0">essentials.command.vote</Permission>
        <Permission Cooldown="3600">essentials.warp.*</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="60">essentials.command.home</Permission>
        <Permission Cooldown="0">essentials.command.vote</Permission>
        <Permission Cooldown="0">essentials.kit.basic</Permission>
        <Permission Cooldown="0">essentials.kit.base</Permission>
        <Permission Cooldown="0">essentials.kit.quick</Permission>
        <Permission Cooldown="0">essentials.kit.tools</Permission>
      </Permissions>
    </Group>
etc.

**Comment by WGSRangerWolf** [comment]
Hm odd.

**Comment by WGSRangerWolf** [comment]
Show the whole config file.

**Comment by symvizan** [comment]
It is the default config file, and if I modify anything, still delay. I will try removing other plugins. I use Votifier, uEssentials, ZaupFeast and TPS.

**Comment by symvizan** [comment]
I reinstalled the server and the delay is removed. At least for admins. I do not know if it is removed for players yet.

**Comment by symvizan** [comment]
Also warps don't work. Please join server we have major problems: ip.finitebadger.tk port:25215

**Comment by leonardosnt** [comment]
Warps is working perfectly...

What is happening?

**Comment by symvizan** [comment]
So I gave permissions to people and they do not work. Sometimes they glitch out and say you have to wait 3600 seconds (an hour) to use this command again, but in the permission files there is no cooldown, home doesnt work with permisison, warps do not work with permission, tpa doesnt work with permission. I am really confused too.
