### ISSUE TITLE
[DOBOUT OR BUG REPORT] CONFIG.JSON

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#337]
PT-BR

AdminBypassWarpCooldown e EnableUnknownMessage ficão sumindo do meu config.json , eu tentei adicionar eles novamente mas quando eu dou /ess reload para aplicar as alterações ele some novamente, não estou conseguindo configurar :( 

como resolver ??

**Comment by leonardosnt** [comment]
Isso foi desativado faz tempo, mas só removi agora.

**Comment by OldCash4u** [comment]
porque quando eu digito ex : /asdakd , ele aparece 2x informando que o comando não existe , 1 e do rocket o outro seria do uessentials ?

**Comment by leonardosnt** [comment]
Vou verificar.

**Comment by OldCash4u** [comment]
verificou ?

**Comment by leonardosnt** [comment]
Já corrigi.
