### ISSUE TITLE
Can't manually edit kits

### ISSUE THREAD

**Issue by NinjaJc01** [uEssentials/uEssentials#339]
Tried 2 different programs, but the files are just taken back to the old version every time... Also tried 2 different server installs.

**Comment by leonardosnt** [comment]
Here is working fine, probably you're doing wrong.

**Comment by NinjaJc01** [comment]
What might I be doing wrong? I am opening the files with a text editor, changing things, and saving them. Whenever the server then loads the files, it changes them to the old version.

**Comment by leonardosnt** [comment]
Are you still having this problem?

**Comment by lammas112** [comment]
Why can´t you do this ?:
