### ISSUE TITLE
Can't run commands.

### ISSUE THREAD

**Issue by DubFriendsFriendlyFriend** [uEssentials/uEssentials#34]
When I try to run a command, this pops up:
```[uEssentials] System.NullReferenceException: Object reference not set to an instance of an object
at Essentials.Core.Command.CommandAdapter.execute (CSteamID executorId, System.String parameter) [0x00000] in <filename unknown>:0```

**Comment by leonardosnt** [comment]
You are using the latest version?

Which command you are trying to run?

**Comment by DubFriendsFriendlyFriend** [comment]
I'm using the latest version, 1.0.6.4

and none of the uEssential commands work.

**Comment by leonardosnt** [comment]
Which is your rocket version?

**Comment by leonardosnt** [comment]
Here is working fine, no errors.

**Comment by waspkiller** [comment]
Ummm i object
Im using rocketversion 4.9.2  and i have no errors.

**Comment by waspkiller** [comment]
when unturned does an update i always download a new version of rocket AND install that while my server is running the update script. maybe u should start doing that. Besides if your running and older version of rocket this cant possibly be a bug. do /rocket

**Comment by DubFriendsFriendlyFriend** [comment]
I just updated my server this morning with latest rocket and plugins

**Comment by leonardosnt** [comment]
Update again

**Comment by DubFriendsFriendlyFriend** [comment]
again?

btw rocket is 4.9.2.0 for unturned 3.14.4.1

**Comment by leonardosnt** [comment]
Try restart your server.

Can you send me your uEssentials folder?

**Comment by waspkiller** [comment]
use mega.nz

**Comment by DubFriendsFriendlyFriend** [comment]
ok

**Comment by DubFriendsFriendlyFriend** [comment]
i just restarted server and it worked the  5th time

weird

**Comment by leonardosnt** [comment]
lol

Solved?

**Comment by DubFriendsFriendlyFriend** [comment]
yah

**Comment by leonardosnt** [comment]
:D
