### ISSUE TITLE
TPA issue

### ISSUE THREAD

**Issue by KeshwaY** [uEssentials/uEssentials#340]
Hello
I want to set up different timer on tpa for each group, but it's looks like it works only with default group. Timer on other groups is ignored and replaced with default.

**Comment by leonardosnt** [comment]
This ?

```xml
  "Tpa": {
    "ExpireDelay": 10,
    "TeleportDelay": 5
  },
```

**Comment by KeshwaY** [comment]
Hmm... But how then to set timer in uEss config to each group?

**Comment by KeshwaY** [comment]
I tried set up all timers in rocket and only works that one in the default group.

**Comment by leonardosnt** [comment]
This is an Rocket bug.

**Comment by KeshwaY** [comment]
So there is another way to do it?

**Comment by leonardosnt** [comment]
Nop

**Comment by KeshwaY** [comment]
Okey, thanks then. I will write to fr34k.
