### ISSUE TITLE
[BUG REPORT] ITEM FACTURE 

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#344]
PT-BR

Quando alguém usa qualquer comando do item facture (não sei ao certo qual é mas acho que é o if autoreload) ele aparece que foi ativado , mas não funciona e também começa a floodar uma mensagem de erro no console do servidor http://prntscr.com/bkk6tk

O Problema passou a ser apresentado apos atualização do Unturned e Rocket

**Comment by leonardosnt** [comment]
Qual a versão do seu Unturned?

**Comment by OldCash4u** [comment]
A Ultima que foi lancada 3.15.6.1

**Comment by leonardosnt** [comment]
Eu testei e ta funcionando perfeitamente, não tem esse erro.

**Comment by OldCash4u** [comment]
o que poderia estar causando isso ?

**Comment by OldCash4u** [comment]
ele somente para de floodar [ http://prntscr.com/bknfae ] quando eu desconecto

**Comment by leonardosnt** [comment]
Atualiza seu Rocket.

**Comment by OldCash4u** [comment]
Ja esta na ultima versão que foi lancada

**Comment by leonardosnt** [comment]
Atualiza todos os arquivos do seu unturned, foi isso que eu fiz aqui e não está dando esse erro.

**Comment by OldCash4u** [comment]
Não esta sendo apresentado quando somente eu uso o comando. VIPS também estão apresentando o mesmo problema ao utilizar :/

**Comment by leonardosnt** [comment]
Não posso fazer nada.

**Comment by OldCash4u** [comment]
Recriei um servidor de teste desdo 0 , com tudo atualizado , e continua apresentando o mesmo problema , estou usando a ultima versão do uessentials 1.2.4.0

**Comment by OldCash4u** [comment]
meu log do rocket http://www.mediafire.com/download/g9c8y46v2kq98lh/Rocket.log

**Comment by OldCash4u** [comment]
Eu disse para ele , mas não acredita...

**Comment by unturnedplayer** [comment]
In addition to the itemfeatures option not working, attempting to enable any of those features constantly returns the error below in the logs:
MissingFieldException: Field 'SDG.Unturned.PlayerEquipment.quality' not found. -

This fills up the log file very quickly.  Disabling those itemfeatures does not stop those errors.

**Comment by leonardosnt** [comment]
@OldCash4u Eu não disse que não acredito, acho que tu tem algum problema pra ler, isso não acontece aqui.

**Comment by OldCash4u** [comment]
@leonardosnt Quase uma semana sem uma solucao para o problema alem de você ter dito "Atualiza seu Rocket." gravei um video recriando um servidor desdo 0 novamente , provando que mesmo com toda a plataforma atualizada , ele continua apresentando o mesmo erro apos a atualização do Unturned... 

https://www.youtube.com/watch?v=3Ut-5qCJ7cc&feature=youtu.be [FULL HD 1800p60]

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/releases/tag/1.2.4.1
