### ISSUE TITLE
Error with kit on death

### ISSUE THREAD

**Issue by focuszed** [uEssentials/uEssentials#346]
Whenever someone dies they get this error: http://pastebin.com/VG21cVfq
And an error when someone disconnects: http://pastebin.com/dVrTUsH4

**Comment by pepixiko** [comment]
http://subefotos.com/ver/?8a1c66dc7903c47ab79c48f8d0a15dcbo.png
version 1.2.6.4

**Comment by leonardosnt** [comment]
This isn't happening anymore
