### ISSUE TITLE
Repair all - Fake Error

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [uEssentials/uEssentials#349]
Прописывая команду /Repair all плагин выдает что команда недоступна и нужно связаться с администратором,но при этом все вещи чинятся,а в консоле выходит такая ошибка http://imgur.com/0KmuXE6

**Comment by cellinho** [comment]
Hmmm, which anti cheat are you using mate ?

**Comment by ZSHADOWWOLF** [comment]
There are developers that understand Russian language
