### ISSUE TITLE
Suggestion Create Command

### ISSUE THREAD

**Issue by AleixReverte** [uEssentials/uEssentials#350]
Would it be possible to create your own commands? I mean, like Text Commands but not only with text.

**Comment by leonardosnt** [comment]
There are an feature called TextCommands, and this only accepts text...

**Comment by pepixiko** [comment]
"AutoCommands": {
    "Commands": [
      {
        "RunOnce": true,
        "Timer": 300,
        "Commands": [
          "say \"Be sure to drink your Ovaltine!\" 0 255 255",
          "item * glue"

which is the command to be put to activate this?

**Comment by leonardosnt** [comment]
@pepixiko 

```java
  "AutoCommands": {
    "Commands": [
      {
        "RunOnce": false,
        "Timer": 120,
        "Commands": [
          "say \"Be sure to drink your Ovaltine!\" 0 255 255",
          "item * glue"
        ]
      },
      {
        "RunOnce": false,
        "Timer": 900,
        "Commands": [
          "clear v",
          "respawnvehicles"
        ]
      }
    ],
    "Enabled": false           <-------------------------------- change to true ...
  },
```

**Comment by pepixiko** [comment]
oh yeah! thank!! :D

**Comment by leonardosnt** [comment]
@AleixReverte 

See 'Rocket/Plugins/uEssentials/textcommands.json'

```json
[
  {
    "Name": "rules",
    "Text": [
      "<cyan>Be Respectful.",
      "<cyan>Don't use cheats.",
      "<cyan>Have fun :D"
    ]
  },
  {
    "Name": "website",
    "Text": [
      "<cyan>Our website: github.com/uEssentials"
    ]
  }
]
```

**Comment by lammas112** [comment]
@leonardosnt  can you give the different <color> ids ..`? i have <purple> but in the server it sais it in green like Brodcast: <purple>: TEXT!

**Comment by leonardosnt** [comment]
<black>
                <blue>
                <clear>
                <cyan>
                <gray>
                <green>
                <grey>
                <magenta>
                <red>
                <white>
                <yellow>
