### ISSUE TITLE
Polls broken.

### ISSUE THREAD

**Issue by SolarSupremacy** [uEssentials/uEssentials#351]
No matter what if you do /vote yes or /vote no, it counts your vote as yes. Then, at the end, it always displays 0 for yes and 0 for no.

**Comment by leonardosnt** [comment]
This bug is already fixed, update your uEssentials...

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/releases/tag/latest

**Comment by SolarSupremacy** [comment]
Thought I already did... Hold on. I'll try again.

**Comment by SolarSupremacy** [comment]
After a crash, I got it to work. When I downloaded the update it may have gotten corrupted.

Re-downloaded and it works. Thanks!
