### ISSUE TITLE
/repair alert message

### ISSUE THREAD

**Issue by westonhowe98** [uEssentials/uEssentials#352]
I am running on ubuntu 14.04. When players use /repair all a message saying please contact an administrator appears, however the command works as intended. There is also no error message in the logs when doing the command. /repair hand does not have this issue.

**Comment by leonardosnt** [comment]
This bug was already fixed... #349

You can download the latest experimental release here https://github.com/uEssentials/uEssentials/releases/tag/experimental-3db3763

**Comment by westonhowe98** [comment]
Okay, thank you! Didn't mean to do a second bug report but I don't speak russian...
