### ISSUE TITLE
Polls

### ISSUE THREAD

**Issue by pepixiko** [uEssentials/uEssentials#353]
Me puede decir como añado los Poll, para que haya votacion por ejemplo:
votar /dia
votar /noche
votar /heal
votar /coche policia

can tell me how to add the Poll, for there to be voting for example:
Vote /day
vote /night
vote /heal
vote /police car

**Comment by pepixiko** [comment]
dentro del juego cuando doy a /poll start list, dice que no hay ningun poll, como los creo?

in the game when I give / poll start list says that there is no poll, as the create?

**Comment by pepixiko** [comment]
"poll": {
    "Aliases": [],
    "Usage": "[start/stop/list/info]",
    "Description": "Start/Stop an poll",
    "Cost": 0.0
  },

text command

**Comment by pepixiko** [comment]
Leonardo, puedes ayudarme para crear polls?

**Comment by leonardosnt** [comment]
`/poll start name duration description`
eg
`poll start somename 120 "do you love this server?"`

**Comment by pepixiko** [comment]
no, my idea, is create poll, 
votar /dia
votar /noche
votar /heal
and change of the server, day, night, all heal...

**Comment by leonardosnt** [comment]
this is not possible.

**Comment by pepixiko** [comment]
ok, close the post
