### ISSUE TITLE
[SUGGESTION] SHOW MESSAGE

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#354]
PT-BR

Teria como fazer aparecer uma menssagem no servidor quando alguem é banido ou expulso ?

Exemplo : <cor> O Usuario {0} foi banido por {1}.
Exemplo : <cor> O Usuario {0} foi desbanido por {1}.
Exemplo : <cor> O Usuario {0} foi expulso por {1}.

**Comment by leonardosnt** [comment]
Apenas com um sistema de banimento próprio do plugin, e eu não pretendo implementar isso agora.

E isso já foi proposto aqui #167, portanto vou fechar esse para não ficar duplicado.
