### ISSUE TITLE
Blacklist id items

### ISSUE THREAD

**Issue by wandereri** [uEssentials/uEssentials#355]
How to add item id to blacklist?
Как добавить предмет в черный список?

**Comment by leonardosnt** [comment]
config.json

"GiveItemBlacklist": [
  "1",
  "2",
  "3"
]

**Comment by lammas112** [comment]
@leonardosnt i did this "GiveItemBlacklist": [
"519",
520",
]
but the people still get rocket and rocket launcher .... is there any way to disable it for admins?

**Comment by leonardosnt** [comment]
@lammas112 Its wrong...

```json
 "GiveItemBlacklist": [
  "519",
  "520",
]
```
