### ISSUE TITLE
New version of uEssentials override Permissons.config.xml  ?

### ISSUE THREAD

**Issue by BlackShape** [uEssentials/uEssentials#356]
Hey, my users are Reporting that they cant use /kits so i was looking in my Permissons.config.xml and the Update from uEssentials has Overwritten my old Permissons.config.xml is this a Bug? 

Here are my Old & New Permissons.config.xml(Before and after the Update)
Old
http://imgur.com/5mc3pA1
New 
http://imgur.com/RARayK0

**Comment by leonardosnt** [comment]
uEssentials does not change Rocket permissions...
