### ISSUE TITLE
Kits

### ISSUE THREAD

**Issue by Toximble** [uEssentials/uEssentials#357]
Hi i have a few questions. Where do i have to type "essentials.command.<name>". No one told me so i eventually did it, writing "<Permission Cooldown="0">(name)</Permission>" in permissions.config. .But please tell me where do i have to type "essentials.command.<name>" and one more thing. I also enabled kits but there are not available for normal players and i don't know what to do. PLEASE help !!

**Comment by leonardosnt** [comment]
You need to add your permissions in Permissions.config.xml, that is located in Rocket folder.

https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference

About kits https://github.com/uEssentials/uEssentials/wiki/Command-Reference#kit
