### ISSUE TITLE
PERMISSIONS DONT WORK

### ISSUE THREAD

**Issue by Toximble** [uEssentials/uEssentials#358]
So, after i write essentials.command.name in permissions, i save, i check it is saved: it is . Then when i start the server and i open the file again, they are deleted. The essentials.command.name are deleted. PLEASE HELP!!!

**Comment by Toximble** [comment]
And now also the Permissions place where i should put the permissions is deleted !!! Now i cant even put themmm !!!

**Comment by Toximble** [comment]
AND NOW ALSO THE ADMIN COMMANDS DONT WORK TFQQ

**Comment by leonardosnt** [comment]
Here is working fine.

Rocket 4.9.8.0
uEssentials: 1.2.6.1
