### ISSUE TITLE
Where to change the default colour of chat ?

### ISSUE THREAD

**Issue by cellinho** [uEssentials/uEssentials#359]
Sorry this is not even a issue.

Where to change the default colour of chat ?

**Comment by KeshwaY** [comment]
uEssentials -> translations -> lang that you use

**Comment by cellinho** [comment]
Yeah i want to change the players chat colour. and the permission already set to white, but still gray. any suggestion ?

**Comment by KeshwaY** [comment]
<Id>idk</Id>
      <DisplayName>idk</DisplayName>
      <Color>7D9C9F</Color>

In color type name of color or hex numbers.

**Comment by leonardosnt** [comment]
^ ^ ^
