### ISSUE TITLE
Suggestion: Home

### ISSUE THREAD

**Issue by PandahutMiku** [uEssentials/uEssentials#36]
Outdated.

**Comment by waspkiller** [comment]
This is already in rocket. more like integrated.

**Comment by Mikuzzzz** [comment]
The rocket one is not built for players, it is built for admins and instantly teleports.

**Comment by leonardosnt** [comment]
@waspkiller You are the flash '-'

**Comment by Mikuzzzz** [comment]
PS. I can't seem to override Rocket's Home Command. 
Not registering HomeCommand.CommandHome (home) because it has been replaced by Rocket.Unturned.Commands.CommandHome

**Comment by waspkiller** [comment]
Mikuzzzzz 
`<Command>Home</Command>` Try that

**Comment by Mikuzzzz** [comment]
@waspkiller 
No, the issue is that I'm trying to get another plugin to take over the command Home. Not trying to give permission for it. Thanks for trying to help though :)

**Comment by waspkiller** [comment]
Ah.

**Comment by waspkiller** [comment]
more like an enhancement correct?

**Comment by Mikuzzzz** [comment]
@waspkiller Don't really get what you mean by enhancement. But anyway i can't override the home command with my own plugin or ZaupHomecommand. I suppose Freaky removed the way we can override rocket's commands.

**Comment by Mikuzzzz** [comment]
If your saying a enhancement to rocket's original home command yes it would be.

**Comment by waspkiller** [comment]
Well that explains it. I think this plugin will be the new go to source for unturned host providers. i see potential. @leonardosnt if im the flash Then what are you :laughing:

**Comment by leonardosnt** [comment]
@waspkiller  :laughing:

**Comment by Mikuzzzz** [comment]
@waspkiller @leonardosnt  One of the biggest issues with this plugin that i see is, it's so big if it breaks EVERYTHING BREAKS. Also it's so big that it probably needs to update after every rocket update.
Although this will be a good source for stealing some code hehe.

**Comment by waspkiller** [comment]
@Mikuzzzz True True True. Rocket Sometimes nearly breaks. And plus its a one man army He needs energy drinks :beer:

**Comment by leonardosnt** [comment]
Added in 1.1.1.0
