### ISSUE TITLE
Tpa and Kits wont work

### ISSUE THREAD

**Issue by Toximble** [uEssentials/uEssentials#360]
Hi. So i made a few kits with /ckit and, when i put them in permissions, they dont work.Tpa doesnt work either, but they work for admins if i put them. So i made /kit bandit and it works but only for admins. And i put it in the same section as the /home command, which actually does work for players. So, to summarize : I put kits and tpa in the same section as /home /p /rocket /compass and only the last 4 work, but tpa and kits work for admins. So it isnt that i wrote them wrong, but that there is some option that doesnt let players have tpa and kits too.
Can u help me please ?

**Comment by lammas112** [comment]
Show your premission config maybe i can help

**Comment by Toximble** [comment]
It says that i cant load that file so ill 
[Permissionstext.txt](https://github.com/uEssentials/uEssentials/files/349852/Permissionstext.txt)
just load the text version :

**Comment by lammas112** [comment]
Kits need to be essentials.kit.name 
and heres your fixed file :)
[Permissionstext.txt](https://github.com/uEssentials/uEssentials/files/349868/Permissionstext.txt)

**Comment by Toximble** [comment]
It still doesn't work :((((. It works for the admins tough but i want the players too  :(

**Comment by Toximble** [comment]
When i type /kits as a regular players it tells me : There are no kit available, altough when im an admin it tells me what kits i can get and i can actually get them

**Comment by lammas112** [comment]
Give me the name of your server lets talk there...

**Comment by Toximble** [comment]
Tpa works by the way. Kits dont work ... No one can help me with kits :((

**Comment by Toximble** [comment]
Anyway, thanks for your help, at least u got my tpa working which matters a lot for my server. Thanks for the time u spent repairing my file also ! :+1:

**Comment by lammas112** [comment]
@Toximble try to create new kits and replace the ones you got in premission conf... they should then work

**Comment by Toximble** [comment]
What do you mean ? They are not the default ones, but i created them. So u are saying i should create new kits with new items and rename them in permission.config. ?

**Comment by lammas112** [comment]
Basically try to remake them ... i had similar bug that kits didnt work so i deleted all and remade them and they worked again .

**Comment by Toximble** [comment]
Oh, nice ! I'll try and let you know ;)

**Comment by Toximble** [comment]
It still doesn't work. As a player, if i type"/kit" it tells me "type /kit name", but when i do "/kit -name of the kit-" or "/kits" it tell me "there are no kits avaiable". It does work for the admins again tough.

**Comment by KeshwaY** [comment]
Check this:

http://pastebin.com/bDeAsf9Q

replace name with yours.

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference
