### ISSUE TITLE
/clear ev causes a mass-disconnect almost everytime

### ISSUE THREAD

**Issue by sharkbound** [uEssentials/uEssentials#361]
Sometimes when i do /clear ev it causes a mass player disconnect, it has even caused the mass disconnect when clearing a small amount of vehicles. Also alot of players discconected from this bug have their unturned crash directly after

Edit: it happens sometimes when clearing a small amount of vehicles, but it does it almost everytime when its clear alot of vehicles

**Comment by leonardosnt** [comment]
`/clear ev` was removed.
