### ISSUE TITLE
Suggestion Shutdown with timer

### ISSUE THREAD

**Issue by AleixReverte** [uEssentials/uEssentials#362]
This is only a suggestion. I think it would be nice if you could do it. A way to program a shutdown at a specific time or in <x> seconds.

**Comment by lammas112** [comment]
Yea would be nice but theres already autoshutdown2.dll as plugin or you can use the rocket one at rocket config theres automaticshutdown :)

**Comment by AleixReverte** [comment]
thanks man :+1:

**Comment by JustOneMoreBlock** [comment]
@AleixReverte 

I restart my servers every 2 hours. In the Rocket config, I have this setup.
```
  <AutomaticShutdown Enabled="true" Interval="7180" />
```

However, to ensure the safety of the files, and a proper save. uEssentials does have a built-in timer.

```
  "AutoCommands": {
    "Commands": [
      {
        "RunOnce": false,
        "Timer": 6900,
        "Commands": [
          "say \"Server Restarting in 5 Minutes!\" 32 150 225"
        ]
      },
      {
        "RunOnce": false,
        "Timer": 7100,
        "Commands": [
          "say \"Server Restarting in 1 Minute!\" 32 150 225",
          "save"
        ]
      }
    "Enabled": true
  },
```

This auto announces and executes a _/save_ command. :) - 80 Seconds later, the server is shut down by Rocket, and I restart it using Rocket Manager which also has the timer. :)
