### ISSUE TITLE
Kit Cooldown Issue

### ISSUE THREAD

**Issue by JustOneMoreBlock** [uEssentials/uEssentials#363]
Related: #330.
Using Build: 1.2.5.0
Using Store Config (ConfigKits is still broken. #273 )
Using WebKits: https://justplayhere.com/unturned/public/uEssentials/kits.json
Using Web Permissions: https://justplayhere.com/utperms.php

A staff member executed any of the following commands:
```
/kit DemoTeamAmmo
/kit DemoTeamSigns
/kit DemoTeamCar
```

The commands work successfully and continually to work until the server has been restarted.
This can be replicated by issuing the following command via console:
```
shutdown
```

Upon, the shutdown of the server, it will save the files and more specifically in the uEssentials: data/ directory:
```
kit_cooldowns.json
```

Inside this file, this is a sample of the what it saves.
```
{
  "76561197972974462": {
    "Global": "0001-01-01T00:00:00"
  }
}
```

Keep in mind; I can also do _/ess savedata_ and writes to the same file with the same data. However, we able to still execute the kits just fine, well at least until the restart.

Error in CONSOLE:
```
[Area] {WC}PistolPete [{WC}PistolPete]: "/kit demoteamcar"
[uEssentials] System.ArgumentException: An element with the same key already exi
sts in the dictionary.
  at System.Collections.Generic.Dictionary`2[System.UInt64,System.Collections.Ge
neric.Dictionary`2[System.String,System.DateTime]].Add (UInt64 key, System.Colle
ctions.Generic.Dictionary`2 value) [0x00000] in <filename unknown>:0
  at Essentials.NativeModules.Kit.Commands.CommandKit.OnExecute (ICommandSource
src, ICommandArgs args) [0x00000] in <filename unknown>:0
  at Essentials.Core.Command.CommandAdapter.Execute (IRocketPlayer caller, Syste
m.String[] args) [0x00000] in <filename unknown>:0
```

Once the server has shut down and brought back online. It reads the kit_cooldowns.json file, and prevents the spawning of any kits.

Here you can see the kit is simple, no cooldown (we had it at 0 too), and no reset options.
```
  {
    "Name": "DemoTeamSigns",
    "Items": [
      {
        "Id": 1098,
        "Durability": 100,
        "Amount": 10
      }
    ],
    "Cooldown": 1,
    "Cost": 0.0,
    "ResetCooldownWhenDie": false
  },
  {
    "Name": "DemoTeamCar",
    "Items": [
      {
        "Vehicle": 93
      }
    ],
    "Cooldown": 1,
    "Cost": 0.0,
    "ResetCooldownWhenDie": false
  }
```

I just added this permission node to our DemoTeam, and possibly might be a temporary fix until this has been resolved. **UNTESTED**
```
        <Permission>essentials.bypass.kitcooldown</Permission>
```

The other method of fixing this issue is, on shutdown. We have to remove the kit_cooldowns.json file from the data directory.

Reproduce:
1.) Install uEssentials
2.) Add Kits (Borrow mine or make your own.)
3.) Start Server
4.) Join Server
5.) Execute a /kit <command>
6.) In CONSOLE type: shutdown
7.) This will create a kits_cooldowns.json file in data/.
8.) Start Server
9.) Join Server
10.) Execute a /kit <command>
11.) Won't receive the kit. However, you will get an error similar to mine in CONSOLE.

**Comment by pepixiko** [comment]
"Vehicle": 93 change to "Vehicle": 93,

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/commit/ec51b5e2da8dfe8474471fe02996a3840456056e

**Comment by leonardosnt** [comment]
Fixed!
