### ISSUE TITLE
kick the server

### ISSUE THREAD

**Issue by pepixiko** [uEssentials/uEssentials#364]
as I can disable the kick in the game, because people take the kick and annoying

como puedo deshabilitar el kick dentro del juego, porque la gente da al kick y molesta

**Comment by sharkbound** [comment]
you mean admins using /kick?

**Comment by pepixiko** [comment]
yo dentro del juego cuando das a la tecla P salen la lista de jugadores, y sale mute y kick, pues quiero desactivar el kick.

I in the game when you press to the key P out the roster, and mute and kick out, because I want to kick off.

**Comment by JustOneMoreBlock** [comment]
I'm pretty sure "Vote to Kick" can be disabled by default in Unturned itself. As we don't have this enabled at all.

**Comment by pepixiko** [comment]
yes, call vote kick! can be disabled by default in unturned itself?

**Comment by pepixiko** [comment]
fix! thank you all!
