### ISSUE TITLE
uEssentials Commands cannot be used by non-admins.

### ISSUE THREAD

**Issue by WobMinerJames** [uEssentials/uEssentials#365]
After realising all regular players could not use essential commands such as TPA and KIT, being given a red text or yellow text "You do not have permission", even though /p shows they can use it.

I have removed all plugins to rocket to see if the issues was there.
A server with just Rocket and uEssetials still creates this issue.

I have tried the prefix for the permissions in the permissions file "essentials.command."
```
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Color>white</Color>
      <Members />
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">essentials.command.home</Permission>
		<Permission Cooldown="0">essentials.command.tpa</Permission>
		<Permission Cooldown="0">tpa</Permission>
		<Permission Cooldown="0">essentials.command.warp</Permission>
		<Permission Cooldown="0">warps</Permission>
		<Permission Cooldown="0">essentials.command.warps</Permission>
		<Permission Cooldown="0">essentials.kit.bandit</Permission>
		<Permission Cooldown="0">essentials.command.kits</Permission>
      </Permissions>
    </Group>
```

What is most odd is that /p will show all their permissions, then doing /tpa will show the /tpa requirements "/tpa <name><etc etc etc...>" in green text.
But then actually doing /tpa InsertNameHere gives the promt in chat "You do not have permission".

<Permission Cooldown="0">essentials.kit.bandit</Permission>
This line was my attempt to see if I can just give the Guests one kit to use, and it does showup in /p as a usable kit, and using /kits even works!!!

So why does /kits work, and /warps.. but none of the others allow the players to execute the commands!

I am in serious need of help on this one, several hours have gone to waste in my troubleshooting, if you need to see any more code/files etc etc, let me know and I will attach them!

-- After checking mod versions, it would appear rocket has gone from _953 to _955 in the short time of setting up my server. The latest version of uEssentials is being used too 1.2.4.1. I will add this new version of rocket tomorrow to see if it has fixed the issue (Right now I need sleep!).

**Comment by leonardosnt** [comment]
Read wiki

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference

**Comment by leonardosnt** [comment]
First: permission for /kit is not present in your pernissions.

Second: tpa have multiple permissions... for sub commands e.g, /tpa cancel = essentials.command.tpa.cancel ...
