### ISSUE TITLE
uEssentials Kit Permissions & Config file not working?

### ISSUE THREAD

**Issue by WobMinerJames** [uEssentials/uEssentials#366]
Thank you to the guy that helped with my previous issue regarding the permissions file.

1. 

Currently my Config.json file seem to do nothing.

[ConfigExample.txt](https://github.com/uEssentials/uEssentials/files/355833/ConfigExample.txt)

The cooldown on kits is non-existent.
All cooldowns I tried to apply to teleport features (tpa, home) are non-existent.
Its rather like this file has an error somewhere and thus does not function.

http://www.jsonschemavalidator.net/    Shows nothing.
http://jsonlint.com/   Shows nothing.

Only Rocket and uEssentials are running.

https://github.com/uEssentials/uEssentials/wiki/Configuration    Used the reload command, restarted server many many times.

**Comment by WobMinerJames** [comment]
Just noticed that the rocket plugins list features uEssentials 1.2.4.1
Whereas uEssentials was updated 7 days ago and is at 1.2.5.0

Will see if this is the cause.

**Comment by WobMinerJames** [comment]
Will be using the Rocket permission file for cooldowns instead. Assuming it is overwriting uEssentials cooldowns.

**Comment by leonardosnt** [comment]
Probably you are testing with an admin account... admins don't have cooldown.
