### ISSUE TITLE
/kits not working plz help

### ISSUE THREAD

**Issue by Wazup3005** [uEssentials/uEssentials#369]
Every time a person (execpt for admin) uses /kit <any_kit_name> it says "An error occurred attempting to execute this command: please contact an admin!" 
plz help 
[Permissions.txt](https://github.com/uEssentials/uEssentials/files/359297/Permissions.txt)
[Kits.txt](https://github.com/uEssentials/uEssentials/files/359298/Kits.txt)
![console error](https://cloud.githubusercontent.com/assets/20419682/16767281/06cccd2a-4882-11e6-97e5-3b60ac24be84.PNG)

**Comment by leonardosnt** [comment]
ec51b5e2da8dfe8474471fe02996a3840456056e
