### ISSUE TITLE
command item

### ISSUE THREAD

**Issue by xstonemetal** [uEssentials/uEssentials#37]
when i spawn one item, example: "/item 363 2" this command give me 2 maplestrike, but when i use this maplestrike, use munition add tacticals etc, the second maplestrike same o.o 

this bug i think when i spawn 2 items use the same metadata

can su fix it?

sorry for my english

**Comment by leonardosnt** [comment]
/item usage: ```[item] <amount> or [player|all] [item] [amount]```

**Comment by xstonemetal** [comment]
i use the same syntax, but when i use /item itemid 2 this 2 ítems have the
same metadata.
example:
/item 363 2.   now i have 2 maplestrike
now i equip supresor in 1 maplestrike
i deequip this maplestrike and equip 2 maplestrike and this maplestrike
have too military supressor

**Comment by leonardosnt** [comment]
lol, this is weird. i will fix it soon.

Thanks for reporting it.

**Comment by waspkiller** [comment]
@leonardosnt I think you need some :beers: Mr :confetti_ball:

**Comment by leonardosnt** [comment]
@waspkiller :laughing: :laughing: :laughing:

**Comment by xstonemetal** [comment]
thanks you leo
muito obrigado

**Comment by leonardosnt** [comment]
@xstonemetal :D

**Comment by xstonemetal** [comment]
Leo y update ES traslation

for last version

2016-02-13 13:02 GMT-03:00 Leonardo Santos <notifications@github.com>:

**Comment by leonardosnt** [comment]
@xstonemetal Ok.
