### ISSUE TITLE
New update broke plugin 

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [uEssentials/uEssentials#371]
С сегодняшним обновлением плагин был сломал вот этой ошибкой http://imgur.com/lIkH62N Нужно срочно обновление!

**Comment by root1k** [comment]
@leonardosnt Please update plugin for new rocket, unturned. Thanks!!

**Comment by tenten8401** [comment]
Can confirm, new update broke it!

**Comment by ZSHADOWWOLF** [comment]
Нет...вы лишь решили половину проблем,но плагин все равно не запускается http://imgur.com/a/0nelB

**Comment by root1k** [comment]
@ZSHADOWWOLF посмотри на rocketmod.net там парень в коменнтах ссылку выложил, скачай, всё работает

**Comment by ZSHADOWWOLF** [comment]
@root1k Это грубая поделка из-за которой у меня стираются названия серверов (А это очень важно) Мне нужен официальный релиз!

**Comment by MrBlaszkNB** [comment]
Ermergerd erpdert! D:<

**Comment by root1k** [comment]
@ZSHADOWWOLF они стираются только у тебя на консоли, в поиске серверов и в самой игре названия остаются такие же, как и в файле commands

**Comment by Svernik** [comment]
[7/15/2016 9:16:38 PM] [Info] 
[loading] uEssentials
[7/15/2016 9:16:38 PM] [Error] Failed to load uEssentials, unloading now... :System.MissingFieldException: Field 'SDG.Unturned.Provider.camera' not found.
  at Essentials.Core.EssCore.Load () [0x00000] in <filename unknown>:0 
  at Rocket.Core.Plugins.RocketPlugin.LoadPlugin () [0x00000] in <filename unknown>:0

**Comment by tenten8401** [comment]
Oh, goodie. Really hoping this won't be the case.
> uEssentials will not be updated in this month (July). Sorry.

**Comment by ZSHADOWWOLF** [comment]
@root1k Именно! Мне сложно следить за серверами в консоли не зная их имена!

**Comment by yawbanana** [comment]
R.I.P UESSENTIALS 15/07/2016 :(

**Comment by cellinho** [comment]
The issue is all about Analytics lol, just ignore that one and rebuild to use it.

i already have essentials working here.
not that big problem.

https://github.com/uEssentials/uEssentials/blob/master/src/Analytics/Metrics.cs#L27

**Comment by MrBlaszkNB** [comment]
Would you be willing to walk me through how this is accomplished? I'm still
fairly new to writing plugins

**Comment by cellinho** [comment]
https://github.com/uEssentials/uEssentials/issues/373

**Comment by cellinho** [comment]
@MrBlaszkNB 
first clone the repo then. replace the libs to new RocketAPI and UnityEngine stuff.
if you try building it you will see the error. look at where the code has changed and change the code to work. finally build it.

**Comment by tenten8401** [comment]
https://github.com/cellinho/uEssentials/releases/download/smallfix/Archive.zip

Thanks @cellinho

**Comment by cellinho** [comment]
@tenten8401 anytime mate!
