### ISSUE TITLE
Please update , and make you a significant donation !

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#373]
R.I.P UESSENTIALS 15/07/2016 :(

**Comment by yawbanana** [comment]
R.I.P UESSENTIALS 15/07/2016 :(

**Comment by xstonemetal** [comment]
PLEASE!!!!!!!!!! :C update the plugins men, i am donator pls men pls pls pls >.<

**Comment by Daniil1288** [comment]
well then, ggs, I'm outta here.

**Comment by OldCash4u** [comment]
That was the day i discovered how much  i love leonardosnt

**Comment by cellinho** [comment]
The issue is all about Analytics lol, just ignore that one and rebuild to use it.

i already have essentials working here.
not that big problem.

https://github.com/uEssentials/uEssentials/blob/master/src/Analytics/Metrics.cs#L27

Or just change the camera to cameraMode.

**Comment by xstonemetal** [comment]
please you can upload and share this rebuild?

2016-07-16 13:47 GMT-04:00 XYZ <notifications@github.com>:

**Comment by OldCash4u** [comment]
please share a working version

**Comment by cellinho** [comment]
https://github.com/cellinho/uEssentials/releases/tag/smallfix

**Comment by xstonemetal** [comment]
thx men

**Comment by OldCash4u** [comment]
@cellinho thanks for everything , you are beast !

@leonardosnt o @cellinho atualizou o seu plugin , esta funcionando normalmente. 
Não fique preocupado ! ^^

**Comment by cellinho** [comment]
@leonardosnt voce nao tem free wife no brazil ? lol

**Comment by tenten8401** [comment]
https://github.com/cellinho/uEssentials/releases/download/smallfix/Archive.zip

Thanks @cellinho
