### ISSUE TITLE
"There are no kits available." for users, not admins.

### ISSUE THREAD

**Issue by MiniAssassin78** [uEssentials/uEssentials#375]
When a user runs the command /kits, they get, "There are no kits available." My admins are able to execute the command fine and show all the kits. My default perms are as follows:

        <Permission Cooldown="1">p</Permission>
        <Permission Cooldown="1">compass</Permission>
        <Permission Cooldown="1">rocket</Permission>
        <Permission Cooldown="1">tpa</Permission>
        <Permission Cooldown="1">tpa.send</Permission>
        <Permission Cooldown="1">tpa.deny</Permission>
        <Permission Cooldown="1">tpa.accept</Permission>
        <Permission Cooldown="1">home</Permission>
        <Permission Cooldown="1">essentials.command.kits</Permission>
        <Permission Cooldown="1">kit.survivor</Permission>

**Comment by cellinho** [comment]
i think the permission for kit is essentials.kit.*

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference
