### ISSUE TITLE
uEssentials plugin refuses to load when starting the server

### ISSUE THREAD

**Issue by idiot101300** [uEssentials/uEssentials#376]
So i'm running the latest version of rocket on the latest version of unturned. up until now everything was fine with the server, but this morning when i started the server it loaded properly, went through all the stages, then tried to load uEssentials and returned the error  _"Failed to load uEssentials, unloading now... :System.MissingFieldException: Field 'SDG.Unturned.Provider.camera' not found.
  at Essentials.Core.EssCore.Load () [0x00000] in <filename unknown>:0
  at Rocket.Core.Plugins.RocketPlugin.LoadPlugin () [0x00000] in <filename unknown>:0"_

I've tried a fresh install of the server, rocket, and the plugin

**Comment by cellinho** [comment]
before opening issue check the oldest issue 1st please.
theres a bunch of same issue closed on github.

thanks.
