### ISSUE TITLE
DisabledCommands error

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [uEssentials/uEssentials#377]
Обновляю,запускаю выдает вот это - http://imgur.com/a/CxQjW Вписывал вот так -   "DisabledCommands": [
"tp",
"kit",
"kits"
  ]
}

**Comment by ZSHADOWWOLF** [comment]
Так...это решено? Что мне делать?

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/releases/tag/experimental-57e5339

**Comment by ZSHADOWWOLF** [comment]
IT WORK! Thanks!

**Comment by leonardosnt** [comment]
:D

**Comment by ZSHADOWWOLF** [comment]
У меня есть некоторые проблемы...я понимаю что это Экспериментальная версия,но всеже.  Я отключил Home в Disabled Commands но она все равно работает,также при наборе ru в translation он выдает вот это - http://imgur.com/a/VR41N

**Comment by leonardosnt** [comment]
Является ли ошибка синтаксиса ... на config.json

Позвольте мне видеть ваше config.json

**Comment by ZSHADOWWOLF** [comment]
{
  "Locale": "ru",
  "PMFormatFrom": "(From {0}): {1}",
  "PMFormatTo": "(To {0}): {1}",
  "UnfreezeOnDeath": true,
  "UnfreezeOnQuit": true,
  "EnableTextCommands": true,
  "EnableDeathMessages": true,
  "EnableJoinLeaveMessage": true,
  "ShowPermissionOnErrorMessage": true,
  "EnablePollRunningMessage": true,
  "PollRunningMessageCooldown": 20,
  "ServerFrameRate": -1,
  "ItemSpawnLimit": 10,
  "AntiSpam": {
    "Enabled": true,
    "Interval": 3
  },
  "Updater": {
    "CheckUpdates": true,
    "DownloadLatest": true,
    "AlertOnJoin": true
  },
  "HomeCommand": {
    "Cooldown": 30,
    "Delay": 5,
    "CancelTeleportWhenMove": true
  },
  "WarpCommand": {
    "Cooldown": 5,
    "CancelTeleportWhenMove": false,
    "PerWarpPermission": true
  },
  "VehicleFeatures": {
    "RefuelPercentage": 20,
    "RepairPercentage": 70
  },
  "WebKits": {
    "Url": "",
    "Enabled": false
  },
  "WebConfig": {
    "Url": "",
    "Enabled": false
  },
  "Kit": {
    "ShowCost": true,
    "ShowCostIfZero": false,
    "CostFormat": "{0}({1}{2})",
    "GlobalCooldown": 0,
    "ResetGlobalCooldownWhenDie": false
  },
  "Tpa": {
    "ExpireDelay": 10,
    "TeleportDelay": 5
  },
  "Economy": {
    "UseXp": false,
    "XpCurrency": "Xp",
    "UconomyCurrency": "$"
  },
  "AutoAnnouncer": {
    "MessageInterval": 30,
    "RandomMessages": false,
    "Enabled": false,
    "Messages": [
      "<red>Automatic message 1",
      "<green>Automatic message 2",
      "<blue>Automatic message 3",
      "<yellow>Automatic message 4",
      "<purple>Automatic message 5"
    ]
  },
  "AutoCommands": {
    "Commands": [
      {
        "RunOnce": false,
        "Timer": 120,
        "Commands": [
          "say \"Be sure to drink your Ovaltine!\" 0 255 255",
          "item * glue"
        ]
      },
      {
        "RunOnce": false,
        "Timer": 900,
        "Commands": [
          "clear v",
          "respawnvehicles"
        ]
      }
    ],
    "Enabled": false
  },
  "GiveItemBlacklist": [],
  "VehicleBlacklist": [],
  "EnabledSystems": [
    "kits",
    "warps"
  ],
  "DisabledCommands": [
    "home",
    "kit",
    "v",
    "spy",
    "tp",
    "tpa",
    "i",
    "kits"
  ]
}

**Comment by leonardosnt** [comment]
Работает нормально здесь ...

**Comment by ZSHADOWWOLF** [comment]
Что-то я сам почему-то удивился...

**Comment by leonardosnt** [comment]
Используйте эту http://www.jsonschemavalidator.net/, чтобы проверить на наличие ошибок синтаксиса

**Comment by ZSHADOWWOLF** [comment]
Как отключить Deadmessage?

**Comment by leonardosnt** [comment]
"EnableDeathMessages": false

**Comment by ZSHADOWWOLF** [comment]
Это должно быть в Config,json?

**Comment by leonardosnt** [comment]
yes

**Comment by ZSHADOWWOLF** [comment]
Thanks :)
