### ISSUE TITLE
commands output not sent to RCON

### ISSUE THREAD

**Issue by SergeySch** [uEssentials/uEssentials#379]
online/ping/servertime and all other uEssentials commands output not visible while connected to RCON.

other commands like players/admins/bans etc shown ok.

Best,
Sergey

**Comment by leonardosnt** [comment]
How you are using RCON?

Putty... ?

**Comment by SergeySch** [comment]
yes, putty in telnet/raw mode.

**Comment by SergeySch** [comment]
Actually it is not show in the Rocket.log file too (just tried online command)

**Comment by xstonemetal** [comment]
same problem, i cant see in my iphone whit vssh terminal

**Comment by SergeySch** [comment]
maybe a solution is to use Rocket.Core.Logging.Log* methods ?
