### ISSUE TITLE
Text Command Maker

### ISSUE THREAD

**Issue by PandahutMiku** [uEssentials/uEssentials#38]
Outdated.

**Comment by waspkiller** [comment]
@Mikuzzzz Damn why didnt i think of that.

**Comment by leonardosnt** [comment]
@waspkiller 
@Mikuzzzz 

I will sleep now, it's been +12 hours I'm awake.

Here is 22:44 pm.

Likely i will wake at 3~4am.

**Comment by waspkiller** [comment]
@Mikuzzzz :night_with_stars:

**Comment by Mikuzzzz** [comment]
@leonardosnt Aw cmon, i went 22 hours without sleep. Lol Cya.

**Comment by leonardosnt** [comment]
@Mikuzzzz Immmmm back

**Comment by leonardosnt** [comment]
Now with a big cup of coffee e.e

**Comment by waspkiller** [comment]
@leonardosnt :coffee: MMmMMMMMm

**Comment by leonardosnt** [comment]
@waspkiller I add you as collaborator. now you can add labels, edit issues and so on.

**Comment by waspkiller** [comment]
@leonardosnt More coding for you :)

**Comment by Mikuzzzz** [comment]
@leonardosnt Oh God...I thought you were gone...Everybody hide the drugs

**Comment by waspkiller** [comment]
@Mikuzzzz You know dealing drugs is illegal now do ya :+1:

**Comment by leonardosnt** [comment]
@Mikuzzzz :laughing: :laughing: :laughing: :laughing: :laughing: :laughing:

**Comment by waspkiller** [comment]
@leonardosnt i found out who you are on the marvel characters now. im flash and your superman

**Comment by leonardosnt** [comment]
@waspkiller :laughing: :laughing: :laughing: :laughing:

**Comment by leonardosnt** [comment]
@Mikuzzzz 
@waspkiller 

I will write an simple program to help configure kits, translations and so on.

**Comment by waspkiller** [comment]
Cool.
