### ISSUE TITLE
error desactivate tp

### ISSUE THREAD

**Issue by pepixiko** [uEssentials/uEssentials#380]
"DisabledCommands": [
"tp",
"tpa"
]
}

Leonard, I get error disable tp

look you example and nothing, no it works :S https://github.com/uEssentials/uEssentials/wiki/Configuration

**Comment by leonardosnt** [comment]
which error ?

**Comment by KazukiRyuu121** [comment]
@leonardosnt Using the disabledcommands feature will output this error in the latest version
![capture](https://cloud.githubusercontent.com/assets/20646614/17109932/d0adc3a4-52a2-11e6-81d8-2720864e02da.PNG)

**Comment by leonardosnt** [comment]
Already fixed... #377

Use the experimental version.
https://github.com/uEssentials/uEssentials/releases/tag/experimental-57e5339
