### ISSUE TITLE
uEssentials have a ton of issues

### ISSUE THREAD

**Issue by noammiz007** [uEssentials/uEssentials#383]
first of all i will start with the kits.
example: 
      {
        "Ammo": 1,
        "Id": 98,
        "Durability": 100,
        "Amount": 3
      },

i am trying to change the ""Ammo": 1," to ""Ammo": 10," and then i am doing /ess or /rocket reload but.. its changing back to 1.

the disablecommands are a little bit buggy.
i dont want to use the uessentials /tpa so i do it like that:
  ],
  "DisabledCommands": [
  "tpa"
  ]

and its still using the essentials plugin tpa. even if i am doing /rocket reload.
and now more bug in kits.
i put a gas in the kit starter
but when i am getting that so its empty.
and more bug.
when i am spawning myself a gas so its 51%

**Comment by leonardosnt** [comment]
Don't use /rocket reload, restart the server.

**Comment by noammiz007** [comment]
btw i disable the custom death messages of the plugin and its still on.

**Comment by noammiz007** [comment]
and how to fix the kits that i cant change them?

**Comment by leonardosnt** [comment]
Here is working. I used /ess reload kits...

**Comment by noammiz007** [comment]
oh is fixed. thx! but how to fix the gas. its empty when i get it from kit

**Comment by leonardosnt** [comment]
I will check...

**Comment by noammiz007** [comment]
and even if i am spawning so its not 100% full

**Comment by leonardosnt** [comment]
Unturned has changed this...  I will fix...

**Comment by noammiz007** [comment]
ok. can you please do it now or as fast as you can please? because i need it very hurry

**Comment by leonardosnt** [comment]
I'm doing this now... just wait.

**Comment by noammiz007** [comment]
ok :D

**Comment by noammiz007** [comment]
hmm wtf. i just used the disable commands to disable the essentials tpa and its still on. i restarted the server

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/releases/tag/experimental-6fd7e77

**Comment by noammiz007** [comment]
fixed all?

**Comment by leonardosnt** [comment]
DisabledCommands is working fine

**Comment by noammiz007** [comment]
],
  "DisabledCommands": [
  "tpa"
  ]
is that good that there is a space? or is need to be like this:
],
"DisabledCommands": [
"tpa"
 ]

or this:
  ],
  "DisabledCommands": ["tpa"]

**Comment by leonardosnt** [comment]
Does not matter...




![](http://i.imgur.com/cEbV8Bb.png)

**Comment by noammiz007** [comment]
ok. thx anyway

**Comment by noammiz007** [comment]
btw the autoannouncer of this are not working.

**Comment by noammiz007** [comment]
dang it. the disable commands of tpa are still not working.

**Comment by noammiz007** [comment]
![dame](https://cloud.githubusercontent.com/assets/10390196/17149527/547febb8-5374-11e6-8da1-aa95bbc83096.png)

**Comment by leonardosnt** [comment]
What part of "DisabledCommands need restart" you don't understand????

**Comment by noammiz007** [comment]
i did...

**Comment by noammiz007** [comment]
i closed the server and then i relaunched it

**Comment by leonardosnt** [comment]
Sure?? see the chat

"Reloading config..."
"Reload finished..."

**Comment by noammiz007** [comment]
because i was just trying it too

**Comment by noammiz007** [comment]
but i restarted before already

**Comment by noammiz007** [comment]
here is a better picture @leonardosnt

**Comment by noammiz007** [comment]
![better](https://cloud.githubusercontent.com/assets/10390196/17150734/3b5b1590-5379-11e6-8d09-6fe5e6de59e9.png)

**Comment by noammiz007** [comment]
now you belive me??

**Comment by noammiz007** [comment]
btw in the message announcer. why its show error message if there is more than 3 messages?

**Comment by noammiz007** [comment]
hello?

**Comment by leonardosnt** [comment]
Your configuration is invalid, you're not seeing the error in console?
