### ISSUE TITLE
Tpa tip

### ISSUE THREAD

**Issue by pepixiko** [uEssentials/uEssentials#384]
You could put the tpa as the home?
Podrias poner el tpa como el home?

example:
  "Tpa": {
    "Cooldown": 30,
    "Delay": 10,
    "CancelTeleportWhenMove": true
    "ExpireDelay": 30,
    "TeleportDelay": 10

would be pretty good
Estaria bastante bien

**Comment by xstonemetal** [comment]
yeah please i like this!

**Comment by leonardosnt** [comment]
Duplicated #334

**Comment by Toso10** [comment]
yes please !!!
