### ISSUE TITLE
disablecommands bug.

### ISSUE THREAD

**Issue by noammiz007** [uEssentials/uEssentials#385]
so i went to disable the tpa of the essentials plugin. but its still staying that. i have a proof:
![better](https://cloud.githubusercontent.com/assets/10390196/17152253/b665e796-537f-11e6-995e-639f7064b7a1.png)
can somebody help me?
i have already restarted the server.

**Comment by leonardosnt** [comment]
Your configuration is invalid, you're not seeing the error in console?

**Comment by noammiz007** [comment]
![better](https://cloud.githubusercontent.com/assets/10390196/17152473/9183f822-5380-11e6-9778-cd61a7ba4ff9.png)
much better?

**Comment by noammiz007** [comment]
oh nvm
