### ISSUE TITLE
Kits - Mod - Invalid id

### ISSUE THREAD

**Issue by sfranke** [uEssentials/uEssentials#391]
When I create a kit containing an item from a mod e.g. 14501 (Jetpack) I get an error message on reload saying 'invalid ID'. Am I missing something?

``` JSON
[{
	"Name": "jetpack",
	"Items": [{
		"Id": 14501,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 28,
		"Durability": 100,
		"Amount": 1
	}],
	"Cooldown": 3600,
	"Cost": 1000.0,
	"ResetCooldownWhenDie": false
}]
```

**Comment by leonardosnt** [comment]
This happens because he can't find an item with id 14501...

**Comment by sfranke** [comment]
Why can't "he" find it? And what can I do to fix it?

**Comment by leonardosnt** [comment]
This id isn't in asset list...

**Comment by sfranke** [comment]
Where do I find the asset list? Maybe i can add it manually?

**Comment by leonardosnt** [comment]
This is not possible. you need to add your assets in `Bundles/Items` folder...

**Comment by sfranke** [comment]
Thank you, sir! I'm sure I could copy the items from the mod to one of the folders to make it work, don't I? On the other hand would it be possible for your plugin to search through the subfolders of `Bundels/Workshop/Content/` and add those automagically?

**Comment by WGSRangerWolf** [comment]
Hello, is this still an issue? thanks

**Comment by JustOneMoreBlock** [comment]
All you need to do is what they said.

This is an example of a custom gun I use on the server.

It's located in:
`Bundles/Items/DemoTeam/`

Inside of it, I have
- Backpacks
- Barrels
- Guns
- Magazines
- Sights

These are located on the server itself and on the client-side, so our Team can use it. Once it's loaded on the server. Then you can use the Kit System to spawn those specific IDs. Which we utilize ourselves. :)

**Comment by sfranke** [comment]
So this might have been a misunderstanding.
The default location for workshop items/bundels is ```~/'application-root-folder'/Bundles/Workshop/Contents/'Workshop-id'.```. I did understand that with the current version of this plugin I am supposed to copy the contents of the workshop's subfolder 'items' into ```~/'application-root-folder'/Bundles/Items.```. Which from my point of view makes it unneccessaryly complicated. In the current state I would have the same items sitting in two locations. One location is for the server to hand out the workshop contents to every client that connects and the second one is soley for uEssential to be able to find those items for its kits. So my question would be, is it possible for you to add ```~/'application-root-folder'/Bundles/Workshop/Contents/'Workshop-id'.``` to your item look-up routine, so we don't have to maintain two different locations?

Thanks in advance.
