### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by ElMinerTrack** [uEssentials/uEssentials#392]
[uEssentials] Invalid kit configuration (Plugins/uEssentials/kits.json)
[uEssentials] Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: {. Path ‘[0].Items[2]’, line 20, position 7.
at Newtonsoft.Json.JsonTextReader.ParsePostValue () [0x00000] in :0
at Newtonsoft.Json.JsonTextReader.ReadInternal () [0x00000] in :0
at Newtonsoft.Json.JsonTextReader.Read () [0x00000] in :0
at Newtonsoft.Json.Linq.JContainer.ReadContentFrom (Newtonsoft.Json.JsonReader r) [0x00000] in :0
at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom (Newtonsoft.Json.JsonReader reader) [0x00000] in :0
at Newtonsoft.Json.Linq.JArray.Load (Newtonsoft.Json.JsonReader reader) [0x00000] in :0
at Newtonsoft.Json.Linq.JArray.Parse (System.String json) [0x00000] in :0
at Essentials.NativeModules.Kit.Data.KitData.Load () [0x00000] in :0

**Comment by ElMinerTrack** [comment]
that is from uessentials plugins. in the kits notebloc i've:
[
  {
    "Name": "Civil",
    "Items": [
      {
        "Id": 253,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 15,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 2,
        "Durability": 100,
        "Amount": 1
      }
      {
        "Id": 16,
        "Durability": 100,
        "Amount": 1
      }      
    ],
    "Cooldown": 0,
    "Cost": 500.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "Pescador",
    "Items": [
      {
        "Id": 503,
        "Durability": 100,
        "Amount": 1
      }
      {
        "Id": 509,
        "Durability": 100,
        "Amount": 1
      }
      {
        "Id": 510,
        "Durability": 100,
        "Amount": 1
      }
      {
        "Id": 511,
        "Durability": 100,
        "Amount": 1
      }
      {
        "Xp": 500
      }
    ],
    "Cooldown": 0,
    "Cost": 700.0,
    "ResetCooldownWhenDie": false
  },
  {
    "Name": "Cadete",
    "Items": [
      {
        "Xp": 500
      }
      {
        "Id": 10,
        "Durability": 100,
        "Amount": 1
      }
      {
        "Id": 223,
        "Durability": 100,
        "Amount": 1
      }     
      {
        "Id": 224,
        "Durability": 100,
        "Amount": 1
      }
      {
        "Id": 225,
        "Durability": 100,
        "Amount": 1
      }
      {
        "Id": 112,
        "Durability": 100,
        "Amount": 1
      }
      {
        "Id": 113,
        "Durability": 100,
        "Amount": 10
      }
      {
        "Id": 1195,
        "Durability": 100,
        "Amount": 7
      }
      {
        "Id": 1196,
        "Durability": 100,
        "Amount": 3
      }
    ],
    "Cooldown": 0,
    "Cost": 3500.0,
    "ResetCooldownWhenDie": false
  },
  {
    "Name": "xp",
    "Items": [
      {
        "Xp": 5000
      }
    ],
    "Cooldown": 1200,
    "Cost": 500.0,
    "ResetCooldownWhenDie": false
  }
]

**Comment by sfranke** [comment]
You are missing a coma in line 15 --> http://jsonlint.com/

**Comment by leonardosnt** [comment]
Bom, acho que você 'fala' português, então vou responder em português ...

A sintaxe está incorreta, está faltando várias 'virgulas'...

Use esse site para verificar a sintaxe:  http://www.jsonschemavalidator.net/


Json corrigido:
```json
[
  {
    "Name": "Civil",
    "Items": [
      {
        "Id": 253,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 15,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 2,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 16,
        "Durability": 100,
        "Amount": 1
      }
    ],
    "Cooldown": 0,
    "Cost": 500.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "Pescador",
    "Items": [
      {
        "Id": 503,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 509,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 510,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 511,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Xp": 500
      }
    ],
    "Cooldown": 0,
    "Cost": 700.0,
    "ResetCooldownWhenDie": false
  },
  {
    "Name": "Cadete",
    "Items": [
      {
        "Xp": 500
      },
      {
        "Id": 10,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 223,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 224,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 225,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 112,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 113,
        "Durability": 100,
        "Amount": 10
      },
      {
        "Id": 1195,
        "Durability": 100,
        "Amount": 7
      },
      {
        "Id": 1196,
        "Durability": 100,
        "Amount": 3
      }
    ],
    "Cooldown": 0,
    "Cost": 3500.0,
    "ResetCooldownWhenDie": false
  },
  {
    "Name": "xp",
    "Items": [
      {
        "Xp": 5000
      }
    ],
    "Cooldown": 1200,
    "Cost": 500.0,
    "ResetCooldownWhenDie": false
  }
]
```
