### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by ElMinerTrack** [uEssentials/uEssentials#397]
[uEssentials] System.ArgumentNullException: Argument cannot be null.
Parameter name: source
  at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull (System.Object value, System.String parameterName) [0x00000] in <filename unknown>:0
  at Newtonsoft.Json.Linq.Extensions.Value[JToken,String] (IEnumerable`1 value) [0x00000] in <filename unknown>:0
  at Newtonsoft.Json.Linq.Extensions.Value[String] (IEnumerable`1 value) [0x00000] in <filename unknown>:0
  at Essentials.NativeModules.Kit.Data.KitData.GetNotNullValue[String] (Newtonsoft.Json.Linq.JObject obj, System.String key, System.String errMsg) [0x00000] in <filename unknown>:0
  at Essentials.NativeModules.Kit.Data.KitData.Load () [0x00000] in <filename unknown>:0
  at Essentials.NativeModules.Kit.KitManager.LoadKits () [0x00000] in <filename unknown>:0
  at Essentials.NativeModules.Kit.KitManager.Load () [0x00000] in <filename unknown>:0

**Comment by ElMinerTrack** [comment]
I've this on kits folder:
[{
	"Name": "civil",
	"Items": [{
		"Id": 253,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 15,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 4201,
		"Durability": 100,
		"Amount": 5
	}, {
		"Id": 4744,
		"Durability": 100,
		"Amount": 5
	}, {
		"Id": 16,
		"Durability": 100,
		"Amount": 1
	}, {
		"Ammo": 1,
		"Id": 33307,
		"Durability": 100,
		"Amount": 1
	}, {
		"Ammo": 1,
		"Id": 33305,
		"Durability": 100,
		"Amount": 2
	}, {
		"Id": 1176,
		"Durability": 100,
		"Amount": 2
	}],
	"Cooldown": 1200,
	"Cost": 0.0,
	"ResetCooldownWhenDie": true
}, {
	"Name": "Pescador",
	"Items": [{
		"Id": 503,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 509,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 510,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 511,
		"Durability": 100,
		"Amount": 1
	}, {
		"Xp": 500
	}],
	"Cooldown": 1200,
	"Cost": 0.0,
	"ResetCooldownWhenDie": true
}, {
	"Name": "mecanico",
	"Items": [{
		"Id": 28,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 76,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 405,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 406,
		"Durability": 100,
		"Amount": 1
	}, {
		"Xp": 500
	}],
	"Cooldown": 1200,
	"Cost": 0.0,
	"ResetCooldownWhenDie": true
}, {
	"Name": "comida",
	"Items": [{
		"Id": 81,
		"Durability": 100,
		"Amount": 10
	}, {
		"Xp": 500
	}],
	"Cooldown": 1200,
	"Cost": 0.0,
	"ResetCooldownWhenDie": true
}, {
	"Name": "taxi",
	"Items": [{
		"Vehicle": 76
	}],
	"Cooldown": 1200,
	"Cost": 0.0,
	"ResetCooldownWhenDie": true
}, {
	"Name": "ropa",
	"Items": [{
		"Id": 253,
		"Durability": 100,
		"Amount": 4
	}, {
		"Id": 209,
		"Durability": 100,
		"Amount": 4
	}, {
		"Ammo": 20,
		"Id": 108,
		"Durability": 100,
		"Amount": 1
	}, {
		"Xp": 500
	}],
	"Cooldown": 1200,
	"Cost": 0.0,
	"ResetCooldownWhenDie": true
}, {
	"Name": "Cadete",
	"Items": [{
		"Xp": 500
	}, {
		"Id": 10,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 223,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 224,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 225,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 112,
		"Durability": 100,
		"Amount": 1
	}, {
		"Ammo": 8,
		"Id": 113,
		"Durability": 100,
		"Amount": 10
	}, {
		"Id": 1195,
		"Durability": 100,
		"Amount": 7
	}, {
		"Id": 1196,
		"Durability": 100,
		"Amount": 3
	}],
	"Cooldown": 1200,
	"Cost": 0.0,
	"ResetCooldownWhenDie": true
}, {
	"Name": "militar",
	"Items": [{
		"Xp": 500
	}, {
		"Id": 1010,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 1012,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 334,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 1270,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 253,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 8,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 146,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 151,
		"Durability": 100,
		"Amount": 2
	}, {
		"Id": 7712,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 7711,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 1013,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 15043,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 15602,
		"Durability": 100,
		"Amount": 1
	}, {
		"Ammo": 60,
		"Id": 15611,
		"Durability": 100,
		"Amount": 5
	}],
	"Cooldown": 3600,
	"Cost": 0.0,
	"ResetCooldownWhenDie": true
}, {
	"Name": "xp",
	"Items": [{
		"Xp": 5000
	}],
	"Cooldown": 900,
	"Cost": 0.0,
	"ResetCooldownWhenDie": true
}, {
	"Name": "taxista",
	"Items": [{
		"Vehicle": 76
	}],
	"Cooldown": 1200,
	"Cost": 0.0,
	"ResetCooldownWhenDie": true
}, {
	"Name": "offroad",
	"Items": [{
		"Vehicle": 1
	}],
	"Cooldown": 1200,
	"Cost": 0.0,
	"ResetCooldownWhenDie": true
}, {
	"Name": "offroad-1",
	"Items": [{
		"Vehicle": 4
	}],
	"Cooldown": 1200,
	"Cost": 0.0,
	"ResetCooldownWhenDie": true
}, {
	"Name": "lamborgini",
	"Items": [{
		"Vehicle": 1100
	}],
	"Cooldown": 1200,
	"Cost": 0.0,
	"ResetCooldownWhenDie": true
}, {
	"Name": "lamborgini-1",
	"Items": [{
		"Vehicle": 1103
	}],
	"Cooldown": 1200,
	"Cost": 0.0,
	"ResetCooldownWhenDie": true
}, {
	"Name": "van",
	"Items": [{
		"Vehicle": 35
	}],
	"Cooldown": 1200,
	"Cost": 0.0,
	"ResetCooldownWhenDie": true
}, {
	"Cooldown": 1200,
	"Cost": 0.0,
	"ResetCooldownWhenDie": true
}, {
	"Name": "EMS",
	"Items": [{
		"Id": 15,
		"Durability": 100,
		"Amount": 5
	}, {
		"Id": 269,
		"Durability": 100,
		"Amount": 5
	}, {
		"Id": 311,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 312,
		"Durability": 100,
		"Amount": 1
	}],
	"Cooldown": 1200,
	"Cost": 0.0,
	"ResetCooldownWhenDie": true
}, {
	"Name": "armero",
	"Items": [{
		"Id": 97,
		"Durability": 100,
		"Amount": 5
	}, {
		"Id": 107,
		"Durability": 100,
		"Amount": 5
	}, {
		"Id": 363,
		"Durability": 100,
		"Amount": 3
	}, {
		"Id": 116,
		"Durability": 100,
		"Amount": 3
	}, {
		"Id": 15003,
		"Durability": 100,
		"Amount": 3
	}, {
		"Id": 15152,
		"Durability": 100,
		"Amount": 2
	}, {
		"Id": 15012,
		"Durability": 100,
		"Amount": 3
	}, {
		"Id": 15034,
		"Durability": 100,
		"Amount": 3
	}, {
		"Id": 132,
		"Durability": 100,
		"Amount": 3
	}, {
		"Id": 15064,
		"Durability": 100,
		"Amount": 3
	}, {
		"Id": 15022,
		"Durability": 100,
		"Amount": 3
	}, {
		"Id": 15043,
		"Durability": 100,
		"Amount": 3
	}, {
		"Id": 15074,
		"Durability": 100,
		"Amount": 3
	}, {
		"Id": 297,
		"Durability": 100,
		"Amount": 3
	}, {
		"Id": 112,
		"Durability": 100,
		"Amount": 3
	}, {
		"Id": 116,
		"Durability": 100,
		"Amount": 3
	}],
	"Cooldown": 3600,
	"Cost": 0.0,
	"ResetCooldownWhenDie": false
}, {
	"Name": "ambulancia",
	"Items": [{
		"Vehicle": 54
	}],
	"Cooldown": 1200,
	"Cost": 0.0,
	"ResetCooldownWhenDie": false
}, {
	"Name": "salario-EMS",
	"Items": [{
		"Ammo": 1,
		"Id": 33307,
		"Durability": 100,
		"Amount": 2
	}],
	"Cooldown": 1200,
	"Cost": 0.0,
	"ResetCooldownWhenDie": true
}, {
	"Name": "salario-cadete",
	"Items": [{
		"Ammo": 1,
		"Id": 33307,
		"Durability": 100,
		"Amount": 2
	}, {
		"Ammo": 1,
		"Id": 33306,
		"Durability": 100,
		"Amount": 1
	}],
	"Cooldown": 1200,
	"Cost": 0.0,
	"ResetCooldownWhenDie": false
}, {
	"Name": "salario-militar",
	"Items": [{
		"Ammo": 1,
		"Id": 33307,
		"Durability": 100,
		"Amount": 5
	}, {
		"Ammo": 1,
		"Id": 33306,
		"Durability": 100,
		"Amount": 1
	}],
	"Cooldown": 1200,
	"Cost": 0.0,
	"ResetCooldownWhenDie": false
}, {
	"Name": "salario-pescador",
	"Items": [{
		"Ammo": 1,
		"Id": 33307,
		"Durability": 100,
		"Amount": 1
	}, {
		"Ammo": 1,
		"Id": 33306,
		"Durability": 100,
		"Amount": 1
	}],
	"Cooldown": 1200,
	"Cost": 0.0,
	"ResetCooldownWhenDie": false
}, {
	"Name": "salario-taxista",
	"Items": [{
		"Ammo": 1,
		"Id": 33307,
		"Durability": 100,
		"Amount": 2
	}, {
		"Ammo": 1,
		"Id": 33306,
		"Durability": 100,
		"Amount": 1
	}],
	"Cooldown": 1200,
	"Cost": 0.0,
	"ResetCooldownWhenDie": false
}, {
	"Name": "salario-mecanico",
	"Items": [{
		"Ammo": 1,
		"Id": 33307,
		"Durability": 100,
		"Amount": 3
	}, {
		"Ammo": 1,
		"Id": 33306,
		"Durability": 100,
		"Amount": 1
	}],
	"Cooldown": 1200,
	"Cost": 0.0,
	"ResetCooldownWhenDie": false
}, {
	"Name": "mafioso",
	"Items": [{
		"Id": 10046,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 10047,
		"Durability": 100,
		"Amount": 1
	}, {
		"Id": 1195,
		"Durability": 100,
		"Amount": 7
	}, {
		"Id": 1196,
		"Durability": 100,
		"Amount": 3
	}, {
		"FireMode": "AUTO",
		"Ammo": 60,
		"Barrel": {
			"AttachmentId": 70,
			"Durability": 100
		},
		"Sight": {
			"AttachmentId": 0,
			"Durability": 100
		},
		"Grip": {
			"AttachmentId": 0,
			"Durability": 100
		},
		"Tactical": {
			"AttachmentId": 0,
			"Durability": 100
		},
		"Magazine": {
			"AttachmentId": 0,
			"Durability": 100
		},
		"Id": 1379,
		"Durability": 100,
		"Amount": 1
	}],
	"Cooldown": 1200,
	"Cost": 0.0,
	"ResetCooldownWhenDie": false
}]

**Comment by leonardosnt** [comment]
Invalid format again...

Try this
```json
[
  {
    "Name": "civil",
    "Items": [
      {
        "Id": 253,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 15,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 4201,
        "Durability": 100,
        "Amount": 5
      },
      {
        "Id": 4744,
        "Durability": 100,
        "Amount": 5
      },
      {
        "Id": 16,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Ammo": 1,
        "Id": 33307,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Ammo": 1,
        "Id": 33305,
        "Durability": 100,
        "Amount": 2
      },
      {
        "Id": 1176,
        "Durability": 100,
        "Amount": 2
      }
    ],
    "Cooldown": 1200,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "Pescador",
    "Items": [
      {
        "Id": 503,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 509,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 510,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 511,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Xp": 500
      }
    ],
    "Cooldown": 1200,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "mecanico",
    "Items": [
      {
        "Id": 28,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 76,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 405,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 406,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Xp": 500
      }
    ],
    "Cooldown": 1200,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "comida",
    "Items": [
      {
        "Id": 81,
        "Durability": 100,
        "Amount": 10
      },
      {
        "Xp": 500
      }
    ],
    "Cooldown": 1200,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "taxi",
    "Items": [
      {
        "Vehicle": 76
      }
    ],
    "Cooldown": 1200,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "ropa",
    "Items": [
      {
        "Id": 253,
        "Durability": 100,
        "Amount": 4
      },
      {
        "Id": 209,
        "Durability": 100,
        "Amount": 4
      },
      {
        "Ammo": 20,
        "Id": 108,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Xp": 500
      }
    ],
    "Cooldown": 1200,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "Cadete",
    "Items": [
      {
        "Xp": 500
      },
      {
        "Id": 10,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 223,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 224,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 225,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 112,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Ammo": 8,
        "Id": 113,
        "Durability": 100,
        "Amount": 10
      },
      {
        "Id": 1195,
        "Durability": 100,
        "Amount": 7
      },
      {
        "Id": 1196,
        "Durability": 100,
        "Amount": 3
      }
    ],
    "Cooldown": 1200,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "militar",
    "Items": [
      {
        "Xp": 500
      },
      {
        "Id": 1010,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 1012,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 334,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 1270,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 253,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 8,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 146,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 151,
        "Durability": 100,
        "Amount": 2
      },
      {
        "Id": 7712,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 7711,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 1013,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 15043,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 15602,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Ammo": 60,
        "Id": 15611,
        "Durability": 100,
        "Amount": 5
      }
    ],
    "Cooldown": 3600,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "xp",
    "Items": [
      {
        "Xp": 5000
      }
    ],
    "Cooldown": 900,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "taxista",
    "Items": [
      {
        "Vehicle": 76
      }
    ],
    "Cooldown": 1200,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "offroad",
    "Items": [
      {
        "Vehicle": 1
      }
    ],
    "Cooldown": 1200,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "offroad-1",
    "Items": [
      {
        "Vehicle": 4
      }
    ],
    "Cooldown": 1200,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "lamborgini",
    "Items": [
      {
        "Vehicle": 1100
      }
    ],
    "Cooldown": 1200,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "lamborgini-1",
    "Items": [
      {
        "Vehicle": 1103
      }
    ],
    "Cooldown": 1200,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "van",
    "Items": [
      {
        "Vehicle": 35
      }
    ],
    "Cooldown": 1200,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "EMS",
    "Items": [
      {
        "Id": 15,
        "Durability": 100,
        "Amount": 5
      },
      {
        "Id": 269,
        "Durability": 100,
        "Amount": 5
      },
      {
        "Id": 311,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 312,
        "Durability": 100,
        "Amount": 1
      }
    ],
    "Cooldown": 1200,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "armero",
    "Items": [
      {
        "Id": 97,
        "Durability": 100,
        "Amount": 5
      },
      {
        "Id": 107,
        "Durability": 100,
        "Amount": 5
      },
      {
        "Id": 363,
        "Durability": 100,
        "Amount": 3
      },
      {
        "Id": 116,
        "Durability": 100,
        "Amount": 3
      },
      {
        "Id": 15003,
        "Durability": 100,
        "Amount": 3
      },
      {
        "Id": 15152,
        "Durability": 100,
        "Amount": 2
      },
      {
        "Id": 15012,
        "Durability": 100,
        "Amount": 3
      },
      {
        "Id": 15034,
        "Durability": 100,
        "Amount": 3
      },
      {
        "Id": 132,
        "Durability": 100,
        "Amount": 3
      },
      {
        "Id": 15064,
        "Durability": 100,
        "Amount": 3
      },
      {
        "Id": 15022,
        "Durability": 100,
        "Amount": 3
      },
      {
        "Id": 15043,
        "Durability": 100,
        "Amount": 3
      },
      {
        "Id": 15074,
        "Durability": 100,
        "Amount": 3
      },
      {
        "Id": 297,
        "Durability": 100,
        "Amount": 3
      },
      {
        "Id": 112,
        "Durability": 100,
        "Amount": 3
      },
      {
        "Id": 116,
        "Durability": 100,
        "Amount": 3
      }
    ],
    "Cooldown": 3600,
    "Cost": 0.0,
    "ResetCooldownWhenDie": false
  },
  {
    "Name": "ambulancia",
    "Items": [
      {
        "Vehicle": 54
      }
    ],
    "Cooldown": 1200,
    "Cost": 0.0,
    "ResetCooldownWhenDie": false
  },
  {
    "Name": "salario-EMS",
    "Items": [
      {
        "Ammo": 1,
        "Id": 33307,
        "Durability": 100,
        "Amount": 2
      }
    ],
    "Cooldown": 1200,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "salario-cadete",
    "Items": [
      {
        "Ammo": 1,
        "Id": 33307,
        "Durability": 100,
        "Amount": 2
      },
      {
        "Ammo": 1,
        "Id": 33306,
        "Durability": 100,
        "Amount": 1
      }
    ],
    "Cooldown": 1200,
    "Cost": 0.0,
    "ResetCooldownWhenDie": false
  },
  {
    "Name": "salario-militar",
    "Items": [
      {
        "Ammo": 1,
        "Id": 33307,
        "Durability": 100,
        "Amount": 5
      },
      {
        "Ammo": 1,
        "Id": 33306,
        "Durability": 100,
        "Amount": 1
      }
    ],
    "Cooldown": 1200,
    "Cost": 0.0,
    "ResetCooldownWhenDie": false
  },
  {
    "Name": "salario-pescador",
    "Items": [
      {
        "Ammo": 1,
        "Id": 33307,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Ammo": 1,
        "Id": 33306,
        "Durability": 100,
        "Amount": 1
      }
    ],
    "Cooldown": 1200,
    "Cost": 0.0,
    "ResetCooldownWhenDie": false
  },
  {
    "Name": "salario-taxista",
    "Items": [
      {
        "Ammo": 1,
        "Id": 33307,
        "Durability": 100,
        "Amount": 2
      },
      {
        "Ammo": 1,
        "Id": 33306,
        "Durability": 100,
        "Amount": 1
      }
    ],
    "Cooldown": 1200,
    "Cost": 0.0,
    "ResetCooldownWhenDie": false
  },
  {
    "Name": "salario-mecanico",
    "Items": [
      {
        "Ammo": 1,
        "Id": 33307,
        "Durability": 100,
        "Amount": 3
      },
      {
        "Ammo": 1,
        "Id": 33306,
        "Durability": 100,
        "Amount": 1
      }
    ],
    "Cooldown": 1200,
    "Cost": 0.0,
    "ResetCooldownWhenDie": false
  },
  {
    "Name": "mafioso",
    "Items": [
      {
        "Id": 10046,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 10047,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 1195,
        "Durability": 100,
        "Amount": 7
      },
      {
        "Id": 1196,
        "Durability": 100,
        "Amount": 3
      },
      {
        "FireMode": "AUTO",
        "Ammo": 60,
        "Barrel": {
          "AttachmentId": 70,
          "Durability": 100
        },
        "Id": 1379,
        "Durability": 100,
        "Amount": 1
      }
    ],
    "Cooldown": 1200,
    "Cost": 0.0,
    "ResetCooldownWhenDie": false
  }
]
```
