### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by SeussCZ** [uEssentials/uEssentials#400]
Hi, can u help me with some question?
1. what does it mean "ServerFrameRate": -1, and "ItemSpawnLimit": 10, ?
2. how to set cooldown on HomeCommand? Players have "Delay": 10, but cooldown dont. 
3. can i make kit for xp? (like uconomy "-50xp")
4. how can i set cooldown on tpa? essentials.command.tpa.send
Thank you

**Comment by JustOneMoreBlock** [comment]
Tad late:

```
"ServerFrameRate": -1,
````

Looking into the source code and I found this link:
Source: http://docs.unity3d.com/ScriptReference/Application-targetFrameRate.html

_Instructs game to try to render at a specified frame rate.

The default targetFrameRate is a special value -1, which indicates that the game should render at the platform's default frame rate._

Comment: I wouldn't change this.

```
"ItemSpawnLimit": 10,
```

For anyone that can spawn items using the "/i" command with given permissions restricts them to spawn only the limit specified.

Comment: If the limit is 10 and I try to spawn "/i mre 100" it will only spawn 10.


# HomeCommand

Well, the delay is there to prevent instant lags or people trying to teleport back to home to try and get out of jam. However, using the permissions file there is a cooldown options and likely be able to prevent players from spamming the home command.

Looking at the file the "HomeCommand" config.json file has a Cooldown in it. If you're not seeing it, you may need to regenerate your config or something.

```
  "HomeCommand": {
    "Cooldown": 30,
    "Delay": 0,
    "CancelTeleportWhenMove": false
  },
```

You could also open the "commands.json" file in the uEssentials file and set a cost. :)

# XP Kit

Yeah, you can do this;

https://github.com/uEssentials/uEssentials/wiki/Kits-Reference

```
      {
        "Xp": 200              // Xp item
      }, 
```

However, if you're trying to use uConomy for a kit. This does appear to be broken or more information is needed. I have created a bug report myself on this.

# TPA Cooldown

Looks like tpa doesn't have a cooldown. However, you can use the permissions file to set a cooldown or the commands.json file to set a cost.
