### ISSUE TITLE
tpa error

### ISSUE THREAD

**Issue by pepixiko** [uEssentials/uEssentials#401]
```
    <Permission Cooldown="30">essentials.command.tpa</Permission>
    <Permission Cooldown="0">essentials.command.tpa.send</Permission>
    <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
    <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
    <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
```

 or

```
    <Permission Cooldown="0">essentials.command.tpa</Permission>
    <Permission Cooldown="30">essentials.command.tpa.send</Permission>
    <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
    <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
    <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
```

does the same

hace lo mismo

English:
I have a problem I do a tpa to a friend and share the cooldown,
for example:
I / tpa leonard and have since used every 30 seconds, but the problem that if you do it to me have the two cooldown of 30 seconds.

Spanish:
tengo un problema yo hago un tpa a un amigo y comparte el cooldown, 
ejemplo:
yo hago /tpa leonard y lo tengo puesto que se use cada 30 segundos, pero el problema que si tu me lo haces a mi tenemos los dos cooldown de 30 segundos.

**Comment by OldCash4u** [comment]
PT-BR

O Primeiro modo que foi descrito é para colocar um tempo de utilização do comando /tpa , e o segundo modo descrito é para colocar tempo de utilização no envio de /tpa name

**Comment by pepixiko** [comment]
Leonard I have the problem.
Example:
(Send tpa): When I send / tpa Leonard I have to wait 300 sec
(Tpa accept): / tpa accept I have to wait 300 sec to send a / tpa
Share the same reuse time  /tpa accept and  /tpa send

config:
  "Tpa": {
    "ExpireDelay": 60,
    "TeleportDelay": 10,
    "CancelTeleportWhenMove": true 

Command_options:
  "tpa": {
    "Cost": 0.0,
    "Cooldown": 600
  },

**Comment by leonardosnt** [comment]
@pepixiko This is right, cooldown is for /tpa command, and applies to all sub commands.

**Comment by pepixiko** [comment]
Because that should not be so? Will you fix it It's that it's a problem

**Comment by leonardosnt** [comment]
No, this is not a problem.
