### ISSUE TITLE
Spawn véhicule

### ISSUE THREAD

**Issue by Riddler76** [uEssentials/uEssentials#402]
Hey,

Do you have a problem with vehicule spawn ?

**Comment by leonardosnt** [comment]
what?

**Comment by Riddler76** [comment]
Hey, 

I delete vehicule.dat, and after it, i don't have vehicule spawn.

I think is not uEssential issue, i just want to know if other people have this issue.

**Comment by leonardosnt** [comment]
Probably because the vehicle spawn table is in vehicles.dat ...

**Comment by Riddler76** [comment]
Yes, the file is generate automatically.
When i spawn a vehicule with /v is ok.
But when i do a /respawnvehicules no spawn at spwnpoint.

**Comment by leonardosnt** [comment]
/respawnvehiclesz does not respawn vehicles that was spawned using /vehicle
