### ISSUE TITLE
Money in Kits

### ISSUE THREAD

**Issue by JustOneMoreBlock** [uEssentials/uEssentials#404]
Hello,

I've mentioned this before. However, there still seems to be some kind of bug.

I use uConomy.
I use Web Kits.

config.json
```
  "Economy": {
    "UseXp": false,
    "XpCurrency": "Xp",
    "UconomyCurrency": "$"
  },
```

kits.json
```
  {
    "Name": "plusmoney",
    "Items": [
      {
        "Money": 5000
      }
    ],
    "Cooldown": 0,
    "Cost": 0.0,
    "ResetCooldownWhenDie": false
  },
```

This is giving Experience and not uConomy money. I was looking through your code, and you do have a uConomy hook and seems like it should work.

Am I overlooking something?

**Comment by leonardosnt** [comment]
This still happening?

Here is working fine.

**Comment by JustOneMoreBlock** [comment]
It's been fixed. Tested on Latest version.
