### ISSUE TITLE
Miku's Idea Archive

### ISSUE THREAD

**Issue by PandahutMiku** [uEssentials/uEssentials#41]
Outdated.

**Comment by JustOneMoreBlock** [comment]
+1 on Permissions for spawning a single item or vehicle like Item.294 and Vehicle.92

**Comment by leonardosnt** [comment]
@JustOneMoreBlock :+1:

**Comment by leonardosnt** [comment]
I will read it tomorrow, now i'm busy...

http://i.imgur.com/Qu3lnk0.png

**Comment by waspkiller** [comment]
Damn @leonardosnt

**Comment by leonardosnt** [comment]
kit maker :D :D

**Comment by Mikuzzzz** [comment]
Update: The Plugin already downloads updates if needed, If it could extract itself while/after shutting down and update itself it would be pretty cool, not sure if this would be done by a external application but it would be really cool to see it happen!

**Comment by waspkiller** [comment]
Yes I would love it to do that. thats less work on my end PLEASE i wanna play frustration free.

**Comment by leonardosnt** [comment]
@Mikuzzzz :+1:

**Comment by Mikuzzzz** [comment]
@leonardosnt I'm not sure how auto-detecting server shutdown would work on other Hosters but we use Windows Services which can be easily detected when they close. Maybe use something like an external watchdog that keep's checking if unturned.exe is running and if not then auto-extract.

**Comment by Mikuzzzz** [comment]
Update: 
Commands to change Config in game
Hook Into Zaupshop - Permission to buy/sell certain items. <command>buy.294</command> and `<command>sell.294</command>`
Permissions to ban players for a certain time like `<command>ban.300s</command> ``<command>ban.300m</command>` or` <command>kick.300s</command>` (like temp bans)
A possible permission hierarchy where a group can have 1 of 5 power's` <command>Power.1</command> `ect. The highest power (Power 1) cannot be kicked/banned by Power 2 and 3 and ect.
Allow only ENGLISH CHARACTERS IN CHAT PLZ I BEG

**Comment by waspkiller** [comment]
@leonardosnt Oh no! lol

**Comment by leonardosnt** [comment]
@waspkiller  ?

**Comment by Mikuzzzz** [comment]
@waspkiller What's the issue lol

**Comment by waspkiller** [comment]
> Allow only ENGLISH CHARACTERS IN CHAT PLZ I BEG
@leonardosnt 
:laughing: @Mikuzzzz

**Comment by Mikuzzzz** [comment]
Yes, I hate Chinese and Brazilian Spammers/People Speaking Non-English in Global chat :P

**Comment by leonardosnt** [comment]
im brazilian

PROBLEM?

uheuhehuehue brbrbrbr

joke

**Comment by Mikuzzzz** [comment]
Yes i do have a big issue.
PS. What's the Permission for Uessentials Teleporting? Essentials.tp?

**Comment by waspkiller** [comment]
![image](https://cloud.githubusercontent.com/assets/10227506/13028860/7796637c-d249-11e5-9d18-e2797f62163d.png)

**Comment by leonardosnt** [comment]
LMAO :laughing: :laughing: :laughing: :laughing: :laughing: :laughing:

**Comment by leonardosnt** [comment]
@Mikuzzzz Essentials.command.tp?

**Comment by Mikuzzzz** [comment]
Will try it.

**Comment by waspkiller** [comment]
![image](https://cloud.githubusercontent.com/assets/10227506/13028872/df1990dc-d249-11e5-9480-faa8cbe9432f.png)
Update that command wiki i wont touch that.

**Comment by Mikuzzzz** [comment]
@leonardosnt *Whisper* Rocket Reloading Breaks /tp... Can't test now. Don't wanna restart full server :p

**Comment by Mikuzzzz** [comment]
@leonardosnt Also, we still have this issue when someone dies.
[2/13/2016 12:06:35 PM] [Error] Error in MulticastDelegate PlayerDeath: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at Essentials.Event.Handling.EssentialsEventHandler.OnPlayerDeath (Rocket.Unturned.Player.UnturnedPlayer player, EDeathCause cause, ELimb limb, CSteamID murderer) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x00000] in <filename unknown>:0 
  at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00000] in <filename unknown>:0 
  at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <filename unknown>:0 
  at Rocket.Core.Extensions.MulticastDelegateExtension.TryInvoke (System.MulticastDelegate theDelegate, System.Object[] args) [0x00000] in <filename unknown>:0  

And no, we do not have deathmessages.

**Comment by leonardosnt** [comment]
@Mikuzzzz Dont use /rocket reload :C It break everything.

See /ess reload, you can reload kits, config and translations.

**Comment by Mikuzzzz** [comment]
@leonardosnt Is there no way to fix /rocket reloading doing that? it's kinda a very important thing to me and i hold it dearly to my heart.

**Comment by leonardosnt** [comment]
@Mikuzzzz ""When you need to use /rocket reload?""

**Comment by leonardosnt** [comment]
"what situation"

I don't know how say this

**Comment by Mikuzzzz** [comment]
@leonardosnt Adding New plugins, Fixing issues, Changing Permissions File, Changing Rocket Configs, Much easier to use then /rocket reload (pluginname)

**Comment by waspkiller** [comment]
I dont feel like doing it but hell its a bug fix ill do it.
![image](https://cloud.githubusercontent.com/assets/10227506/13028881/420fa1b8-d24a-11e5-8aa5-303eaa0a6282.png)

**Comment by leonardosnt** [comment]
@Mikuzzzz But, /rocket reload just reload "the superficial part", files, and so on, but does not reload the 'assembly' and cause issues.

I'll add an option to reload rocket files, and reload NEW plugins

**Comment by leonardosnt** [comment]
@waspkiller '-' :laughing:

**Comment by waspkiller** [comment]
Load too.

**Comment by Mikuzzzz** [comment]
Well the issue is it's a essential command to a lot of people (See What I did there?)
- Manual Donation System? Rip Uessentials
- Fucked up some permissions? rip Uessentials
- Adding your friend to a group like Admin/Moderator Or just players to regular? Rip Uessentials.
-Too lazy to reload one plugin per command? rip Uessentials
-Want to change Rocket Config? Rip Uessentials
-Want to kill yourself? Rip Uessentials, Has no /suicide.
-Forgetful and do /rocket reload? Rip UEssentials
Also, some of our custom plugins REQUIRE a /rocket reload to reload their Configs and such. I bet other plugins and things require this too.

**Comment by waspkiller** [comment]
![image](https://cloud.githubusercontent.com/assets/10227506/13028959/3f0861a6-d24c-11e5-8b87-85da7d20ea7c.png)

**Comment by Mikuzzzz** [comment]
Also I think MYSQL Or Web Interaction Plugins require a full rocket reload to reconnect to the database or website.

**Comment by waspkiller** [comment]
add a rocket reload command for uessentials? Have uessentials interact in rocket in a way to Make it work.

**Comment by Mikuzzzz** [comment]
@waspkiller I doubt that'd work. Or at least require a lot of work. Might as well fix /rocket reload.

**Comment by waspkiller** [comment]
or chew freaky out for Messing crap up and help him in the process of chewing him out

**Comment by leonardosnt** [comment]
"- Adding your friend to a group like Admin/Moderator Or just players to regular? "

why rip? what is happen?

**Comment by leonardosnt** [comment]
I will get my big cup of coffee.

**Comment by Mikuzzzz** [comment]
IF i wanted to add my friend to admin/moderator or any group at all i'd have to rocket reload to reload the permissions file

**Comment by waspkiller** [comment]
Still taking English classes? @leonardosnt ?

**Comment by Mikuzzzz** [comment]
And It isn't Freaky's fault /rocket reload doesn't work with uessentials, I blame Leon :P

**Comment by waspkiller** [comment]
![image](https://cloud.githubusercontent.com/assets/10227506/13029000/379cbec0-d24d-11e5-9d20-5e912b174834.png)
i blame everyone for me using this cup. geese
i dont think its nobodys fault really. cause conclusively it all leads to nelson at some point.

**Comment by Mikuzzzz** [comment]
Nah, It's Leon's Fault obviously. boo Leon. Bad Coder. Go back to coding school.

**Comment by leonardosnt** [comment]
who is leon?

**Comment by Mikuzzzz** [comment]
Leon= leonardosnt? no?

**Comment by leonardosnt** [comment]
just leo

**Comment by Mikuzzzz** [comment]
Lol okay. Leo.

**Comment by leonardosnt** [comment]
anything else?

**Comment by Mikuzzzz** [comment]
@leonardosnt 
PS. If your going with "I'll add an option to reload rocket files, and reload NEW plugins"
Please add a command to reload all plugins.

**Comment by Mikuzzzz** [comment]
Nice.
