### ISSUE TITLE
SkillSets Lose AfterDeath

### ISSUE THREAD

**Issue by SolidSnake916** [uEssentials/uEssentials#410]
So I didn't have essentials.keepskill.75 in permissions and it would wipe my skills, after searching I found you need to use that permission flag. So I tested it , but I lose 1-2 points in everything... Even my Special SKILLSET, Sharpshooter and Dexterity. Default Unturned you don't lose your specialized skills no matter what.

So what I'm asking is how do I make uEssentials not interfere will default skill loss, or make it mimic exactly how default unturned works... 

I cant just use essentials.keepskill.Sharpshooter either, because what if a player isn't that skillset and they will keep it...I don't want that happening.

Thanks

**Comment by WGSRangerWolf** [comment]
I can confirm this bug.

**Comment by WGSRangerWolf** [comment]
As i am an owner of a server and i remain admin, When i die i loose all the skills no matter what of the situation.

**Comment by WGSRangerWolf** [comment]
This is not a bug but rather an configuration file now.
This is my config
```
"Lose_Skills_PvP": 0.0,
      "Lose_Skills_PvE": 0.0,
      "Lose_Items_PvP": 1.0,
      "Lose_Items_PvE": 0.0,
```
