### ISSUE TITLE
 IT IS POSSIBLE ?  INCREASE SERVER SLOTS

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#413]
PT-BR

É Possível conseguir fazer um plugin que faça acontecer isso ? você acha que pode conseguir ? ;-;

Ele travou os slots no 23 de alguma forma... e o servidor continuou a dizer que tinha vaga e a lotar,  sem sair da lista publica

http://prnt.sc/c7tk1a

**Comment by JustOneMoreBlock** [comment]
Apparently so, https://dev.rocketmod.net/plugins/more-players/

Wouldn't mind if this was added.

**Comment by OldCash4u** [comment]
@JustOneMoreBlock 
Is presenting this page error 404 :( 

Where I could find a plugin to do this ?
It would be very nice if it were added to uessentials...

**Comment by WGSRangerWolf** [comment]
it is possible but i think the plugin got removed

**Comment by WGSRangerWolf** [comment]
https://dev.rocketmod.net/plugins/reservedslots/
