### ISSUE TITLE
Need Help With Kits

### ISSUE THREAD

**Issue by visloom28vi** [uEssentials/uEssentials#414]
Edit, I solved my first problem with kits now my permissions for kits are not working.

Is this still a thing? "Remove permissions with .* e.g essentials.kits.* otherwise all players will have access to admin commands…" because right now my permissions for kits are, but they are not working, please help, thanks! Can someone tell me their kit permissions or the right kit permissions?

>         <Permission Cooldown="0">essentials.kit.food</Permission>
>         <Permission Cooldown="0">essentials.kit.starter</Permission>
>         <Permission Cooldown="0">essentials.kit.build</Permission>
>         <Permission Cooldown="0">essentials.kit</Permission>
>         <Permission Cooldown="0">essentials.kits</Permission>

**Comment by leonardosnt** [comment]
```xml
 <Permission Cooldown="0">essentials.kit</Permission>
    <Permission Cooldown="0">essentials.kits</Permission>```
This is wrong...


https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference
