### ISSUE TITLE
Still Having Issues with kits .-.

### ISSUE THREAD

**Issue by visloom28vi** [uEssentials/uEssentials#415]
So i fixed the first part, now people dont have permission to do /kits and /kit (name)
i dont know why. these are my kit permissions , 

>         <Permission Cooldown="0">essentials.kit.starter</Permission>
        <Permission Cooldown="0">essentials.kit.food</Permission>
        <Permission Cooldown="0">essentials.kit.build</Permission>
        <Permission Cooldown="0">essentials.kit</Permission>
        <Permission Cooldown="0">essentials.kits</Permission>

i was told that these are wrong but i got them from https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference but they still do not work, Can someone write me ones that will work? Because i need it very badly for my server, thank you!

**Comment by leonardosnt** [comment]
The permission for commands are 'essentials.command.COMMAND-NAME' not 'essentials.COMMAND-NAME'
