### ISSUE TITLE
STILL having issues with kit permissions .-.

### ISSUE THREAD

**Issue by visloom28vi** [uEssentials/uEssentials#416]
OMFG i did everything, i did `<Permission Cooldown="0">essentials.command.kits</Permission>`
`<Permission Cooldown="0">essentials.kits</Permission>`
but NONE of them work, idk what im doing wrong, im such a retard, please help me.
i made like 3 threads already.....

**Comment by lammas112** [comment]
<Permission Cooldown="0">essentials.kit.Common</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
Rename the Common kit with your kit thats it

**Comment by leonardosnt** [comment]
Working fine... 

![](https://i.imgur.com/1DVHsbG.png)
