### ISSUE TITLE
CUSTOMIZE SERVER NAME IN ACTION [SUGGESTION]

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#418]
PT-BR

@leonardosnt teria como você fazer para ser personalizado o apelido do servidor que é exibido quando executa uma ação ? por exemplo o ./kill que aparece "server admin" para quem morreu , e o ./tell quando enviado pelo console que aparece "*CONSOLE*" para quem recebeu a mensagem...

É possível criar um "ServerActionName" para ser customizado a gosto ?

**Comment by leonardosnt** [comment]
Nao entendi. Poderia enviar um screenshot dessas mensagens?

**Comment by OldCash4u** [comment]
@leonardosnt

Quando uma mensagem privada é enviada no console pelo "/tell" o servidor é identificado como *console*

Foto 1 : http://prnt.sc/cctcne
Foto 2 : http://prnt.sc/cctb2c

Quando um jogador é morto pelo "/kill" o servidor ou jogador é identificado como "server admin"

Foto : http://prnt.sc/cctc76

**Comment by leonardosnt** [comment]
O primeiro eu posso adicionar uma opção pra mudar, mas o segundo é do Unturned, não tem como mudar.

**Comment by OldCash4u** [comment]
@leonardosnt ta bom :) :+1:
