### ISSUE TITLE
Outupdate 

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [uEssentials/uEssentials#419]
Need Hotfix in Build: #986 please http://imgur.com/a/XdY6H

**Comment by leonardosnt** [comment]
Can you upload the latest Rocket files? I cant download on rocketmod.net

**Comment by ZSHADOWWOLF** [comment]
Sure https://mega.nz/#!jdhyhLCQ!tLu_l1oMGBW5tEV7CbZXFUosM0vuIUCXhzxlQJmeY2w

**Comment by leonardosnt** [comment]
Thanks

**Comment by ZSHADOWWOLF** [comment]
How soon updated?

**Comment by rwalkos** [comment]
I have the same exact problem.

**Comment by leonardosnt** [comment]
I don't know, maybe tomorrow. I'm having problems with my internet.

**Comment by ZSHADOWWOLF** [comment]
Ohh...Not good

**Comment by rwalkos** [comment]
Sounds good man, thank you so much for this plugin, Your work is awesome.

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/releases/tag/1.2.0.7
