### ISSUE TITLE
Kits?

### ISSUE THREAD

**Issue by ZombieUNTURNED** [uEssentials/uEssentials#42]
I want to remove the Uessentials Kits.. it effects my other kits, and i even tried disabling it and i have no freaking clue of how it works either. could someone give me a file i can download.. a trusted member too...

**Comment by Mikuzzzz** [comment]
This is a example config file 

> {
>     "Locale": "en",
>     "PrivateMessageFormat": "(From {0}): {1}",
>     "UnfreezeOnDeath": true,
>     "UnfreezeOnQuit": true,
>     "EnableUnknownMessage": true,
>     "AdminBypassWarpCooldown": true,
>     "PerWarpPermission": true,
>     "WarpCooldown": 5,
>     "EnableJoinLeaveMessage": true,
>     "EnablePollRunningMessage": true,
>     "PollRunningMessageCooldown": 20,
>     "AntiSpam": {
>         "Enabled": true,
>         "Interval": 3
>     },
>     "Updater": {
>         "CheckUpdates": true,
>         "DownloadLatest": true
>     },
>     "AutoAnnouncer": {
>         "MessageInterval": 30,
>         "RandomMessages": true,
>         "Enabled": true,
>         "Messages": [
>             "<red>You can see kits by typing /kits, and to get a kit by typing /kit <name>",
>             "<red>Some Commands are not working. Please be patient with us",
>             "<red>We are Woof Gaming Community! Join our server group for updates! J.mp/WGS247",
>             "<red>Want VIP? Vote for our server for a chance to win vip!",
>             "<red>You can see our warps by typing /warps and doing /warp <name>",
>             "<red>Teleportaton tools: /tpa <name> /tpa <accept> /tpa <decline>",
>             "<red>Type /ping to view your ping",
>             "<red>Did you just die and want to get your loot back? Do /ret to fight for it!"
> 
> 
>         ]
>     },
>     "DisabledCommands": [
>         "kit",
>         "kits",
>         "warps",
>         "warp"
>     ]
> }
Just add that Disabled commands with only Kits and kit being blocked to the bottom of your config.json and restart the server

**Comment by leonardosnt** [comment]
```
"DisabledCommands": [
    "kit",
    "kits"
]
```

**Comment by waspkiller** [comment]
Psst @leonardosnt update commands! /itemfeatures and /vehiclefeatures
Psst If you donno where to find this thing u called disable commands. go to your plugins folder>uessentials and edit config.json and insert what they said.
