### ISSUE TITLE
Error in console. Please fix this

### ISSUE THREAD

**Issue by noammiz007** [uEssentials/uEssentials#421]
so i am getting an error in console. something about update. or idk. please fix this:
![image](https://cloud.githubusercontent.com/assets/10390196/18138067/a4fd1524-6fb3-11e6-898c-b41e33bca5b4.png)

**Comment by lammas112** [comment]
Please read other issues before posting.... uEssentials is not UPDATED YET. ...

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/releases/tag/1.2.0.7
