### ISSUE TITLE
IMPROVEMENT IN COMMAND /REQUESTURL [SUGGESTION]

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#427]
PT-BR

@leonardosnt

Teria como você adicionar a possibilidade de ser customizado a mensagem exibida pelo comando "/resquesturl" e a sua cor também ?

Foto : http://prnt.sc/cd5w34

E Também poderia ser adicionado um novo modo de uso , o (*) igual tem no comando "/kill "

Foto : http://prnt.sc/cd5ure

**Comment by leonardosnt** [comment]
Você pode alterar a cor nas traduções.

Amanha eu adiciono a opção (*)
