### ISSUE TITLE
command /requesturl doesn't work with the wildcard "*"

### ISSUE THREAD

**Issue by jserodio** [uEssentials/uEssentials#429]
I am trying to 
/requesturl * web http://some.web
but it keeps saying Player "*" not found. I've it in spanish, just in case it matters. (el jugador "*" no está).
but it works if I /requesturl player web http://some.web
Hope it gets fixed, I saw the code but it seemed to be fine.

**Comment by leonardosnt** [comment]
c197cb9a9965ccc7d7de6cd97dd80c95bee92616
