### ISSUE TITLE
join/leave feature request

### ISSUE THREAD

**Issue by WGSRangerWolf** [uEssentials/uEssentials#43]
Ok loving the join/leave messages . Request: is it possible we can add options like steam id . and or/ change colors of the text of how it appears.?
Can we customize it to say lets say
%player% joined The crazy world?
 Thanks.

**Comment by leonardosnt** [comment]
lang_en.json

``´json
    "PLAYER_JOINED": "<yellow>{0} joined the game",
    "PLAYER_EXITED": "<yellow>{0} left the game",
```

**Comment by leonardosnt** [comment]
...
