### ISSUE TITLE
 HOW TO MAKE ? [DOUBT]

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#430]
Como eu posso definir um requesturl * no AutoCommands ?

Eu coloquei "requesturl * \"Example\" www.example.com" , mas não deu certo...

**Comment by leonardosnt** [comment]
Aqui esta funcionando.

```json
"Commands": [
  "requesturl * \"Some example\" www.example.com"
]
```

![](http://imgur.com/yFb2hxs.png)
