### ISSUE TITLE
UEssentials Text commands not working

### ISSUE THREAD

**Issue by Zachman153** [uEssentials/uEssentials#432]
My /rules /laws and /teamspeak have stopped working for no apparent reason. Please help. Thank you.
My code is this: 
[
  {
    "Name": "rules",
    "Text": [
      "<cyan>DOTP Rules:",
      "<cyan>1) NO disrespecting players AND staff ",
      "<cyan>2) NO Kill ON SIGHT/Mugging/Raiding in Moscow (KOS) (all area's OUTSIDE MOSCOW is Kill on Sight/Raiding/Mugging is allowed)",
      "<cyan>3) If you see a player breaking a rule, Get an admin! Don't deal with it your self! ",
      "<cyan>4) Players can raid, ONLY OUTSIDE MOSCOW",
      "<cyan>5) Dawn of the Phoenix Staff member (Admin) words is final!",
      "<cyan>6) New Life Rule APPLIES(NLR)which means if you die you do NOT REMEMBER ANYTHING FROM YOUR PAST LIFE!",
      "<cyan>7) NO BUILDING IN MOSCOW! Without Adminsssss permission with a Land deed.",
      "<cyan>8) THIS IS YOUR WARNING! IF YOU BREAK A RULE YOUR BANNED! IF YOU DID NOT READ THE RULES OH WELL YOU MISSED OUT ON YOUR ONE WARNING!",
      "<cyan>9) Remember to have fun, and bring your friends."
    ]
  },
  {
    "Name": "teamspeak",
    "Text": [
      "<cyan>Our teamspeak: ts02-uk.nitrado.net:11500"
    ]
  },
  {
    "Name": "laws",
    "Text": [
      "<cyan> Failure to comply with laws will result in death of arrest.",
      "<cyan>#1: No shooting in town",
      "<cyan>#2: No stealing",
      "<cyan>#3: No mugging",
      "<cyan>#4: No destruction of property",
      "<cyan>#5: No killing",
      "<cyan>#6: If you are in the street and a car hits you, it is your fault.",
      "<cyan>#7: No Tresspassing",
      "<cyan>#8: Do not have weapons out in moscow Unless you are Military or Police",
      "<cyan>#9: ALL Ranger Weapons & High Caliber military weapons are ILLEGAL in moscow Except to Military & Police"
    ]
  }
]

**Comment by leonardosnt** [comment]
I've tried here and is working fine, probably you forgot to add the permissions for these commands.

The permission for text command are ```essentials.textcommand.<COMMAND_NAME>```

E.g

```xml
<Permission Cooldown="0">essentials.textcommand.rules</Permission>
<Permission Cooldown="0">essentials.textcommand.laws</Permission>
```

**Comment by Zachman153** [comment]
Where should i put that in the code?

**Comment by leonardosnt** [comment]
Check if there are any error on console.

**Comment by Zachman153** [comment]
How would I do this?

**Comment by Zachman153** [comment]
I put the permission thing in as you had it. It still dosent work still. "command not found"

**Comment by Zachman153** [comment]
They are still not working.

**Comment by leonardosnt** [comment]
You need to check the console... check if there are errors...

This is the console.

![](https://i.imgur.com/lkgXYs6.png)

**Comment by leonardosnt** [comment]
How you are opening your server?

**Comment by Zachman153** [comment]
Im using the control panel on my server hosting company's website.

**Comment by leonardosnt** [comment]
You need to find the console.

**Comment by Zachman153** [comment]
Would a screen shot help?

**Comment by leonardosnt** [comment]
Maybe

**Comment by Zachman153** [comment]
![image](https://cloud.githubusercontent.com/assets/22110572/18456397/388a747e-7916-11e6-9d53-5cd866f51d12.png)

**Comment by leonardosnt** [comment]
Open Web Console or CommandLine Manager

**Comment by Zachman153** [comment]
![image](https://cloud.githubusercontent.com/assets/22110572/18456641/3036b902-7918-11e6-946a-18f5ba96e731.png)

**Comment by Zachman153** [comment]
now what do i do?

**Comment by leonardosnt** [comment]
This is loading... wait it finish and take another screenshot.

**Comment by Zachman153** [comment]
its been doing it for about 5 min now. How long does it usually take?

**Comment by leonardosnt** [comment]
~ 30 seconds here...

**Comment by Zachman153** [comment]
Its still doing the loading thing......

**Comment by Zachman153** [comment]
does the server need to be shut down for this?

**Comment by leonardosnt** [comment]
Idk, restart the server...
