### ISSUE TITLE
UEssentials AutoAnnouncer not Working.

### ISSUE THREAD

**Issue by Gumpy** [uEssentials/uEssentials#435]
I enabled AutoAnnouncer in the Config file of UEssentials then it worked but when i edit the text and reload rocket nothing comes up. Please help me

**Comment by leonardosnt** [comment]
Check if there are errors on console.

**Comment by Gumpy** [comment]
i cant check console cuz im using www.gameservers.com to host my server

**Comment by leonardosnt** [comment]
Show me your `config.json`.
