### ISSUE TITLE
[BUG REPORT] /BOOM

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#439]
PT-BR

O Comando "/boom" parou de funcionar após atualização 3.17.0.0 do Unturned que ocorreu nesta sexta-feira 30/09/2016. :(

**Comment by leonardosnt** [comment]
Já arrumei 08c083fa29fd91875f0ab93fc648ef8623039989

Ainda hoje eu atualizo.

**Comment by OldCash4u** [comment]
@leonardosnt Você tem alguma nova previsão de quando vai ser lançado a nova versão do seu plugin ?

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/releases/tag/1.2.9.1
