### ISSUE TITLE
Delete items on death and on drop

### ISSUE THREAD

**Issue by Railgun69** [uEssentials/uEssentials#44]
here's a few features that creative servers need
when players die, they drop nothing - (plugin config option, able to be toggled true or false)

when players try to drop items on the floor, the items are instantly deleted - (plugin config option, able to be toggled true or false)

when players overflow their inventory with items, the excess items that drop on the floor are instantly deleted - (plugin config option, able to be toggled true or false)

we need this options to avoid server lag, especially on creative pvp servers

**Comment by waspkiller** [comment]
I would want this to be more configurable. sort of speak cause i run a pvp server and We have backpacks and pistols everywhere!

**Comment by Mikuzzzz** [comment]
I'm not trying to advertise or something plz don't hurt me... buut I don't think Uessentials needs this feature simply because another plugin already done it and does a pretty good job at it. https://dev.rocketmod.net/?rplugin=dropmanager

**Comment by leonardosnt** [comment]
@Mikuzzzz :+1:

**Comment by waspkiller** [comment]
@Mikuzzzz offense taken. Nah jk just make sure you give @leonardosnt :beer:

**Comment by leonardosnt** [comment]
https://dev.rocketmod.net/?rplugin=dropmanager
