### ISSUE TITLE
I have a suggstion

### ISSUE THREAD

**Issue by saitamasen** [uEssentials/uEssentials#440]
So im thinking if its possible to do two commands or 3 in 1 command only?
Example:
If i do command /set1
it will do  /kits and /skills.

Like it will give me a certain kit, and a certain skill.

**Comment by leonardosnt** [comment]
You can do this with Text Commands (text_commands.json)...

```json
  {
    "Name": "set1",
    "Text": [
      "execute: /kit foo",
      "execute: /maxskills"
    ]
  }
```

**Comment by saitamasen** [comment]
Thank you! Can it be also possible that you can only use 1 kit until you die?

**Comment by leonardosnt** [comment]
config.json:

  "Kit": {
   // ...
    "GlobalCooldown": 86400, // 24 hours (you can change this...)
    "ResetGlobalCooldownWhenDie": true
  },

**Comment by saitamasen** [comment]
Thanks a LOT! you're a life saver!

**Comment by saitamasen** [comment]
Btw one last time xD can it be also possible that you can use /set1 only not the other set and it will reset until you die like the kit you posted ? :D

**Comment by saitamasen** [comment]
@leonardosnt Sorry the /set1 doesnt work. it doesnt do anything , sometimes it says command not found. :/

**Comment by leonardosnt** [comment]
Put here your text_commands.json

**Comment by saitamasen** [comment]
Here it is
 [
  {
    "Name": "set1",
    "Text": [
      "execute: /kit class3",
      "execute: /skill parkour 2",
  "execute: /skill exercicse 2",
  "execute: /skill cardio 2",
  "execute: /skill overkill 1",
  "execute: /skill immunity 2"
    ]
  },
  {
    "Name": "set2",
    "Text": [
      "execute: /kit class2",
      "execute: /skill toughness 2",
  "execute: /skill sharpshooter 1",
  "execute: /skill immunity 2",
  "execute: /skill survival 2",
  "execute: /skill strength 1",
  "execute: /skill dexterity 1"
    ]
  },
  {
    "Name": "set3",
    "Text": [
      "execute: /kit class1",
      "execute: /skill sneakybeaky 2",
  "execute: /skill parkour 1",
  "execute: /skill exercise 1",
  "execute: /skill cardio 1",
  "execute: /skill sharpshooter 2",
  "execute: /skill healing 1",
  "execute: /skill immunity 1"
    ]
  },
]

**Comment by saitamasen** [comment]
@leonardosnt Okay so its working now, So can we have a cooldown on the text commands? like the kits? pick 1 command ,( you cannot pick another command/set) , and it will reset upon death.

**Comment by leonardosnt** [comment]
@saitamasen This is not possible.

**Comment by saitamasen** [comment]
nuuuu feels bad man :pepe:
