### ISSUE TITLE
Possible BUG

### ISSUE THREAD

**Issue by WGSRangerWolf** [uEssentials/uEssentials#442]
Everyone on my server is able to use the spawn commands. i did not allow them to spawn items in.......

**Comment by WGSRangerWolf** [comment]
My permissions
<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Color>gray</Color>
      <Members />
      <Permissions>
        <Permission Cooldown="12">essentials.command.kits</Permission>
        <Permission Cooldown="12">essentials.command.home</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.kit.*</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.online</Permission>
        <Permission Cooldown="0">essentials.command.rules</Permission>
        <Permission Cooldown="0">essentials.command.discord</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>vip</Id>
      <DisplayName>VIP</DisplayName>
      <Color>FF9900</Color>
      <Members>
        <Member>76561198016438091</Member>
      </Members>
      <ParentGroup>default</ParentGroup>
      <Permissions>
        <Permission Cooldown="0">effect</Permission>
        <Permission Cooldown="120">heal</Permission>
        <Permission Cooldown="30">v</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>

**Comment by leonardosnt** [comment]
> Remove permissions with .* e.g essentials.kits.* otherwise all players will have access to admin commands…

> Rocket broke it.

**Comment by WGSRangerWolf** [comment]
```
<Permission Cooldown="12">essentials.command.kits</Permission>
        <Permission Cooldown="12">essentials.command.kit.</Permission>
        <Permission Cooldown="12">essentials.command.home</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.kit.chainsaw</Permission>
        <Permission Cooldown="0">essentials.command.kit.survival</Permission>
        <Permission Cooldown="0">essentials.command.kit.eaglefire</Permission>
        <Permission Cooldown="0">essentials.command.kit.plane</Permission>
        <Permission Cooldown="0">essentials.command.kit.xp</Permission>
```
renders people not being allowed to use /kits

**Comment by WGSRangerWolf** [comment]
But if <Permission Cooldown="12">essentials.command.kit.*</Permission> is there it lets them use kits.
Before you ask i looked at the wiki. @leonardosnt

**Comment by leonardosnt** [comment]
this permission does not exist ```essentials.command.kit.eaglefire```

read permissins wiki again...

the correct permission is```essentials.kit.eaglefire```
