### ISSUE TITLE
/warp permissions

### ISSUE THREAD

**Issue by xShineyThighx** [uEssentials/uEssentials#445]
Am i missing something?

`<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Color>white</Color>
      <Members />
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="120">warp</Permission>
        <Permission Cooldown="120">warp.safezone</Permission>
        <Permission Cooldown="120">warp</Permission>
        <Permission Cooldown="120">essentials.command.warp</Permission>
        <Permission Cooldown="120">essentials.command.warp.safezone</Permission>
        <Permission Cooldown="120">essentials.command.warps</Permission>
        <Permission Cooldown="0">warps</Permission>
        <Permission Cooldown="30">home</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>vip</Id>
      <DisplayName>VIP</DisplayName>
      <Color>FF9900</Color>
      <Members>
        <Member>76561198016438091</Member>
      </Members>
      <ParentGroup>default</ParentGroup>
      <Permissions>
        <Permission Cooldown="0">effect</Permission>
        <Permission Cooldown="120">heal</Permission>
        <Permission Cooldown="30">v</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>`

whenever new users join they can` /warps `but no warps are defined, and when they `/warp <name>` they do not have access to this warp.

I've tried multiple ways to code the perm node, nothing working :(

**Comment by WGSRangerWolf** [comment]
essentials.warp.safezone
