### ISSUE TITLE
Making a vehicle kit?

### ISSUE THREAD

**Issue by Mcguy65** [uEssentials/uEssentials#446]
I know there is a plane kit that comes with the plugin when installed but dont know how to create my own?
Any help, would be very usefull. 
Thank you!

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/Kits-Reference

**Comment by Mcguy65** [comment]
Well, I was looking at that. But it doesnt really tell me on "how" to do it.
Is there some sort of command in game like /ckit? But for vehicle kits?

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/Command-Reference#editkit

**Comment by Mcguy65** [comment]
Thanks for the feed back. But, That doesnt really say anything about adding a VEHICLE to a kit..

**Comment by leonardosnt** [comment]
No ?

``Use /ekit [kit] additem vehicle [id]``

**Comment by WGSRangerWolf** [comment]
https://github.com/uEssentials/uEssentials/wiki/Kits-Reference
