### ISSUE TITLE
Need help with russian translation?

### ISSUE THREAD

**Issue by NoAdO** [uEssentials/uEssentials#452]
I have already tried to translate chat messages to Russian, but uessentials checks for updates and re-write my files at startup. Maybe you need someone to finish translation? Or maybe there's a way to permit uessentials to update translate file so i can do my translate?

**Comment by leonardosnt** [comment]
uEssentials will re-write only if your translation is invalid.

Here is working fine...
![image](https://cloud.githubusercontent.com/assets/13869336/19620140/854c39d2-984c-11e6-9d15-87081c9e1f41.png)

**Comment by NoAdO** [comment]
Well i'll try, but all death messages still are not translated. Was that planned?

**Comment by leonardosnt** [comment]
just translate...

**Comment by NoAdO** [comment]
OK :3
`{
    /*
        Colors:
            Use: <colorName OR hex value>
            HEX:
                <hex_value>, Example: <#FFFFFF>

            Names:
                <black>
                <blue>
                <clear>
                <cyan>
                <gray>
                <green>
                <grey>
                <magenta>
                <red>
                <white>
                <yellow>

        The unturned chat only suports ONE color.
        The algorithm will check if text contains an determined color,
        and will use it, doesn't matter a position in the message.

        For example:
            "<red>player joined the game"
            "player <red>joined the game"
            "player join<red>ed the game"

        The default color is Green.
    */

    "ALL_REPAIRED": "<cyan>Все ваши предметы починены.",
    "ALREADY_FROZEN": "<yellow>Этот игрок уже заморожен.",
    "ANYONE_ONLINE": "Нет игроков онлайн.",
    "ASCENDED": "Вы поднялись на {0} метров",
    "AUTO_REFUEL_DISABLED": "<magenta>Авто-заправка запрещена!",
    "AUTO_REFUEL_ENABLED": "<cyan>Авто-заправка разрешена!",
    "AUTO_RELOAD_DISABLED": "<magenta>Авто-перезарядка отключена!",
    "AUTO_RELOAD_ENABLED": "<cyan>Авто-перезарядка включена!",
    "AUTO_REPAIR_DISABLED": "<magenta>Авто-ремонт отключен!",
    "AUTO_REPAIR_ENABLED": "<cyan>Авто-ремонт включен!",
    "BLACKLISTED_ITEM": "Нельзя вызвать  '{0}' из черного списка.",
    "BLACKLISTED_VEHICLE": "Нельзя вызвать транспорт '{0}' из чёрного списка.",
    "CANNOT_TELEPORT_DRIVING": "<yellow>Вы не можете быть телепортированны, пока Вы в транспорте",
    "CHAT_ANTI_SPAM": "<yellow>Антиспам активирован. Ждите чтобы писать снова.",
    "CLEAR_EMPTY_VEHICLES": "Очищено {0} механизмов.",
    "CLEAR_ITEMS": "<magenta>Все предметы удалены!",
    "CLEAR_VEHICLES": "<magenta>Весь транспорт удален!",
    "COMMAND_ERROR_OCURRED": "<red>Произошла ошибка при попытке выполнить эту команду; Свяжитесь с админом!",
    "COMMAND_ERROR_OCURRED_ADMIN": "<red>An error occurred while executing this command. Check the console for more information.",
    "COMMAND_NO_MONEY": "Вы должны иметь ({0}{1}) для использования команды.",
    "COMMAND_NO_PERMISSION": "<yellow>У Вас нет прав на выполнение этой команды",
    "COMMAND_PAID": "Вы заплатили ({0}{1}) за использование команды.",
    "CONSOLE_CANNOT_EXECUTE": "<yellow>This command can't be executed from the console.",
    "CREATED_KIT": "<cyan>Вы создали новый кит с именем '{0}'!",
    "COMMAND_COOLDOWN": "<yellow>Можно использовать через {0} секунд.",
    "DAY": "день",
    "DAYS": "дней",
    "DEATH_ANIMAL": "{0} погиб от животного!",
    "DEATH_ARENA": "{0} был убит на арене!",
    "DEATH_BLEEDING": "{0} истёк кровью!",
    "DEATH_BONES": "{0} получил смертельный перелом!",
    "DEATH_BREATH": "{0} задохнулся!",
    "DEATH_BURNING": "{0} сгорел заживо!",
    "DEATH_FOOD": "{0} умер от голода!",
    "DEATH_FREEZING": "{0} замёрз насмерть!",
    "DEATH_GRENADE": "{0} погиб от взрыва гранаты!",
    "DEATH_GUN": "{2} убил {0} выстрелом в {1}!",
    "DEATH_INFECTION": "{0} умер от инфекции!",
    "DEATH_KILL": "{0} был убит.",
    "DEATH_LANDMINE": "{0} подорвался на мине!",
    "DEATH_MELEE": "{2} дорезал {0} ударом в {1}!",
    "DEATH_PUNCH": "{2} нанёс {0} смертельный удар в {1}!",
    "DEATH_ROADKILL": "{0} переехал {1}",
    "DEATH_SHRED": "{0} покромсали на куски!",
    "DEATH_SUICIDE": "{0} самоубился!",
    "DEATH_VEHICLE": "{0} погиб от взрыва транспорта!",
    "DEATH_WATER": "{0} умер от жажды!",
    "DEATH_ZOMBIE": "{0} был съеден зомби!",
    "DELETED_KIT": "<magenta>Вы удалили кит '{0}'.",
    "DESCENDED": "Вы опустились на {0} метров",
    "DROPKIT_LOCATION": "Брошен кит '{0}' на (x: {1:0.00}, y: {2:0.00}, z: {3:0.00})",
    "DROPKIT_PLAYER": "Брошен кит '{0}' на позиции '{1}'.",
    "DROPKIT_SENDER": "Брошен кит '{0}' на Вашей позиции.",
    "EMPTY_HANDS": "<yellow>В руках нет предмета.",
    "EVERYONE": "everyone",
    "EXPERIENCE_GIVEN": "<cyan>Вы дали {0} опыта игроку {1}.",
    "EXPERIENCE_LOST": "<magenta>Вы потеряли {0} опыта.",
    "EXPERIENCE_RECEIVED": "<cyan>Вы получили {0} опыта.",
    "EXPERIENCE_TAKE": "<magenta>Вы получили {0} опыта от игрока {1}.",
    "FAILED_FIND_PLACE_OR_PLAYER": "<yellow>Не найдено место или игрок '{0}'.",
    "FROZEN_ALL": "<cyan>Вы заморозили всех игроков!",
    "FROZEN_PLAYER": "<cyan>Вы были заморожены игроком {0}!",
    "FROZEN_SENDER": "<cyan>Игрок {0} заморожен!",
    "GIVEN_ITEM": "<cyan>Вы дали {0}x {1} ({2}) to '{3}'!",
    "GIVEN_ITEM_ALL": "<cyan>Вы дали {0}x {1} ({2}) всем игрокам!",
    "GIVEN_VEHICLE": "Вы дали {0} ({1}) игроку '{2}'",
    "GIVEN_VEHICLE_ALL": "Вы дали {0} ({1}) всем игрокам.",
    "HAND_REPAIRED": "<cyan>Предмет в Ваших руках восстановлен.",
    "HOUR": "hour",
    "HOURS": "hours",
    "INVALID_BOOLEAN": "<yellow>Неверное значение '{0}'.  Ожидается 'true' или 'false'.",
    "INVALID_COORDS": "<yellow>Неверные координаты ({0}, {1}, {2})!",
    "INVALID_ITEM_ID": "<red>Неверный id предмета '{0}'.",
    "INVALID_ITEM_ID_NAME": "<yellow>Неверные id/имя предмета '{0}'.",
    "INVALID_NUMBER": "<yellow>Неверное число '{0}'.",
    "INVALID_SKILL": "<yellow>Неверный скилл: {0}",
    "INVALID_STEAMID": "<yellow>SteamID '{0}' не верный!",
    "INVALID_VEHICLE_ID": "<yellow>Неверные id/имя транспорта '{0}'.",
    "INVENTORY_CLEAN": "<magenta>Ваш инвентарь очищен.",
    "INVENTORY_FULL": "<yellow>Ваш инвентарь полон. Предметы выпали на землю.",
    "ITEM_LIMIT": "<red>Нельзя вызвать больше {0} единомоментно.",
    "ITEM_NOT_FOUND": "<yellow>Предмет не найден: {0}",
    "JUMP_NO_POSITION": "<yellow>Позиция не найдена, попробуйте использовать /jump <distance>.",
    "JUMPED": "Вы прыгнули на (x: {0:0.00}, y: {1:0.00}, z: {2:0.00}).",
    "KICK_NO_SPECIFIED_REASON": "Не указана",
    "KICKED_ALL": "Кикнуто {0} игроков!",
    "KILL_ALL": "Вы убили всех!",
    "KILL_PLAYER": "Вы убиты {0}!",
    "KILLED_ANIMALS": "убито {0} животных.",
    "KILLED_ZOMBIES": "убито {0} зомби.",
    "KIT_ALREADY_EXIST": "<yellow>Уже существует кит с именем '{0}'.",
    "KIT_COOLDOWN": "<yellow>Вы должны ждать {0} секунд чтобы использовать кит снова.",
    "KIT_GIVEN_RECEIVER": "<cyan>Вы получили кит '{0}'!",
    "KIT_GIVEN_SENDER": "<cyan>Кит '{0}' выдан игроку {1}!",
    "KIT_GIVEN_SENDER_ALL": "<cyan>Кит '{0}' был выдан всем!",
    "KIT_GLOBAL_COOLDOWN": "<yellow>Вы должны ждать {0} чтобы использовать другой кит снова.",
    "KIT_LIST": "<blue>Доступные киты: {0}",
    "KIT_NO_MONEY": "Вы должны иметь ({0}{1}) для использования кита.",
    "KIT_NO_PERMISSION": "<yellow>У Вас нет доступа к этому киту.",
    "KIT_NONE": "<yellow>Нет доступа к этому киту.",
    "KIT_NOT_EXIST": "<yellow>Кит '{0}' не существует. Используйте /kits чтобы увидеть доступные киты.",
    "KIT_PAID": "Вы заплатили ({0}{1}) для использования кита.",
    "LIMB_ARM": "руку",
    "LIMB_HEAD": "голову",
    "LIMB_LEG": "ногу",
    "LIMB_TORSO": "торс",
    "MAX_SKILLS": "<cyan>Все Ваши скилы улучшены до максимального уровня.",
    "MAX_SKILLS_TARGET": "<cyan>Все скилы игрока {0} улучшены до максимального уровня.",
    "MINUTE": "минута",
    "MINUTES": "минут",
    "MUST_POSITIVE": "<yellow>Значение должно быть положительным.",
    "NEGATIVE_OR_LARGE": "<yellow>Значение отрицательное или слишком большое!",
    "NO_LONGER_ONLINE": "<yellow>Этого игрока нет в игре.",
    "NO_PLAYERS_FOR_KICK": "<yellow>Нет игроков для кика!",
    "NO_PLAYERS_FOR_TELEPORT": "<yellow>Нет игроков для телепортации!",
    "NOBODY_TO_REPLY": "<yellow>Некому отвечать.",
    "NONE_FOR_REPLY": "<yellow>Некому отвечать!",
    "NOT_DIED_YET": "<yellow>You have not died yet.",
    "NOT_FROZEN": "<cyan>Этот игрок не заморожен.",
    "NOT_IN_VEHICLE": "<yellow>Вы не в машине.",
    "NUMBER_BETWEEN": "<yellow>Используйте число из диапазона от {0} до {1}",
    "ONLINE_PLAYERS": "<blue>{0}/{1} игроков онлайн.",
    "ONLY_NUMBERS": "<yellow>Используйте число.",
    "PING": "<blue>Ваш пинг: {0}",
    "PING_OTHER": "<blue>Пинг игрока {0}: {1}",
    "PLAYER_CANNOT_EXECUTE": "<yellow>Эта команда не может быть выполнена в игре.",
    "PLAYER_EXITED": "<blue>{0} вышел из игры.",
    "PLAYER_JOINED": "<blue>{0} вошел в игру.",
    "PLAYER_NOT_FOUND": "<yellow>Игрок '{0}' не найден!",
    "PLAYER_RESET": "Игрок был очищен.",
    "PLAYER_RESET_KICK": "Вы были очищены.",
    "POLL_ALREADY_VOTED": "<yellow>Вы уже голосовали в этом голосовании.",
    "POLL_INFO": "<blue>Информация о голосовании '{0}':",
    "POLL_LIST": "<blue>Запущенные голосования:",
    "POLL_LIST_ENTRY": "<blue>  Название: {0}, За: {2}, Против: {3}",
    "POLL_NAME_IN_USE": "<yellow>Голосование с таким именем уже существует.",
    "POLL_NONE": "<yellow>Нет запущенных голосований.",
    "POLL_NOT_EXIST": "<yellow>Голосования с таким именем не существует.",
    "POLL_RUNNING": "<cyan>Голосование '{0}' запущено, используйте /vote yes|no для голосования.",
    "POLL_STARTED": "<cyan>Голосование создано, используйте /vote yes|no для голосования:  {1}",
    "POLL_STOPPED": "<magenta>Голосование '{0}' закончено, Голосов yes: {2}, Голосов no: {3}",
    "POLL_VOTED_NO": "Вы проголосовали NO в голосовании '{0}'.",
    "POLL_VOTED_YES": "Вы проголосовали YES в голосовании '{0}'.",
    "POSITION": "<blue>Ваши координаты: (x: {0:0.00}, y: {1:0.00}, z: {2:0.00})",
    "POSITION_OTHER": "<blue>Координаты игрока {0}: (x: {1:0.00}, y: {2:0.00}, z: {3:0.00})",
    "PVP_DISABLED": "PvP запрещен!",
    "PVP_ENABLED": "PvP разрешен!",
    "RECEIVED_ITEM": "<cyan>Вы получили {0}x {1} ({2})",
    "RECEIVED_VEHICLE": "Вы получили {0} ({1})",
    "RESPAWNED_ANIMALS": "<cyan>Заспавнено {0} животных!",
    "RESPAWNED_ITEMS": "<cyan>Все предметы снова заспавнены!",
    "RESPAWNED_VEHICLES": "<cyan>Весь транспорт снова заспавнен!",
    "RESPAWNED_ZOMBIES": "<cyan>Заспавнено {0} зомби!",
    "RETURNED": "Вы вернулись на место своей смерти.",
    "SECOND": "секунда",
    "SECONDS": "секунд",
    "SKILL_SET": "Уровень Вашего скилла '{0}' установлен на {1}",
    "SKILL_SET_ALL": "Уровень скилла '{0}' установлен на {1} для всех.",
    "SKILL_SET_PLAYER": "Для игрока '{0}' уровень скилла '{1}' установлен на {2}.",
    "SPAWNED_ITEM": "<cyan>Вы заспавнили ({0}x) {1}!",
    "SPAWNED_ITEM_AT": "<cyan>Вы заспавнили ({0}x) {1} на (x: {2:0.00}, y: {3:0.00}, z: {4:0.00})!",
    "SPAWNED_VEHICLE_AT_PLAYER": "<cyan>Вы заспавнили транспорт возле игрока {0}.",
    "SPAWNED_VEHICLE_AT_POSITION": "<cyan>Вы заспавнили транспорт на (x: {0:0.00}, y: {1:0.00}, z: {2:0.00}).",
    "SPY_MODE_OFF": "<magenta>Режим Spy отключен.",
    "SPY_MODE_ON": "<cyan>Режим Spy включен.",
    "SUDO_EXECUTED": "{0} выполнил команду '{1}'.",
    "TELEPORT_CANCELLED_MOVED": "<yellow>Телепортация отменена - Вы двигались.",
    "TELEPORT_DELAY": "<blue>Вы будете телепортированны через {0} секунд.",
    "TELEPORTED": "Вы телепортированы к '{0}'.",
    "TELEPORTED_ALL_COORDS": "Все игроки телепортированы на (x: {0:0.00}, y: {1:0.00}, z: {2:0.00})!",
    "TELEPORTED_ALL_PLAYER": "Все игроки телепортированы к {0}!",
    "TELEPORTED_ALL_YOU": "Все игроки телепортированы к Вам!",
    "TELEPORTED_BED": "Вы телепортированны к кровати.",
    "TELEPORTED_SENDER": "'{0}' телепортирован к '{1}'.",
    "TPA_ACCEPTED": "'{0}' принял Ваш запрос телепортации.",
    "TPA_ACCEPTED_SENDER": "Вы приняли запрос телепортации игрока {0}.",
    "TPA_CANCELLED": "Вы отменили свой запрос телепортации.",
    "TPA_CANNOT_TELEPORT": "Игрок {0} не может телепортироваться пока он в машине.",
    "TPA_DENIED": "'{0}' отклонил Ваш запрос телепортации.",
    "TPA_DENIED_SENDER": "Вы отклонили запрос телепортации игрока {0}.",
    "TPA_NONE": "У Вас нет никаких запросов телепортации.",
    "TPA_SENT": "Вы отправили запрос телепортации игроку {0}.",
    "TPA_SENT_SENDER": "{0} отправил Вам запрос телепортации, используйте /tpa accept чтобы принять.",
    "TPA_YOURSELF": "Вы не можете отправить запрос телепортации самому себе.",
    "UNFROZEN_ALL": "<magenta>Вы разморозили всех игроков!",
    "UNFROZEN_PLAYER": "<magenta>Вы были разморожены игроком {0}!",
    "UNFROZEN_SENDER": "<magenta>Игрок {0} разморожен!",
    "USE_COOLDOWN": "<yellow>Ждите {0} секунд чтобы использовать снова.",
    "VEHICLE_REFUELED": "<cyan>Ваша машина заправлена!",
    "VEHICLE_REFUELED_ALL": "<cyan>Все машины заправлены!",
    "VEHICLE_REPAIRED": "<cyan>Ваша машина отремонтирована!",
    "VEHICLE_REPAIRED_ALL": "<cyan>Все машины отремонтированы!",
    "WARP_ALREADY_EXISTS": "<yellow>Варп с этим именем уже существует.",
    "WARP_COOLDOWN": "<blue>Вы будете телепортированы через {0} секунд.",
    "WARP_LIST": "<blue>Доступно варпов: {0}",
    "WARP_NO_PERMISSION": "<yellow>У Вас нет доступа к этому варпу.",
    "WARP_NONE": "<red>Варп не существует!",
    "WARP_NOT_EXIST": "<yellow>Варп '{0}' не существует!",
    "WARP_REMOVED": "<magenta>Варп '{0}' удален.",
    "WARP_SET": "<cyan>Варп '{0}' установлен.",
    "WARP_TELEPORTED": "Телепортированы на варп '{0}'.",
    "WITHOUT_BED": "<yellow>У Вас нет кровати для телепортации.",
    "REQUEST_URL_SUCCESS": "Вы предложили '{0}' открыть ссылку '{1}'"
}
`
