### ISSUE TITLE
[BUG REPORT] /BOOM

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#454]
PT-BR

O Comando "/boom" parou de funcionar novamente , após atualização 3.17.2.1 do Unturned que ocorreu nesta sexta-feira 21/10/2016.
Mensagem exibida no console : http://prnt.sc/cxa8k0

**Comment by WGSRangerWolf** [comment]
Error log output when the /boom command is executed

**Comment by WGSRangerWolf** [comment]
3.17.2.2 Current unturned version

**Comment by leonardosnt** [comment]
Você já reportou isso, e foi corrigido.
