### ISSUE TITLE
Missing Deathnotes

### ISSUE THREAD

**Issue by WGSRangerWolf** [uEssentials/uEssentials#458]
Ecxdirerr has been blown up by a missle?
Add it plz

**Comment by WGSRangerWolf** [comment]
[Ecxdirerr] was crushed by a zombie!

**Comment by WGSRangerWolf** [comment]
[Ecxdirerr] was electrocuted by a zombie!

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/tree/experimental-139127b

**Comment by WGSRangerWolf** [comment]
Explosive Bullet

**Comment by WGSRangerWolf** [comment]
Lets leave this open While i keep finding it.

**Comment by leonardosnt** [comment]
I've implemented all missing death notes.

**Comment by WGSRangerWolf** [comment]
Really? even explosive bullet?

**Comment by leonardosnt** [comment]
I said ALL

explosive bullet are "splash"

**Comment by WGSRangerWolf** [comment]
Not according to unturned

**Comment by leonardosnt** [comment]
I tested.

**Comment by WGSRangerWolf** [comment]
k ima install the experimental build

**Comment by WGSRangerWolf** [comment]
Do you need the api key for serverwide announcment that unturned update?

**Comment by leonardosnt** [comment]
Yes, just for testing, I'll add an option in config.json to specify the api key...

**Comment by WGSRangerWolf** [comment]
installed latest version and tested the death, Do i need to restart the server and delete translation for it 2 work?

**Comment by WGSRangerWolf** [comment]
Ill give you api key through steam
Steam name: ecxdirerr

**Comment by leonardosnt** [comment]
Try `/ess reload lang`

**Comment by WGSRangerWolf** [comment]
[World] LucasBB [LucasBB]: "/tpa accept"
[World] Turtle's Sidekick [Ecxdirerr | Bday next Tues]: "/ess reload lang"
[World] {Suicide Squad} [Leader]  boubir [boubir]: "/kit rifle"
[World] Turtle's Sidekick [Ecxdirerr | Bday next Tues]: "/tp nac"
Turtle's Sidekick moved x:-304.4977 y:49.87226(+21.95875) z:70.42836 in the last second (0.07236862)
IsAbusing >> Turtle's Sidekick Died by a player not in godmode
Turtle's Sidekick [Ecxdirerr | Bday next Tues] was blown up by NaCl [NaClmore] with an explosive bullet!

**Comment by WGSRangerWolf** [comment]
Got the steam apikey, Just waiting for you to get on steam

**Comment by leonardosnt** [comment]
Check if your translation file contains these entries https://github.com/uEssentials/uEssentials/blob/master/default/lang_en.json#L83-L92

**Comment by leonardosnt** [comment]
ok

**Comment by WGSRangerWolf** [comment]
ah shit copied it in the wrong section lol

**Comment by leonardosnt** [comment]
add me: leonard0sc

**Comment by WGSRangerWolf** [comment]
This you? http://steamcommunity.com/profiles/76561198144490276/

**Comment by WGSRangerWolf** [comment]
Just provide me with your steam64id And i can find u faster

**Comment by leonardosnt** [comment]
http://steamcommunity.com/id/leonardosnt/

**Comment by WGSRangerWolf** [comment]
added
