### ISSUE TITLE
Login/Register

### ISSUE THREAD

**Issue by Aceheliflyer** [uEssentials/uEssentials#459]
A player won't be able to move or get damaged by anything without signing in.
This can be used to prevent being killed by a player/zombie when loading into the server.

User information will be saved to MySQL. Information can also be bound to the user Steam64 ID. This can prevent other players from getting into one's Steam account and griefing the server and can prevent people from blaming other users.

`/register <username> <password>`
`/login <username> <password>`

Note: This option can be turned on or off.

**Comment by WGSRangerWolf** [comment]
Or make the login info store in a xml

**Comment by leonardosnt** [comment]
I'm not sure if this is useful...
Just don't share your password and anyone will be able to log in your Steam account.

**Comment by Aceheliflyer** [comment]
@leoardosnt The accounts are completely separate from Steam. When you register the account, it's saved to the SQL database with the persons Steam Id, the username they chose to use, and the password. It's like how Uconomy stores the data. The accounts are not linked to anything.

**Comment by leonardosnt** [comment]
Why did you need this???? you can only join on unturned if you are logged on steam.

**Comment by Aceheliflyer** [comment]
It was just a simple idea. It could be used for admins where they can't receive their rank before they sign in. It could also be used to restrict players from impersonating other users by trying to use a character name that already exists. New users will keep the default rank, once they sign in they can receive the registered rank. There are many possibilities.

**Comment by WGSRangerWolf** [comment]
Administration is verified by Steamid. Solid idea but steam got that covered

**Comment by leonardosnt** [comment]
^
