### ISSUE TITLE
save command

### ISSUE THREAD

**Issue by WGSRangerWolf** [uEssentials/uEssentials#46]
Sometimes save command doesn't save our Structures D: i know devastating Could this. maybe there is a conflict in this plugin and rocket and unturned where something doesnt wanna work right and prevents something :disappointed:

**Comment by Mikuzzzz** [comment]
Our /Save Works fine.

**Comment by waspkiller** [comment]
why isnt it working for me? :/

**Comment by Mikuzzzz** [comment]
A Plugin conflict or maybe your disk sucks :p

**Comment by waspkiller** [comment]
I had a feeling it was a plugin conflict
