### ISSUE TITLE
[Question] Why does using "/ess reload" not entirely work?

### ISSUE THREAD

**Issue by Aceheliflyer** [uEssentials/uEssentials#467]
When I use the command `ess reload` in the console, it does not entirely reload everything. For example, when I make changes to the message announcer and I use `ess reload`, it doesn't update the message announcer. So I end up having to do `rocket reload uess` to get it to update. However, it does cause bugs as the red text implies. Is this a bug or is it the way it's supposed to be?

**Comment by leonardosnt** [comment]
"is the way it's supposed to be"

**Comment by WGSRangerWolf** [comment]
Closing as question has been answered
