### ISSUE TITLE
Suggestion / Generator Refuel

### ISSUE THREAD

**Issue by warmharddeath** [uEssentials/uEssentials#468]
Thinking of a command like /refuel which can refuel any generators that the player is looking at.

**Comment by WGSRangerWolf** [comment]
#417

**Comment by Aceheliflyer** [comment]
Why does `/clear i` not have a radius too?

**Comment by Aceheliflyer** [comment]
Oops, wrong issue.

**Comment by leonardosnt** [comment]
It was already suggested here: #417

@Aceheliflyer 

Because it use a method that is built in Unturned, and I can't change.

I'll "fix" it, is already in my todo list.
