### ISSUE TITLE
item

### ISSUE THREAD

**Issue by waspkiller** [uEssentials/uEssentials#47]
doing /item all 334 spawns something different and having to remove all. Shown here
it gives me 334 birtch frames

**Comment by waspkiller** [comment]
Server people didnt let me use gyso to show ya

**Comment by leonardosnt** [comment]
Use ```/i all [item] [amount]``` instead ```/i [item] [amount]```

**Comment by waspkiller** [comment]
i did.....

**Comment by leonardosnt** [comment]
"doing /item all 334 spawns..." sure?

It give will a smALL birch frame...

**Comment by waspkiller** [comment]
Yeah ill double check

**Comment by waspkiller** [comment]
it spawns 334 x birtch frame. ID FOr nightvision is 334

**Comment by waspkiller** [comment]
Got picture proof stand by.

**Comment by leonardosnt** [comment]
/i maplestr 334 -> give you 334 maplestrikes
/i all 334 -> give you 334 small frames

You should use /ITEM all [ITEM] [!!!!AMOUNT!!!!]

**Comment by leonardosnt** [comment]
for example

/i all 364 1

**Comment by waspkiller** [comment]
![image](https://cloud.githubusercontent.com/assets/10227506/13028784/29e4cefe-d247-11e5-8b5b-ad12d47c908d.png)
![image](https://cloud.githubusercontent.com/assets/10227506/13028785/3bbe352a-d247-11e5-8868-60bb15678836.png)
Say again mate?

**Comment by waspkiller** [comment]
well on the wiki it says Military night vision is 334
sup with that?

**Comment by waspkiller** [comment]
Welp. my bad lol. needs 3 i guess. We should compile a faq to minimkize confusion
