### ISSUE TITLE
Make a release :(

### ISSUE THREAD

**Issue by WGSRangerWolf** [uEssentials/uEssentials#471]

**Comment by leonardosnt** [comment]
Can you fucking wait? I am working on it.

**Comment by WGSRangerWolf** [comment]
yes i can, but my playerbase cant. and they are bugging me to bug you

**Comment by OldCash4u** [comment]
PT-BR

@WGSRangerWolf kkkkk meus jogadores também ficarão desesperados , meu servidor é todo baseado encima do uEssentials , sem ele é nada :P
