### ISSUE TITLE
bug when starting the plugin

### ISSUE THREAD

**Issue by noammiz007** [uEssentials/uEssentials#473]
here is the picture:
![uessentials error](https://cloud.githubusercontent.com/assets/10390196/20030079/1e40c3dc-a366-11e6-850d-6eec8571b97d.png)

**Comment by leonardosnt** [comment]
Are your LPX plugin working ? Here is not working...

**Comment by noammiz007** [comment]
i am not using lpx

**Comment by leonardosnt** [comment]
Which plugins are you using?

**Comment by Aceheliflyer** [comment]
I found out that some of the plugins can screw with uEssnetials; the older Jail plugin can cause a shipload of errors.

**Comment by leonardosnt** [comment]
#484
