### ISSUE TITLE
cooldown back

### ISSUE THREAD

**Issue by pepixiko** [uEssentials/uEssentials#474]
Hello leonard, you could put cooldown to back ?? I would greatly appreciate it: D
delay: 10
cooldown: 300

**Comment by leonardosnt** [comment]
????
You can do this in command_options.json

**Comment by leonardosnt** [comment]
```java
  "back": {
    "Delay": 10,
    "Cooldown": 30
  }
```

**Comment by pepixiko** [comment]
yes?? ok thank!! and /tpa also??
  "tpa": {
    "Cooldown": 600
  }  
for example?

**Comment by leonardosnt** [comment]
yes

**Comment by pepixiko** [comment]
thank you! closed topic!
