### ISSUE TITLE
experience 1 hour

### ISSUE THREAD

**Issue by pepixiko** [uEssentials/uEssentials#476]
"AutoCommands": {
    "Commands": [
      {
        "RunOnce": false,
        "Timer": 1200,
        "Commands": [
          "say \"Hora de la comida!\" 0 255 255", "
          "item * mre"   ---> add 100 experience all player??
        ]
      }
    ],

there is some command that each 1 hour experience?

**Comment by leonardosnt** [comment]
`exp * 100`

**Comment by pepixiko** [comment]
"back": {
    "TeleportDelay": 10,
    "Cooldown": 30
  }, 
no work :S
What I want is that when you put / back that afternoon 10 seconds and not instant

**Comment by pepixiko** [comment]
"AutoCommands": {
    "Commands": [
      {
        "RunOnce": false,
        "Timer": 30,
        "Commands": [
          "say \"Exp free!\" 0 255 255",
          "exp 1000"		  
        ]
      }
    ],

**Comment by leonardosnt** [comment]
# exp 100 *

**Comment by leonardosnt** [comment]
**Back** does not have "TeleportDelay", only **Tpa**.

**Comment by pepixiko** [comment]
and you can add cooldown the /back?

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/issues/474#issuecomment-258647707
https://github.com/uEssentials/uEssentials/issues/474#issuecomment-258647707

**Comment by pepixiko** [comment]
the message that I have given 100 experience appears, but press a key or and experience does not increase

**Comment by leonardosnt** [comment]
The experience command was broken in Rocket 4.9.3.0, I'll fix...

https://github.com/uEssentials/uEssentials/blob/5eaee8b4cdc410a7efdb045139e73425416ea931/src/Commands/CommandExperience.cs#L104

**Comment by pepixiko** [comment]
a ok! thank you! :) wait fix!

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/releases/tag/experimental-143eb19

**Comment by pepixiko** [comment]
Fixed errors?

**Comment by leonardosnt** [comment]
experience thing

**Comment by pepixiko** [comment]
yes? i love!! xD
