### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by WGSRangerWolf** [uEssentials/uEssentials#477]
Exp does not give to everyone.
Cooldown sometimes bugs out to 3k instead of 30 second cooldown.

**Comment by leonardosnt** [comment]
Exp does not give to everyone. ???

Could you explain better?

**Comment by WGSRangerWolf** [comment]
it doesn't give exp to everyone else... like /exp 90000 * says it gave but the people don't receive it

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/releases/tag/experimental-143eb19

**Comment by WGSRangerWolf** [comment]
ah k, and i think the cooldown one is more like. a rocketmod issue? as it creaps up overtime
