### ISSUE TITLE
Deathmessages work incorrect

### ISSUE THREAD

**Issue by NoAdO** [uEssentials/uEssentials#479]
`    "DEATH_MELEE": "{2} дорезал {0} ударом в {1}!",`
Supposed to be like "Murder дорезал Victim ударом в left hand!" but the announe is "Murder дорезал Victim ударом в ?!"

My translation looks like

```
    "KIT_PAID": "Вы заплатили ({0}{1}) для использования кита.",
    "SKULL": "голову",
    "LEFT_HAND": "левую ладонь",
    "RIGHT_HAND": "правую ладонь",
    "LEFT_ARM": "левую руку",
    "RIGHT_ARM": "правую руку",
    "LEFT_FOOT": "левую ступню",
    "RIGHT_FOOT": "правую ступню",
    "LEFT_LEG": "левую ногу",
    "RIGHT_LEG": "правую ногу",
    "SPINE": "spine",
    "LEFT_BACK": "левую лопатку",
    "RIGHT_BACK": "правую лопатку",
    "LEFT_FRONT": "грудь слева",
    "RIGHT_FRONT": "грудь справа",
    "MAX_SKILLS": "<cyan>Все Ваши скилы улучшены до максимального уровня.",
```

Is there a problem with addon or with my files? It started after friday update..

**Comment by leonardosnt** [comment]
Just change the order of variables "{number}";

**Comment by leonardosnt** [comment]
I forgot to add the "LIMB_" prefix in russian translation, I'll fix.

You can fix this by adding the "LIMB_" prefix, like here:
https://github.com/uEssentials/uEssentials/blob/master/default/lang_en.json#L148-L161

**Comment by NoAdO** [comment]
OK, then it should be

`    "LIMB_SKULL": "голову",
    "LIMB_LEFT_HAND": "левую ладонь",
    "LIMB_RIGHT_HAND": "правую ладонь",
    "LIMB_LEFT_ARM": "левую руку",
    "LIMB_RIGHT_ARM": "правую руку",
    "LIMB_LEFT_FOOT": "левую ступню",
    "LIMB_RIGHT_FOOT": "правую ступню",
    "LIMB_LEFT_LEG": "левую ногу",
    "LIMB_RIGHT_LEG": "правую ногу",
    "SPINE": "позвоночник",
    "LEFT_BACK": "левую лопатку",
    "RIGHT_BACK": "правую лопатку",
    "LEFT_FRONT": "грудь слева",
    "RIGHT_FRONT": "грудь справа",`

Just helping copypaste to someone =)

**Comment by NoAdO** [comment]
К сожалению плагин перегружает свой перевод обратно, заменяя мои правки

**Comment by leonardosnt** [comment]
Try https://github.com/uEssentials/uEssentials/releases/tag/experimental-b3d6f86

**Comment by NoAdO** [comment]
Works! Will it update to release? Or next pre-release? Or no update?
