### ISSUE TITLE
Death Messages

### ISSUE THREAD

**Issue by Mikuzzzz** [uEssentials/uEssentials#48]
Error: http://pastebin.com/jQMmxgus

**Comment by waspkiller** [comment]
Sadokus deathmessage plugin doesnt like this plugin
The other plugins seems to be geard towards the same plugin but the claim flag i donno gotta experment with that.
Warning DO NOT DO /clear -v while your in a vehicle
will completely remove you from the game and your there.

**Comment by waspkiller** [comment]
Closing this issue as it is related to another plugin.

**Comment by Mikuzzzz** [comment]
we don't have deathmessages.

**Comment by waspkiller** [comment]
Reopened as requested via steam

**Comment by leonardosnt** [comment]
Stackoverflow fixed!

But, how you gotten this error?

**Comment by Mikuzzzz** [comment]
Sorry, what? how i got the error? It just started occuring?

**Comment by waspkiller** [comment]
it occurs every so often and doesnt really effect the functions of plugins
It just happens.

**Comment by leonardosnt** [comment]
@Mikuzzzz When it happens? here is fine, no errors.

Poor english sorry :laughing: :laughing: :laughing:

**Comment by waspkiller** [comment]
@leonardosnt dont forget your :coffee: and :beer: and keep :snowflake: :pill:

**Comment by leonardosnt** [comment]
:laughing: okok

**Comment by waspkiller** [comment]
Closed due to bug being fixed

**Comment by leonardosnt** [comment]
It istn fixed

**Comment by waspkiller** [comment]
@leonardosntleonardosnt added a commit that closed this issue 33 minutes ago
 @leonardosnt	Fix #48

**Comment by leonardosnt** [comment]
'it's not fixed "totally"

**Comment by waspkiller** [comment]
AH should have said that!

**Comment by leonardosnt** [comment]
leonardosnt reopened this 34 minutes ago

Stackoverflow fixed!

..


okopkok

**Comment by waspkiller** [comment]
Sorry on my 2nd cup of coffee!

**Comment by Mikuzzzz** [comment]
Did you try drugs yet

**Comment by leonardosnt** [comment]
This was "probably" fixed in https://github.com/uEssentials/uEssentials/commit/c310f789df849b68bbaa76624b3bd33f2b8c3073#diff-856dd449d8e59dcdb0fa230612ea5af5R165
