### ISSUE TITLE
Kit XP goes strange

### ISSUE THREAD

**Issue by NoAdO** [uEssentials/uEssentials#480]
Well, typing again about strange things :D 
`  {
    "Name": "xp",
    "Items": [
      {
        "Xp": 1
      }
    ],
    "Cooldown": 1200,
    "Cost": 50.0,
    "ResetCooldownWhenDie": false
  },`

That's the code. When i discovered a problem it was         "Xp": 200 but if i try to obtain a kit i have a strange numbers, which are twice than last ones. Player reported that he obtained about 400 yesterday and about 2600 today - instead of 200.

I tried it now about 10 times and now system reports i get 2362344 exp. 

I made a test - killed myself - started with 0 exp. typing kit-start brought me 1, than 2, than 4 exp. Total 7. I killed a zombie and that was total 10 exp. kit -> +11, +22. That's not normal so i started again:

0, +3 zombie, +4 from kit

That means that kit gives you [yourexp]+[number_in_options] - 1 in my expample.

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/releases/tag/experimental-8ab1590

**Comment by NoAdO** [comment]
Do not work, or restart needed

**Comment by leonardosnt** [comment]
of course you need to restart the server.

**Comment by NoAdO** [comment]
Thanks a lot, it works! Will experimental addon self-update to release version or i need to change it to new release manually?

**Comment by leonardosnt** [comment]
Yes, it will do the same of a normal release.
