### ISSUE TITLE
exp kit bug

### ISSUE THREAD

**Issue by pepixiko** [uEssentials/uEssentials#483]
http://pastebin.com/VYkd2PBn

I have a problem that each kit of 100 experience and when you put the kit in the game gives 5200 or 1231 or 4353 (are examples)
http://subefotos.com/ver/?21430b75be45faffde1b7414f960c4aeo.png
look... 15.5988.416 of exp... bug??

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/releases/tag/experimental-8ab1590
