### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [uEssentials/uEssentials#484]
Here is error pic - http://imgur.com/a/C40B8

**Comment by Aceheliflyer** [comment]
It has to do with one of your plugins. I haven't quit figured out what caused mine to have the same error yet.

**Comment by Aceheliflyer** [comment]
It has to do with one of your plugins. I haven't quit figured out what caused mine to have the same error yet.

**Comment by ZSHADOWWOLF** [comment]
Yep Thanks for Help)

**Comment by leonardosnt** [comment]
Can you list your plugins ?

**Comment by ZSHADOWWOLF** [comment]
Yep http://imgur.com/a/R1Jot

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/releases/tag/experimental-d897799
