### ISSUE TITLE
Reputation command

### ISSUE THREAD

**Issue by BlueOrange775** [uEssentials/uEssentials#485]
One of the things this plugin is missing is a reputation command

**Comment by OldCash4u** [comment]
:+1:

**Comment by leonardosnt** [comment]
How this works?

**Comment by WGSRangerWolf** [comment]
/reputation 1000 
You have given yourself 1000 rep http://images.akamai.steamusercontent.com/ugc/146759246756236234/7A9904CF9123609C870655F5111E45D51203757C/

**Comment by WGSRangerWolf** [comment]
Its a command currently being able to be used while the server has cheat enabled.

**Comment by OldCash4u** [comment]
PT-BR

Tinha que ter esse comando via plugin , porque não tem como utilizar ele sem ficar com o "cheats enable" :(

**Comment by aviadmini** [comment]
I added it in #609
