### ISSUE TITLE
Permissions bug

### ISSUE THREAD

**Issue by rube200** [uEssentials/uEssentials#486]
I'm trying to make a permission but the essentials itself bug it.
In my permissions file I put there for normal players "essentials.command.hm" and for vip players I put "essentials.command.home".

The command "hm" was created from "home" but the command "hm" is paid.

Only when I play and I'm like a normal player can do "/ home" but should only be able to "/ hm".

Could see problem pls

**Comment by leonardosnt** [comment]
is `/hm` an alias of `/home` ?

**Comment by rube200** [comment]
Sim é, mas foi a única forma que encontrei, queria que para o mesmo comando um player normal paga-se e um player VIP não.
{
  "home": {
    "Cost": 0.0,
    "CustomAliases": [ "hm" ],
    "Cooldown": 300
  },
  "hm": {
    "Cost": 1000.0,
    "Cooldown": 300
  },
  "vote": {
    "Cost": 0.0,
    "CustomAliases": [ "vt" ]
  }
}

E no meu server eu tenho ja uma fuçao com /vote então desativei em essentials mas criei o /vt para ver se o substituía mas nao funciona.

**Comment by leonardosnt** [comment]
Não é possível fazer isso, não assim.

Eu pretendo adicionar isso

```java
    "PerGroupCost": { 
        "vip": 100,
        "admins": 0
    },
```

no arquivo de configuração dos comandos, que no caso seria um custo separado pra cada grupo.

https://github.com/uEssentials/uEssentials/issues/151

**Comment by rube200** [comment]
ok, obrigado vou ficar esperando por isso.
Só queira dizer que tenho uma sugestao para uma plugin bastante util, se voce quiser depois eu explico.
