### ISSUE TITLE
/ess help command

### ISSUE THREAD

**Issue by WGSRangerWolf** [uEssentials/uEssentials#49]
Add help command.
/help
Lists all the commands.

**Comment by leonardosnt** [comment]
/? commands

**Comment by leonardosnt** [comment]
/? help warp

**Comment by Mikuzzzz** [comment]
Or how about you use messageannouncer's Text command's Creater and make a help command
and set it up to display commands and things you want.

**Comment by waspkiller** [comment]
What miku said. Use message announcer coding can also be added to #1
