### ISSUE TITLE
[BUG REPORT OR DOUBT] /REPLY

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#492]
PT-BR

@leonardosnt hoje a noite eu fui responder um tell por /r e reparei uma coisa , mas não tenho certeza se é um bug ou não foi programado... Quando a gente da /r ou /replay para responder alguem a gente não pode colocar espaço na menssagem , sinão ele não envia :/ 

Exemplo : /r abc123 (menssagem envia) , /r abc 123 (menssagem NÃO envia)

Mas quando a gente envia um /tell a gente pode colocar de boa espaço que ele envia normal , mas no /r ele não envia a menssagem caso a gente coloque espaço. 

Exemplo : /tell player abc123 (menssagem envia) , /tell player abc 123 (menssagem envia) 

Você poderia corrigir este bug por favor ou implementar para que fique igual a quando utilizamos o comando /tell ???

**Comment by leonardosnt** [comment]
https://ci.appveyor.com/project/leonardosnt/uessentials/build/master/21/artifacts
