### ISSUE TITLE
item command fucks up ids.

### ISSUE THREAD

**Issue by WGSRangerWolf** [uEssentials/uEssentials#493]
The latest unturned update messes up the item ids.
This should be fixed to match rocketmod.

**Comment by WGSRangerWolf** [comment]
http://images.akamai.steamusercontent.com/ugc/146759339003172674/3DF0BB8448CDADC672B544A5E29141F0E3F28A18/

**Comment by leonardosnt** [comment]
99edd20553030a2c63cbaf241bd831e1f5244a9e

**Comment by WGSRangerWolf** [comment]
When can i expect this to be released

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/releases/tag/1.3.1.1
