### ISSUE TITLE
AutoAnnouncer broken

### ISSUE THREAD

**Issue by xstonemetal** [uEssentials/uEssentials#494]
i update to lasted uessentials and autoAnnouncer dont work, is a bug?

**Comment by leonardosnt** [comment]
Just go in config.json and change 

```json
"AutoAnnoucer": {
  "MessageInterval"
}
```

to

```json
"AutoAnnoucer": {
  "Interval"
}
```

**Comment by xstonemetal** [comment]
thx men but now i have another problem
kits whit uconomy system dont work
i dont know why...



2016-11-15 12:16 GMT-03:00 Leonardo Santos <notifications@github.com>:

**Comment by leonardosnt** [comment]
Download latest build: https://ci.appveyor.com/project/leonardosnt/uessentials/build/artifacts

**Comment by xstonemetal** [comment]
i download lasted buy look:
kit spec cost 1000 and i have this problem:
[World] [Supremo]StoneMetal [StoneMetal]: "/kit spec"
[uEssentials] [ERROR] System.Reflection.TargetException: Object does not
match target type.
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags
invokeAttr, System.Reflection.Binder binder, System.Object[] parameters,
System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0
  at System.Reflection.MethodBase.Invoke (System.Object obj,
System.Object[] parameters) [0x00000] in <filename unknown>:0
  at Essentials.Compatibility.Hooks.UconomyHook.GetBalance
(Essentials.Api.Unturned.UPlayer player) [0x00000] in <filename unknown>:0
  at Essentials.Compatibility.Hooks.UconomyHook.Has
(Essentials.Api.Unturned.UPlayer player, Decimal amount) [0x00000] in
<filename unknown>:0
  at Essentials.NativeModules.Kit.Commands.CommandKit.OnExecute
(ICommandSource src, ICommandArgs args) [0x00000] in <filename unknown>:0
  at Essentials.Core.Command.CommandAdapter.Execute (IRocketPlayer caller,
System.String[] args) [0x00000] in <filename unknown>:0

2016-11-15 21:13 GMT-03:00 Leonardo Santos <notifications@github.com>:
