### ISSUE TITLE
people on my server had access to admin commands!!

### ISSUE THREAD

**Issue by RJGamer1002** [uEssentials/uEssentials#497]

**Comment by leonardosnt** [comment]
Show me your permissions

**Comment by RJGamer1002** [comment]
<DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Prefix />
      <Suffix />
      <Color>white</Color>
      <Members />
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.abort</Permission>
        <Permission Cooldown="0">home</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit.*</Permission>
        <Permission Cooldown="0">rules</Permission>
        <Permission Cooldown="0">report</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>vip</Id>
      <DisplayName>VIP</DisplayName>
      <Prefix />
      <Suffix />
      <Color>FF9900</Color>
      <Members>
        <Member>76561198016438091</Member>
      </Members>
      <ParentGroup>default</ParentGroup>
      <Permissions>
        <Permission Cooldown="0">effect</Permission>
        <Permission Cooldown="120">heal</Permission>
        <Permission Cooldown="30">v</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>

**Comment by leonardosnt** [comment]
Remove the "essentials.command.kit.*"

You cant use permissions with ```*```

**Comment by RJGamer1002** [comment]
ok

**Comment by leonardosnt** [comment]
And also, the right permission for kits is "essentials.kit.(kit name)" not  "essentials.command.kit.(kit name)"

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki

**Comment by RJGamer1002** [comment]
ok
