### ISSUE TITLE
Share time kit

### ISSUE THREAD

**Issue by pepixiko** [uEssentials/uEssentials#498]
Hello leonard, one question, I can share time of the kits? example:
  {
    "Name": "kit 1",
    "Items": [
      {
        "Id": 269,
        "Durability": 100,
        "Amount": 1
      }
    ],
    "Cooldown": 300,
    "ResetCooldownWhenDie": false
  },
  {
    "Name": "kit 2",
    "Items": [
      {
        "Id": 394,
        "Durability": 100,
        "Amount": 3
      }
    ],
    "Cooldown": 300,
    "ResetCooldownWhenDie": false
  },

When use one kit 1, share cooldown kit 2
example: I use kit 1, and cooldown is 300 sec no?, Since kit 2 has cooldown also

That if you use one you can not use another

**Comment by leonardosnt** [comment]
You can use the '```GlobalCooldown```'

_config.json_
```java
"Kit": {
    "ShowCost": true,
    "ShowCostIfZero": false,
    "CostFormat": "{0}({1}{2})",
    "GlobalCooldown": 0,   <==============
    "ResetGlobalCooldownWhenDie": false
  },
```

**Comment by pepixiko** [comment]
There is no other way?

**Comment by leonardosnt** [comment]
?

**Comment by leonardosnt** [comment]
> You can use the 'GlobalCooldown'

> config.json

>"Kit": {
>    "ShowCost": true,
>    "ShowCostIfZero": false,
>    "CostFormat": "{0}({1}{2})",
>    "GlobalCooldown": 0,   <==============
>    "ResetGlobalCooldownWhenDie": false
>  },

**Comment by pepixiko** [comment]
There is no other way to share cooldown?

**Comment by leonardosnt** [comment]
No

**Comment by pepixiko** [comment]
ok, thank you leonard! :) other question no Are there economy commands?

**Comment by leonardosnt** [comment]
No yet
