### ISSUE TITLE
Self-open url

### ISSUE THREAD

**Issue by NoAdO** [uEssentials/uEssentials#499]
Can it be done in some way, maybe based on text-commands or smth. else to make it possible for players?

Ex: i associate /wiki with /wikipedia.org, player write /wiki in chat and get wikipedia/org in ingame browser. Is it possible?

**Comment by leonardosnt** [comment]
Try this.

text_commands.json
```java
  {
    "Name": "wiki",
    "Text": [
      "console_execute: requesturl %sender% wikipedia http://wikipedia.org/"
    ]
  }
```

**Comment by NoAdO** [comment]
Works! That's great!
