### ISSUE TITLE
Autogive kits after death

### ISSUE THREAD

**Issue by NoAdO** [uEssentials/uEssentials#501]
Can't figure how some servers do this. Neither in uessentials nor in kits plugin - no information. Maybe You can help me with that? All i want is to make people spawn after death already equipped with some kit or cloth or smth. Is there a way to do that?

P.S. Some more explanations about how command_options.json work would be great!)

**Comment by leonardosnt** [comment]
There's no way to do that with uEssentials.

**Comment by WGSRangerWolf** [comment]
Closed as this is has been answered

**Comment by NoAdO** [comment]
That was loadout command, stupid me :dancing_men:
