### ISSUE TITLE
how do you create kits with this

### ISSUE THREAD

**Issue by x1DRAGONZ** [uEssentials/uEssentials#502]
so i used to use the kits plug in but now that i have uessentials i can use it and i dont know how to make new kits in this please help

**Comment by leonardosnt** [comment]
1. You can use the [CreateKit](https://github.com/uEssentials/uEssentials/wiki/Command-Reference#createkit) command, that creates a kit with your inventory contents.
2. Edit directly in **kits.json**, https://github.com/uEssentials/uEssentials/wiki/Kits-Reference

**Comment by WGSRangerWolf** [comment]
Closed as answered
