### ISSUE TITLE
Players Getting insane xp

### ISSUE THREAD

**Issue by SkyeAZGA** [uEssentials/uEssentials#505]
Hey guys im currently having an issue on my unturned server where players are getting double there xp. 
so whats happening is when players use a kit (Using Kits plugin not uessentials kits) and the kit is meant to give them 45 xp but it doubles there xp. i have messed around with the Experience Multiplier in config.json i put it to 0.0 and players get no xp from kits and put it to 1.0 and they get heaps how do i fix cheers!

**Comment by leonardosnt** [comment]
This place is only for uEssentials issues, as you said, this is not related with uEssentials, so I can't help you.

**Comment by SkyeAZGA** [comment]
Oh sorry my fsult
