### ISSUE TITLE
Leonard

### ISSUE THREAD

**Issue by pepixiko** [uEssentials/uEssentials#506]
text_commands.json
  {
    "Name": "Votar",
    "Text": [
      "console_execute: requesturl %sender% Votar https://unturned-servers.net/server/87868/"
    ]
  }, 

and permisson.json
 <Permission Cooldown="0">Votar</Permission>

Players sometimes run /vote and sometimes do not
https://fotos.subefotos.com/980f082704b519c48b1eff8ce5ef239co.png

**Comment by leonardosnt** [comment]
You must use quotes.

Try this
```java
{
"Name": "Votar",
"Text": [
"console_execute: requesturl \"%sender%\" Votar https://unturned-servers.net/server/87868/"
]
},
```
