### ISSUE TITLE
update version kits error

### ISSUE THREAD

**Issue by pepixiko** [uEssentials/uEssentials#507]
https://fotos.subefotos.com/b7e2a37b79d9956caeac974eba2c99c3o.png update broke.. kits

**Comment by pepixiko** [comment]
https://fotos.subefotos.com/c09ff94f87eb2add1a63f38a0220f491o.png other error

**Comment by leonardosnt** [comment]
Just update your server. It worked for me.

![](http://i.imgur.com/eTU2LQc.png)

**Comment by pepixiko** [comment]
https://fotos.subefotos.com/785c78c8709437917282397c1f89ee4bo.png

**Comment by leonardosnt** [comment]
![](http://i.imgur.com/GL2uMsV.png)

**Comment by leonardosnt** [comment]
Seems to be an error related with assembly references, I'll recompile.

**Comment by pepixiko** [comment]
https://fotos.subefotos.com/08eaa34952856b4542e0b79b238dfdf4o.png I have ultimate update, you too? 
I do not understand: S, I'm going crazy! jeje

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/releases/tag/1.3.1.5

**Comment by pepixiko** [comment]
Fixed but now I download the latest update in folder, add it and go back out: S

**Comment by leonardosnt** [comment]
Wait

**Comment by pepixiko** [comment]
ok :)

**Comment by leonardosnt** [comment]
Download 1.3.1.6 again

https://github.com/uEssentials/uEssentials/releases/tag/1.3.1.6

**Comment by pepixiko** [comment]
yeah! 0 problems! thank you
