### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#51]
Not sure what this means or why this is happening, please help.

[2/13/2016 9:40:07 PM] [Error] NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.UseableGun.tick ()
SDG.Unturned.PlayerEquipment.Update ()

Server spammed about 10 of those errors per second, then after about 30 minutes it crashed.

error.log:
http://pastebin.com/uWvgjhUY

output_log.txt:
========== OUTPUTING STACK TRACE ==================

0x00007FF70591AC6C (Unturned) Matrix4x4f::Invert_Full
0x0000000016314535 (Mono JIT Code) (wrapper managed-to-native) UnityEngine.Component:get_transform ()
0x000000001636D063 (Mono JIT Code) SDG.Unturned.Zombie:FixedUpdate ()
0x0000000004ED8BBB (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
0x00007FFA456F40CB (mono) mono_set_defaults
0x00007FFA456483DD (mono) mono_runtime_invoke
0x00007FF70582F9C3 (Unturned) ScriptingArguments::AddString
0x00007FF70582F707 (Unturned) ScriptingArguments::AddString
0x00007FF705751FE0 (Unturned) IIMGUI::IIMGUI
0x00007FF70575476D (Unturned) GetMonoBehaviourInConstructor
0x00007FF70572EB5F (Unturned) BaseBehaviourManager::~BaseBehaviourManager
0x00007FF7057E7B32 (Unturned) RectT<int>::Contains
0x00007FF7058B4F40 (Unturned) PlayerMainWndProc
0x00007FF7058B78C1 (Unturned) PlayerWinMain
0x00007FF705CD1B7C (Unturned) RectT<int>::GetBottom
0x00007FFA600B2D92 (KERNEL32) BaseThreadInitThunk
0x00007FFA62309F64 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

**** Crash! ****

Any ideas?

**Comment by leonardosnt** [comment]
This appear to be a Unturned or Rocket error.

Try updating your files.

**Comment by Daniil1288** [comment]
Thank you for quick response, will do. Closing for now, will reopen if problem persists.
