### ISSUE TITLE
Question: How do I make my own text commands?

### ISSUE THREAD

**Issue by YuBh8Tn** [uEssentials/uEssentials#510]
I see the text-commands file, and I added my own commands, but when I type them in the server it says "Command not found." Here is my code for it.

[
  {
    "Name": "rules",
    "Text": [
      "<green> Do /robrules to see the rules about robbing.",
      "<green> Do /raidrules to see the rules about raiding.",
      "<green> Do /killrules to see the rules about killing.",
	  "<green> Do /baserules to see the rules about bases.",
	  "<green> Do /rules2 to see the general rules.",
	  "<cyan> Hit enter and scroll up to see all rules.",
    ]
  },
    {
    "Name": "rules2",
    "Text": [
      "<green> Obviously, do not cheat or hack.",
      "<green> Be respectful to all kinds of players.",
	  "<green> Take arguements to private chats. No flame wars.",
      "<green> Do /rules3 to see the final set of rules.",

    ]
      {
    "Name": "rules3",
    "Text": [
      "<green> Staff cannot bend the rules to their will. If you do not break these rules, then you break no rules.",
      "<green> Do not be afraid to report any staff. High-ranking staff will be reported to the owner.",
      "<red> DISCLAIMER: THIS SERVER BELIEVES RULES ARE IN PLACE TO KEEP DISORDER AT BAY.",
      "<red> DISCLAIMER: IF DISORDER OCCURS, THE PERPETRATOR WILL BE DISCIPLINED, AND RULES WILL BE ADJUSTED.",
    ]
  },
  {
    "Name": "robrules",
    "Text": [
      "<green> You may use voice chat to rob someone, but you must establish the robbery at least once in area or global chat."
      "<green> You cannot kill the victim unless they disobey you or try to fight back."
      "<green> After robbing the victim, you may NOT kill him/her for 5 minutes. Same applies to victim to robber."
    ]
  },
    {
    "Name": "raidrules",
    "Text": [
      "<green> Before you begin raiding, you must ensure the owner of the base is on the server. If not, you will have to wait until s/he is."
      "<green> Before you begin raiding, you say that you are beginning a raid IN WORLD CHAT."
      "<green> The owner of the base is allowed to defend, and any defences they have in place are legal."
    ]
  },
    {
    "Name": "killrules",
    "Text": [
      "<green> No RDMing or KoSing; kill only if fired at first.",
      "<green> The safezone is a no-kill zone. It is safe. You cannot be robbed, killed, or attacked in safezone.",
      "<green> If you are harmed in safezone, or if your items are taken from safezone, report it to the staff immediately.",
    ]
  },
        {
    "Name": "baserules",
    "Text": [
      "<green> Skybases are not allowed and will be removed on sight.",
      "<green> Bases over the size of 15x15 will be removed.",
      "<green> You may be allowed to build a larger base if you get permission from an administrator.",
      "<green> You are not allowed to build bases that take over the military base or Zavod, but you may build bases inside them.",
    ]
  },
]

**Comment by leonardosnt** [comment]
There are a lot of errors...

Try this:
```json
[
  {
    "Name":"rules",
    "Text":[
      " Do /robrules to see the rules about robbing.",
      " Do /raidrules to see the rules about raiding.",
      " Do /killrules to see the rules about killing.",
      " Do /baserules to see the rules about bases.",
      " Do /rules2 to see the general rules.",
      " Hit enter and scroll up to see all rules."
    ]
  },
  {
    "Name":"rules2",
    "Text":[
      " Obviously, do not cheat or hack.",
      " Be respectful to all kinds of players.",
      " Take arguements to private chats. No flame wars.",
      " Do /rules3 to see the final set of rules."
    ]
  },
  {
    "Name":"rules3",
    "Text":[
      "<green> Staff cannot bend the rules to their will. If you do not break these rules, then you break no rules.",
      "<green> Do not be afraid to report any staff. High-ranking staff will be reported to the owner.",
      "<red> DISCLAIMER: THIS SERVER BELIEVES RULES ARE IN PLACE TO KEEP DISORDER AT BAY.",
      "<red> DISCLAIMER: IF DISORDER OCCURS, THE PERPETRATOR WILL BE DISCIPLINED, AND RULES WILL BE ADJUSTED."
    ]
  },
  {
    "Name":"robrules",
    "Text":[
      " You may use voice chat to rob someone, but you must establish the robbery at least once in area or global chat.",
      " You cannot kill the victim unless they disobey you or try to fight back.",
      " After robbing the victim, you may NOT kill him/her for 5 minutes. Same applies to victim to robber."
    ]
  },
  {
    "Name":"raidrules",
    "Text":[
      " Before you begin raiding, you must ensure the owner of the base is on the server. If not, you will have to wait until s/he is.",
      " Before you begin raiding, you say that you are beginning a raid IN WORLD CHAT.",
      " The owner of the base is allowed to defend, and any defences they have in place are legal."
    ]
  },
  {
    "Name":"killrules",
    "Text":[
      " No RDMing or KoSing; kill only if fired at first.",
      " The safezone is a no-kill zone. It is safe. You cannot be robbed, killed, or attacked in safezone.",
      " If you are harmed in safezone, or if your items are taken from safezone, report it to the staff immediately."
    ]
  },
  {
    "Name":"baserules",
    "Text":[
      " Skybases are not allowed and will be removed on sight.",
      " Bases over the size of 15x15 will be removed.",
      " You may be allowed to build a larger base if you get permission from an administrator.",
      " You are not allowed to build bases that take over the military base or Zavod, but you may build bases inside them."
    ]
  }
]
```
