### ISSUE TITLE
Player Created Kits.

### ISSUE THREAD

**Issue by rwalkos** [uEssentials/uEssentials#512]
This is a feature request.

It would be awesome if each player could make their own kits. Ideally, kits would be stored in a database and kits made would only work for the person that made them.
I'm thinking playerinfolib plugin could be utilized somehow to make this work.
If this is definitely not going to happen I understand.

Other then that, is there a way to allow everyone on the server make kits and allow use to all kits, without having to use specific permissions for each kit name?

I tried ```essentials.kit.*``` but as expected, that gave everyone on the server access to all of uEssentials commands.

**Comment by WGSRangerWolf** [comment]
At the moment. The wildcard * is busted by rocket mod and we can't fix it.. You have to manually add the permissions, https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference

**Comment by Ecxdirerr** [comment]
Closing as no response and has been answered

**Comment by AcrylaGaming** [comment]
Has this been fixed yet?
