### ISSUE TITLE
uEssentials overriding Loss of XP on PvP Death?

### ISSUE THREAD

**Issue by paulsoaresjr** [uEssentials/uEssentials#513]
Hey there! Just installed uEssentials on a server configured for players to not lose any XP on PvP death ("Lose_Skills_PvP": 1.0,) and now we're losing 100% of XP and skills! Any ideas?

Thanks

**Comment by 450ufm** [comment]
Having the exact same problem.

Rocket v4.9.3.0 Unturned v3.17.8.0 uEssentials build #60

**Comment by leonardosnt** [comment]
8a9934f2467b911f13ea9415af415a34b0e03318
