### ISSUE TITLE
How to use the "AutoCommand" it seems to be not working for me

### ISSUE THREAD

**Issue by kuropristo** [uEssentials/uEssentials#515]
Here is my config:

**{
  "Locale": "en",
  "PrivateMessage": {
    "FormatFrom": "(From {0}): {1}",
    "FormatTo": "(To {0}): {1}",
    "FormatSpy": "<gray>Spy: {0} -> {1}: {2}",
    "ConsoleDisplayName": "*console*"
  },
  "UnfreezeOnDeath": true,
  "UnfreezeOnQuit": true,
  "EnableTextCommands": true,
  "EnableDeathMessages": true,
  "EnableJoinLeaveMessage": true,
  "ShowPermissionOnErrorMessage": true,
  "SaveCommandCooldowns": false,
  "EnablePollRunningMessage": true,
  "PollRunningMessageCooldown": 20,
  "ServerFrameRate": -1,
  "BackDelay": 10,
  "ItemSpawnLimit": 10,
  "AntiSpam": {
    "Enabled": true,
    "Interval": 3
  },
  "Updater": {
    "CheckUpdates": true,
    "DownloadLatest": true,
    "AlertOnJoin": true
  },
  "Home": {
    "TeleportDelay": 5,
    "CancelTeleportWhenMove": true
  },
  "Warp": {
    "TeleportDelay": 5,
    "CancelTeleportWhenMove": false,
    "PerWarpPermission": true
  },
  "VehicleFeatures": {
    "RefuelPercentage": 20,
    "RepairPercentage": 70
  },
  "Kit": {
    "ShowCost": true,
    "ShowCostIfZero": false,
    "CostFormat": "{0}({1}{2})",
    "GlobalCooldown": 0,
    "ResetGlobalCooldownWhenDie": false
  },
  "Tpa": {
    "CancelTeleportWhenMove": true,
    "ExpireDelay": 10,
    "TeleportDelay": 5
  },
  "Economy": {
    "UseXp": false,
    "XpCurrency": "Xp",
    "UconomyCurrency": "$"
  },
  "AutoAnnouncer": {
    "Interval": 360,
    "RandomMessages": true,
    "Enabled": true,
    "Messages": [
      "<red>Kill or be Killed",
      "<green>Stop asking admin",
      "<yellow>Potato",
      "<magenta>Noone is safe"
    ]
  },
  "AutoCommands": {
    "Commands": [
      {
        "RunOnce": true,
        "Timer": 120,
        "Commands": [
          "say \"Be sure to drink your Ovaltine!\" 0 255 255",
          "item * glue"
        ]
      },
	   {
        "RunOnce": false,
        "Timer": 120,
        "Commands": [
          "say \"respawnItems!\" 0 255 255",
          "clear i",
          "respawnitems"
        ]
      }
	  ,
      {
        "RunOnce": false,
        "Timer": 120,
        "Commands": [
          "clear ev",
          "respawnvehicles"
        ]
      }
    ],
    "Enabled": true
  },
  "GiveItemBlacklist": [],
  "VehicleBlacklist": ["Forest Tank","Desert Tank","Russia Tank"],
  "EnabledSystems": [
    "kits",
    "warps"
  ],
  "DisabledCommands": []
}**

**Comment by leonardosnt** [comment]
VehicleBlackList only accepts ID's, you can't use names.
