### ISSUE TITLE
[BUG REPORT] /REFUELGENERATOR

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#518]
PT-BR

A Nova função adicionada recentemente na Wiki Command Reference do uEssentials , o /refuelgenerator , não está funcionando... 

Diz que o comando não existe.

**Comment by leonardosnt** [comment]
Este comando ainda não foi lançado oficialmente.

Caso queira utilizar, basta fazer o download do build experimental: https://github.com/uEssentials/Builds/releases/tag/build-1ec6858
