### ISSUE TITLE
/refuelgenerator > Experimental Build

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#519]
PT-BR

@leonardosnt por favor , deixe o refuelgenerator assim : 

/refuelgenerator <.percentage> <range OR * = all generators>

e que o "*" possa ser executado pelo console por favor , pretendo adicionar ele no AutoCommands

assim que postar uma nova build , que o refuelgenerator esteja editado assim , por favor me avise !!!
quero muito testar :D

E também está faltando a tradução da KEY "REFUEL GENERATOR REFUELED" , mas acredito que ainda não colocou , porque ainda não terminou...

Você é muito bom no que faz Leo , um Deus

**Comment by leonardosnt** [comment]
Eu não adicionei ainda pois pode ser que isso trave o servidor, igual aconteceu com o respawnvehicles.

O networking do Unturned é um pouco limitado, eu teria que escrever um algorítimo pra enviar os pacotes por partes... vou ver o que posso fazer.

**Comment by OldCash4u** [comment]
@leonardosnt em meus testes do refuelgenerator ele não travou , somente quando usei mais que 9 digitos de rage aumentou a latência e voltou , o meu mapa testado até que havia bastante geradores , acredito que havia cerca de uns 20 ~ 40

**Comment by leonardosnt** [comment]
Quantos jogadores online havia no seu servidor ?

Se tiver apenas 1 jogador ele não trava...

**Comment by OldCash4u** [comment]
@leonardosnt fiz um teste no meu servidor , havia cerca de 20 ~ 24 players , ele vive lotado o dia inteiro

**Comment by OldCash4u** [comment]
@leonardosnt por favor implemente isto rápido , seria de grande utilidade em meu servidor :(

**Comment by leonardosnt** [comment]
Basta adicionar um número grande ao **range**
