### ISSUE TITLE
Stacktrace issue

### ISSUE THREAD

**Issue by waspkiller** [uEssentials/uEssentials#52]
its for people who use duty command in particular. Plugin conlfict
https://dev.rocketmod.net/?rplugin=duty
stackflow issue.

**Comment by leonardosnt** [comment]
print...?

**Comment by Mikuzzzz** [comment]
I have no issue with my duty plugin.
PS. What is ETA on Release with fixed /rocket reload?

**Comment by waspkiller** [comment]
@leonardosnt I will not install the plugin again. I think it conflicts between owner command and other stuff. this plugin has crashed my server 2 times. im not going through that again

**Comment by waspkiller** [comment]
@leonardosnt Add me on steam for the life of me i cannot FIND YA! [RangerWolf](http://steamcommunity.com/id/eyeoftigger/)

**Comment by Mikuzzzz** [comment]
What about me... :P http://steamcommunity.com/profiles/76561198138254281/

**Comment by waspkiller** [comment]
http://pastebin.com/GmwZ0tjh

**Comment by waspkiller** [comment]
crashed again

**Comment by waspkiller** [comment]
#53
