### ISSUE TITLE
[SUGGESTION] NEW PARAMETER 

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#520]
PT-BR

@leonardosnt , seria possível adicionar os seguintes paramentos para estes comandos : 

/clearinventory <player OR * = all> + essentials.command.clearinventory.all

/maxskills <overpower[true|false]> <player OR * = all> + essentials.command.maxskills.all

obrigado pelo excelente trabalho que está realizando no uEssentials , agradeço desde já ! leo :+1:

**Comment by OldCash4u** [comment]
@leonardosnt  VOCÊ É FERA CARA , VALEU !

**Comment by leonardosnt** [comment]
:D

Caso já queira usar: https://github.com/uEssentials/Builds/releases/tag/build-70cb9f2
