### ISSUE TITLE
[SUGGESTION] NEW COMMAND TPHERE , BASED ON TOPIC #522

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#523]
PT-BR

@leonardosnt , a sugestão proposta é baseado no tópico #522 , porem com o inverso do TP , o TPHERE.

Por este ser mais "complexo" que o outro , descrevi a ideia bem detalhadamente , para que você possa me entender bem...

TP > TELEPORTA VOCÊ , ATÉ ... (SUGESTÃO DO OUTRO TÓPICO)

TPHERE > TRAZ ALGUÉM ou TODOS  , ATÉ...  (SUGESTÃO DESTE TÓPICO)

FICARIA ASSIM : /tphere [player OR * = ALL] [player|place|coordinate]

PERMISSÕES :

essentials.command.tphere - LIBERA O ACESSO AO USO DO TPHERE

essentials.command.tphere.all - LIBERA ACESSO DO TPHERE , PLAYERS A "P/P/C"
(FUNÇÃO : "*" ou seja /tphere * player|place|coordinate)

essentials.command.tphere.other - LIBERA ACESSO DO TPHERE , DE PLAYER A PLAYER
 (FUNÇÃO : /tphere player1 player2) ; o player1 vai até o player2

essentials.command.tphere.place - LIBERA ACESSO DO TPHERE , DE PLAYER A PLACE
(FUNÇÃO : /tphere player place

essentials.command.tphere.coordinate - LIBERA ACESSO DO TPHERE , DE PLAYER A COORDINATE
(FUNÇÃO : /tphere player coordinate

**Comment by leonardosnt** [comment]
Tudo isso, com exceção do `*`, pode ser feito com o `/tp`.

Exemplos
- /tp player1 player2
- /tp player place
- /tp player coordinate

https://github.com/uEssentials/uEssentials/wiki/Command-Reference#tp

**Comment by leonardosnt** [comment]
E para teleportar todos os jogadores para algum lugar/jogador, basta usar o [/tpall](https://github.com/uEssentials/uEssentials/wiki/Command-Reference#tpall)

**Comment by OldCash4u** [comment]
@leonardosnt  a ta , ok , mas tenta fazer o novo parâmetro sugerido para o TP

quero poder liberar ele para certos grupos...
