### ISSUE TITLE
[SUGGESTION] NEW PARAMETER 2

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#524]
PT-BR

@leonardosnt , seria possível adicionar os seguintes parâmetros para estes comandos :

1 - /suicide [player OR * = ALL] 

A Intenção é poder utilizar ele como o /kill , meio que um disfarce para o player pensar que foi um bug ou algo do tipo , porque no "kill" para que foi morto por um administrador na tela de morte do jogo...

essentials.command.suicide
essentials.command.suicide.other
essentials.command.suicide.all

2 - /ascend [amount] [player OR * = ALL]

Pretendo fazer um sistema de evento automático que estou bolando , com este.
Teria como liberar o seu uso por console ? pretendo adicionar ele no AutoCommands 

essentials.command.ascend
essentials.command.ascend.other
essentials.command.ascend.all

3 - /descend [amount] [player OR * = ALL]

Pretendo fazer um sistema de evento automático que estou bolando , com este.
Teria como liberar o seu uso por console ? pretendo adicionar ele no AutoCommands 

essentials.command.descend
essentials.command.descend.other
essentials.command.descend.all

Agradeço , desde já por tudo que você tem feito pelo uEssentials , Léo ! :+1: , ta de parabéns :D

**Comment by leonardosnt** [comment]
Agora que eu lembrei, todos estes comandos podem ser executados usando o [/sudo](https://github.com/uEssentials/uEssentials/wiki/Command-Reference#sudo)

Exemplo:
- /sudo * suicide
- /sudo * ascend 20
- /sudo * descend 20

**Comment by OldCash4u** [comment]
@leonardosnt mas a pessoa só vai conseguir utilizar o comando pelo sudo , caso ela tenha permissão
