### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by typicalcoder** [uEssentials/uEssentials#527]
Hi.
[12/18/2016 5:15:26 PM] [Error] ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection. - System.Buffer.BlockCopy (System.Array src, Int32 srcOffset, System.Array dst, Int32 dstOffset, Int32 count)
SDG.Unturned.Block.writeUInt64 (UInt64 value)
SDG.Unturned.Block.writeSteamID (CSteamID steamID)
SDG.Unturned.Block.write (System.Object objects)
SDG.Unturned.Block.write (System.Object[] objects)
SDG.Unturned.SteamPacker.write (System.Object[] objects)
SDG.Unturned.SteamChannel.write (System.Object[] objects)
SDG.Unturned.VehicleManager.sendVehicle (SDG.Unturned.InteractableVehicle vehicle)
SDG.Unturned.VehicleManager.askVehicles (CSteamID steamID)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.Provider.receiveServer (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel)
SDG.Unturned.Provider.listenServer (Int32 channel)
SDG.Unturned.Provider.listen ()
SDG.Unturned.Provider.Update ()

What is it?

**Comment by leonardosnt** [comment]
Idk, but it isn't from uEssentials.

**Comment by typicalcoder** [comment]
Where to write for this bug?

**Comment by typicalcoder** [comment]
Current plugins: Rocket->uEssentials;Uconomy;ZaupShop

**Comment by leonardosnt** [comment]
@typicalcoder I don't know.

**Comment by typicalcoder** [comment]
ok, thanks
