### ISSUE TITLE
Confusion 101# What the ???

### ISSUE THREAD

**Issue by Ecxdirerr** [uEssentials/uEssentials#531]
Ok so players on my servers are complaining about the following issue
Their skills get rest on death and reconnect to the server
Permissions file preview: https://puu.sh/sXfih/f786f33df7.png
And i would like to keep their exp aswell.

**Comment by leonardosnt** [comment]
Change
 `essentials.keepskill.100`  
to
 `essentials.keepskill.all.100` 
or just 
`essentials.keepskill.all`
