### ISSUE TITLE
Item/Vehicle restrictions

### ISSUE THREAD

**Issue by Bossinas** [uEssentials/uEssentials#532]
I am having trouble figuring out how to restrict item and vehicle use

**Comment by leonardosnt** [comment]
what kind of trouble?

**Comment by Bossinas** [comment]
I'm just not clear on where/ how to add them in. I see it in the config file but I can't figure out how to write it out

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/Configuration


```java
  "GiveItemBlacklist": [ put id's here ],
  "VehicleBlacklist": [ put id's here  ],
```

e.g

```java
  "GiveItemBlacklist": [ 10, 5, 2 ],
  "VehicleBlacklist": [  4, 3, 43  ],
```

**Comment by Bossinas** [comment]
Ok it worked. I was adding in a similar way to adding a permission :/. Last question is there a way to unblock a single item for particular groups? Thanks a ton tho

**Comment by Ecxdirerr** [comment]
Just remove the id. :smile:

**Comment by leonardosnt** [comment]
Unfortunately not.

**Comment by Ecxdirerr** [comment]
closed as question answered
