### ISSUE TITLE
/kits

### ISSUE THREAD

**Issue by AlexitoPambi** [uEssentials/uEssentials#533]
NullReferenceException: Object reference not set to an instance of an object - Rocket.Core.Permissions.RocketPermissionsManager.HasPermission (IRocketPlayer player, System.Collections.Generic.List`1 permissions)
Essentials.Core.Permission.EssentialsPermissionsProvider.HasPermission (IRocketPlayer player, System.Collections.Generic.List`1 requestedPermissions)
Rocket.API.IRocketPermissionsProviderExtensions.HasPermission (IRocketPermissionsProvider rocketPermissionProvider, IRocketPlayer player, IRocketCommand command)
Rocket.Unturned.Permissions.UnturnedPermissions.CheckPermissions (SDG.Unturned.SteamPlayer caller, System.String permission)
Rocket.Unturned.U.<bindDelegates>m__9 (SDG.Unturned.SteamPlayer player, System.String text, System.Boolean& shouldExecuteCommand, System.Boolean& shouldList)
SDG.Unturned.ChatManager.process (SDG.Unturned.SteamPlayer player, System.String text)
SDG.Unturned.ChatManager.askChat (CSteamID steamID, Byte mode, System.String text)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)
SDG.Unturned.SteamChannel.receive (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size)
SDG.Unturned.Provider.receiveServer (CSteamID steamID, System.Byte[] packet, Int32 offset, Int32 size, Int32 channel)
SDG.Unturned.Provider.listenServer (Int32 channel)
SDG.Unturned.Provider.listen ()
SDG.Unturned.Provider.Update ()

**Comment by leonardosnt** [comment]
Here is working
![](http://i.imgur.com/aqAormp.png)

Can you show me your `kits.json` and `config.json`?

**Comment by Ecxdirerr** [comment]
Closing as the creator of issue  has not replied back
