### ISSUE TITLE
Permissions for kits

### ISSUE THREAD

**Issue by MLGConservative** [uEssentials/uEssentials#537]
I can acess the kits and so can an admin, however nobody else can do /kits or /kit, any solutions?

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference

**Comment by MLGConservative** [comment]
Where do I put that command though, sorry I am new to this

**Comment by leonardosnt** [comment]
`Rocket/Pemissions.config.xml`
