### ISSUE TITLE
EXPERIENCE Issue

### ISSUE THREAD

**Issue by OldCash4u** [uEssentials/uEssentials#538]
PT-BR

@leonardosnt as pessoas de meu servidor estão conseguindo utilizar o /experience do uEssentials sem ter qualquer permissão a "essentials.command.experience". 

obs : estou utilizando a experimental build-6c71769 (ultima publicada)  , 
não sei se a release oficial também está.

**Comment by leonardosnt** [comment]
Mostre seu arquivo de permissões.

**Comment by OldCash4u** [comment]
@leonardosnt meu arquivo atual de permissões > https://mega.nz/#!p4siybbJ!MjGSSAqGwtyRSKG9MyERa7vO_n9cDxlyW8URxDxpO_c
