### ISSUE TITLE
Rocket cooldowns

### ISSUE THREAD

**Issue by Boowick** [uEssentials/uEssentials#540]
Hello I was wondering how I set cooldowns? because if i for example set one cooldown at 50 sec for a kit then it will set 50 sec for ALL kit(s) commands... (Btw this is the rocket permissions file im setting the cooldowns in)  I want to have separate cooldowns for each kit
Please help!

**Comment by Ecxdirerr** [comment]
Did you make it via the in-game command or did u hand edit it? 

Please refer to the https://github.com/uEssentials/uEssentials/wiki/Kits-Reference for separated Cooldowns
Closing as this isn't a real issue and user has been redirected to Wikia to read
You may reopen this if you run into any more issues

**Comment by Boowick** [comment]
Yea I do it in the file but i also tried the in-game command now, and even tough I type for example : /createkit starter 200 false 0
 It still doesnt make so that the cooldown is 200 sec, and im going crazy! ;(
