### ISSUE TITLE
Make it to where any player can use any kit

### ISSUE THREAD

**Issue by AcrylaGaming** [uEssentials/uEssentials#546]
I added /createkit to the permissions so every player can make there own loadout but they can't access the kits they make. Is it possible to make it to where anyone can use any kit?

**Comment by Ecxdirerr** [comment]
No, you need to grant the permission of the kit manually.

as essentials.kit.* gives all commands

**Comment by leonardosnt** [comment]
@Ecxdirerr Is '*' working normally?

**Comment by Ecxdirerr** [comment]
No.

**Comment by Ecxdirerr** [comment]
Remeber? We had this issue but did it get fixed?
where if wildcard is found it grants everyhting to everyone...

**Comment by unknownguy2002** [comment]
talking about *, does *.* do anything? how about essentials.* or Rocket.*?

**Comment by leonardosnt** [comment]
It works with `essentials.kit.*`

I tested using the following permissions:
```xml
        <Permission Cooldown="0">essentials.kit.*</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.createkit</Permission>
```
