### ISSUE TITLE
Warp Permission Problem Help Needed ASAP

### ISSUE THREAD

**Issue by mreasyy** [uEssentials/uEssentials#547]
<Permission Cooldown="3">essentials.command.warps</Permission>
        <Permission Cooldown="0">essentials.command.warp.rptown</Permission>

those are the permisions along with others in my default user group
these came straight from uessentials wiki so idk why they dont work? what am i doing wrong?

when someone tries to warp rptown they dont have access and /warps says message "no warps defined" works for admins tho.

Please Help this is the only problem i need to fix to run my server

**Comment by leonardosnt** [comment]
essentials.warp.rptown

https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference
