### ISSUE TITLE
Is there a way to make /donate ask the player to open a link?

### ISSUE THREAD

**Issue by mreasyy** [uEssentials/uEssentials#548]
wondering if a command can lead to link thanks.

**Comment by Ecxdirerr** [comment]
/Rocket/Plugins/uEssentials
edit text commands
```
   {
      "Name":"donate",
      "Text":[
         "console_execute: requesturl \"%sender%\ Link INSERTURL"
      ]
   }
```
save and close
add the permission
<Permission Cooldown"0">donate</Permission>
and then your all set. please let me know if u run into any issues

**Comment by mreasyy** [comment]
Where do i add the permision? rocket permisions? 

        <Permission Cooldown="2">essentials.command.donate</Permission>
        <Permission Cooldown="2">donate</Permission>

?? what do i put in the rocket perms or where do i put the permission

**Comment by leonardosnt** [comment]
``` <Permission Cooldown="2">essentials.textcommand.donate</Permission>```

https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference
https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference

**Comment by mreasyy** [comment]
i put that exact line of code in and still /donate does nothing ingame ?

**Comment by mreasyy** [comment]
{
      "Name":"donate",
      "Text":[
         "console_execute: requesturl \"%sender%\" Link http://www.google.com"
      ]
   }

Is this right?

**Comment by Ecxdirerr** [comment]
yes

**Comment by Ecxdirerr** [comment]
Did u do ess reload? or rocket reload?

**Comment by mreasyy** [comment]
i fixed it thank you for responding to me very good support here.

**Comment by Ecxdirerr** [comment]
Closing as issue is fixed
