### ISSUE TITLE
How To Add Suffix To Group?

### ISSUE THREAD

**Issue by mreasyy** [uEssentials/uEssentials#549]
<Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Prefix />
      <Suffix />              <----------------
      <Color>white</Color>
      <Members />
      <Permissions>

the suffix thing right there how do i put text into it properly so it shows in game like [Guest] Den Trey

I tried this  <Suffix Guest>  and it doesnt show ingame

please help

**Comment by leonardosnt** [comment]
```xml
<Suffix>SUFFIX HERE</Suffix>
```

**Comment by mreasyy** [comment]
Still doesnt show the suffix ingame ?

**Comment by leonardosnt** [comment]
This is not from uEssentials, so I can't help you.

**Comment by Ecxdirerr** [comment]
mreasyy you need to reconnect
