### ISSUE TITLE
essentials.keepskill.all.100

### ISSUE THREAD

**Issue by Ecxdirerr** [uEssentials/uEssentials#551]
I'm honestly getting tired of this breaking. I have set it to where it needs to be, but everyone keeps losing skills?
Also is there a option to make players stop loosing their exp?

Permissions.xml
https://puu.sh/tmO2B/b579899374.png

**Comment by Ecxdirerr** [comment]
Changed to verified Bug as it keeps some skills not all.

**Comment by leonardosnt** [comment]
Here is working fine.

**Comment by Ecxdirerr** [comment]
i c what i did.
