### ISSUE TITLE
Dúvida config

### ISSUE THREAD

**Issue by ChuckDoll** [uEssentials/uEssentials#552]
Bom dia Leonardo,
Eu não sou o cara mais qualificado do mundo em scripts por isso tenho tido uma dificuldade absurda em desabilitar alguns dos plugins contidos no essentials.
Me dá uma luz, por favor.
Eu quero ter alguns comandos como /tell e /tpa, o resto usarei os plugins que já possuo. Como fazer para desabilitar o resto? 
Obrigado desde já
Tem alguma forma de comunicação mais rápida? Valeu

**Comment by leonardosnt** [comment]
Basta ir no arquivo de configuração (config.json), e adicionar os comandos que você deseja desabilitar  em"DisabledCommands".

Exemplo:

```json
"DisabledCommands": [
  "kits",
  "kit"
]
```

**Comment by ChuckDoll** [comment]
Hmmm... Eu fiz isso, acredito que tenha funcionado! 
Cara, parabéns pelo plugin! Muito bom mesmo. 
Muito obrigado pela atenção e por disponibilizar o conhecimento.
Abraço!

**Comment by leonardosnt** [comment]
Vlw
