### ISSUE TITLE
Command's сooldowns do not work

### ISSUE THREAD

**Issue by WhoIsFatosententia** [uEssentials/uEssentials#553]
Hello, command's cooldowns do not work on my server, such as /kit and /home, although I have them wrote in the plugin settings, as in the file permissions. Could you please help me solve this problem?
Сommands themselves are working properly.

**Comment by leonardosnt** [comment]
Where exactly you are adding the cooldowns ?

**Comment by WhoIsFatosententia** [comment]
kits.json like that

> {
>     "Name": "plane",
>     "Items": [
>       {
>         "Vehicle": 92
>       }
>     ],
>     "Cooldown": 3600,
>     "Cost": 300.0,
>     "ResetCooldownWhenDie": false
>   },
>   {
>     "Name": "Exp",
>     "Items": [
>       {
>         "Xp": 300
>       }
>     ],
>     "Cooldown": 1200,
>     "Cost": 0.0,
>     "ResetCooldownWhenDie": false
>   }

and Permissions.config.xml

**Comment by sachk** [comment]
Are you admin? I was experiencing this too on my account even when i removed admin but my friends account which has never been admin has normal cooldowns.

**Comment by WhoIsFatosententia** [comment]
All the players didn't have cooldowns, and I noticed that all players could use all kits, although I wrote only some of them in Permissions.config.xml.
