### ISSUE TITLE
Kits Permissions

### ISSUE THREAD

**Issue by J3RWU** [uEssentials/uEssentials#554]
Hello. I made 2 kits for normal members of my server, but they don't have permission to use it. I have done the permission thing in "Permission" and they look like this :
<Permission Cooldown="172800">essentials.kit.claimflag</Permission>
<Permission Cooldown="86400">essentials.kit.survival</Permission>
What is wrong?

**Comment by Ecxdirerr** [comment]
please show me your permissions.xml config?
Btw the permissions should look like this:
'<Permission Cooldown="0">essentials.command.kit</Permission>'
'<Permission Cooldown="0">essentials.command.kits</Permission>'
'<Permission Cooldown="0">essentials.kit.survival</Permission>'
'<Permission Cooldown="0">essentials.kit.claimflag</Permission>'



*Have an amazing day,*

*Derrick McLean*

**Comment by J3RWU** [comment]
Here is the link for permissions.xml : http://pastebin.com/QtGkhx57

**Comment by Ecxdirerr** [comment]
<Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Prefix />
      <Suffix />
      <Color>white</Color>
      <Members />
      <Permissions>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="30">essentials.command.home</Permission>
        <Permission Cooldown="172800">essentials.kit.claimflag</Permission>
        <Permission Cooldown="86400">essentials.kit.survival</Permission>
        <Permission Cooldown="0">essentials.command.online</Permission>
        <Permission Cooldown="30">essentials.command.suicide</Permission>
        <Permission Cooldown="0">essentials.command.tell</Permission>
        <Permission Cooldown="5">essentials.command.tpa</Permission>
        <Permission Cooldown="5">essentials.command.tpa.send</Permission>
        <Permission Cooldown="5">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="5">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="5">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="5">essentials.command.vote</Permission>
        <Permission Cooldown="0">rules</Permission>
        <Permission Cooldown="0">vip</Permission>
        <Permission Cooldown="0">donate</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="0">essentials.kit.survival</Permission>
        <Permission Cooldown="0">essentials.kit.claimflag</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">ad</Permission>
        
      </Permissions>
    </Group>``
This should fix your issue.

**Comment by J3RWU** [comment]
Thank you!

**Comment by J3RWU** [comment]
Oh, and btw: what does <Prefix /> and <Suffix /> mean?

**Comment by Ecxdirerr** [comment]
Prefix adds whatver you place there
instance [Owner]Ecxdirerr
suffix
[Owner]Ecxdirerr[AHAHA]
