### ISSUE TITLE
Can't set the Vip/Admin/Owner nametag/Prefix for players

### ISSUE THREAD

**Issue by J3RWU** [uEssentials/uEssentials#559]
Basically the title: Can't set the Vip/Admin/Owner nametag/Prefix for players, and where do i set it?

**Comment by leonardosnt** [comment]
This is not from uEssentials, so I can't help you.
This is not from uEssentials, so I can't help you.
This is not from uEssentials, so I can't help you.
This is not from uEssentials, so I can't help you.
This is not from uEssentials, so I can't help you.
This is not from uEssentials, so I can't help you.
