### ISSUE TITLE
Grammar pls.

### ISSUE THREAD

**Issue by DubFriendsFriendlyFriend** [uEssentials/uEssentials#56]
When frozen:

"You has been frozen by PLAYERNAME"

**Comment by axiomaticTwist** [comment]
Well, it's not his fault he can't speak English well. You get the idea of what he's trying to say, don't you? And can't you change what it says in the translation.xml file?

**Comment by WGSRangerWolf** [comment]
Axiomatic its a .json file. the translation file is in GDIR/Servers/woof/Rocket/Plugins/uEssentials/translations/lang_en.json and english is a very complex language. he is not an american.

**Comment by shadyx** [comment]
https://github.com/uEssentials/uEssentials/blob/master/default/lang_en.json 

Better English: http://pastebin.com/4FpSMbJ1

**Comment by leonardosnt** [comment]
I DON'T speak english. so, i can't FIX my english T.T

If you can help to improve it, i will be very grateful.

@shadyx Can i use it as default?

**Comment by shadyx** [comment]
@leonardosnt Of course :)

**Comment by leonardosnt** [comment]
#62

**Comment by DubFriendsFriendlyFriend** [comment]
"I DON'T speak english."

Didn't know that o.o

**Comment by axiomaticTwist** [comment]
Can't tell if that's sarcasm or not... If it's not, really? It was kinda obvious...

**Comment by WGSRangerWolf** [comment]
same

**Comment by DubFriendsFriendlyFriend** [comment]
was not obvious ok?

**Comment by Daniil1288** [comment]
@DubFriendsFriendlyFriend damn this is an old issue :O

**Comment by DubFriendsFriendlyFriend** [comment]
yes yes it is i just forgot to reply to my haters so I'm doing it now
