### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by NoFakeGuy** [uEssentials/uEssentials#560]
**Hello**, I am trying to make a server, where default players have access to the commands "/ i" - "/ Item" "/ v" - "Vehicle" / "Skill" "Tpa" and "Home", but when I try add the permissions, "Essentials" crashes and I have to return all plugin settings to the default settings. Any solution?

_Best regards_

(I apologize for my misuse of English, I am Chilean).

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference

**Comment by NoFakeGuy** [comment]
Thanks!
