### ISSUE TITLE
Giving players kit permissions, in-game

### ISSUE THREAD

**Issue by ImBadAtUnturned** [uEssentials/uEssentials#565]
So i have a little RP server and I've made a bunch of roles for people to play as eg: police, medic, farmer, thief, just stuff like that.
My issue is that i have no idea how to let certain players do certain kits without putting there id64 in the permissions folder that correlates to that kit and then restarting the server. 
Is there a way around this, such as a command that i type that gives that player that kit and all the have to do is leave and rejoin the server to do teh kit over and over?
is there suck a thing as /assignkit police <name> ??? i know (_/givekit is a command but i want it so they can do /kit <kitname>_)
Any help would be Greatly appreciated

**Comment by nojo123** [comment]
You have to setup permissions for people to use the command. something like this:

<Permission Cooldown="0">essentials.command.kits</Permission>
<Permission Cooldown="0">essentials.kit.start</Permission>
<Permission Cooldown="0">essentials.command.kits.start</Permission>
<Permission Cooldown="0">essentials.command.kit.start</Permission>
<Permission Cooldown="0">essentials.command.kit</Permission>

the permission file can be found in the rocket folder
"start" would be the kit name. You have to make kits inside the: rocket>plugins>uEssentials folder>kits.json

there is someone who had some problems aswell here is a link with help: https://github.com/uEssentials/uEssentials/issues/554

Hope this is enough info to help you out ;)

**Comment by ImBadAtUnturned** [comment]
@nojo123 yes mate, i know this and i state that i know this in my post. My issue is that i would have to restart the server every time i give someone the permission for them to have access to the kit. What i would like to know is what the command is in-game to give someone access to a kit. For instance, i'm playing on an RP server and i want a role, i go to the admin "hey could i have this role" they say "yup okey" they type in a command and all i have to do to get access to the kit is to re-log onto the server. What command does the admin type in to give this player the kit without restarting the server.
Thanks for your input.

**Comment by nojo123** [comment]
Im not sure if a command like that actually exists what you could do is make multiple groups and assign people to groups called; medic, farmer, police etc. just give these groups the permissions they need and you can freely assign each person to a group with
`/p [add | remove] <player> <group> - add / remove player to group (p.add, p.remove)`

Hope this helps you out, feel free to ask more things

**Comment by ImBadAtUnturned** [comment]
Thank you, i think that's the command i needed, much love xD

**Comment by nojo123** [comment]
haha awesome, goodluck with your server mate :)

**Comment by ImBadAtUnturned** [comment]
Thanks

**Comment by nojo123** [comment]
If you feel like this issue has been fixed i think we should close it. :)
