### ISSUE TITLE
Config.json not registering and not working :(

### ISSUE THREAD

**Issue by mreasyy** [uEssentials/uEssentials#566]
Below are the contents of my config.json file, also i took this one out and generated a completely new one and that still did not work which surprised me? what could i be doing wrong? my auto messages use to announce but they stopped lately and idk why? can anyone help? auto messages dont work. but the delay for warps i set up works? and the tpa delay works? why does the auto messages not work ?

**{
  "Locale": "en",
  "PrivateMessage": {
    "FormatFrom": "(From {0}): {1}",
    "FormatTo": "(To {0}): {1}",
    "FormatSpy": "<gray>Spy: {0} -> {1}: {2}",
    "ConsoleDisplayName": "*console*"
  },
  "UnfreezeOnDeath": true,
  "UnfreezeOnQuit": true,
  "EnableTextCommands": true,
  "EnableDeathMessages": true,
  "EnableJoinLeaveMessage": true,
  "ShowPermissionOnErrorMessage": true,
  "SaveCommandCooldowns": false,
  "EnablePollRunningMessage": true,
  "PollRunningMessageCooldown": 20,
  "ServerFrameRate": -1,
  "BackDelay": 10,
  "ItemSpawnLimit": 10,
  "AntiSpam": {
    "Enabled": true,
    "Interval": 3
  },
  "Updater": {
    "CheckUpdates": true,
    "DownloadLatest": true,
    "AlertOnJoin": true
  },
  "Home": {
    "TeleportDelay": 10,
    "CancelTeleportWhenMove": true
  },
  "Warp": {
    "TeleportDelay": 5,
    "CancelTeleportWhenMove": false,
    "PerWarpPermission": false
  },
  "VehicleFeatures": {
    "RefuelPercentage": 20,
    "RepairPercentage": 70
  },
  "Kit": {
    "ShowCost": true,
    "ShowCostIfZero": false,
    "CostFormat": "{0}({1}{2})",
    "GlobalCooldown": 0,
    "ResetGlobalCooldownWhenDie": false
  },
  "Tpa": {
    "CancelTeleportWhenMove": false,
    "ExpireDelay": 10,
    "TeleportDelay": 5
  },
  "Economy": {
    "UseXp": false,
    "XpCurrency": "Xp",
    "UconomyCurrency": "Dolla"
  },
  "AutoAnnouncer": {
    "Interval": 10,
    "RandomMessages": false,
    "Enabled": true,
    "Messages": [
      "<red>Read The Rules Please and type /roleplayrules and read that",
      "<red>To Get Started Type /jobs and choose a job, the job will give you a kit",
      "<green>Join Our Official Discord - https://discordapp.com/invite/MhFMFqU or type /discord",
      "<green>TYPE /website And Look At The Top Of Our Site To Vote For Our Server Then Type /reward When Done For items! (DO NOT KOS)",
      "<green>To Trade/Buy Items/Apartments type /warps and go to a roleplay town!",
      "<green>KOS IS ALLOWED ON FULL MOON",
      "<green>Apply For Helper, Type /forums",
      "<green>REMEMBER THIS IS RP DO NOT KOS ANYWHERE"
      "<green>Convoys Are A Pair Of Vehicles At A Location You Must Attack In Order To Get The Goods In The Vehicles",
      "<green>Website Link - Beforedawnteam.enjin.com -For Info Ask Staff",
      "<green>We Run purely off donations please consider donating to keep us alive! and make us even better! you can get ranks too!",
      "<green>METAL SCRAP IS CURRENCY"
      "<green>type /website to go to our website! also consider donating so we dont shutdown!",
      "<green>type /website to vote for our server (at top of site) then /reward when done for epic loot! (Chance for freighterpack/fury)",
      "<green>Anybody Can Rob Banks! Try The One Near Seattle! (Police may kos robbers)",
      "<blue>To Private Message type /tell -playername- (Type /donate to donate)",
      "<green>Join Our Official Discord - https://discordapp.com/invite/MhFMFqU or type /discord",
      "<green>Talk to Easy Or Moto If Your A Cop In Game, To Join The Cop Steam Group To Get Access To The Cop Station!",
      "<green>If u r being robbed u cannot tp away.",
      "<green>THIS IS RP type /warp rptown to get to rptown ",
      "<green>For some very nice items go to a feast! or try mili! base(NO KOS)",
      "<yellow>To Donate For Ranks And To Make Us Better type /donate",
      "<yellow>Always announce in global chat if you raid a base and the near location",
      "<yellow>To Leave Your Job Type /jobleave Must wait 20 mins to get another job",
      "<yellow>Police have /warp copstation (can only enter if in police steam group) (talk to easy to get invite)",
      "<magenta>For Suggestions Talk To Easy Or Go To Forums",
      "<magenta>Type /website to vote for our server then type /reward for a chance at epic loot! (MK2-1%,Fury,Scalar,FreighterPack,SherrifVest, AND MORE",
      "<magenta>DO NOT USE A FAKE VOICE OF ANYKIND WHEN TALKING TO ADMINS (DO NOT KOS)",
      "<green>Join Our Official Discord - https://discordapp.com/invite/MhFMFqU or type /discord",
      "<green>Website Link - Beforedawnteam.enjin.com -For Info Ask Staff",
      "<blue>Bunkers Are Hidden All Over The Map",
      "<green>To See If An Admin Is Abusing Type /isgod or /isvanish -adminnamehere-",
      "<green>Currency Ingame Is Metal Scrap"
    ]
  },
  "AutoCommands": {
    "Commands": [
      {
        "RunOnce": false,
        "Timer": 120,
        "Commands": [
          "say \"Be sure to drink your Ovaltine!\" 0 255 255",
          "item * glue"
        ]
      },
      {
        "RunOnce": false,
        "Timer": 900,
        "Commands": [
          "clear v",
          "respawnvehicles"
        ]
      }
    ],
    "Enabled": false
  },
  "GiveItemBlacklist": [],
  "VehicleBlacklist": [],
  "EnabledSystems": [
    "kits",
    "warps"
  ],
  "DisabledCommands": []
}
**

**Comment by leonardosnt** [comment]
There are a lot of syntax errors.

http://www.jsonschemavalidator.net/

```json
{
  "Locale": "en",
  "PrivateMessage": {
    "FormatFrom": "(From {0}): {1}",
    "FormatTo": "(To {0}): {1}",
    "FormatSpy": "Spy: {0} -> {1}: {2}",
    "ConsoleDisplayName": "console"
  },
  "UnfreezeOnDeath": true,
  "UnfreezeOnQuit": true,
  "EnableTextCommands": true,
  "EnableDeathMessages": true,
  "EnableJoinLeaveMessage": true,
  "ShowPermissionOnErrorMessage": true,
  "SaveCommandCooldowns": false,
  "EnablePollRunningMessage": true,
  "PollRunningMessageCooldown": 20,
  "ServerFrameRate": -1,
  "BackDelay": 10,
  "ItemSpawnLimit": 10,
  "AntiSpam": {
    "Enabled": true,
    "Interval": 3
  },
  "Updater": {
    "CheckUpdates": true,
    "DownloadLatest": true,
    "AlertOnJoin": true
  },
  "Home": {
    "TeleportDelay": 10,
    "CancelTeleportWhenMove": true
  },
  "Warp": {
    "TeleportDelay": 5,
    "CancelTeleportWhenMove": false,
    "PerWarpPermission": false
  },
  "VehicleFeatures": {
    "RefuelPercentage": 20,
    "RepairPercentage": 70
  },
  "Kit": {
    "ShowCost": true,
    "ShowCostIfZero": false,
    "CostFormat": "{0}({1}{2})",
    "GlobalCooldown": 0,
    "ResetGlobalCooldownWhenDie": false
  },
  "Tpa": {
    "CancelTeleportWhenMove": false,
    "ExpireDelay": 10,
    "TeleportDelay": 5
  },
  "Economy": {
    "UseXp": false,
    "XpCurrency": "Xp",
    "UconomyCurrency": "Dolla"
  },
  "AutoAnnouncer": {
    "Interval": 10,
    "RandomMessages": false,
    "Enabled": true,
    "Messages": [
      "Read The Rules Please and type /roleplayrules and read that",
      "To Get Started Type /jobs and choose a job, the job will give you a kit",
      "Join Our Official Discord - https://discordapp.com/invite/MhFMFqU or type /discord",
      "TYPE /website And Look At The Top Of Our Site To Vote For Our Server Then Type /reward When Done For items! (DO NOT KOS)",
      "To Trade/Buy Items/Apartments type /warps and go to a roleplay town!",
      "KOS IS ALLOWED ON FULL MOON",
      "Apply For Helper, Type /forums",
      "REMEMBER THIS IS RP DO NOT KOS ANYWHERE",
      "Convoys Are A Pair Of Vehicles At A Location You Must Attack In Order To Get The Goods In The Vehicles",
      "Website Link - Beforedawnteam.enjin.com -For Info Ask Staff",
      "We Run purely off donations please consider donating to keep us alive! and make us even better! you can get ranks too!",
      "METAL SCRAP IS CURRENCY",
      "type /website to go to our website! also consider donating so we dont shutdown!",
      "type /website to vote for our server (at top of site) then /reward when done for epic loot! (Chance for freighterpack/fury)",
      "Anybody Can Rob Banks! Try The One Near Seattle! (Police may kos robbers)",
      "To Private Message type /tell -playername- (Type /donate to donate)",
      "Join Our Official Discord - https://discordapp.com/invite/MhFMFqU or type /discord",
      "Talk to Easy Or Moto If Your A Cop In Game, To Join The Cop Steam Group To Get Access To The Cop Station!",
      "If u r being robbed u cannot tp away.",
      "THIS IS RP type /warp rptown to get to rptown ",
      "For some very nice items go to a feast! or try mili! base(NO KOS)",
      "To Donate For Ranks And To Make Us Better type /donate",
      "Always announce in global chat if you raid a base and the near location",
      "To Leave Your Job Type /jobleave Must wait 20 mins to get another job",
      "Police have /warp copstation (can only enter if in police steam group) (talk to easy to get invite)",
      "For Suggestions Talk To Easy Or Go To Forums",
      "Type /website to vote for our server then type /reward for a chance at epic loot! (MK2-1%,Fury,Scalar,FreighterPack,SherrifVest, AND MORE",
      "DO NOT USE A FAKE VOICE OF ANYKIND WHEN TALKING TO ADMINS (DO NOT KOS)",
      "Join Our Official Discord - https://discordapp.com/invite/MhFMFqU or type /discord",
      "Website Link - Beforedawnteam.enjin.com -For Info Ask Staff",
      "Bunkers Are Hidden All Over The Map",
      "To See If An Admin Is Abusing Type /isgod or /isvanish -adminnamehere-",
      "Currency Ingame Is Metal Scrap"
    ]
  },
  "AutoCommands": {
    "Commands": [
      {
        "RunOnce": false,
        "Timer": 120,
        "Commands": [
          "say \"Be sure to drink your Ovaltine!\" 0 255 255",
          "item * glue"
        ]
      },
      {
        "RunOnce": false,
        "Timer": 900,
        "Commands": [
          "clear v",
          "respawnvehicles"
        ]
      }
    ],
    "Enabled": false
  },
  "GiveItemBlacklist": [],
  "VehicleBlacklist": [],
  "EnabledSystems": [
    "kits",
    "warps"
  ],
  "DisabledCommands": []
}
```
