### ISSUE TITLE
How To Blacklist Vehicles?

### ISSUE THREAD

**Issue by mreasyy** [uEssentials/uEssentials#568]
in the uessentials config it says 

    ]
  },
  "AutoCommands": {
    "Commands": [
      {
        "RunOnce": false,
        "Timer": 1500,
        "Commands": [
          "respawnitems",
          ""
        ]
      },
      {
        "RunOnce": false,
        "Timer": 900,
        "Commands": [
          "",
          ""
        ]
      }
    ],
    "Enabled": false
  },
  "GiveItemBlacklist": [],
  "VehicleBlacklist": [],
  "EnabledSystems": [
    "kits",
    "warps"
  ],
  "DisabledCommands": []
}

^^^^^ VehicleBlacklist how do i blacklist vehicles??? i want to blacklist all tanks

**Comment by leonardosnt** [comment]
e.g

```json
"VehicleBlacklist": [
  1,
  2,
  3
],
```

Note: this will only prevent vehicles being spawned using /vehicles
