### ISSUE TITLE
Add option in kits to set fuel percentage for gas cans (ItemFuelAsset)

### ISSUE THREAD

**Issue by aviadmini** [uEssentials/uEssentials#573]
Currently uEssentials is refueling both gas cans when spawned or in kits. Would be great to be able to have kit with empty or partially filled up gas cans too.

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/Builds/releases/tag/build-ff6760d

kits.json
```json
      {
        "Id": 1440,
        "Durability": 100,
        "Amount": 1,
        "FuelPercentage": 50
      },
```

**Comment by aviadmini** [comment]
@leonardosnt Thanks a lot, gonna use right away

**Comment by aviadmini** [comment]
@leonardosnt 2 things
1) [this](https://github.com/uEssentials/uEssentials/blob/ff6760dedd2425c67776919b45dab4ffce4ae92c/src/Common/Util/ItemUtil.cs#L208-L210) method is recursive - delete it (because [this](https://github.com/uEssentials/uEssentials/blob/ff6760dedd2425c67776919b45dab4ffce4ae92c/src/Common/Util/ItemUtil.cs#L212-L221) already covers same overload)
2) [this line ](https://github.com/uEssentials/uEssentials/blob/ff6760dedd2425c67776919b45dab4ffce4ae92c/src/Common/Util/ItemUtil.cs#L216) is super lame. So totally no option for custom fuel cans. Any way to prevent hardcode?

**Comment by leonardosnt** [comment]
1. Thanks, my bad
2. I'll check later

**Comment by aviadmini** [comment]
@leonardosnt use `ItemFuelAsset.fuel` property, that's the max value

**Comment by leonardosnt** [comment]
@aviadmini I did, https://github.com/uEssentials/uEssentials/blob/master/src/Common/Util/ItemUtil.cs#L212
