### ISSUE TITLE
essentials groups question

### ISSUE THREAD

**Issue by xShineyThighx** [uEssentials/uEssentials#574]
I have a few ranks in my server

default > redgang> blugang > staff
is there  command to add people to a group ingame without going into the server FTP?

**Example: /group <add/remove> <player> <groupname>**

I'd like to be able to add someone to the redgang ingame
**Example: /group add xShineyThighx redgang**

**Comment by leonardosnt** [comment]
No, there is not.

You can check available commands here: https://github.com/uEssentials/uEssentials/wiki/Command-Reference

**Comment by Ecxdirerr** [comment]
@xShineyThighx RocketMod Built in permissions system is what we use

Example:  /p add Name groupid  it will add person, to groupid

**Comment by xShineyThighx** [comment]
Thanks
