### ISSUE TITLE
clear items doesn't respond to distance value

### ISSUE THREAD

**Issue by lizardrock11** [uEssentials/uEssentials#577]
In trying to use "clear i" to clear items within a 10 meter radius on a Russia map, it always clears all items on the map and not just those within the specified distance.

The format of the command used was "clear i 10"

This is done as an admin and there is no value in the permissions file for the clear command since it is only being used by admins.

Is the distance specified using meters?

Is the lack of response to the distance value a known bug?
Is there any workaround?

**Comment by leonardosnt** [comment]
The "distance" parameter is not implemented...
