### ISSUE TITLE
Kit permission issue

### ISSUE THREAD

**Issue by WGSRangerWolf** [uEssentials/uEssentials#58]
>         <Command>essentials.kit.*</Command>
> 	<Command>essentials.command.kits</Commands>
>         <Command>essentials.kit.specops</Command>
>         <Command>essentials.kit.police</Command>
>         <Command>essentials.kit.desertmiltary</Command>
>         <Command>essentials.kit.grizzlycamp</Command>
>         <Command>essentials.kit.sniper</Command>
>         <Command>essentials.command.ping</Command>
> 

heres my essentials folder.
I donno if it is a bug but Please take a look at it. I have done those permissions mentioned above and nobody wasnt able to use them. I had to disable the kit system. I had the other one in for backup pruposes. 

https://www.mediafire.com/?qz2pc1vqyaw86on

**Comment by DubFriendsFriendlyFriend** [comment]
Yeah happening to me too

but I thought it was just my stupidity

**Comment by WGSRangerWolf** [comment]
Leonard is pretty good at fixes his own mistakes and bugs :)
Even though he isn't an English man he sure can read it well.

**Comment by WGSRangerWolf** [comment]
issue is resloved
