### ISSUE TITLE
Clear V? Option disabled

### ISSUE THREAD

**Issue by MichaelMajere** [uEssentials/uEssentials#582]
I run a Unturned server, Admin is set correctly for me. I can run every command but "clear V"
Clear i = works
Clear V= This Option is currently disabled
Clear EV= Works 

I am unable to figure out how to enable the clear V option, and am confused if the EV is the buggy experimental one, why that wouldnt be disabled instead of the Clear V. 

I am running the latest Rocket mod Version 1.3.3.1

**Comment by leonardosnt** [comment]
Clear V doesn't work properly.

You can't enable.
