### ISSUE TITLE
Assign people baised on membership on a steam group

### ISSUE THREAD

**Issue by Ecxdirerr** [uEssentials/uEssentials#584]
Or add theses two :D
https://gist.github.com/fr34kyn01535/d0da2fd65ccbf0b21bed
https://gist.github.com/fr34kyn01535/802cf6c5ce62428c47fe

**Comment by leonardosnt** [comment]
You can load your kits/config from a webserver by using `web_resources`

```json
{
  "Enabled": false,
  "URLs": {
    "Config": "http://example.com/config.json",
    "Kits": "http://example.com/kits.json"
  }
}
```
