### ISSUE TITLE
double menssage anouncer and uessentials version

### ISSUE THREAD

**Issue by xstonemetal** [uEssentials/uEssentials#588]
leo help me! my server say this is 1.3.3.0 version but i install lasted version 1.3.3.2 
second, my server have double menssages, in menssage anouncer and when a player die. is a bug?

**Comment by xstonemetal** [comment]
pls fix this problem >.<
[http://imgur.com/a/yh4lT](url)

**Comment by leonardosnt** [comment]
This will happen if you have 2 uEssentials.dll in the plugins/ folder or its subfolders

**Comment by xstonemetal** [comment]
I have 1 but dont worry, i m going to close my server
