### ISSUE TITLE
Execute effect on login is this possible?

### ISSUE THREAD

**Issue by mreasyy** [uEssentials/uEssentials#589]
is it possible on u-essentials to do a /effect on a player when they login, when the player logs in i want the effect : 133 to be displayed on top of them its a cool glow effect. is this possible? thanks for answers

PS - Also since your already reading this, how do i make it so a kit gives the player XP ?

**Comment by Ecxdirerr** [comment]
https://github.com/uEssentials/uEssentials/wiki/Kits-Reference
as for the effect 133 i am unsure if this is implemented

**Comment by leonardosnt** [comment]
No, it is not possible. You need another plugin to do that.
