### ISSUE TITLE
issue whit command disable

### ISSUE THREAD

**Issue by xstonemetal** [uEssentials/uEssentials#59]
i use: 
   "DisabledCommands": [
      "warp",
    "warps",
    "setwarp",
    "delwarp",
    "delwarps",
    "deletewarp",
]

but in console "Found 'Command.Warps.DelWarp (delwarp)'. disabling it..."

i dont know why, because i add this command in "DisabledCommands"

i wanna use you warp command buy you can add money uconomy system? 
example:  use 1 warp cost x money

muito obrigado leo

**Comment by Daniil1288** [comment]
It says "Found 'Command.Warps.DelWarp (delwarp)'. disabling it..." because you added delwarp to your DisabledCommand list and now you can't use that command. No one on your server can, actually.

You can't make commands cost money, yet. This was suggested some time ago already, and Leo is working on it (I hope :D)

**Comment by xstonemetal** [comment]
i think what uEssential automatic disable duplicated commandos for another
plugins, this disabling list is for disabling uEssential commands no for
another plugins but.
example i add kits in disabling commands list be cause i dont wanna use it.
but i dont wanna use warpcommand whit uEssentials because dont have system
money.

**Comment by xstonemetal** [comment]
[uEssentials] Searching for commands that conflict with Essential's command.
[uEssentials] Found 'Warps.CommandDelWarp (delwarp)'. Disabling it...
[uEssentials] Disabled 1 commands from another's plugins.
[uEssentials] if you prefer use another command instead of Essentials command, disable it in configuration.

**Comment by xstonemetal** [comment]
"DisabledCommands": [
    "kit",
    "kits",
    "warp",
    "warps",
    "exp",
    "ci",
    "setwarp",
    "delwarp",
    "delwarps",
    "exp",
    "deletewarp"
]
[uEssentials] Unregistered command: 'kit'
[uEssentials] Unregistered command: 'kits'
[uEssentials] Unregistered command: 'warp'
[uEssentials] Unregistered command: 'warps'
[uEssentials] Unregistered command: 'exp'
[uEssentials] Unregistered command: 'ci'
[uEssentials] Unregistered command: 'setwarp'
[uEssentials] Unregistered command: 'delwarp'

[uEssentials] Searching for commands that conflict with Essential's command.
[uEssentials] Found 'Warps.CommandDelWarp (delwarp)'. Disabling it...
[uEssentials] Disabled 1 commands from another's plugins.
[uEssentials] if you prefer use another command instead of Essentials command, disable it in configuration.

**Comment by Daniil1288** [comment]
Yep, that's an error, I think. Well, let's wait for Leo to fix it, then :P
