### ISSUE TITLE
Clear V

### ISSUE THREAD

**Issue by Sadisticrabbit** [uEssentials/uEssentials#590]
Hi All,

Quick question. When I try to use /clear V I get "This option is currently disabled" 

I can't seem to find anywhere to enable it. Any ideas? 

Thanks

**Comment by Tortellio** [comment]
i think it's bugged so leo disable it, use /clear ev instead

**Comment by Sadisticrabbit** [comment]
What's the permission node for ev? 

essentials.command.clear.ev?

**Comment by Sadisticrabbit** [comment]
OK, checked the source code and it's essentials.command.clear.emptyvehicles :)
