### ISSUE TITLE
trying to disable a command named rules

### ISSUE THREAD

**Issue by RJGamer1002** [uEssentials/uEssentials#593]
when i try to disable a command it says: 
[uEssentials] [WARN] There is no command named 'rules' to disable.
[uEssentials] [INFO] Disabled command: 'kit'
[uEssentials] [INFO] Overriding Rocket command (rules)
what????...... plz help

**Comment by leonardosnt** [comment]
`rules` is a TextCommand, you should remove it from text_commands.json

E.g

Before:
```json
[
  {
    "Name": "rules",
    "Text": [
      "<cyan>Be Respectful.",
      "<cyan>Don't use cheats.",
      "<cyan>Have fun :D"
    ]
  },
  {
    "Name": "website",
    "Text": [
      "<cyan>Our website: github.com/uEssentials"
    ]
  }
]
```

After:
```json
[
  {
    "Name": "website",
    "Text": [
      "<cyan>Our website: github.com/uEssentials"
    ]
  }
]
```

**Comment by RJGamer1002** [comment]
Ok thank

**Comment by Tortellio** [comment]
well, this can be closed now
