### ISSUE TITLE
Kits Not Working

### ISSUE THREAD

**Issue by bruris** [uEssentials/uEssentials#594]
i setup my kits for the essentials plugin and i even restarted the server and they didn't show up or save the kits, am i doing something wrong? can you help me?

**Comment by leonardosnt** [comment]
Comment here the content of the file ``kits.json``.

**Comment by FlipmeisterWill** [comment]
I am having the same issue, even if I only change the name of the default kit in the kits.json file and then rocket reload.. It just resets the kit.json file.

**Comment by 2000jbm** [comment]
Same thing here with my config. Here is my kits.json file, for your debugging
[Kits Zip.zip](https://github.com/uEssentials/uEssentials/files/894785/Kits.Zip.zip)

**Comment by leonardosnt** [comment]
@2000jbm Of course that will not work, there alot of syntax errors. http://www.jsonschemavalidator.net/
