### ISSUE TITLE
Cooldowns on kits reset after a restart

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#595]
I know that active cooldowns are stored in a separate folder in a separate file. But after I restart the server they're no longer there! This means that players can access kits that they have already used and are on cooldown after a server restart (for example: using a kit with a 3-day cooldown after a daily server restart). Can this get fixed, please?

**Comment by leonardosnt** [comment]
How are you shutting down your server?

**Comment by Daniil1288** [comment]
@leonardosnt by using RocketManager (the python script) from here: https://rocketmod.net/forum/thread/140-tool-rocketmanager-v1-9-5-windows-and-linux/

**Comment by Daniil1288** [comment]
here's the source code: @leonardosnt https://github.com/SergiX44/Rocket_Manager

**Comment by leonardosnt** [comment]
RocketManager is killing the process: https://github.com/SergiX44/Rocket_Manager/blob/master/Rocket_Manager.py#L232-L238

You must use /shutdown.
