### ISSUE TITLE
/kits not working

### ISSUE THREAD

**Issue by ServerOne** [uEssentials/uEssentials#597]
I tried making kits, they are working for admins, when a player tries to the cmd,  they don't have the permission when they have it.

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference#kits

**Comment by ServerOne** [comment]
i don't get it, i checked and made sure they had permissions, but yet they were still unable to do the kits.

**Comment by Ecxdirerr** [comment]
Have you added the permissions to the permissions.config.xml?
By default, all kits are not available when you first create them. You need to add them to the default group.
<Permission cooldown="0">essentials.kit.examplekit</Permission>
This is noted on the github wiki documentation @leonardosnt has linked you.
Please note that essentials.kit.* is not functioning properly and will grant every permission
