### ISSUE TITLE
New command "sucide" should be named "suicide"

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#60]
Yes, I do know that your engrish isn't perfect, but I'm trying to help :)

Title. I'm afraid that the name of the command is spelt wrongly. It should be "suicide".

https://github.com/uEssentials/uEssentials/commit/8eb6fac39eb2fd33763ec8560ad91364501c1f6b

added a note.

**Comment by leonardosnt** [comment]
Fixed
