### ISSUE TITLE
Disable commands

### ISSUE THREAD

**Issue by alvinmg10** [uEssentials/uEssentials#601]
I have an issue where this plugin uses the same command as other plugins, FeeExp and Votifier.
The commands are /experience and /vote

The problem with the /exp command was that both plugins used the same permissions so deafult players got acces to the /exp command. I fixed this by making the command price to some ridiculus price.

the problem with the /vote command is that the Votifier plugin uses the same command and I can't make voting for the server to work.

The question i have is, is it possible to dissable or remove on of the uEssential commands?

**Comment by leonardosnt** [comment]
Yes.

Check at end: https://github.com/uEssentials/uEssentials/wiki/Configuration

E.g
```java
"DisabledCommands": [
  "vote",
  "experience"
]

**Comment by alvinmg10** [comment]
Thanks alot!
