### ISSUE TITLE
Change How respawnitems Works.

### ISSUE THREAD

**Issue by Avesnis** [uEssentials/uEssentials#602]
I was just wondering if there is a config somewhere where i can change the percentages of the items that spawn, as well as how much ammo is spawned. I run a hardcore server and love the feature but i find it makes things too easy once you find a gun and what not if i respawn the items.

**Comment by leonardosnt** [comment]
Unfortunately this is not possible.

**Comment by Avesnis** [comment]
ah okay well it was worth a shot, thanks anyway!
