### ISSUE TITLE
Staff can't use commands

### ISSUE THREAD

**Issue by Paradonix** [uEssentials/uEssentials#603]
So i today when i joined my server one of my mods told me that he couldn't use some commands and some had cooldown but when i checked the permissions file no commands had cooldowns and now i don't know what the problem is. 
Edit: I also found out that people without the permissions can do /v or /i
Here the Moderator permissions:
https://pastebin.com/zeEgZdDJ

**Comment by Sadisticrabbit** [comment]
Remove this: 

<Permission Cooldown="0">essentials.command.kit.*</Permission>

Kit.* no longer works. It will give all permissions to everyone. You have to specify them individually now.
