### ISSUE TITLE
Airdrop,Messages

### ISSUE THREAD

**Issue by LuXusKaMel** [uEssentials/uEssentials#606]
I have this in my Config but the Server don´t show me the Announcer and The Airdrop only comes without Message. Is there any Problem with there tool ? },
  "AutoAnnouncer": {
    "Interval": 180,
    "RandomMessages": false,
    "Enabled": true,
    "Messages": [
      "<yellow>Do '/kits' to see your kits!",
      "<yellow>Do '/kit <name>' to use your kits!"
    ]
  },
  "AutoCommands": {
    "Commands": [
      {
        "RunOnce": false,
        "Timer": 60,
        "Commands": [
          "say \"AIRDROP!\" 0 255 255",
          "airdrop"
        ]

**Comment by Tortellio** [comment]
"say \"AIRDROP!\" 0 255 255",
