### ISSUE TITLE
Could not connect to metrics server

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#61]
Error: ConnectFailure

pops up in the console after server restart, but for some reason I can't find the error in my logs. There was a lot of gibberish after ConnectFailure in brackets, probably another language that my console doesn't support.

Also, does anyone know how to make Unturned server's console support UTF-8? I can't read other languages because of (presumably) ANSI :(

**Comment by leonardosnt** [comment]
I know thanks, i'll disable it.

**Comment by Daniil1288** [comment]
No problem ;)
