### ISSUE TITLE
i need help what did i do wrong

### ISSUE THREAD

**Issue by dannythehacker** [uEssentials/uEssentials#610]
<Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Prefix />
      <Suffix />
      <Color>white</Color>
      <Members />
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">home</Permission>
        <Permission Cooldown="0">maxskills</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.warp</Permission>
        <Permission Cooldown="0">essentials.command.warp.rules</Permission>
        <Permission Cooldown="0">essentials.command.warp.town</Permission>
        <Permission Cooldown="0">essentials.command.warp.RP</Permission>
        <Permission Cooldown="0">essentials.command.warps</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit.Civilian</Permission>
        <Permission Cooldown="0">buy</Permission>
        <Permission Cooldown="0">sell</Permission>
        <Permission Cooldown="0">cost</Permission>
        <Permission Cooldown="0">balance</Permission>
        <Permission Cooldown="0">jobs</Permission>
        <Permission Cooldown="0">joinjob</Permission>
        <Permission Cooldown="0">leavejob</Permission>
      </Permissions>
    </Group>

the kits and the warps are not working

**Comment by Ecxdirerr** [comment]
Link permissions.config.xml

**Comment by dannythehacker** [comment]
how

**Comment by dannythehacker** [comment]
http://www.mediafire.com/file/5l5ma2l5acexgci/Permissions.config.xml

**Comment by leonardosnt** [comment]
Wrong
- essentials.command.kit.Civilian
- essentials.command.warp.rules 
- essentials.command.warp.town 
- essentials.command.warp.RP

Right:
- essentials.kit.Civilian
- essentials.warp.rules 
- essentials.warp.town 
- essentials.warp.RP


See https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference

**Comment by dannythehacker** [comment]
tty
