### ISSUE TITLE
Cooldowns on kits reset after a restart using /shutdown

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#615]
I checked, the cooldowns do reset even if you do
/save
/shutdown
1st screen: before the restart, you have to wait 2d 23hr to use this kit again (in russian)
2st screen: after the restart, you received the kit!
![image](https://cloud.githubusercontent.com/assets/1404955/26531738/634a5780-43f8-11e7-9a35-0900aec2b5ee.png)
![image](https://cloud.githubusercontent.com/assets/1404955/26531740/685d9778-43f8-11e7-8694-e4aeb15cd012.png)

**Comment by leonardosnt** [comment]
Try to execute `/ess savedata` before executing `/shutdown`.

Here is working fine, I don't need to use /ess savedata...

**Comment by aviadmini** [comment]
I'll take a look too. Probably an easy solution is to save them on plugin unload

**Comment by leonardosnt** [comment]
@aviadmini It was already being saved.

**Comment by leonardosnt** [comment]
![hihnnbp](https://cloud.githubusercontent.com/assets/13869336/26644114/0f66c572-460a-11e7-8a0a-fe7f1ebf30ba.png)

**Comment by aviadmini** [comment]
Saved if using default config?

**Comment by leonardosnt** [comment]
Yes. 
You can't disable.

**Comment by Daniil1288** [comment]
Okay, tried to test this out again!
Using the latest version of the plugin.
The 1st screenshot, uploaded with steam, 25 minutes remaining until the cooldown ends: http://steamcommunity.com/sharedfiles/filedetails/?id=936931615
The 2nd screenshot, same thing, after a restart: http://steamcommunity.com/sharedfiles/filedetails/?id=936941775
As you can see, only 13 minutes passed, but the second screenshot says that you have to wait ~1hr to use the same kit again (because the command "/kit start" worked and items were given, they're just not shown)
The third screenshot, attached, has the commands which I've used: 

![image](https://cloud.githubusercontent.com/assets/1404955/26652065/5b2f496e-4657-11e7-8631-a46dd6b6f3c6.png)

What's really interesting is that the cooldowns are being saved! Here's a screenshot from uEssentials\data\kit_cooldowns.json: 

![image](https://cloud.githubusercontent.com/assets/1404955/26652324/33b102be-4658-11e7-9ac1-ea0df3aaea00.png)

Of course, the cooldowns are of a guy who helped me out and took, uploaded the screenshots on steam.

**Comment by leonardosnt** [comment]
@Daniil1288 I'll try to take a look tomorrow.

**Comment by Daniil1288** [comment]
Sure.
Here they are:
https://pastebin.com/idks7iSY
I have to say that the problem exists with other kits, too.

**Comment by Daniil1288** [comment]
...I might have just fixed this issue with magical manipulations, but not too sure, will try testing this out again soon.

Here's what happened afterwards: dropped items started despawning instantly and no new loot was being spawned. I shut my server down, removed all the plugins, restarted it, the problem was gone, shutted it down again, placed the plugins back into the server's plugin folder, restarted it again, everything worked. And the cooldowns were back.

I also removed the registered commands xml file, switched a lot of open files' encoding to UTF8 and did some other nonsensical things. Not sure how any of this could fix anything, but it just might have done that. Again, will report after testing again numerous times.

P.S. Oh, and I removed the Players folder and the level data one - basically, wiped the server. But that was even before the instant item despawn started happening.

**Comment by Daniil1288** [comment]
Nope, restarted the server again today and one of my testers got /kit boom (which has a 3-day cooldown). This means that the glitch is still present, false alarm. I've got no idea what causes it.

**Comment by persiafighter** [comment]
I believe I found what causes the bug, it is primarily how the kit cooldowns are loaded back into the memory of uessentials. See https://github.com/uEssentials/uEssentials/blob/master/src/NativeModules/Kit/Data/CooldownData.cs#L44 for what I mean.

If you look carefully, the code will clear the already in memory cooldowns every time it adds a new cooldown and it will only keep the last cooldown of the file, therefore pretty much ignoring every single other kit cooldown and causing them to disappear and not apply.
