### ISSUE TITLE
Permissions Problem

### ISSUE THREAD

**Issue by Clucks** [uEssentials/uEssentials#618]
People in my server can't use the commands for uEssentials. When someone types a tpa request it says they don't have permission.

![unturned help](https://cloud.githubusercontent.com/assets/29190332/26770293/ebdbd3a8-497a-11e7-928a-f738b3421cb6.png)

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference

**Comment by Clucks** [comment]
I replaced the tpa.accept with "essentials.command.tpa.accept" but it still says no permission

**Comment by leonardosnt** [comment]
You should add
- essentials.command.tpa
- essentials.command.tpa.accept
- essentials.command.tpa.cancel
- essentials.command.tpa.deny
- essentials.command.tpa.send

**Comment by Clucks** [comment]
Thanks it worked on your website it doesn't say the essentials.command.tpa
