### ISSUE TITLE
kit/kits permission

### ISSUE THREAD

**Issue by puggy5566** [uEssentials/uEssentials#619]
Hello, i have a question about kit/kits permission.
People on my server can use uEssentials commands except kit and kits.
Here is my permission. Could someone look at it and tell me what the problem is?
Thank you. 

![capture](https://cloud.githubusercontent.com/assets/29209919/26797722/784ff40e-49f3-11e7-8d26-e90882dcbfd1.PNG)

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference#kits
https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference#kits

**Comment by puggy5566** [comment]
Thank you.
https://github.com/uEssentials/uEssentials/wiki/Command-Reference#kit

**Comment by leonardosnt** [comment]
This is wrong: `essentials.command.kit.starter`, it should be `essentials.kit.starter` and you need to add `essentials.command.kit`.

**Comment by puggy5566** [comment]
[https://github.com/uEssentials/uEssentials/issues/554#issuecomment-274278005](url)
I have tried what you mentioned, but it didn't work.
My problem is solved by the link above. 
Thanks.
