### ISSUE TITLE
Problem With Permission Kit

### ISSUE THREAD

**Issue by takahashitakeshi** [uEssentials/uEssentials#620]
<Permission Cooldown="0">essentials.command.kits</Permission>
<Permission Cooldown="0">essentials.kit.starter</Permission>
When i write : /kits in game. It said :  "Access kit : starter"
When i write : /kit starter. It said : i dont have permssion.
I dont know why, it's running without any error. I dont understand
when I change the permission like that :
<Permission Cooldown="0">essentials.command.kit.starter</Permission>
It said : No access kit avaiable

**Comment by leonardosnt** [comment]
You must add `essentials.command.kit`.
