### ISSUE TITLE
Permissions don´t work

### ISSUE THREAD

**Issue by DiabloMusicTM** [uEssentials/uEssentials#621]
#618 #620     
<Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Prefix />
      <Suffix />
      <Color>white</Color>
      <Members />
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">essentials.kits</Permission>
        <Permission Cooldown="100">essentials.kit.asalto-1</Permission>
        <Permission Cooldown="100">kit.asalto-1</Permission>
	<Permission Cooldown="100">kits</Permission>
      </Permissions>
    </Group>
# 
# When a normal user logs in, he can not pick up that kit and says he does not have permissions

**Comment by leonardosnt** [comment]
You must add `essentials.command.kit` also.

https://github.com/uEssentials/uEssentials/wiki/Command-Reference#kit

**Comment by DiabloMusicTM** [comment]
I already tried it, it does not work
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit.asalto-1</Permission>
        <Permission Cooldown="0">kit.asalto-1</Permission>
        <Permission Cooldown="0">kits</Permission>
		<Permission Cooldown="0">essentials.kit.asalto-1</Permission>

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference#kits
https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference#kits

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/FAQ#why-my-users-cant-access-any-kits

**Comment by DiabloMusicTM** [comment]
Thank you and sorry for the inconvenience
