### ISSUE TITLE
Basic players can use /i and /v

### ISSUE THREAD

**Issue by bobthecow111** [uEssentials/uEssentials#622]
for awhile now i thought people in my server were hacking or spawning stuff in for them stuff in with clients but it seems the entire time it was because they can use /i and /v . in permissions i never gave them access and i made sure of this by having my one friend join on another account and it still worked .dont know why it is letting them spawn stuff . plz help my server is down till this is fixed!

**Comment by leonardosnt** [comment]
Show me your permissions.config.xml

**Comment by bobthecow111** [comment]
ok here it is
`<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>default</DisplayName>
      <Prefix />
      <Suffix />
      <Color>white</Color>
      <Members>
        <Member>76561198083742690</Member>
      </Members>
      <Permissions>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.abort</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit.xp</Permission>
        <Permission Cooldown="0">essentials.command.kit.starter</Permission>
        <Permission Cooldown="0">essentials.command.kit.daily</Permission>
        <Permission Cooldown="0">essentials.command.kit.tools</Permission>
        <Permission Cooldown="0">essentials.command.kit.*</Permission>
        <Permission Cooldown="0">home</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">reward</Permission>
        <Permission Cooldown="0">avi.shop.cost</Permission>
        <Permission Cooldown="0">avi.shop.buy</Permission>
        <Permission Cooldown="0">avi.shop.sell</Permission>
        <Permission Cooldown="0">avi.economy.pay</Permission>
        <Permission Cooldown="0">avi.economy.balance.other</Permission>
        <Permission Cooldown="0">avi.economy.balance</Permission>
        <Permission Cooldown="0">avi.economy.exchange</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>`

**Comment by bobthecow111** [comment]
did you look at it

**Comment by leonardosnt** [comment]
You must remove this: `essentials.command.kit.*`

#562

And this: `essentials.command.kit.daily`  is wrong, it should be `essentials.kit.daily`. See https://github.com/uEssentials/uEssentials/wiki/FAQ#why-my-users-cant-access-any-kits

**Comment by bobthecow111** [comment]
ok thanks

**Comment by bobthecow111** [comment]
when i do that will my kits still work
