### ISSUE TITLE
Commands not working.

### ISSUE THREAD

**Issue by nathan24476** [uEssentials/uEssentials#623]
Hello, My commands aren't working for uEssentials, Rocket is updated, i'm using the newest uessentials. I have attached a screenshot showing my plugins. 
![screenshot_8](https://user-images.githubusercontent.com/29510923/27256062-1f49da28-53a3-11e7-8312-8d1b5e8631f5.jpg)

**Comment by leonardosnt** [comment]
Link your permissions.config.xml

https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference

**Comment by nathan24476** [comment]
Hello, I'm admin on it and I haven't edited the confit and added all the basic permissions for the players and it still doesn't work.

**Comment by nathan24476** [comment]
config*

**Comment by leonardosnt** [comment]
Link your permissions.config.xml
