### ISSUE TITLE
Can't load my kits.json file.

### ISSUE THREAD

**Issue by XanderCodes** [uEssentials/uEssentials#624]
Hello, I am creating a RP sever and am using the latest version of uEssentials for kits. I have written my kits file outside of the direct server folder then dragged it in, but every time i boot or restart my server, the kit file reverts to the default one. I have attached most of the files to this post. Please help, as a lot of people are waiting for my server to launch.

Thanks, AppleManYT

[Server Files.zip](https://github.com/uEssentials/uEssentials/files/1082839/Server.Files.zip)

**Comment by leonardosnt** [comment]
Use this website: http://www.jsonschemavalidator.net/ to check if the JSON syntax is valid.

**Comment by XanderCodes** [comment]
I put the file through, and it had an error parsing schema, i loaded the default file in aswell, and it gave the same error. Do i have to set the Schema to anything??

**Comment by leonardosnt** [comment]
If you don't know how to use JSON, you should use [/createkit](https://github.com/uEssentials/uEssentials/wiki/Command-Reference#createkit) or [/editkit](https://github.com/uEssentials/uEssentials/wiki/Command-Reference#editkit)

> i loaded the default file in aswell, and it gave the same error.

Sure?
![](http://i.imgur.com/EwqCNnS.png)

>  Do i have to set the Schema to anything??

Leave the default. It's the Empty Schema.
