### ISSUE TITLE
Disable some features in uEssentials.

### ISSUE THREAD

**Issue by iiEpixx** [uEssentials/uEssentials#626]
Is there any way to disable certain features of uEssentials?
I need to make it so uEssentials doesn't override a couple of my already installed plugins. i.e: TPA, warps, kits, and rules.
I tried to poke around in uEssentials' rocket folder to see if I could delete or disable some of its commands to no avail. It seems there aren't any pieces I can delete or anything so what should I do if it **is** possible.
Please help me with this otherwise I'll probably have to get rid of uEssentials, although I do love its commands and how helpful it is.
Thanks.

**Comment by leonardosnt** [comment]
config.json https://github.com/uEssentials/uEssentials/wiki/Configuration

To disable kits and warps, remove they from the "EnabledSystems" list.
```json
  "EnabledSystems": [
    "kits",
    "warps"
  ],
```

To disable /tpa, add it to the "DisabledCommands" list.
E.g 
```json
  "DisabledCommands": [
     "tpa"
  ]
```

To disable /rules you must remove it from `text_commands.json`

Before:
```json
[
  {
    "Name": "rules",
    "Text": [
      "<cyan>Be Respectful.",
      "<cyan>Don't use cheats.",
      "<cyan>Have fun :D"
    ]
  },
  {
    "Name": "website",
    "Text": [
      "<cyan>Our website: github.com/uEssentials"
    ]
  }
]
```
After:
```
[
  {
    "Name": "website",
    "Text": [
      "<cyan>Our website: github.com/uEssentials"
    ]
  }
]
```

**Comment by iiEpixx** [comment]
@leonardosnt Thank you so much! I changed what you said to and I ran my server and voila! uEssentials is no longer overriding those plugins. Once again I thank you because I've been trying to fix this for a while.

**Comment by iiEpixx** [comment]
Edit: After starting my server for the second time the commands seem to have broken. I removed the kits, tpa, rules, and some other stuff to "Disabled commands" and then set the commands thet I wanted enabled into "EnabledSystems" but they didn't activate. Fix?

**Comment by iiEpixx** [comment]
I'm going to attempt to reinstall uEssentials then change the config.json again.
