### ISSUE TITLE
uEssentials causes NRE in other plugins (R.Permissions is null) on /rocket reload

### ISSUE THREAD

**Issue by aviadmini** [uEssentials/uEssentials#628]
If any another plugin uses `R.Permissions` on plugin load it gets broken on /rocket reload

A dumb workaround (for other plugins) is to use `R.Plugins.OnPluginsLoaded` event but I'd suggest fixing that in uEss ;)

**Comment by aviadmini** [comment]
Did some more testing:

* It doesn't happen without uEssentials
* Reassigning the R.Permissions on essentials unload doesn't help

@leonardosnt I actually think you can delete the `EssentialsPermissionsProvider` because Rocket already has negative permissions (although with "-" instead of "!").

**Comment by leonardosnt** [comment]
I think I'll remove LPX  support, since it is "dead".
