### ISSUE TITLE
not found claim flag, and money

### ISSUE THREAD

**Issue by pepixiko** [uEssentials/uEssentials#629]
{
        "RunOnce": false,
        "Timer": 30,
        "Commands": [
          "item * Claim Flag",  ---> say number [flag] incorrect
          "item * 1158",  ---> say no get nothing
          "money 500 *",  ---> say I do not get money
        ]
      },

**Comment by leonardosnt** [comment]
If the item name has spaces you should put between single/doublequotes

`item * Claim Flag` => `item * "Claim Flag"`


```json
```

**Comment by pepixiko** [comment]
thankyou leonard!
