### ISSUE TITLE
CHANGE MONEY!

### ISSUE THREAD

**Issue by DiabloMusicTM** [uEssentials/uEssentials#633]
FOR EXAMPLE   
"home": {
    "Cost": 20.0,
    "Cooldown": 30,
#     **_"PerGroupCost": {         <------------- For example
      "Recluta-Usa": 10
    }
# **_THAT THE PRICE OF THE COMMAND VARY BY THE GROUP THAT YOU ARE xD_**

**Comment by leonardosnt** [comment]
??

**Comment by DiabloMusicTM** [comment]
THAT THE PRICE OF THE COMMAND VARY BY THE GROUP THAT YOU ARE

**Comment by DiabloMusicTM** [comment]
xD

**Comment by DiabloMusicTM** [comment]
Or that once you have paid for the command you do not have to pay again xD

**Comment by leonardosnt** [comment]
You can't do that... yet.

**Comment by DiabloMusicTM** [comment]
is a suggestion xD

**Comment by DiabloMusicTM** [comment]
for uessentials xD
