### ISSUE TITLE
Default Group Issue

### ISSUE THREAD

**Issue by khlawrence** [uEssentials/uEssentials#638]
I probably screwed something up, but when people join my server they are not put into the default group? They can't use the kits nor tpa when I have it in the permissions section; however, I (admin) can use all commands, probably because my id is in the members list.

**Comment by leonardosnt** [comment]
Link your permissions

**Comment by khlawrence** [comment]
[permissions.zip](https://github.com/uEssentials/uEssentials/files/1137445/permissions.zip)

i don't know why but the text kept coming out weird so i put it in a zip folder

**Comment by leonardosnt** [comment]
That looks like ok. I saw that you added permissions for some kits but haven't added for the `/kit` command.... See https://github.com/uEssentials/uEssentials/wiki/FAQ#why-my-users-cant-access-any-kits

**Comment by khlawrence** [comment]
oh the kits are working now! But the tpa are not, is there something I missed?

**Comment by leonardosnt** [comment]
You must add `essentials.command.tpa`...
https://github.com/uEssentials/uEssentials/wiki/Command-Reference#tpa
