### ISSUE TITLE
Kits not working for new players?

### ISSUE THREAD

**Issue by FlairGamezDK** [uEssentials/uEssentials#641]
![skaermbillede 10](https://user-images.githubusercontent.com/30197398/28239661-f0fb8bf0-6971-11e7-8a45-0d9b99d2c15f.png)
new players can /kit, it says they dont have permisiion, Some1? help?

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/FAQ#why-my-users-cant-access-any-kits

**Comment by FlairGamezDK** [comment]
@leonardosnt Its still not working ;=
![skaermbillede 11](https://user-images.githubusercontent.com/30197398/28239772-bc6aed16-6973-11e7-9bd9-c23a87cedb27.png)

**Comment by leonardosnt** [comment]
wtf is this "essentials.command.kit.Bluntforce" ???????? it should be "essentials.kit.Bluntforce" read the WIKI!!!

**Comment by FlairGamezDK** [comment]
ph, iam stupid sorry ;) Thx alot ;) love you work <3
