### ISSUE TITLE
Problem with cost on a kit.  Help!

### ISSUE THREAD

**Issue by LostFox404** [uEssentials/uEssentials#645]
Hi! I have a problem on my server. When i put /kit Meta, her cost don't withdraw of my experience but they spawn the vehicle.

I need open the server in 2 days D: There is a big project on Unturned spanish rol servers

There is the config of the kit:

```
  {
    "Name": "Meta",
    "Items": [
      {
        "Vehicle": 106
      }
    ],
    "Cooldown": 0,
    "Cost": 40000.0,
    "ResetCooldownWhenDie": false
  },
```
If anyone can help me I would be very grateful!

**Comment by leonardosnt** [comment]
Did you set the "UseXp" to true, in the config.json ?

**Comment by LostFox404** [comment]
@leonardosnt Oh, I thought it was already set by default. Thaaanks <3 jajajaja
