### ISSUE TITLE
/freeze doesnt work

### ISSUE THREAD

**Issue by andsrs** [uEssentials/uEssentials#647]
Command /freeze doesnt work. 
**Console**: NullReferenceException: Object reference not set to an instance of an object - Essentials.Components.Player.PlayerComponent.FixedUpdate ()

NullReferenceException: Object reference not set to an instance of an object - Essentials.Components.Player.PlayerComponent.FixedUpdate ()............. etc. It's flooding until i'll write /unfreeze. WTF

**Comment by Aceheliflyer** [comment]
It also doesn't freeze the user, that too.

**Comment by leonardosnt** [comment]
Just tested, it's working in the latest build https://github.com/uEssentials/Builds/releases
