### ISSUE TITLE
Accidental Perma Ban

### ISSUE THREAD

**Issue by aaaaaaaaa1234** [uEssentials/uEssentials#650]
Hi there, I was wondering if there was a way to unban someone with a perma ban. I am not the owner of the server.

**Comment by leonardosnt** [comment]
If you aren't the owner of the server, you can't do that.

**Comment by aaaaaaaaa1234** [comment]
Is there any other way to do without the owner? @leonardosnt

**Comment by Ecxdirerr** [comment]
unban Steamid
