### ISSUE TITLE
No one can use any of the commands.

### ISSUE THREAD

**Issue by Brockpig47** [uEssentials/uEssentials#653]
I have the plugin installed right, permissions are good but no one can use them except admins. No idea why this isn't working.

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference

**Comment by Brockpig47** [comment]
I put those in. Still is broken.

**Comment by leonardosnt** [comment]
Show me your permissions.
