### ISSUE TITLE
How to make an autocommand for xp at intervals?

### ISSUE THREAD

**Issue by SrAmarillo** [uEssentials/uEssentials#656]
I want my players to receive a "salary" of 200xp each 1200 seconds, but it doesn't work

> {
  "Locale": "es",
  "PrivateMessage": {
    "FormatFrom": "(From {0}): {1}",
    "FormatTo": "(To {0}): {1}",
    "FormatSpy": "<gray>Spy: {0} -> {1}: {2}",
    "ConsoleDisplayName": "*console*"
  },
  "UnfreezeOnDeath": true,
  "UnfreezeOnQuit": true,
  "EnableTextCommands": true,
  "EnableDeathMessages": true,
  "EnableJoinLeaveMessage": true,
  "ShowPermissionOnErrorMessage": true,
  "SaveCommandCooldowns": false,
  "EnablePollRunningMessage": true,
  "PollRunningMessageCooldown": 20,
  "ServerFrameRate": -1,
  "BackDelay": 10,
  "ItemSpawnLimit": 10,
  "AntiSpam": {
    "Enabled": true,
    "Interval": 3
  },
  "Updater": {
    "CheckUpdates": true,
    "DownloadLatest": true,
    "AlertOnJoin": true
  },
  "Home": {
    "TeleportDelay": 5,
    "CancelTeleportWhenMove": true
  },
  "Warp": {
    "TeleportDelay": 5,
    "CancelTeleportWhenMove": false,
    "PerWarpPermission": true
  },
  "VehicleFeatures": {
    "RefuelPercentage": 20,
    "RepairPercentage": 70
  },
  "Kit": {
    "ShowCost": true,
    "ShowCostIfZero": false,
    "CostFormat": "{0}({1}{2})",
    "GlobalCooldown": 0,
    "ResetGlobalCooldownWhenDie": false
  },
  "Tpa": {
    "CancelTeleportWhenMove": true,
    "ExpireDelay": 10,
    "TeleportDelay": 5
  },
  "Economy": {
    "UseXp": false,
    "XpCurrency": "Xp",
    "UconomyCurrency": "$"
  },
  "AutoAnnouncer": {
    "Interval": 30,
    "RandomMessages": false,
    "Enabled": false,
    "Messages": [
      "<red>Automatic message 1",
      "<green>Automatic message 2",
      "<blue>Automatic message 3",
      "<yellow>Automatic message 4",
      "<magenta>Automatic message 5"
    ]
  },
  "AutoCommands": {
    "Commands": [
      {
        "RunOnce": false,
        "Timer": 1200,
        "Commands": [
          "say \"Recibes tu cheque semanal de $200\",
          "experiencie 200"
        ]
      },
    ],
    "Enabled": true
  },
  "GiveItemBlacklist": [],
  "VehicleBlacklist": [],
  "EnabledSystems": [
    "kits",
    "warps"
  ],
  "DisabledCommands": []
}

**Comment by leonardosnt** [comment]
Change this: ```experiencie 200``` to ```experience 200 *```

**Comment by SrAmarillo** [comment]
Thank you very much! At first it didn't work, but I reinstalled uessentials and it was fixed
