### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by bananaTrumpXx** [uEssentials/uEssentials#658]
How do i get the warps and kits to work with other players. ive bin trying to find out how to do it and i keep failing.

**Comment by leonardosnt** [comment]
What permissions are you using?

Check the wiki... https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference

**Comment by bananaTrumpXx** [comment]
Right now i got it to work but only admins can use the kits and warps and tpa im trying to make both kits and warps and tpa public for other players to use  i just dont know how to do it... if i sound retarded im terribly sorry this is my first time launching a public/rented server with kits n such

**Comment by leonardosnt** [comment]
Can you post here your permissions?

**Comment by bananaTrumpXx** [comment]
{
  "Locale": "en",
  "PrivateMessage": {
    "FormatFrom": "(From {0}): {1}",
    "FormatTo": "(To {0}): {1}",
    "FormatSpy": "<gray>Spy: {0} -> {1}: {2}",
    "ConsoleDisplayName": "*console*"
  },
  "UnfreezeOnDeath": true,
  "UnfreezeOnQuit": true,
  "EnableTextCommands": true,
  "EnableDeathMessages": true,
  "EnableJoinLeaveMessage": true,
  "ShowPermissionOnErrorMessage": true,
  "SaveCommandCooldowns": false,
  "EnablePollRunningMessage": true,
  "PollRunningMessageCooldown": 20,
  "ServerFrameRate": -1,
  "BackDelay": 10,
  "ItemSpawnLimit": 10,
  "AntiSpam": {
    "Enabled": true,
    "Interval": 3
  },
  "Updater": {
    "CheckUpdates": true,
    "DownloadLatest": true,
    "AlertOnJoin": true
  },
  "Home": {
    "TeleportDelay": 5,
    "CancelTeleportWhenMove": true
  },
  "Warp": {
    "TeleportDelay": 5,
    "CancelTeleportWhenMove": false,
    "PerWarpPermission": true
  },
  "VehicleFeatures": {
    "RefuelPercentage": 20,
    "RepairPercentage": 70
  },
  "Kit": {
    "ShowCost": true,
    "ShowCostIfZero": false,
    "CostFormat": "{0}({1}{2})",
    "GlobalCooldown": 0,
    "ResetGlobalCooldownWhenDie": false
  },
  "Tpa": {
    "CancelTeleportWhenMove": true,
    "ExpireDelay": 10,
    "TeleportDelay": 5
  },
  "Economy": {
    "UseXp": false,
    "XpCurrency": "Xp",
    "UconomyCurrency": "$"
  },
  "AutoAnnouncer": {
    "Interval": 30,
    "RandomMessages": false,
    "Enabled": false,
    "Messages": [
      "<red>Automatic message 1",
      "<green>Automatic message 2",
      "<blue>Automatic message 3",
      "<yellow>Automatic message 4",
      "<magenta>Automatic message 5"
    ]
  },
  "AutoCommands": {
    "Commands": [
      {
        "RunOnce": false,
        "Timer": 120,
        "Commands": [
          "say \"Be sure to drink your Ovaltine!\" 0 255 255",
          "item * glue"
        ]
      },
      {
        "RunOnce": false,
        "Timer": 900,
        "Commands": [
          "clear v",
          "respawnvehicles"
        ]
      }
    ],
    "Enabled": false
  },
  "GiveItemBlacklist": [],
  "VehicleBlacklist": [],
  "EnabledSystems": [
    "kits",
    "warps"
  ],
  "DisabledCommands": []
}

**Comment by bananaTrumpXx** [comment]
Thats my config.json file 
under my config is my kits.json

**Comment by leonardosnt** [comment]
I was talking about the permissions file. You can find it in `Rocket/Permissions.config.xml`.

**Comment by bananaTrumpXx** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Prefix />
      <Suffix />
      <Color>white</Color>
      <Members />
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>vip</Id>
      <DisplayName>VIP</DisplayName>
      <Prefix>[VIP]</Prefix>
      <Suffix>[VIP]</Suffix>
      <Color>FF9900</Color>
      <Members>
        <Member>76561198016438091</Member>
      </Members>
      <ParentGroup>default</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">effect</Permission>
        <Permission Cooldown="120">heal</Permission>
        <Permission Cooldown="30">v</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>


sorry that it took me a while but i found it

**Comment by bananaTrumpXx** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Prefix />
      <Suffix />
      <Color>white</Color>
      <Members />
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>vip</Id>
      <DisplayName>VIP</DisplayName>
      <Prefix>[VIP]</Prefix>
      <Suffix>[VIP]</Suffix>
      <Color>FF9900</Color>
      <Members>
        <Member>76561198016438091</Member>
      </Members>
      <ParentGroup>default</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">effect</Permission>
        <Permission Cooldown="120">heal</Permission>
        <Permission Cooldown="30">v</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>

**Comment by bananaTrumpXx** [comment]
i am trying to post it now but  when i do it dosent show it completly i am trying to download the file to put it here but its not letting me do anything

**Comment by leonardosnt** [comment]
Post it between ```

Or just post it here. I can see it completely.

**Comment by bananaTrumpXx** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Prefix />
      <Suffix />
      <Color>white</Color>
      <Members />
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="10">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>vip</Id>
      <DisplayName>VIP</DisplayName>
      <Prefix>[VIP]</Prefix>
      <Suffix>[VIP]</Suffix>
      <Color>FF9900</Color>
      <Members>
        <Member>76561198016438091</Member>
      </Members>
      <ParentGroup>default</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">effect</Permission>
        <Permission Cooldown="120">heal</Permission>
        <Permission Cooldown="30">v</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>

Wolfboy!

**Comment by leonardosnt** [comment]
It should look something like this:

```
<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Prefix />
      <Suffix />
      <Color>white</Color>
      <Members />
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="10">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        
        <Permission Cooldown="0">essentials.kit.default</Permission> <!-- Allow to use the 'default' kit -->
        
        <Permission Cooldown="0">essentials.command.warp</Permission>
        <Permission Cooldown="0">essentials.command.warps</Permission>
        <Permission Cooldown="0">essentials.warp.idk</Permission> <!-- Allow to use the 'idk' warp. (Change to the Warp you want) -->
      </Permissions>
    </Group>
    <Group>
      <Id>vip</Id>
      <DisplayName>VIP</DisplayName>
      <Prefix>[VIP]</Prefix>
      <Suffix>[VIP]</Suffix>
      <Color>FF9900</Color>
      <Members>
        <Member>76561198016438091</Member>
      </Members>
      <ParentGroup>default</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">effect</Permission>
        <Permission Cooldown="120">heal</Permission>
        <Permission Cooldown="30">v</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>```

**Comment by leonardosnt** [comment]
Of course.
