### ISSUE TITLE
How to disable uEssentials /website command?

### ISSUE THREAD

**Issue by XanderCodes** [uEssentials/uEssentials#660]
Hello, I am using the plugin WebsiteCommands to create commands where players can get those URL popups. I have created one to display my website with /website, but it is conflicting with the link to this GitHub page. Is it possible and how would i go about disabling the uEssentials /website command in place of my own? Do I just allow the perm for the WebsiteCommands command but not the uEssentials one? or do i have to change something in the config? I also don't want to go about changing the uEssentials URL to my own, as i want players to click the button to open the link, and not have to type it.
Thanks, Xander

**Comment by leonardosnt** [comment]
Remove it from `text_commands.json`.

Before
```
[
  {
    "Name": "rules",
    "Text": [
      "<cyan>Be Respectful.",
      "<cyan>Don't use cheats.",
      "<cyan>Have fun :D"
    ]
  },
  {
    "Name": "website",
    "Text": [
      "console_exec: requesturl \"%sender%\" \"Our site\" http://google.com/"
    ]
  }
]
```

After

```
[
  {
    "Name": "rules",
    "Text": [
      "<cyan>Be Respectful.",
      "<cyan>Don't use cheats.",
      "<cyan>Have fun :D"
    ]
  }
]
```

**Comment by XanderCodes** [comment]
I have already removed it from the file, but yet it still show in-game. All i see is the rules, edited to fit my server :(

**Comment by leonardosnt** [comment]
Did you restart the server?

**Comment by XanderCodes** [comment]
It was changed a long time ago and the server has been restarted numerous times after the change
