### ISSUE TITLE
Help with kits?

### ISSUE THREAD

**Issue by Double-213** [uEssentials/uEssentials#661]
Hi! 
So i'm having a problem with giving out permissions with my kits, i have all the kits made, and each is usable by me or other admins, but i cant for the life of me figure out how to give someone permission to use a kit when they please.
i've been looking at the commands list under the permission tab bu tno matter how i put it in it always comes up invalid. 
Is there a command i have to put in a certain way like - /p kit <player> <kit> or is there some other way i have to input it? 
any help would be appreciated.
![2017-09-07 4](https://user-images.githubusercontent.com/31757144/30197532-e6f4aba0-942d-11e7-9421-e6dc2691f682.png)

**Comment by leonardosnt** [comment]
Check this: https://github.com/uEssentials/uEssentials/wiki/FAQ#why-my-users-cant-access-any-kits
