### ISSUE TITLE
 Help with text command :/

### ISSUE THREAD

**Issue by xRockAndRoll** [uEssentials/uEssentials#662]
@leonardosnt

How do I make a text command that displays my website ?

I had tried with this code that I found around here that you shared, but it does not work.

```
> {
>     "Name": "website",
>     "Text": [
>       "console_exec: requesturl \"%sender%\" \"Our site\" http://google.com/"
>     ]
>   }
> ]
```

**Comment by leonardosnt** [comment]
Post here your `text_commands.json`

**Comment by xRockAndRoll** [comment]
I was like this :/ , just have this

```
[
  {
    "Name": "fly",
    "Text": [
      "console_exec: requesturl \"%sender%\" \"Our site\" http://google.com/"
    ]
  }
]
```

**Comment by xRockAndRoll** [comment]
Look what happens when I use the in-game command on the server :(
http://prntscr.com/gj6q2z

**Comment by leonardosnt** [comment]
Change `console_exec` to `console_execute`

**Comment by xRockAndRoll** [comment]
@leonardosnt , you could add a page to uEssentials wikipedia by telling us about these customization commands that we can use in the text commands feature... ^^

as the 'console_execute' , %sender% , etc
