### ISSUE TITLE
Is there any way to do this ?

### ISSUE THREAD

**Issue by xRockAndRoll** [uEssentials/uEssentials#663]
I was thinking of doing this in uEssentials AutoCommands , but I do not think it would work at all...

AutoCommands :

`"requesturl %playerconnect% \"test.\" abc123.com.br/",`

But let it run only once , Then I thought about putting the "RunOnce" : true , however I wanted it to do this only when some player connects to the server :/

Is it possible to accomplish this with some uEssentials feature ?

**Comment by leonardosnt** [comment]
Try this: `"requesturl * \"test.\" abc123.com.br/"`

**Comment by leonardosnt** [comment]
> But let it run only once , Then I thought about putting the "RunOnce" : true , however I wanted it to do this only when some player connects to the server :/
> Is it possible to accomplish this with some uEssentials feature ?

No

If you want to request url to all players, use this: `requesturl * \"test.\" abc123.com.br/`

**Comment by xRockAndRoll** [comment]
ok , thx !
