### ISSUE TITLE
Text command does not work

### ISSUE THREAD

**Issue by xRockAndRoll** [uEssentials/uEssentials#665]
Hi , @leonardosnt 

Am I doing something wrong ? because this does not work for me at all ! :/

```
[
  {
    "Name": "addplayergroup",
    "Text": [
      "console_execute: p add %sender% example"
    ]
  }
]
```
This is the Rocket command , I'm trying to execute.
/p [add | remove] player group

**Comment by xRockAndRoll** [comment]
I just tried this method , but it also does not work.

```
{
    "Name": "addplayergroup",
    "Text": [
      "console_execute: sudo *console* p add %sender% example"
    ]
  }
```

**Comment by leonardosnt** [comment]
What is shown when you execute the command?

**Comment by xRockAndRoll** [comment]
It says that the command that was created does not exist.

I've been trying to fix a form of it since yesterday , but so far I have not been successful. :(

**Comment by leonardosnt** [comment]
Did you restart the server?

**Comment by xRockAndRoll** [comment]
Yes , you can try to do on some test server yours , it will see that it also did not work , I do not know why...

**Comment by xRockAndRoll** [comment]
Problem solved , but I do not know what I did to solve. o.o

**Comment by xRockAndRoll** [comment]
I just found out , can not have number in the command of text , only letter.
