### ISSUE TITLE
Command open Website

### ISSUE THREAD

**Issue by qeary** [uEssentials/uEssentials#667]
I would like to make my players be able to open my webshop by typing /wshop.

I found a command that works like this /requesturl, but i want them to choose when and what they want to see so like a textcommand, but idk their ways to make it open.
Also, dont forget please, i dont want one player to make every player open it, just himself.

**Comment by xRockAndRoll** [comment]
This is possible by using the uEssentials text command feature.
```
[
 {
     "Name": "wshop",
     "Text": [
       "console_execute: requesturl \"%sender%\" \"Message\" 
 Website/"
     ]
   }
]
```
