### ISSUE TITLE
/boom is not working.

### ISSUE THREAD

**Issue by xRockAndRoll** [uEssentials/uEssentials#668]
Hi , @leonardosnt 

/boom feature of uEssentials , stopped working after the Unturned update (3.20.6.0)

**Comment by DubFriendsFriendlyFriend** [comment]
@xRockAndRoll You forgot to add the error message, so I'll just leave it here...

```
[uEssentials] [ERROR] An error ocurred while executing command: 'boom '
[uEssentials] [ERROR] System.MissingMethodException: Method not found: 'SDG.Unturned.DamageTool.explode'.
  at Essentials.Commands.CommandBoom.OnExecute (ICommandSource src, ICommandArgs args) [0x00000] in <filename unknown>:0
  at Essentials.Core.Command.CommandAdapter.Execute (IRocketPlayer caller, System.String[] args) [0x00000] in <filename unknown>:0
```

**Comment by xRockAndRoll** [comment]
Yeah , thanks for that. You must help him !

**Comment by xdlewisdx** [comment]
Created a pull request to fix this, but the owner is like dead...

**Comment by xdlewisdx** [comment]
This has been fixed in the latest pull request https://github.com/uEssentials/uEssentials/pull/680
