### ISSUE TITLE
Kits and messages not working(My fault, i have no idea what to do...)

### ISSUE THREAD

**Issue by unknownguy2002** [uEssentials/uEssentials#669]
I have a problem, kits don’t cost any money and auto messages/command don’t run
my config:

https://pastebin.com/3nBCce7q

my kit:

https://pastebin.com/kmiz55bT

my perms:

https://pastebin.com/MNB5fqna

**Comment by leonardosnt** [comment]
Try this:

Open the `config.json` and change the "UseXp" from `true` to `false`
