### ISSUE TITLE
Website command not working

### ISSUE THREAD

**Issue by DubFriendsFriendlyFriend** [uEssentials/uEssentials#673]
Trying to get a /discord command to work, but it just messages the text rather than doing /requesturl like it should.

`[
  {
    "Name": "discord",
    "Text": [
      "console_exec: requesturl \"%sender%\" \"Official Server Discord\" https://discord.gg/nmprHtk"
    ]
  }
]`

**Comment by leonardosnt** [comment]
The right prefix is `console_execute` not `console_exec`
