### ISSUE TITLE
Question about Auto Commands

### ISSUE THREAD

**Issue by qeary** [uEssentials/uEssentials#674]
Hello! How can i run /day and /rocket reload with auto commands?
If i run /rocket reload with autocommands won't it bug itself and run always i do /rocket reload?

  "AutoCommands": {
    "Commands": [
      {
        "RunOnce": false,
        "Timer": 120,
        "Commands": [
          "say \"Be sure to drink your Ovaltine!\" 0 255 255",
          "item * glue"
        ]
      },
      {
        "RunOnce": false,
        "Timer": 900,
        "Commands": [
          "clear v",
          "respawnvehicles"
        ]
      }
    ],
    "Enabled": false
  },

**Comment by leonardosnt** [comment]
> Hello! How can i run /day and /rocket reload with auto commands?

First you should change the `Enabled` property to `true`, then add the commands you want to the `Command` list.
It should looks like this:
```json
"AutoCommands": {
  "Commands": [
    {
      "RunOnce": false,
      "Timer": 1200,
      "Commands": [
        "rocket reload"
      ]
    },
    {
      "RunOnce": false,
      "Timer": 900,
      "Commands": [
        "day"
      ]
    }
  ],
  "Enabled": true
},
```

> If i run /rocket reload with autocommands won't it bug itself and run always i do /rocket reload?  

I don't think so. It will only run when the __timer__ is over.

**Comment by qeary** [comment]
Does the timer start when the plugin start to run? So like i restart my server and the plugin autocommand will run itself or just later like 1200 seconds more?

**Comment by leonardosnt** [comment]
Just later.
