### ISSUE TITLE
How can i make custom command ?

### ISSUE THREAD

**Issue by alp2423** [uEssentials/uEssentials#681]
İ want to create new command like this

when player write this: "/adminsteam" .

I want the code to work:
 /requesturl {player?}(i do not know what to write here) "mymessage" "www.steamprofile.com"

i dont know how can i do this.  sorry for bad english i really dont know.

**Comment by leonardosnt** [comment]
See https://github.com/uEssentials/uEssentials/issues/667#issuecomment-330669804
