### ISSUE TITLE
After restart server not working

### ISSUE THREAD

**Issue by iBowie** [uEssentials/uEssentials#682]
After planned restart, players can't join server, they have loading screen with game sounds and all game controls, but they don't see anything. No exceptions in console/logs.

**Comment by iBowie** [comment]
And if i remove uEssentials, all work good!

**Comment by persiafighter** [comment]
Hello @iBowie,

Could you please post the logs rocket produces? Or tell us if there are any errors in console? This is too broad or not specific enough for us to identify the exact issue.
