### ISSUE TITLE
Kits permissions aren't working.

### ISSUE THREAD

**Issue by Lt-Bellamy** [uEssentials/uEssentials#684]
Hey i was wondering if someone could help me, my kit permissions aren't working, i've played around with the coding to check if I made an error in typing it out or if i wasnt typing the right thing but it should be,

<Permission Cooldown="0">essentials.command.kit</Permission>
<Permission Cooldown="0">essentials.command.kit.default</Permission>

If you could tell me if that's correct or not that'd be of great help,
Thanks.

**Comment by persiafighter** [comment]
Hello @Lt-Bellamy,
Your permission for the `/kit` command is correct, however it is not for the default kit nor for the `/kits` command (as `/kits` is not even there, but it's not necessary to get the kit, only to know).

As stated in the permission reference wiki (https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference) a permission for a specific kit is `essentials.kit.<kit_name>`, so for you the permission should be `essentials.kit.default`.

Hope this solves your issue.

**Comment by Lt-Bellamy** [comment]
Ah right so you're meant to write it without the Commands addition, and that was just a small sample as what i wrote sorry, I just wanted to give an example as to what I wrote to see if it was correct. Thanks again.

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/FAQ#why-my-users-cant-access-any-kits
