### ISSUE TITLE
Kits Permission Not Working At All

### ISSUE THREAD

**Issue by RageYT** [uEssentials/uEssentials#688]
So, I've set up all my permissions for my kits and what not but it says that the default or group that has the correct permissions doesn't have access to any kit.  The permission node I'm using is `essentials.commands.kit.<kitname>`. Even though I used that and some other permission nodes, nothing still yet works. I am so frustrated at this as I really enjoy using uEssentials kit system but the permission doesn't work for it. Someone mind helping me?

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/FAQ#why-my-users-cant-access-any-kits

**Comment by dakr80** [comment]
Thx
