### ISSUE TITLE
Kits permissions 

### ISSUE THREAD

**Issue by trollsplaymc** [uEssentials/uEssentials#69]
go to to the rocket permissions folder and put kit default for a command then put `<CommandMapping Name="kit default" Enabled="true">essentials.kit.default</CommandMapping>` in the command mapping but when i type /kit default  in game it says i have no permissions Help!!! Thanks in advanced.

**Comment by leonardosnt** [comment]
#67

**Comment by WGSRangerWolf** [comment]
/utn/Servers/woof/Rocket/permissions.xml
insert what i have on #67  and kits should work. Change the names tho
