### ISSUE TITLE
Permissions not working

### ISSUE THREAD

**Issue by ChooleyChee** [uEssentials/uEssentials#690]
Hello. So im new to starting a server and when ever players type in /warp safezone it says they dont have access. then i added the command essentials.command.warp to the permissions and when they typed /warp safezone it said "you dont have access to this warp!" so i tried a bunch of stuff...
essentials.command.warp.safezone
essentials.command.warp safezone
essentials.command.warp_safezone
essentials.command.warp-safezone

what am i doing wrong? If you would like to join my RP/PVP join here!  192.154.228.121:27020

**Comment by leonardosnt** [comment]
The right permission is `essentials.warp.<warp_name>`, not `essentials.command.warp.<warp_name>`.

Please, check the https://github.com/uEssentials/uEssentials/wiki

**Comment by ChooleyChee** [comment]
I tried that and it didn’t work what do I do? I typed essentials.warp.safezone

**Comment by leonardosnt** [comment]
Let me see your permissions
