### ISSUE TITLE
Persisting permissions problem

### ISSUE THREAD

**Issue by Lt-Bellamy** [uEssentials/uEssentials#694]
Hey how y'all doing, 
Started an Unturned server a while back and the permissions didn't work but I shut it down so I didn't need the issue resolved, but I've decided to pick up where I left off and I require help again. 
Here is a sample of my permissions for the default group:
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Prefix />
      <Suffix />
      <Color>FFFFFF</Color>
      <Members />
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">essentials.command.warp</Permission>
        <Permission Cooldown="0">essentials.command.warp.*</Permission>
        <Permission Cooldown="0">essentials.command.warps</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">jobs</Permission>
        <Permission Cooldown="0">joinjob</Permission>
        <Permission Cooldown="0">leavejob</Permission>
        <Permission Cooldown="0">acceptjob</Permission>
        <Permission Cooldown="0">essentials.kit</Permission>
        <Permission Cooldown="0">essentials.kits</Permission>
        <Permission Cooldown="0">essentials.kit.Survival</Permission>
        <Permission Cooldown="0">essentials.kit.Xp</Permission>
        <Permission Cooldown="0">tpa</Permission>
        <Permission Cooldown="0">home</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
      </Permissions>
    </Group>

**Comment by Lt-Bellamy** [comment]
If anyone could give me a hand that'd be much appreciated.
Cheers.

**Comment by leonardosnt** [comment]
The right permission is `essentials.warp.[warp name]` not `essentials.command.warp.[warp name]`

See https://github.com/uEssentials/uEssentials/wiki

**Comment by Lt-Bellamy** [comment]
My problem isn't with the warp commands, my kit permissions aren't working sorry should've been more specific

**Comment by leonardosnt** [comment]
This is wrong:
```
essentials.kit
essentials.kits
```
it should be
```
essentials.command.kit
essentials.command.kits
```

See https://github.com/uEssentials/uEssentials/wiki/FAQ
