### ISSUE TITLE
Permissions not working

### ISSUE THREAD

**Issue by SpectreNuke** [uEssentials/uEssentials#695]
So I was setting up the guest permissions, and its just not working. I swear i have it all correct. Its also got CRLF next to the stuff on Notepad++. I dont understand why its not working.
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Prefix />
      <Suffix />
      <Color>white</Color>
      <Members />
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">discord</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.home</Permission>
        <Permission Cooldown="10">essentials.kit.Starter</Permission>
        <Permission Cooldown="10">essentials.kit.Rifle</Permission>
        <Permission Cooldown="1440">essentials.kit.Daily Car</Permission>
        <Permission Cooldown="10">essentials.kit.xp</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
      </Permissions>
    </Group>

**Comment by leonardosnt** [comment]
What exactly isn't working?

**Comment by SpectreNuke** [comment]
Its not allowing the guests to do the commands @leonardosnt

**Comment by leonardosnt** [comment]
What commands? kit and warp?

Did you reload the permissions?

**Comment by Ecxdirerr** [comment]
is this issue still persistant?
