### ISSUE TITLE
Permissions problems

### ISSUE THREAD

**Issue by Lt-Bellamy** [uEssentials/uEssentials#696]
Sorry I wasn't specific enough, my kits aren't working and i was wondering if it was because of the code. 
Cheers.

default
Guest

FFFFFF

100

p
essentials.warp
essentials.warp.*
essentials.warps
compass
rocket
jobs
joinjob
leavejob
acceptjob
essentials.kit
essentials.kits
essentials.kit.Survival
essentials.kit.Xp
tpa
home
essentials.command.tpa
essentials.command.tpa.send
essentials.command.tpa.accept
essentials.command.tpa.deny
essentials.command.tpa.cancel

**Comment by Lt-Bellamy** [comment]
Also I don't know if it matters but I'm using USO to host my server

**Comment by persiafighter** [comment]
Your permissions are incorrect for the players to use the kit and kits command. Review https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference again.

**Comment by Lt-Bellamy** [comment]
Oh so i need to actually type the <kit_name> in. like kit survival would be 
essentials.kit.<Survival>

**Comment by Lt-Bellamy** [comment]
Cause i just tried that and my rocket just kinda flip flopped. like died.

**Comment by Lt-Bellamy** [comment]
or is it like 
essentials.kit.<kit_survival>

**Comment by persiafighter** [comment]
Like essentials.kit.survival (because <kit_name> here is an ENTIRE VARIABLE, so you replace it entirely. The <> are used in this text on purpose to show you it's a variable and you should replace it that entirely)

**Comment by Lt-Bellamy** [comment]
then how is essentials.kit.Survival wrong?

**Comment by persiafighter** [comment]
It's not, it's that you forgot a permission for the /kit command and for the /kits command. I gave you a link for the permission reference, and the permissions you posted at the original post don't have the ones for /kit command and /kits command (essentials.command.kit and essentials.command.kits).

**Comment by Lt-Bellamy** [comment]
Oh sorry, when i posted the above exert with the essentials.command.kit one of the commenters said it was wrong and to check the permissions reference

**Comment by Lt-Bellamy** [comment]
omg I just tried having both sets of variables and IT WORKS!
Thankyou so much persia you are a god!
