### ISSUE TITLE
I wanna do a command like /discord

### ISSUE THREAD

**Issue by Slowyo** [uEssentials/uEssentials#697]
And it should pop up middle of the screen where u can press "open or close"

HOW?

**Comment by leonardosnt** [comment]
You must add this to the file **text_commands.json**
```json
  {
      "Name":"discord",
      "Text":[
         "console_execute: requesturl \"%sender%\" [message] [url]"
      ]
   }
```

replace **[message]** with the message you would like to appear in the popup.
replace **[url]** with the link to your discord

make sure the contents of **text_commands.json** are valid (use this website to validate: jsonschemavalidator.net)
then restart your server
