### ISSUE TITLE
Help with custom command.

### ISSUE THREAD

**Issue by rwalkos** [uEssentials/uEssentials#698]
I would like people to be able to type /ride and it spawn a specific vehicle with a cool down.

I have a kit made with  the vehicle I want to spawn and the cooldown I want with a reset after death.

I have tried:
```
{
    "Name": "ride",
    "Text": [
	"console_execute: sudo \"%sender%\" \"/kit car"
    ]
  }
```
And in the console it shows:
```
UserName ran the command '/kit car'

But it doesn't actually work.

**Comment by Ecxdirerr** [comment]
Why not use kits? check documentation

**Comment by rwalkos** [comment]
I already have the kit made for it and permissions set, /kit car works as I want it to. I just wanted it easier through the use of /ride.

**Comment by leonardosnt** [comment]
try this
`"console_execute: sudo \"%sender%\" /kit car"`
or 
`"console_execute: sudo \"%sender%\" \"/kit car\""`

**Comment by rwalkos** [comment]
Thank you.
