### ISSUE TITLE
It keep saying kit does not exist

### ISSUE THREAD

**Issue by jorea143** [uEssentials/uEssentials#7]
I setup a kit to test at least the kit part of this plugin but it seems it does not work. When I do /kits, it says I have a kit. Then when I do /kit name, it keep saying it does not exist. No errors in console--FYI, and it says I have 1 kit.

**Comment by jorea143** [comment]
Oh, it doesn't even reload like the other report said.

**Comment by leonardosnt** [comment]
I will check it

**Comment by leonardosnt** [comment]
Here it is working fine

You need to restart your server after you edit kits.

**Comment by jorea143** [comment]
oh it might be the changes I made for kits. Am i supposed to follow the wiki on how to add weapon attachment, and weapons to kits?  It would save me less time if I don't have to specify all those details like fire mode, attachment types, etc. Durability is okay since it might actually help in the future. Other details seems irrelevant especially if I just want to copy my kits config from other kit plugin.

**Comment by jorea143** [comment]
Oh so I can't edit kits on the fly? Will it be like that permanently or are you working on to fix the loading error?

**Comment by leonardosnt** [comment]
What loading error??

**Comment by jorea143** [comment]
Sorry it is more like reloading error. 

[Error] Failed to unload uEssentials:System.NullReferenceException: Object reference not set to an instance of an object
  at Essentials.Core.EssCore.Unload () [0x00000] in <filename unknown>:0 
  at Rocket.Core.Plugins.RocketPlugin.UnloadPlugin (PluginState state) [0x00000] in <filename unknown>:0 
  at Rocket.Core.Plugins.RocketPlugin.LoadPlugin () [0x00000] in <filename unknown>:0

**Comment by leonardosnt** [comment]
Don't reload!! Just restart the server.

I will add an command to reload the kits, and so on...

**Comment by jorea143** [comment]
Yeah I learn that the hard way. I was asking if you are gonna add reload or fix it if it is already implemented. It seems like you have a "todo list" about it added yesterday. I will wait for that.

About the previous question I have. Do i have to follow this:

 "Sight": {
          "AttachmentId": 146,
          "Durability": 100
}

just to add an attachment item in a kit? And there's this:

"FireMode": "AUTO",    // The valid firemodes are: AUTO, SAFETY & SEMI
        "Ammo": 30,
        "Id": 4,
        "Durability": 100,
        "Amount": 1
      }

I am not sure why do I need to specify firemode and ammo just to spawn the items. It is nice to have these details but for me who has kits configured for another kit plugin and I just want to transfer those config to your plugin, it's seems unnecessary. So my question is, are those syntax necessary or is it just an option and I can just use this instead:

{
        "Id": 4,
        "Durability": 100,
        "Amount": 1
      },

**Comment by leonardosnt** [comment]
@jorea143 Firemode, ammo, attachments and so on is for "weapons" and is optional, you don't need to add if you dont need it.

Normal items have only "Id", "Durability" and "Amount"

**Comment by jorea143** [comment]
Great. Awesome work, great help. Thank you so much. I will wait for that reload command, then I will use the plugin. I tend to edit things on fly.

Thank you again for the help.

**Comment by leonardosnt** [comment]
i'm working on it now.
