### ISSUE TITLE
Ranger Wolfs Idea's Archive

### ISSUE THREAD

**Issue by WGSRangerWolf** [uEssentials/uEssentials#70]
Allow players with permissions to start votes and other players on the server to vote yes for it.  Players that want to vote no can simply ignore the vote.  Players can only vote once and only have a certain amount of time to vote before voting closes.  After a successful or unsuccessful vote, there is a cool down time before it can be called again.  If the percent of players voting yes equals or exceeds the configurable successful vote amount, then the vote passes.
callvote day
callvote night
callvote vehicleall
callvote item <id><N#>
Offline bans which can be logged into a .log file and whatever id is on there they are banned.
Jail command. Can be configured to a cell number 1 2 3 4 5 6 and so on.
Wrecking ball removes items with a set filter list. Will delete all buildings within the area.

**Comment by axiomaticTwist** [comment]
Callvotes are already a separate plugin on dev.rocketmod.net

**Comment by WGSRangerWolf** [comment]
Yes i know :+1:
