### ISSUE TITLE
The way text work needs updated.

### ISSUE THREAD

**Issue by rwalkos** [uEssentials/uEssentials#701]
https://github.com/RocketMod/Rocket.Unturned/commit/5f6671cb1dfbf5f29007caec49dac0efa7f07a61

**Comment by leonardosnt** [comment]
Why? I don't see any breaking changes. 

uEssentials 1.3.4.0 works fine with latest Rocket build.

**Comment by rwalkos** [comment]
Nevermind, thanks for looking into this. I just compiled and updated rocket myself with the fix. And uEssentials chat does indeed work just fine now. Sorry to of bothered you.
