### ISSUE TITLE
passive ability + command cooldown save not working

### ISSUE THREAD

**Issue by lvlbgn** [uEssentials/uEssentials#707]
Hello!
As you are an active, good plugin creator, i would like to report you the 2 new bug.
It's me, the one who reported you the missing text_command config.

1. I was using keep maxskills all passive ability by permissions on my arena server by your plugin.
So, after your update, it's broken.
PPL are losing the maxskills at every single time they die, and need to write /maxskills again, which is useless, annoying move.

> 

essentials.keepskill.all.<%> | Keep <percentage> of all skills, when player die.
-- | --

> 

This is what i talk about, so for me it's "essentials.keepskill.all.100" and won't work.
I tested it in many ways, to make sure if it's the plugin, yes.

2. I was using your /v, so "essentials.command.vehicles" and added the cooldown in command-config which is created by your plugin, so i did it the same way as before your update, and now it's also broken.
The cooldown won't be on the command, so they can keep spaming /v.

3. in uessentials CONFIG, there is something called "savecommandcooldowns" so what is that for?
It's to save cooldowns at server restart? If yes, won't work, even it doesn't work at all, restart or no.

These are important bugs, please take care about them if you can as soon as possible.
Thank you.

**Comment by leonardosnt** [comment]
Fixed 1 and 2.

About the SaveCommandCooldowns: I saw that the SaveCommandCooldowns option is not being used anywhere. I'm not sure if I forgot to implement it or I removed it accidentally. I need to figure out.

**Comment by lvlbgn** [comment]
How can i get the fixed version of Uessential? I don't see u uploaded it yet.

About savecommandcooldown, well, idk who didnt want to use, but it would be really useful to have the cooldowns saved after a server restart.

**Comment by leonardosnt** [comment]
Here: https://github.com/uEssentials/Builds/releases

**Comment by lvlbgn** [comment]
oke
so, maxskills now stay, so its good
/v command also will stay on cooldown
BUT seeing this error:
![errorwhenfirstv](https://user-images.githubusercontent.com/37576886/37856858-17028538-2ef7-11e8-8ec0-dfeebfd2a19d.PNG)

this error is somewhy can't be seen in ROCKETLOG
but i see it in the server's console
it happens for the FIRST command using.


and this is what the player saw ingame:
![ingame](https://user-images.githubusercontent.com/37576886/37856902-64065f12-2ef7-11e8-8348-a249168052a2.jpg)
spawned the ghost and got the error message by first /v 123
then for second time using it, it will show the cooldown.

so what i report, it's the error.


Also, would u gimme some details about savecommandscooldown ? Will you remove it? or add it back? Could u figure it out? It would be really useful!

**Comment by leonardosnt** [comment]
I'll take a look tomorrow.

> Also, would u gimme some details about savecommandscooldown ? Will you remove it? or add it back? Could u figure it out? It would be really useful!

I think I'll have to implement it.

**Comment by lvlbgn** [comment]
If you want, we can continue talking on Discord or somewhere else tomorrow, so i can easier report any bugs to you, and you can react anytime, i wouldn't disturb you, if you are busy.
But i probably will have another things to report.
If you say yes, you simply can answer here your discord#tag so i get email, then just remove ur comment so others wont see it.

Plus i could remind you tomorrow to take a look at it, etc, just asking.
Thanks for fast answers btw.

**Comment by lvlbgn** [comment]
Or, just add me if you want to! :)
awedy#6312

**Comment by lvlbgn** [comment]
Sorry for reposting
The error i reported to you causing error for ALL commands that we give cooldown for, so like /tpa, /home aswell

**Comment by leonardosnt** [comment]
The first issue is a compatibility issue with AviEconomy. 
Can you link the AviEconomy download you are using?

**Comment by lvlbgn** [comment]
https://imperialplugins.com/Products/ProductDetails?ProductID=64
this is it.
and note, as i mentioned it happens only with the commands that i put on cooldown in commands settings xml
