### ISSUE TITLE
/pm /r bug

### ISSUE THREAD

**Issue by lvlbgn** [uEssentials/uEssentials#708]
Hello.
But i would like to report to you an extra bug.
This bug is here since i just use ur plugin, so for a half year and still not fixed, prob noone reported it cuz it's not that important, but annoying.

So, the bug is with /pm and /r (which would reply to the one that last sent you a pm)
Details:
If someone do /pm leonard hello, then if you do /r hello it will say, you have noone to reply to if you didn't use it since you are logged in, or is no longer online if you did it to a guy already but logged off, OR you will be able to REPLY but to the guy before the last one sent you pm.

So shortly, it won't work as it shall work in my opinion.
IDK when the plugin catches the guy who you shall be able to reply, but it let u reply to the guy who sent you pm and you sent him pm aswell with /pm

![image](https://user-images.githubusercontent.com/37576886/38163110-a5d70192-34ee-11e8-90f9-1d8379395492.png)

On this picture, Jayce sent him pm, and the sender sent jayce pm, but as you see an other guy sent pm to him and then he used /r hi, but replied to the one before, and not to the LAST one who sent him pm.

**Comment by leonardosnt** [comment]
I would really appreciate if you could test it with another player. It's hard to test a command that needs multiple players if you are alone.

**Comment by lvlbgn** [comment]
Tested it with 4 guys, all works, good job.

**Comment by leonardosnt** [comment]
Thanks!!
