### ISSUE TITLE
uEssentials ignores permissions?

### ISSUE THREAD

**Issue by Aaron2550** [uEssentials/uEssentials#709]
New players joining the Server cant use /tpa, they get the "No permission"-Error but /kit works...(See config below)
We tried everything even running it through a .xml validator... Server logs dont state anything.

http://prntscr.com/j2ag3h

**Comment by leonardosnt** [comment]
you forgot the `essentials.command.tpa`

https://github.com/uEssentials/uEssentials/wiki
https://github.com/uEssentials/uEssentials/wiki/Command-Reference#tpa

**Comment by Aaron2550** [comment]
Oh mah lorrrrrd, beginner error, SORRY xd
