### ISSUE TITLE
Aliases

### ISSUE THREAD

**Issue by lvlbgn** [uEssentials/uEssentials#711]
Hello!
I saw examples in commands config but i don't really understand so i would like to ask:
1. Can i do alias from a command from other plugin?
Like if i have a plugin with /sell, can UEssential make it for ppl usable like /storetobank or something?

2. If possible, would you give me an example with the commands i told above?

Thanks.

**Comment by leonardosnt** [comment]
No. The `command_options` (used to create aliases) only works with commands from uEssentials
