### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by ColdAF** [uEssentials/uEssentials#712]
So bassically I am setting up a Rp server in unturned. It was all going great made all the kits, warps e.t.c. but then I had to do the permissions. So I did, after I finished them I saved everything added the file.
When I restarted the server 
1. When I do /kits or any other plugin it does not work
2. It does not even say "Command not found" it just does not work
3. On the server page in unturned where it shows the plugins it shows that Uessentials is installed

Please help if you can

**Comment by ColdAF** [comment]
I made sure to not mess up the Permissions file this time, still not working

**Comment by leonardosnt** [comment]
did you see any error in the console?
