### ISSUE TITLE
Command's options do not work

### ISSUE THREAD

**Issue by SdwStorm** [uEssentials/uEssentials#715]
Hi. I got a problem with command options. I configure commands in file "command_option.json". Such options as cost and cooldown. But it dont work. Im using commands without cooldown and cost. Can you check it?

**Comment by leonardosnt** [comment]
If you are admin you will bypass (ignore) costs and cooldown by default. Try with the default group.

**Comment by SdwStorm** [comment]
I know it. Of course i tried with the default group. I didnt find anything can give me bypass then i created a new steam account, tried and still no cooldown/cost.

**Comment by leonardosnt** [comment]
Are you restarting the server, right? Did you see any errors in the console?

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/Builds/releases
