### ISSUE TITLE
looks like the new update broke everything (again)

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#717]
![image](https://user-images.githubusercontent.com/1404955/40565531-a11b7086-6075-11e8-822f-915cbad6e104.png)
When someone joins/disconnects.
Possibly related to the last commit on the Rocket.Unturned repo (?).

**Comment by Daniil1288** [comment]
![image](https://user-images.githubusercontent.com/1404955/40566056-a76bd10e-6077-11e8-995f-e971ab1244dd.png)
Also this.

**Comment by DronXa** [comment]
I can confirm this!

**Comment by leonardosnt** [comment]
Can you try with the latest build please: https://github.com/uEssentials/Builds/releases ?

I updated Rocket and used the latest uEssentials build and it fixed the issue.

**Comment by Daniil1288** [comment]
@leonardosnt, the error still persists. Here's the full text of it:
![image](https://user-images.githubusercontent.com/1404955/40584743-06080b5a-61af-11e8-92a6-af50c8ec44f3.png)

**Comment by Daniil1288** [comment]
hey @DronXa, is the issue still there for you?

**Comment by leonardosnt** [comment]
Are you running the server on Linux?

This is a REALLY weird error message. Are you using the default translation file or a custom one?
![](https://i.imgur.com/8cO53Ox.png)



Seems to be working fine here. (Windows 10)
![](https://i.imgur.com/cn0TYPB.png)

**Comment by Daniil1288** [comment]
@leonardosnt, running my server on windows, using a custom translation file (for uEssentials), here's yet another screenshot
![image](https://user-images.githubusercontent.com/1404955/40860911-b83c3122-65ef-11e8-80cb-01be84873455.png)

**Comment by leonardosnt** [comment]
@Daniil1288 Please, comment here the contents of your **config.json**, or just the **AutoAnnouncer** stuff if you prefer.

**Comment by Daniil1288** [comment]
Figured it out, the problem wasn't in uEssentials.
