### ISSUE TITLE
fix command broken with last update

### ISSUE THREAD

**Issue by NoAdO** [uEssentials/uEssentials#725]
```
[World] Царь [PUVEL]: "/fix"
An error ocurred while executing command: 'fix '
Object reference not set to an instance of an object
Broadcast: varkravt покромсали на куски!
```

**Comment by leonardosnt** [comment]
> Also ess reload and ess reload config don't reload config..

It just reload some settings, not all. Try to use `/rocket reload` or just restart the server.

**Comment by Ferom2** [comment]
Also, the /boom command does not work

**Comment by leonardosnt** [comment]
It's working in the latest build.
