### ISSUE TITLE
need help with disabling certain features 

### ISSUE THREAD

**Issue by ServerOne** [uEssentials/uEssentials#729]
how would I disable TPA and the WARPS plugins please?

**Comment by leonardosnt** [comment]
open config.json
remove "Warps" from "EnabledSystems"
add "tpa" to "DisabledCommands"

e.g
```
  "EnabledSystems": [
    "kits"
  ],
  "DisabledCommands": [ "tpa" ],
```

https://github.com/uEssentials/uEssentials/wiki/Configuration
