### ISSUE TITLE
Modded IDs in kits break if WorkshopDownloadIds.json is used.

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#730]
I've been meaning to report this issue for ages.
After booting up a server with mods:
![image](https://user-images.githubusercontent.com/1404955/43685096-50373bb4-98b5-11e8-965a-8a23afdd427a.png)
![image](https://user-images.githubusercontent.com/1404955/43685105-6c8a2ce0-98b5-11e8-8af8-289b3d9a01ba.png)
All modded IDs are removed from kits.json.
After copying over a saved backup of kits.json and doing /ess reload (/rocket reload won't work):
![image](https://user-images.githubusercontent.com/1404955/43685163-6ce66d38-98b6-11e8-8b89-e51395a34e4f.png)
This issue probably comes from the fact that uEssentials checks for modded IDs before they're downloaded:
![image](https://user-images.githubusercontent.com/1404955/43685176-bdaaf464-98b6-11e8-8302-989d01fc0053.png)
Can this be fixed?

**Comment by leonardosnt** [comment]
Can you upload your `WorkshopDownloadIds.json` file here? I need to test it here.

**Comment by Daniil1288** [comment]
@leonardosnt, sure: 
[WorkshopDownloadIDs.zip](https://github.com/uEssentials/uEssentials/files/2281341/WorkshopDownloadIDs.zip)

**Comment by leonardosnt** [comment]
It seems to be working here. You can try with the latest build -> https://github.com/uEssentials/Builds/releases/tag/build-87a0642
