### ISSUE TITLE
Uessentials commands not loading in my server, HELP!

### ISSUE THREAD

**Issue by Lecheloaner** [uEssentials/uEssentials#731]
i've followed the guide on how t install Uessentials but when i turn on my server it doesnt load any of the commands. Lecheloaner #7607 for screenshots.

**Comment by leonardosnt** [comment]
Please, upload the screenshots here.

**Comment by Lecheloaner** [comment]
Thank you, but i already resolved it. I just made a new server because i
didnt want to wait. I installed Uessentials and it worked fine. Thanks
again.
