### ISSUE TITLE
Kits breaking

### ISSUE THREAD

**Issue by ImJustJamie** [uEssentials/uEssentials#735]
Title says it all, I noticed a few days ago that the kits were broken, so I went and remade all of them, just to find out that after making the i /saved and then restarted the server, type and tested all the kits and it turns out that they broke upon the server restart, Anyone able to help me with this issue thanks.

**Comment by ImJustJamie** [comment]
I think i found the issue

**Comment by Daniil1288** [comment]
@ImJustJamie, you should post the solution in case someone else has this problem, you know :P
