### ISSUE TITLE
Modded items Wont work in my kits???

### ISSUE THREAD

**Issue by Marshall0703** [uEssentials/uEssentials#736]
My Uessentials on the server i am working for the modded items wont spawn in when u redeem a kit but it only happens after a restart. Can anyone Help?

**Comment by Marshall0703** [comment]
It doesnt Give me any errors it justs deletes its

**Comment by griffindor301** [comment]
I have this same error does anyone know how to fix it?

**Comment by Kr4ken-9** [comment]
Hello, this issue should be fixed in the latest release which you can find here: https://github.com/uEssentials/Builds/releases

You can test it for yourself and close this issue once you have confirmed it is working.
