### ISSUE TITLE
Kits Not Working

### ISSUE THREAD

**Issue by xxJBoyxx** [uEssentials/uEssentials#738]
Hello , Why are the kits not working ? 
![permissions](https://user-images.githubusercontent.com/43218033/45446326-7eae5680-b6c4-11e8-991d-d629b21cc0c5.PNG)

These are the permissions , I don't see what is wrong with them. Please help.

**Comment by leonardosnt** [comment]
What happens when you execute: `/kits` ? Does it show `civilian` in the `Available kits`?

**Comment by TheMatrixAgent** [comment]
The permission of a kit is essentials.command.kit.[kit_name]

**Comment by TheMatrixAgent** [comment]
Altho I am having a problem, I am using the perms correctly, but I still have no access... I'll try to fix it.

**Comment by leonardosnt** [comment]
@TheMatrixAgent Actually, it's `essentials.kit.[kit_name]`

https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference
