### ISSUE TITLE
Kit Permissions

### ISSUE THREAD

**Issue by LiamMoroney** [uEssentials/uEssentials#745]
I can’t get my kits to work it says I have permission to kit whe I do /kits and I’m in guest group but when I do /kit Survior it doesn’t work this is my permission files https://pastebin.com/AsPdGJiK

**Comment by Ferom2** [comment]
Add <Permission Cooldown="0">essentials.kit</Permission> and it will be work

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference
