### ISSUE TITLE
/repair doesn't work

### ISSUE THREAD

**Issue by yoyoyogurt** [uEssentials/uEssentials#746]
when i use /repair is gives this error:
[uEssentials] [ERROR] An error ocurred while executing command: 'repair '
[uEssentials] [ERROR] Object reference not set to an instance of an object

**Comment by matthew57778** [comment]
Same thing as me except "An error occurred while executing this command. Please contact and admin!"

**Comment by shad6030** [comment]
same

**Comment by ZSHADOWWOLF** [comment]
Yup same problem

**Comment by Kr4ken-9** [comment]
Hello, this issue should be fixed in the latest release which you can find here: https://github.com/uEssentials/Builds/releases

You can test it for yourself and close this issue once you have confirmed it is working.
