### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by yawbanana** [uEssentials/uEssentials#75]
hey my brother, could u make in-game Private Message sent's notification

**Comment by leonardosnt** [comment]
what does it do exactly?

**Comment by WGSRangerWolf** [comment]
an enhancement to tell command. instead of it Saying nothing when u use the command, it will tell ya. You told "message" to "person"

**Comment by leonardosnt** [comment]
:+1:

**Comment by leonardosnt** [comment]
Added :D

If you like this project do not forget to leave your star :D
