### ISSUE TITLE
Death message cannot be translated

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [uEssentials/uEssentials#751]
Plugin not use Russian translate + sometimes i see this errors

General: Exception raised when RPC invoked tellChat:
NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.ChatManager.receiveChatMessage (Steamworks.CSteamID speakerSteamID, System.String iconURL, SDG.Unturned.EChatMode mode, UnityEngine.Color color, System.Boolean isRich, System.String text) (at <38f41fa4578a47189a8f270b9543a27c>:0)
SDG.Unturned.ChatManager.tellChat (Steamworks.CSteamID steamID, Steamworks.CSteamID owner, System.String iconURL, System.Byte mode, UnityEngine.Color color, System.Boolean rich, System.String text) (at <38f41fa4578a47189a8f270b9543a27c>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <cfc149f8218b496788d8493c87de777a>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <cfc149f8218b496788d8493c87de777a>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <cfc149f8218b496788d8493c87de777a>:0)
SDG.Unturned.SteamChannel.receive (Steamworks.CSteamID steamID, System.Byte[] packet, System.Int32 offset, System.Int32 size) (at <38f41fa4578a47189a8f270b9543a27c>:0)
UnityEngine.Debug:LogException(Exception)
SDG.Unturned.SteamChannel:receive(CSteamID, Byte[], Int32, Int32)
SDG.Unturned.SteamChannel:send(String, CSteamID, ESteamPacket, Object[])
Rocket.Unturned.Chat.UnturnedChat:Say(CSteamID, String, Color, Boolean)
Rocket.Unturned.Chat.UnturnedChat:Say(CSteamID, String, Boolean)
Rocket.Unturned.Chat.UnturnedChat:Say(CSteamID, String)
Uconomy_Essentials.PlayerUE:rpe_OnPlayerDeath(UnturnedPlayer, EDeathCause, ELimb, CSteamID)
System.Delegate:DynamicInvoke(Object[])
Rocket.Core.Extensions.MulticastDelegateExtension:TryInvoke(MulticastDelegate, Object[])
Rocket.Unturned.Events.UnturnedPlayerEvents:TriggerSend(SteamPlayer, String, ESteamCall, ESteamPacket, Object[])
Rocket.Unturned.U:<bindDelegates>m__7(SteamPlayer, String, ESteamCall, ESteamPacket, Object[])
SDG.Unturned.SteamChannel:send(String, ESteamCall, ESteamPacket, Object[])
SDG.Unturned.PlayerLife:doDamage(Byte, Vector3, EDeathCause, ELimb, CSteamID, EPlayerKill&, Boolean, ERagdollEffect)
SDG.Unturned.PlayerLife:askDamage(Byte, Vector3, EDeathCause, ELimb, CSteamID, EPlayerKill&, Boolean, ERagdollEffect)
SDG.Unturned.PlayerLife:askDamage(Byte, Vector3, EDeathCause, ELimb, CSteamID, EPlayerKill&)
SDG.Unturned.PlayerLife:simulate(UInt32)
SDG.Unturned.PlayerInput:FixedUpdate()

General: Exception raised when RPC invoked tellChat:
NullReferenceException: Object reference not set to an instance of an object - SDG.Unturned.ChatManager.receiveChatMessage (Steamworks.CSteamID speakerSteamID, System.String iconURL, SDG.Unturned.EChatMode mode, UnityEngine.Color color, System.Boolean isRich, System.String text) (at <38f41fa4578a47189a8f270b9543a27c>:0)
SDG.Unturned.ChatManager.tellChat (Steamworks.CSteamID steamID, Steamworks.CSteamID owner, System.String iconURL, System.Byte mode, UnityEngine.Color color, System.Boolean rich, System.String text) (at <38f41fa4578a47189a8f270b9543a27c>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <cfc149f8218b496788d8493c87de777a>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <cfc149f8218b496788d8493c87de777a>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <cfc149f8218b496788d8493c87de777a>:0)
SDG.Unturned.SteamChannel.receive (Steamworks.CSteamID steamID, System.Byte[] packet, System.Int32 offset, System.Int32 size) (at <38f41fa4578a47189a8f270b9543a27c>:0)
UnityEngine.Debug:LogException(Exception)
SDG.Unturned.SteamChannel:receive(CSteamID, Byte[], Int32, Int32)
SDG.Unturned.SteamChannel:send(String, CSteamID, ESteamPacket, Object[])
Rocket.Unturned.Chat.UnturnedChat:Say(CSteamID, String, Color, Boolean)
Rocket.Unturned.Chat.UnturnedChat:Say(CSteamID, String, Boolean)
Rocket.Unturned.Chat.UnturnedChat:Say(CSteamID, String)
Uconomy_Essentials.PlayerUE:rpe_OnPlayerDeath(UnturnedPlayer, EDeathCause, ELimb, CSteamID)
System.Delegate:DynamicInvoke(Object[])
Rocket.Core.Extensions.MulticastDelegateExtension:TryInvoke(MulticastDelegate, Object[])
Rocket.Unturned.Events.UnturnedPlayerEvents:TriggerSend(SteamPlayer, String, ESteamCall, ESteamPacket, Object[])
Rocket.Unturned.U:<bindDelegates>m__7(SteamPlayer, String, ESteamCall, ESteamPacket, Object[])
SDG.Unturned.SteamChannel:send(String, ESteamCall, ESteamPacket, Object[])
SDG.Unturned.PlayerLife:doDamage(Byte, Vector3, EDeathCause, ELimb, CSteamID, EPlayerKill&, Boolean, ERagdollEffect)
SDG.Unturned.PlayerLife:askDamage(Byte, Vector3, EDeathCause, ELimb, CSteamID, EPlayerKill&, Boolean, ERagdollEffect)
SDG.Unturned.PlayerLife:askDamage(Byte, Vector3, EDeathCause, ELimb, CSteamID, EPlayerKill&)
SDG.Unturned.PlayerLife:simulate(UInt32)
SDG.Unturned.PlayerInput:FixedUpdate()

**Comment by leonardosnt** [comment]
This doesn't seems to a uEssentials error. There's a mention to `Uconomy_Essentials` in the stacktrace, which is not part of uEssentials.
