### ISSUE TITLE
oof new update new error.

### ISSUE THREAD

**Issue by RainOfPain125** [uEssentials/uEssentials#753]
[uEssentials] [ERROR] An error occurred while enabling uEssentials.
[uEssentials] [ERROR] If this error is not related with wrong configuration please report
[uEssentials] [ERROR] immediatly here https://github.com/uEssentials/uEssentials/issues
[uEssentials] [ERROR] Error: System.NullReferenceException: Object reference not set to an instance of an object
  at Essentials.Core.EssCore.Load () [0x00640] in <7c63fcc57fec4c429502c54276e1859e>:0
[uEssentials] [ERROR] I detected that you are using a different version of the recommended, please update your uEssentials/Unturned.
[uEssentials] [ERROR] If you are using the latest uEssentials release, please wait for update.

**Comment by burak195181** [comment]
I'm getting this problem too
