### ISSUE TITLE
i can't get disabledcommands to work

### ISSUE THREAD

**Issue by CraZfalcon** [uEssentials/uEssentials#754]
i've tried rearranging some items in the config, restarted the server several times, i even reinstalled entire uessentials.

i think i configurated it correctly, but i'm not completely sure.

https://github.com/uEssentials/uEssentials/wiki/Configuration

atempt 1: (the arrangement the plugin came with)

  "EnabledSystems": [
    "kits",
    "warps"
  ],
  "CommandsToOverride": [],
  "DisabledCommands": [
      "vote",
      "airdrop"
  ]
}

&&

atempt 2: (the arrangement shown on the website)

  "EnabledSystems": [
    "kits",
    "warps"
  ],
  "DisabledCommands": [
      "vote",
      "airdrop"
  ],
  "CommandsToOverride": []
}

**Comment by leonardosnt** [comment]
Airdrop command is not uEssentials. DisabledCommands only works with uEssentials commands.
