### ISSUE TITLE
Modded items in uEssentials kits are deleted in kits.json file

### ISSUE THREAD

**Issue by VoidLost** [uEssentials/uEssentials#756]
Need a possible solution or a patch. 

-Edit
Seems that the plugin is loaded before workshop items. (servers\server\workshop\steam\content)

So the ID'S seem invalid and they are deleted.
Possible solution could be disabling the deletion of invalid ID's.

![image](https://user-images.githubusercontent.com/55337535/72265647-e44e8200-362d-11ea-9d95-67ce0e5d50cc.png)

**Also:** server owners can fix this problem by putting the workshop folder into the *Servers\server\Workshop\Content* instead of typing the ID in the WorkshopDownloadConfig

**Comment by Warlock-Egemen** [comment]
Same problem :(

**Comment by VoidLost** [comment]
**Update**

Confirmed fix is manually adding mods into the workshop\content folder.

**Comment by Kr4ken-9** [comment]
Hello, this issue should be fixed in the latest release which you can find here: https://github.com/uEssentials/Builds/releases

You can test it for yourself and close this issue once you have confirmed it is working.
