### ISSUE TITLE
When i do /Refuelgen this error comes

### ISSUE THREAD

**Issue by Williampayr** [uEssentials/uEssentials#758]
[uEssentials] [ERROR] An error ocurred while executing command: 'refuelgen '
[uEssentials] [ERROR] Field 'SDG.Unturned.RayMasks.BARRICADE' not found.

**Comment by Kr4ken-9** [comment]
Hello, this issue should be fixed in the latest release which you can find here: https://github.com/uEssentials/Builds/releases

You can test it for yourself and close this issue once you have confirmed it is working.
