### ISSUE TITLE
Kits not found when kits.json is stacked

### ISSUE THREAD

**Issue by Rhys-Woolcott** [uEssentials/uEssentials#759]
I am trying to use the kits but when i do /kits it says `There are not kits defined`

here is my kits.json
`[
  {
    "Name": "start",
    "Items": [
      {
        "Id": 2,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 181,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 200,
        "Durability": 100,
        "Amount": 1
      }
    ],
    "Cooldown": 600,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "police",
    "Items": [
      {
        "Id": 10,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 223,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 224,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 1195,
        "Durability": 100,
        "Amount": 2
      },
      {
        "Id": 1196,
        "Durability": 100,
        "Amount": 2
      },
      {
        "Id": 8065,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Magazine": {
          "AttachmentId": 51103,
          "Durability": 100
        },
        "FireMode": "SEMI",
        "Ammo": 5,
        "Id": 51102,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Sight": {
          "AttachmentId": 146,
          "Durability": 100
        },
        "Magazine": {
          "AttachmentId": 1339,
          "Durability": 100
        },
        "FireMode": "SEMI",
        "Ammo": 35,
        "Id": 1337,
        "Durability": 100,
        "Amount": 1
      }
    ],
    "Cooldown": 600,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "mpolice",
    "Items": [
      {
        "Id": 1171,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 1172,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 1389,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 1195,
        "Durability": 100,
        "Amount": 2
      },
      {
        "Id": 1196,
        "Durability": 100,
        "Amount": 2
      },
      {
        "Id": 8065,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 1169,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 17,
        "Durability": 100,
        "Amount": 3
      },
      {
        "Barrel": {
          "AttachmentId": 7,
          "Durability": 100
        },
        "Sight": {
          "AttachmentId": 146,
          "Durability": 100
        },
        "Grip": {
          "AttachmentId": 8,
          "Durability": 100
        },
        "Magazine": {
          "AttachmentId": 17,
          "Durability": 100
        },
        "Tactical": {
          "AttachmentId": 151,
          "Durability": 100
        },
        "FireMode": "BURST",
        "Ammo": 30,
        "Id": 4,
        "Durability": 100,
        "Amount": 1
      }
    ],
    "Cooldown": 600,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "mafia",
    "Items": [
      {
        "Id": 1385,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 1386,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 1387,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 253,
        "Durability": 100,
        "Amount": 2
      },
      {
        "Id": 334,
        "Durability": 100,
        "Amount": 2
      },
      {
        "Id": 185,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Id": 1169,
        "Durability": 100,
        "Amount": 1
      },
      {
        "Barrel": {
          "AttachmentId": 51902,
          "Durability": 100
        },
        "Magazine": {
          "AttachmentId": 51322,
          "Durability": 100
        },
        "FireMode": "AUTO",
        "Ammo": 100,
        "Id": 51321,
        "Durability": 100,
        "Amount": 1
      }
      {
        "Barrel": {
          "AttachmentId": 51901,
          "Durability": 100
        },
        "Magazine": {
          "AttachmentId": 51120,
          "Durability": 100
        },
        "FireMode": "SEMI",
        "Ammo": 20,
        "Id": 51118,
        "Durability": 100,
        "Amount": 1
      }
    ],
    "Cooldown": 600,
    "Cost": 0.0,
    "ResetCooldownWhenDie": true
  },
  {
    "Name": "paycheck",
    "Items": [
      {
        "Xp": 5000
      }
    ],
    "Cooldown": 86400,
    "Cost": 0.0,
    "ResetCooldownWhenDie": false
  }
]`

**Comment by leonardosnt** [comment]
There are syntax errors in that JSON.
If you are not familiar with JSON, try using `/createkit` and `/editkit` to create kits ingame.
You can also use https://jsonlint.com/ to validate the JSON before starting the server.

Try this (fixed missing comma):
```
[
   {
      "Name":"start",
      "Items":[
         {
            "Id":2,
            "Durability":100,
            "Amount":1
         },
         {
            "Id":181,
            "Durability":100,
            "Amount":1
         },
         {
            "Id":200,
            "Durability":100,
            "Amount":1
         }
      ],
      "Cooldown":600,
      "Cost":0.0,
      "ResetCooldownWhenDie":true
   },
   {
      "Name":"police",
      "Items":[
         {
            "Id":10,
            "Durability":100,
            "Amount":1
         },
         {
            "Id":223,
            "Durability":100,
            "Amount":1
         },
         {
            "Id":224,
            "Durability":100,
            "Amount":1
         },
         {
            "Id":1195,
            "Durability":100,
            "Amount":2
         },
         {
            "Id":1196,
            "Durability":100,
            "Amount":2
         },
         {
            "Id":8065,
            "Durability":100,
            "Amount":1
         },
         {
            "Magazine":{
               "AttachmentId":51103,
               "Durability":100
            },
            "FireMode":"SEMI",
            "Ammo":5,
            "Id":51102,
            "Durability":100,
            "Amount":1
         },
         {
            "Sight":{
               "AttachmentId":146,
               "Durability":100
            },
            "Magazine":{
               "AttachmentId":1339,
               "Durability":100
            },
            "FireMode":"SEMI",
            "Ammo":35,
            "Id":1337,
            "Durability":100,
            "Amount":1
         }
      ],
      "Cooldown":600,
      "Cost":0.0,
      "ResetCooldownWhenDie":true
   },
   {
      "Name":"mpolice",
      "Items":[
         {
            "Id":1171,
            "Durability":100,
            "Amount":1
         },
         {
            "Id":1172,
            "Durability":100,
            "Amount":1
         },
         {
            "Id":1389,
            "Durability":100,
            "Amount":1
         },
         {
            "Id":1195,
            "Durability":100,
            "Amount":2
         },
         {
            "Id":1196,
            "Durability":100,
            "Amount":2
         },
         {
            "Id":8065,
            "Durability":100,
            "Amount":1
         },
         {
            "Id":1169,
            "Durability":100,
            "Amount":1
         },
         {
            "Id":17,
            "Durability":100,
            "Amount":3
         },
         {
            "Barrel":{
               "AttachmentId":7,
               "Durability":100
            },
            "Sight":{
               "AttachmentId":146,
               "Durability":100
            },
            "Grip":{
               "AttachmentId":8,
               "Durability":100
            },
            "Magazine":{
               "AttachmentId":17,
               "Durability":100
            },
            "Tactical":{
               "AttachmentId":151,
               "Durability":100
            },
            "FireMode":"BURST",
            "Ammo":30,
            "Id":4,
            "Durability":100,
            "Amount":1
         }
      ],
      "Cooldown":600,
      "Cost":0.0,
      "ResetCooldownWhenDie":true
   },
   {
      "Name":"mafia",
      "Items":[
         {
            "Id":1385,
            "Durability":100,
            "Amount":1
         },
         {
            "Id":1386,
            "Durability":100,
            "Amount":1
         },
         {
            "Id":1387,
            "Durability":100,
            "Amount":1
         },
         {
            "Id":253,
            "Durability":100,
            "Amount":2
         },
         {
            "Id":334,
            "Durability":100,
            "Amount":2
         },
         {
            "Id":185,
            "Durability":100,
            "Amount":1
         },
         {
            "Id":1169,
            "Durability":100,
            "Amount":1
         },
         {
            "Barrel":{
               "AttachmentId":51902,
               "Durability":100
            },
            "Magazine":{
               "AttachmentId":51322,
               "Durability":100
            },
            "FireMode":"AUTO",
            "Ammo":100,
            "Id":51321,
            "Durability":100,
            "Amount":1
         },
         {
            "Barrel":{
               "AttachmentId":51901,
               "Durability":100
            },
            "Magazine":{
               "AttachmentId":51120,
               "Durability":100
            },
            "FireMode":"SEMI",
            "Ammo":20,
            "Id":51118,
            "Durability":100,
            "Amount":1
         }
      ],
      "Cooldown":600,
      "Cost":0.0,
      "ResetCooldownWhenDie":true
   },
   {
      "Name":"paycheck",
      "Items":[
         {
            "Xp":5000
         }
      ],
      "Cooldown":86400,
      "Cost":0.0,
      "ResetCooldownWhenDie":false
   }
]
```
