### ISSUE TITLE
Please guys help me with this uEssentials error 

### ISSUE THREAD

**Issue by Williampayr** [uEssentials/uEssentials#760]
Hello Owner or hoever is reading this i need ur help to fix my uEssentials /Refuelgen. when i do /Refuelgen thiss error comes up in console and idk what to do
[uEssentials] [ERROR] An error ocurred while executing command: 'refuelgen '
[uEssentials] [ERROR] Field 'SDG.Unturned.RayMasks.BARRICADE' not found.

please anyone that know and that can help me please do because my server really needs /refuelgen

**Comment by leonardosnt** [comment]
Download the latest build here https://github.com/uEssentials/Builds/releases/tag/build-29b2f5c and check if it's working.

**Comment by leonardosnt** [comment]
It's working in the latest build.
