### ISSUE TITLE
/home = doesn't work

### ISSUE THREAD

**Issue by VortDyn** [uEssentials/uEssentials#765]
When I write a command /home, a notification comes that I am teleported to my bed, but in fact I am not moving to my bed. What to do? :(

![image](https://user-images.githubusercontent.com/54004093/81425812-186c2680-917a-11ea-929f-5d37ffe931a5.png)

**Comment by Kraken555** [comment]
my / home doesn't work either

**Comment by Kr4ken-9** [comment]
Hello, this issue should be fixed in the latest release which you can find here: https://github.com/uEssentials/Builds/releases

You can test it for yourself and close this issue once you have confirmed it is working.

**Comment by megoesrawr** [comment]
@Kr4ken-9 How did you find the fix? I forgot to put a PR here for that fix. I did this like 3 months ago. Good job though updating it for everyone else!

**Comment by Kr4ken-9** [comment]
@RawrUniversal I looked at how Nelson does it after he broke it:
![](https://i.imgur.com/mYB9Z6R.png)

**Comment by RawrUniversal** [comment]
Ok. Nice.
