### ISSUE TITLE
Update to Rocket Unturned v4.9.3.2

### ISSUE THREAD

**Issue by VortDyn** [uEssentials/uEssentials#768]
Rocket Unturned v4.9.3.2 for Unturned v3.20.5.4

**Comment by wolfhound871** [comment]
nelson pushes rocket updates / patches in the extras folder just take the rocket.unturned file and throw it in modules

**Comment by leonardosnt** [comment]
The latest build is working fine with Rocket v4.9.3.2 and Unturned v3.20.7.0

https://github.com/uEssentials/Builds/releases
