### ISSUE TITLE
Autoannouncer not working, btw keep up the great work!

### ISSUE THREAD

**Issue by Viggors** [uEssentials/uEssentials#769]
Hi! so as the title says i have tried to make an autoannouncer with your mod but it dosent seem to wanna work!

here is what i have done so far:

 },
  "AutoAnnouncer": {
    "Interval": 30,
    "RandomMessages": false,
    "Enabled": true,
    "Messages": [
      "<magenta>Need some quick loot? try one of our kits!"
	  "<magenta>Wanna join our discord? tell viggors or fisher!"
	  "<magenta>Need that quick fix of meth? of course you do look at yourself! well do warp bar to fix it!"
	  "<magenta>Our /home command is currently not working but dont worry! it will be fixed soon!"
	  "<magenta>Are you tired of the RP? well fear not try /warp pvp and try our arena!"
	  "<magenta>Did you and your boys spawn at diffrent parts of the map? well try /tpa!"
	  "<magenta>Looking to stash your items in a safe space? /vault is coming soon to the server or buy a private locker from viggors which is unraideble"
	  "<magenta>Do /vote and follow the vote button to get a reward from viggors!"
    ]

**Comment by leonardosnt** [comment]
There are syntax errors. You need to add a comma after the closing quote in the messages, except the last one.

It should look something like this:

```json

"Messages": [
  "Need some quick loot? try one of our kits!",
  "Wanna join our discord? tell viggors or fisher!",
  "Need that quick fix of meth? of course you do look at yourself! well do warp bar to fix it!",
  "Our /home command is currently not working but dont worry! it will be fixed soon!",
  "Are you tired of the RP? well fear not try /warp pvp and try our arena!",
  "Did you and your boys spawn at diffrent parts of the map? well try /tpa!",
  "Looking to stash your items in a safe space? /vault is coming soon to the server or buy a private locker from viggors which is unraideble",
  "Do /vote and follow the vote button to get a reward from viggors!"
]
```

You can use a [json validator](https://www.google.com/search?q=json+validator) to make sure the syntax is correct.

**Comment by Viggors** [comment]
Ok! ty for your repsonse. 
it currently looks like this:
 "AutoAnnouncer": {
    "Interval": 30,
    "RandomMessages": false,
    "Enabled": true,
    "Messages": [
      "<magenta>Need some quick loot? try one of our kits!",
	  "<magenta>Wanna join our discord? tell viggors or fisher!",
	  "<magenta>Need that quick fix of meth? of course you do look at yourself! well do warp bar to fix it!",
	  "<magenta>Our /home command is currently not working but dont worry! it will be fixed soon!",
	  "<magenta>Are you tired of the RP? well fear not try /warp pvp and try our arena!",
	  "<magenta>Did you and your boys spawn at diffrent parts of the map? well try /tpa!",
	  "<magenta>Looking to stash your items in a safe space? /vault is coming soon to the server or buy a private locker from viggors which is unraideble",
	  "<magenta>Do /vote and follow the vote button to get a reward from viggors!",
    ]
but it still wont work! is it the color i am going with or is it something i am completly missing?

**Comment by leonardosnt** [comment]
The **last message** should not contain a comma at end.
> "Do /vote and follow the vote button to get a reward from viggors!",

If you show me the whole file, I can fix the syntax errors for you.
