### ISSUE TITLE
Setting kit permission

### ISSUE THREAD

**Issue by Viggors** [uEssentials/uEssentials#771]
Hi i am,  trying to set so that only a certain permission group can use a certain kit but i cant seem to get it to work, here are my files.

<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Prefix />
      <Suffix />
      <Color>white</Color>
      <Members />
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">voterewards.vote</Permission>
        <Permission Cooldown="0">voterewards.reward</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="140">essentials.command.kit.*</Permission>
        <Permission Cooldown="0">essentials.kits</Permission>
        <Permission Cooldown="0">essentials.kit</Permission>
        <Permission Cooldown="140">essentials.kit.*</Permission>
        <Permission Cooldown="0">essentials.command.warps</Permission>
        <Permission Cooldown="0">essentials.command.warp</Permission>
        <Permission Cooldown="0">essentials.warp.*</Permission>
        <Permission Cooldown="0">essentials.command.home</Permission>
        <Permission Cooldown="0">essentials.home.*</Permission>
        <Permission Cooldown="0">vaults</Permission>
        <Permission Cooldown="0">vault</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>vip</Id>
      <DisplayName>VIP1</DisplayName>
      <Prefix />
      <Suffix />
      <Color>#99fc35</Color>
      <Members>
        <Member>76561198016438091</Member>
        <Member>76561198269434398</Member>
      </Members>
 <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">voterewards.vote</Permission>
        <Permission Cooldown="0">voterewards.reward</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="140">essentials.command.kit.*</Permission>
        <Permission Cooldown="0">essentials.kits</Permission>
        <Permission Cooldown="0">essentials.kit</Permission>
        <Permission Cooldown="140">essentials.kit.*</Permission>
        <Permission Cooldown="0">essentials.command.warps</Permission>
        <Permission Cooldown="0">essentials.command.warp</Permission>
        <Permission Cooldown="0">essentials.warp.*</Permission>
        <Permission Cooldown="0">essentials.command.home</Permission>
        <Permission Cooldown="0">essentials.home.*</Permission>
        <Permission Cooldown="0">vaults</Permission>
        <Permission Cooldown="0">vault</Permission>
<Permission Cooldown="0">essentials.command.kit.VIP1</Permission>
      </Permissions>
      <ParentGroup>default</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">essentials.command.kit.VIP1</Permission>
        <Permission Cooldown="120">heal</Permission>
        <Permission Cooldown="30">v</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>

**Comment by Viggors** [comment]
wait that copy and pastew looked rly weird <?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Prefix />
      <Suffix />
      <Color>white</Color>
      <Members />
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">voterewards.vote</Permission>
        <Permission Cooldown="0">voterewards.reward</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="140">essentials.command.kit.*</Permission>
        <Permission Cooldown="0">essentials.kits</Permission>
        <Permission Cooldown="0">essentials.kit</Permission>
        <Permission Cooldown="140">essentials.kit.*</Permission>
        <Permission Cooldown="0">essentials.command.warps</Permission>
        <Permission Cooldown="0">essentials.command.warp</Permission>
        <Permission Cooldown="0">essentials.warp.*</Permission>
        <Permission Cooldown="0">essentials.command.home</Permission>
        <Permission Cooldown="0">essentials.home.*</Permission>
        <Permission Cooldown="0">vaults</Permission>
        <Permission Cooldown="0">vault</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>vip</Id>
      <DisplayName>VIP1</DisplayName>
      <Prefix />
      <Suffix />
      <Color>#99fc35</Color>
      <Members>
        <Member>76561198016438091</Member>
        <Member>76561198269434398</Member>
      </Members>
 <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">voterewards.vote</Permission>
        <Permission Cooldown="0">voterewards.reward</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="140">essentials.command.kit.*</Permission>
        <Permission Cooldown="0">essentials.kits</Permission>
        <Permission Cooldown="0">essentials.kit</Permission>
        <Permission Cooldown="140">essentials.kit.*</Permission>
        <Permission Cooldown="0">essentials.command.warps</Permission>
        <Permission Cooldown="0">essentials.command.warp</Permission>
        <Permission Cooldown="0">essentials.warp.*</Permission>
        <Permission Cooldown="0">essentials.command.home</Permission>
        <Permission Cooldown="0">essentials.home.*</Permission>
        <Permission Cooldown="0">vaults</Permission>
        <Permission Cooldown="0">vault</Permission>
<Permission Cooldown="0">essentials.command.kit.VIP1</Permission>
      </Permissions>
      <ParentGroup>default</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">essentials.command.kit.VIP1</Permission>
        <Permission Cooldown="120">heal</Permission>
        <Permission Cooldown="30">v</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>

**Comment by leonardosnt** [comment]
Some permissions are not correct. For example, **essentials.command.kit.VIP1** should be **essentials.kit.VIP1**

Check out the permission guide here: https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference

**Comment by Viggors** [comment]
Hi sorry for late respose! but i did some changes and the uessentials wiki wasent rly to any help. however it currewntly looks like this but it still wont work, why is that?

<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Prefix />
      <Suffix />
      <Color>white</Color>
      <Members />
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">voterewards.vote</Permission>
        <Permission Cooldown="0">voterewards.reward</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="140">essentials.command.kit.*</Permission>
        <Permission Cooldown="0">essentials.kits</Permission>
        <Permission Cooldown="0">essentials.kit</Permission>
        <Permission Cooldown="140">essentials.kit.*</Permission>
        <Permission Cooldown="0">essentials.command.warps</Permission>
        <Permission Cooldown="0">essentials.command.warp</Permission>
        <Permission Cooldown="0">essentials.warp.*</Permission>
        <Permission Cooldown="0">essentials.command.home</Permission>
        <Permission Cooldown="0">essentials.home.*</Permission>
        <Permission Cooldown="0">vaults</Permission>
        <Permission Cooldown="0">vault</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>vip</Id>
      <DisplayName>VIP1</DisplayName>
      <Prefix />
      <Suffix />
      <Color>green</Color>
      <Members>
        <Member>76561198016438091</Member>
        <Member>76561198269434398</Member>
        <Member>76561198269434398</Member>
      </Members>
      <ParentGroup>default</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">voterewards.vote</Permission>
        <Permission Cooldown="0">voterewards.reward</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="140">essentials.command.kit.*</Permission>
        <Permission Cooldown="0">essentials.kits</Permission>
        <Permission Cooldown="0">essentials.kit</Permission>
        <Permission Cooldown="140">essentials.kit.*</Permission>
        <Permission Cooldown="0">essentials.command.warps</Permission>
        <Permission Cooldown="0">essentials.command.warp</Permission>
        <Permission Cooldown="0">essentials.warp.*</Permission>
        <Permission Cooldown="0">essentials.command.home</Permission>
        <Permission Cooldown="0">essentials.home.*</Permission>
        <Permission Cooldown="0">vaults</Permission>
        <Permission Cooldown="0">vault</Permission>
        <Permission Cooldown="0">essentials.kit.VIP1</Permission>
        <Permission Cooldown="120">heal</Permission>
        <Permission Cooldown="30">v</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>

**Comment by Viggors** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Prefix />
      <Suffix />
      <Color>white</Color>
      <Members />
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">voterewards.vote</Permission>
        <Permission Cooldown="0">voterewards.reward</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="140">essentials.command.kit.*</Permission>
        <Permission Cooldown="0">essentials.kits</Permission>
        <Permission Cooldown="0">essentials.kit</Permission>
        <Permission Cooldown="140">essentials.kit.*</Permission>
        <Permission Cooldown="0">essentials.command.warps</Permission>
        <Permission Cooldown="0">essentials.command.warp</Permission>
        <Permission Cooldown="0">essentials.warp.*</Permission>
        <Permission Cooldown="0">essentials.command.home</Permission>
        <Permission Cooldown="0">essentials.home.*</Permission>
        <Permission Cooldown="0">vaults</Permission>
        <Permission Cooldown="0">vault</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>vip</Id>
      <DisplayName>VIP1</DisplayName>
      <Prefix />
      <Suffix />
      <Color>green</Color>
      <Members>
        <Member>76561198016438091</Member>
        <Member>76561198269434398</Member>
        <Member>76561198269434398</Member>
      </Members>
      <ParentGroup>default</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">voterewards.vote</Permission>
        <Permission Cooldown="0">voterewards.reward</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="140">essentials.command.kit.*</Permission>
        <Permission Cooldown="0">essentials.kits</Permission>
        <Permission Cooldown="0">essentials.kit</Permission>
        <Permission Cooldown="140">essentials.kit.*</Permission>
        <Permission Cooldown="0">essentials.command.warps</Permission>
        <Permission Cooldown="0">essentials.command.warp</Permission>
        <Permission Cooldown="0">essentials.warp.*</Permission>
        <Permission Cooldown="0">essentials.command.home</Permission>
        <Permission Cooldown="0">essentials.home.*</Permission>
        <Permission Cooldown="0">vaults</Permission>
        <Permission Cooldown="0">vault</Permission>
        <Permission Cooldown="0">essentials.kit.VIP1</Permission>
        <Permission Cooldown="120">heal</Permission>
        <Permission Cooldown="30">v</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>

**Comment by Viggors** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Prefix />
      <Suffix />
      <Color>white</Color>
      <Members />
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">voterewards.vote</Permission>
        <Permission Cooldown="0">voterewards.reward</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="140">essentials.command.kit.*</Permission>
        <Permission Cooldown="0">essentials.kits</Permission>
        <Permission Cooldown="0">essentials.kit</Permission>
        <Permission Cooldown="140">essentials.kit.*</Permission>
        <Permission Cooldown="0">essentials.command.warps</Permission>
        <Permission Cooldown="0">essentials.command.warp</Permission>
        <Permission Cooldown="0">essentials.warp.*</Permission>
        <Permission Cooldown="0">essentials.command.home</Permission>
        <Permission Cooldown="0">essentials.home.*</Permission>
        <Permission Cooldown="0">vaults</Permission>
        <Permission Cooldown="0">vault</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>vip</Id>
      <DisplayName>VIP1</DisplayName>
      <Prefix />
      <Suffix />
      <Color>green</Color>
      <Members>
        <Member>76561198016438091</Member>
        <Member>76561198269434398</Member>
        <Member>76561198269434398</Member>
      </Members>
      <ParentGroup>default</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">voterewards.vote</Permission>
        <Permission Cooldown="0">voterewards.reward</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="140">essentials.command.kit.*</Permission>
        <Permission Cooldown="0">essentials.kits</Permission>
        <Permission Cooldown="0">essentials.kit</Permission>
        <Permission Cooldown="140">essentials.kit.*</Permission>
        <Permission Cooldown="0">essentials.command.warps</Permission>
        <Permission Cooldown="0">essentials.command.warp</Permission>
        <Permission Cooldown="0">essentials.warp.*</Permission>
        <Permission Cooldown="0">essentials.command.home</Permission>
        <Permission Cooldown="0">essentials.home.*</Permission>
        <Permission Cooldown="0">vaults</Permission>
        <Permission Cooldown="0">vault</Permission>
        <Permission Cooldown="0">essentials.kit.VIP1</Permission>
        <Permission Cooldown="120">heal</Permission>
        <Permission Cooldown="30">v</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>

**Comment by Viggors** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Prefix />
      <Suffix />
      <Color>white</Color>
      <Members />
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">voterewards.vote</Permission>
        <Permission Cooldown="0">voterewards.reward</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="140">essentials.command.kit.*</Permission>
        <Permission Cooldown="0">essentials.kits</Permission>
        <Permission Cooldown="0">essentials.kit</Permission>
        <Permission Cooldown="140">essentials.kit.*</Permission>
        <Permission Cooldown="0">essentials.command.warps</Permission>
        <Permission Cooldown="0">essentials.command.warp</Permission>
        <Permission Cooldown="0">essentials.warp.*</Permission>
        <Permission Cooldown="0">essentials.command.home</Permission>
        <Permission Cooldown="0">essentials.home.*</Permission>
        <Permission Cooldown="0">vaults</Permission>
        <Permission Cooldown="0">vault</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>vip</Id>
      <DisplayName>VIP1</DisplayName>
      <Prefix />
      <Suffix />
      <Color>green</Color>
      <Members>
        <Member>76561198016438091</Member>
        <Member>76561198269434398</Member>
        <Member>76561198269434398</Member>
      </Members>
      <ParentGroup>default</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">voterewards.vote</Permission>
        <Permission Cooldown="0">voterewards.reward</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="140">essentials.command.kit.*</Permission>
        <Permission Cooldown="0">essentials.kits</Permission>
        <Permission Cooldown="0">essentials.kit</Permission>
        <Permission Cooldown="140">essentials.kit.*</Permission>
        <Permission Cooldown="0">essentials.command.warps</Permission>
        <Permission Cooldown="0">essentials.command.warp</Permission>
        <Permission Cooldown="0">essentials.warp.*</Permission>
        <Permission Cooldown="0">essentials.command.home</Permission>
        <Permission Cooldown="0">essentials.home.*</Permission>
        <Permission Cooldown="0">vaults</Permission>
        <Permission Cooldown="0">vault</Permission>
        <Permission Cooldown="0">essentials.kit.VIP1</Permission>
        <Permission Cooldown="120">heal</Permission>
        <Permission Cooldown="30">v</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>

**Comment by Viggors** [comment]
I did a few changes but it still wont work it currently looks like this.

<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Prefix />
      <Suffix />
      <Color>white</Color>
      <Members />
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">voterewards.vote</Permission>
        <Permission Cooldown="0">voterewards.reward</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="140">essentials.command.kit.*</Permission>
        <Permission Cooldown="0">essentials.kits</Permission>
        <Permission Cooldown="0">essentials.kit</Permission>
        <Permission Cooldown="140">essentials.kit.*</Permission>
        <Permission Cooldown="0">essentials.command.warps</Permission>
        <Permission Cooldown="0">essentials.command.warp</Permission>
        <Permission Cooldown="0">essentials.warp.*</Permission>
        <Permission Cooldown="0">essentials.command.home</Permission>
        <Permission Cooldown="0">essentials.home.*</Permission>
        <Permission Cooldown="0">vaults</Permission>
        <Permission Cooldown="0">vault</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>vip</Id>
      <DisplayName>VIP1</DisplayName>
      <Prefix />
      <Suffix />
      <Color>green</Color>
      <Members>
        <Member>76561198016438091</Member>
        <Member>76561198269434398</Member>
        <Member>76561198269434398</Member>
      </Members>
      <ParentGroup>default</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">voterewards.vote</Permission>
        <Permission Cooldown="0">voterewards.reward</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="140">essentials.command.kit.*</Permission>
        <Permission Cooldown="0">essentials.kits</Permission>
        <Permission Cooldown="0">essentials.kit</Permission>
        <Permission Cooldown="140">essentials.kit.*</Permission>
        <Permission Cooldown="0">essentials.command.warps</Permission>
        <Permission Cooldown="0">essentials.command.warp</Permission>
        <Permission Cooldown="0">essentials.warp.*</Permission>
        <Permission Cooldown="0">essentials.command.home</Permission>
        <Permission Cooldown="0">essentials.home.*</Permission>
        <Permission Cooldown="0">vaults</Permission>
        <Permission Cooldown="0">vault</Permission>
        <Permission Cooldown="0">essentials.kit.VIP1</Permission>
        <Permission Cooldown="120">heal</Permission>
        <Permission Cooldown="30">v</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>

what have i done wrong?

**Comment by leonardosnt** [comment]
I've removed the invalid permissions. Check if this works:

```xml
<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Prefix />
      <Suffix />
      <Color>white</Color>
      <Members />
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">voterewards.vote</Permission>
        <Permission Cooldown="0">voterewards.reward</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="140">essentials.kit.*</Permission>
        <Permission Cooldown="0">essentials.command.warps</Permission>
        <Permission Cooldown="0">essentials.command.warp</Permission>
        <Permission Cooldown="0">essentials.warp.*</Permission>
        <Permission Cooldown="0">essentials.command.home</Permission>
        <Permission Cooldown="0">essentials.home.*</Permission>
        <Permission Cooldown="0">vaults</Permission>
        <Permission Cooldown="0">vault</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>vip</Id>
      <DisplayName>VIP1</DisplayName>
      <Prefix />
      <Suffix />
      <Color>green</Color>
      <Members>
        <Member>76561198016438091</Member>
        <Member>76561198269434398</Member>
        <Member>76561198269434398</Member>
      </Members>
      <ParentGroup>default</ParentGroup>
      <Priority>100</Priority>
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">voterewards.vote</Permission>
        <Permission Cooldown="0">voterewards.reward</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="140">essentials.kit.*</Permission>
        <Permission Cooldown="0">essentials.command.warps</Permission>
        <Permission Cooldown="0">essentials.command.warp</Permission>
        <Permission Cooldown="0">essentials.warp.*</Permission>
        <Permission Cooldown="0">essentials.command.home</Permission>
        <Permission Cooldown="0">essentials.home.*</Permission>
        <Permission Cooldown="0">vaults</Permission>
        <Permission Cooldown="0">vault</Permission>
        <Permission Cooldown="0">essentials.kit.VIP1</Permission>
        <Permission Cooldown="120">heal</Permission>
        <Permission Cooldown="30">v</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>
```
