### ISSUE TITLE
Kit not working help please

### ISSUE THREAD

**Issue by MrBacks07** [uEssentials/uEssentials#772]
in file "kit.json" i have only this:
[]

and in console i have "Out date plugin" but i have newest plugin

**Comment by leonardosnt** [comment]
Delete the kits.json file and restart the server.

**Comment by leonardosnt** [comment]
If you are not familiar with JSON, try using /createkit and /editkit do create and edit kits.

**Comment by MrBacks07** [comment]
I Delete kit.json and restart the server.
and i all the time have in the kit.json
this: []

**Comment by leonardosnt** [comment]
That's weird. Try the latest build: https://github.com/uEssentials/Builds/releases/tag/build-4387ef4

Do you see any errors (might show up as a red text) in the console when the server starts?

**Comment by MrBacks07** [comment]
No, I use command /createkit and now working

**Comment by leonardosnt** [comment]
Is it working know? Can I close this issue?

**Comment by MrBacks07** [comment]
Yes :)

**Comment by leonardosnt** [comment]
Great! :tada:
