### ISSUE TITLE
Failed to load 'avi_economy' hook

### ISSUE THREAD

**Issue by Ferom2** [uEssentials/uEssentials#773]
```
[loading] uEssentials
[uEssentials] [INFO] Enabling uEssentials...
[uEssentials] [INFO] Plugin version: 1.3.6.0
[uEssentials] [INFO] Recommended Rocket version: 4.9.3.3
[uEssentials] [INFO] Recommended Unturned version: 3.20.7.0
[uEssentials] [INFO] Author: leonardosnt
[uEssentials] [INFO] Wiki: uessentials.github.io
[uEssentials] [INFO] Loading AviEconomy hook...
[uEssentials] [ERROR] Failed to load 'avi_economy' hook.
[uEssentials] [ERROR] AviEconomy Bank type couldn't be loaded...
[uEssentials] [INFO] Loading Uconomy hook...
[uEssentials] [INFO] Uconomy hook loaded.
[uEssentials] [INFO] Loaded 0 warps
[uEssentials] [INFO] Loading modules...
[uEssentials] [INFO] Loaded 0 modules
[uEssentials] [INFO] Loaded 70 commands
[uEssentials] [INFO] Enabled (221 ms)
[uEssentials] [INFO] Checking updates.
```

Because of this, the player cannot receive a paid kit.
```
[uEssentials] [ERROR] An error ocurred while executing command: 'kit coalit'
[uEssentials] [ERROR] Object reference not set to an instance of an object
```

**Comment by leonardosnt** [comment]
I couldn't find the AviEconomy plugin. Where did you download it?

**Comment by Ferom2** [comment]
Here's the installation instructions: https://vk.com/@avirockets-instrukciya-k-obnovleniu-47
This is the AviRockets module: https://drive.google.com/file/d/11ZUq0P501YuzEP62X1Ywegg-mPvYoQO8/view
This is the AviRockets Gateway: https://drive.google.com/file/d/1PzDond8NK3tFbmsvUB92Ec-hxnTuK0w_/view

**Comment by leonardosnt** [comment]
I'll take a look as soon as I have time.

**Comment by leonardosnt** [comment]
AviGateway is heavily obfuscated, which means that it's trying to hide something. I also noticed that the updater, which is inside the module, can run arbitrary code on the server because it loads an Assembly directly from an HTTP request. This is a big red flag.

Sorry, but I'm not going to add support for that kind of plugin.
