### ISSUE TITLE
ERROR that i need answer to

### ISSUE THREAD

**Issue by Tr1ckdk** [uEssentials/uEssentials#774]
![image](https://user-images.githubusercontent.com/69484202/89830343-4a679d00-db5c-11ea-8890-5e67b033afa0.png)

**Comment by leonardosnt** [comment]
Does it happen every time you start the server?

**Comment by Tr1ckdk** [comment]
yes it does

**Comment by Tr1ckdk** [comment]
sry for the late respond i am very busy IRL

**Comment by leonardosnt** [comment]
This issue has been fixed. Thanks for reporting! 

You can get the latest build here https://github.com/uEssentials/Builds/releases/tag/build-bc6683f

**Comment by Tr1ckdk** [comment]
:)
