### ISSUE TITLE
Crash on OS Linux

### ISSUE THREAD

**Issue by MihailHavenT** [uEssentials/uEssentials#778]
So when I start button on the server, the uEssentials half loads and starts crashing my server... And so on.
![Capture](https://user-images.githubusercontent.com/57589652/101266341-49cbc580-374e-11eb-9357-2fb7b897cfdc.png)

**Comment by MihailHavenT** [comment]
hello ?

**Comment by leonardosnt** [comment]
I have no clue what's going on. 

Does it start without uEssentials?

**Comment by MihailHavenT** [comment]
I know the same , I tried to put the oldest version of uEssentials but NOTHING... If you can investigate the problem ?
I started the server without uEssentials and it does not show this error and without crashing.
