### ISSUE TITLE
/i command (alias /item)

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#78]
Gives me this error when I type into chat /i any_id (meaning /i 100, /i 1, /i 2, /i 3, etc...)
![2016-02-19_00001](https://cloud.githubusercontent.com/assets/1404955/13187131/8e1d9852-d75a-11e5-9eac-3daab44e47c2.jpg)

**Comment by leonardosnt** [comment]
Update your translation (translations/lang_en.json)

**Comment by Daniil1288** [comment]
Thank you very much, everything works as expected now! :)
