### ISSUE TITLE
Kits not working 

### ISSUE THREAD

**Issue by JustCloaked** [uEssentials/uEssentials#781]
Tpa works fine it's just the kits command 

 ```
       <Permission Cooldown="0">essentials.kit.default</Permission>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">home</Permission>
        <Permission Cooldown="0">essentials.kits</Permission>
        <Permission Cooldown="0">essentials.kit</Permission>
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
```

**Comment by leonardosnt** [comment]
It should be `essentials.command.kit` and `essentials.command.kits`. See https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference

**Comment by JustCloaked** [comment]
> It should be `essentials.command.kit` and `essentials.command.kits`. See https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference

I looked at that, and I adjusted the perms and it still doesn't work it just says "You don't have any access to a kit"
`<Permission Cooldown="0">essentials.command.kit.Default</Permission>`
