### ISSUE TITLE
Illegal Analytics and Tracking

### ISSUE THREAD

**Issue by Trojaner** [uEssentials/uEssentials#786]
Your plugin contains analytics code that is not mentioned anywhere and which can not be opted out. There is also no way of consenting. This is illegal and violates data protection laws such as the GDPR. The plugin is tracking information from the server (e.g. server start) as well as from players (when a player joins a server).

Neither the players nor the server owners are notified about this tracking, can consent to it or have any option to opt-out. Aside regulations such as the GDPR, this tracking may additionally violate the Google Analytics Terms of Services. Google has been notified about this.

https://github.com/uEssentials/uEssentials/blob/bc6683fc80cd8e801d32dee6858456fb26e2022f/src/Misc/Analytics.cs
https://github.com/uEssentials/uEssentials/blob/bc6683fc80cd8e801d32dee6858456fb26e2022f/src/Event/Handling/EssentialsEventHandler.cs#L93
https://github.com/uEssentials/uEssentials/blob/bc6683fc80cd8e801d32dee6858456fb26e2022f/src/Core/EssCore.cs#L258

**Comment by XanderCodes** [comment]
I'm surprised it's taken this long for someone to notice. That's stupid.

**Comment by leonardosnt** [comment]
I've added that years ago just to see how many people were using the plugin. Feel free to remove that and open PR if you want.
