### ISSUE TITLE
Question: How do I make a weapon be auto-equipped with a laser?

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#79]
This is a Cobra.
```
      {
        "Ammo": 40,
        "Barrel": {
          "AttachmentId": 7,
          "Durability": 100
        },
        "Sight": {
          "AttachmentId": 1004,
          "Durability": 100
        },
        "Magazine": {
          "AttachmentId": 1006,
          "Durability": 100
        },
        "Id": 99,
        "Durability": 100,
        "Amount": 1
      },
```

I want this Cobra to be equipped with a laser (id: 151), but there's no such thing as "Tactical" (slot, where the laser needs to be equipped), only "Barrel", "Sight" and "Magazine".

How do I make a Cobra with a laser to appear in my kit?

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/Kits-Reference

"The valid attachments are: Barrel, Sight, Tatical, Grip & Magazine"

**Comment by leonardosnt** [comment]
Solved?

**Comment by Daniil1288** [comment]
Yes, thank you ;)

Can you change Tatical to Tactical, though? That's an obvious typo, it's really not intuitive...

**Comment by leonardosnt** [comment]
:+1:

**Comment by Daniil1288** [comment]
Can you please change Tatical to Tactical? :)

**Comment by Daniil1288** [comment]
Oh, nevermind, Tactical works, too...

Sorry :D
