### ISSUE TITLE
Uessentials keep doing announcements in chat like "This is an announcement" or "this is something"

### ISSUE THREAD

**Issue by Radyrm1** [uEssentials/uEssentials#806]
![Unturned Screenshot](https://github.com/uEssentials/uEssentials/assets/138830392/1e3d8192-ca6e-489d-99b6-e779464637ba)

**Comment by Acool79** [comment]
yo did you ever find a fix??

**Comment by Radyrm1** [comment]
> yo did you ever find a fix??

Nope, nothing

**Comment by Box2444** [comment]
for anyone that comes here looking for a fix for this, this is an example announcement from the autoannouncer module, you need to go to the config.json file and look up "announcement" then on that block look for the line that says "enabled:true" and set it to "false"

**Comment by Radyrm1** [comment]
> for anyone that comes here looking for a fix for this, this is an example announcement from the autoannouncer module, you need to go to the config.json file and look up "announcement" then on that block look for the line that says "enabled:true" and set it to "false"

Thanks! it worked :)
