### ISSUE TITLE
Is there any way to give ALL permissions via ONE permission entry, such as "essentials.command.*" or "essentials.command.all"?

### ISSUE THREAD

**Issue by Ejraiel** [uEssentials/uEssentials#82]

**Comment by leonardosnt** [comment]
Added :D

If you like this project do not forget to leave your star :D

**Comment by Ejraiel** [comment]
hehe, just joined github to open issues on this and the deathmessage plugins; now that i know what a star means, you have my very first one ;]

**Comment by leonardosnt** [comment]
Oh, thanks :D

**Comment by Ejraiel** [comment]
by the way, what is the new permission?

i don't see it on the wiki permissions reference.

**Comment by leonardosnt** [comment]
essentials.command.*

**Comment by Ejraiel** [comment]
aha.  thanks.  =]

**Comment by Ejraiel** [comment]
would be nice to add that for warps as well, if you haven't already ;D

**Comment by leonardosnt** [comment]
it work it warps & kits

**Comment by Ejraiel** [comment]
awesome.  thanks again.  ^_^
