### ISSUE TITLE
Suggestion: The itemfeature to repair suppressors as well

### ISSUE THREAD

**Issue by ShizzlePants** [uEssentials/uEssentials#85]
I've been trying out the itemfeature command and saw it repairs and reloads items whilst using them. However, in recent updates, suppressors have durability when used. Could you make it possible to repair suppressors with this command also? Or maybe a new command. Thanks for making such a cool plugin - Shizzle

**Comment by leonardosnt** [comment]
Added :D

If you like this project do not forget to leave your star :D

**Comment by ShizzlePants** [comment]
Cheers mate, I'll update my plugin now. Absolutely fantastic!
- Shizzle
