### ISSUE TITLE
Spawn Ammo 

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [uEssentials/uEssentials#86]
Entering the command /i and other Id 43-44 ammo I was faced with such a problem that the number of cartridges and boxes of ammunition exactly 1

I need the full amount in the holder and the boxes of ammunition

**Comment by Daniil1288** [comment]
Dunno, gives me 40 ammo...

Btw, if you want ammo boxes to give you 40 ammo in kits, specify "Ammo": 40/any value up to 255... Just some friendly advice :)

But yep, I am not able to customize ammo amount while using the command /i neither.

**Comment by ZSHADOWWOLF** [comment]
I want it in the game spawn! Why need to touch this setting by adding Plugin?

**Comment by WGSRangerWolf** [comment]
@ZSHADOWWOLF /ckit :smile:

**Comment by leonardosnt** [comment]
@ZSHADOWWOLF You can get the kit and execute /createkit, it will create a kit with itens that is in your inventory. EASILY.

**Comment by Punky69** [comment]
turn of uessentinales /i command and use bukkit /i it willl give you full ammo box

**Comment by leonardosnt** [comment]
It already fixed. Update your uEssentials to latest version;
