### ISSUE TITLE
itemfeatures & repair bugs.

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#87]
ITEM FEATURES:

1) autoreload doesn't work on rocket launchers; bows; crossbows. Anything that has a temporary mag that will be gone after you shoot (possibly because there is no mag present after you fire?). Results in ammo being 50/0

1.1) If there is no mag in a weapon, then autoreload doesn't work. Ammo becomes 50/0 (0 because no mag, and I don't know why it puts primary ammo at 50)

2) You need to shoot all ammo out for autoreload to work for Eaglefire and other submachine guns/assault rifles/pistols/etc, meaning that if you had 100 ammo you need to shoot all 100 bullets out for autoreload to trigger. (For shotguns - I tested Bluntforce. You only need to shoot 4/8 bullets out.)

3) autorepair doesn't repair suppressors.

REPAIR:

1) Doesn't repair suppressors on any weapons.

----------------------------------------------------------------------------------------------------------------------------------

Please fix :)

**Comment by leonardosnt** [comment]
i know

**Comment by Daniil1288** [comment]
alright then :D

**Comment by leonardosnt** [comment]
WOW autoreload with Rocket Laucher is SOO OP!!!

**Comment by Daniil1288** [comment]
Did you fix it somehow? O_O

**Comment by leonardosnt** [comment]
Yep...

**Comment by Daniil1288** [comment]
Woah. I am definitely looking forward to the next version, then! :D

(way too excited to express this feeling in text :O)

**Comment by leonardosnt** [comment]
1) fixed

1.1) fixed

2) fixed

3) I will fix now.

1) fixed

**Comment by Daniil1288** [comment]
Wow, Leo, you're so fast at fixing things! :D

By the way, I think that autoreload worked with shadowstalkers... But it was buggy: sometimes it worked, sometimes it didn't. It was bows, crossbows and rocket launchers that didn't work at all with autoreload... 

Thank you SO MUCH for fixing all these nasty bugs! :+1:

**Comment by leonardosnt** [comment]
:D
