### ISSUE TITLE
Question: no error output

### ISSUE THREAD

**Issue by Daniil1288** [uEssentials/uEssentials#90]
When I execute a non-existent command, say, /id from the game's chat, I see a red question mark in my console, but nothing in chat. Therefore, I can't be sure if the command did anything at all.

See, if I execute /vehicle dan/92, then it writes in console: "Successfully gave Daniil1288 92!" and a plane appears, but I still see nothing in my server's chat in-game. If I executed /vehicle dan/200, then nothing would've happened and there would've been no error message in my chat at all... (There would be one in my console, though.)

**Comment by leonardosnt** [comment]
what

**Comment by Daniil1288** [comment]
I want to know when I got something wrong. Like I said, when an ID doesn't exist (be that a weapon, a vehicle or anything else), I have to check the console in order to see what I got wrong: the command (misspelling it) or the ID. (I may write /vehicl instead of /vehicle, or /vehicle 92 dan instead of /vehicle 92/dan; /vehicle wrong_id right_player or /vehicle right_id wrong_player. etc etc etc.)

Would be nice to get notified if I get something wrong in chat, and not only in console.

(That would be really useful if any of my fellow friends get a command wrong somehow. Then they would get notified in chat instead of me having to check the console each time)

**Comment by leonardosnt** [comment]
All my commands say if something went wrong...

**Comment by Daniil1288** [comment]
Oh, so it's related to Rocket? I thought that uEssentials replaced that command. Is there any way I could see if something went wrong in chat, and not only in console?

**Comment by leonardosnt** [comment]
Pooooor english coming...

Nope, i will try to send the "unknown command" message if command does not exist.

He already send the "unknown message" but only for normal players (isn't admin)

**Comment by Daniil1288** [comment]
Oh, so if I wasn't an admin (same for my friends), then I (we) would get errors in chat (not only in console)? If normal players had access to the command /v or /vehicle, etc. of course.

(My english isn't perfect at all neither :D)

**Comment by Daniil1288** [comment]
Interesting...

If I execute /v 92, then I get a message in chat.
If I execute /v 200, I get:

[2/20/2016 11:55:31 PM] [Error] An error occured while executing v [200]: System.NullReferenceException: Object reference not set to an instance of an object
  at Rocket.Unturned.Commands.CommandV.Execute (IRocketPlayer caller, System.String[] command) [0x00000] in <filename unknown>:0 
  at Rocket.Core.Commands.RocketCommandManager.Execute (IRocketPlayer player, System.String command) [0x00000] in <filename unknown>:0

If I execute /vehicle dan/92, I get a message in the console, not in the chat
If I execute /vehicle dan/invalid_id (say, 2000), I get an error in the console, still not in the chat.

Hmmm... why does /v give me a message in the chat, but /vehicle doesn't?

**Comment by leonardosnt** [comment]
I already said that /v is ROCKET command.

And, if you isn't an admin and execute an non-existent command he will send "This command does not exist" or something like that.

**Comment by Daniil1288** [comment]
Oh well... So, there's actually no way for me to see all the errors that Rocket commands produce if I'm an admin? (And get something wrong, of course :P)

**Comment by Daniil1288** [comment]
Sorry for taking so much of your time, by the way... :D

**Comment by Daniil1288** [comment]
It's okay, I'm not in a hurry :D I just thought that I was too annoying :)

**Comment by WGSRangerWolf** [comment]
we arn't having an issue with our Vehicle command can ya add me on steam?

**Comment by WGSRangerWolf** [comment]
http://steamcommunity.com/profiles/76561198067704805/

**Comment by Daniil1288** [comment]
added

**Comment by Daniil1288** [comment]
You need to add a translation file (or an entry) for this error...

[2/21/2016 2:03:24 AM] [Error] An error occured while executing v [200]: System.NullReferenceException: Object reference not set to an instance of an object
  at Rocket.Unturned.Commands.CommandV.Execute (IRocketPlayer caller, System.String[] command) [0x00000] in <filename unknown>:0 
  at Rocket.Core.Commands.RocketCommandManager.Execute (IRocketPlayer player, System.String command) [0x00000] in <filename unknown>:0

**Comment by WGSRangerWolf** [comment]
Did u code a /v command?

**Comment by WGSRangerWolf** [comment]
Closed as I talked to him on steam
