### ISSUE TITLE
Vehicle command

### ISSUE THREAD

**Issue by WGSRangerWolf** [uEssentials/uEssentials#95]
essentials command like /v all <id>
Would need to remove spawnvehicle tho.

**Comment by Ejraiel** [comment]
Do you mean spawning or deleting vehicles?

**Comment by WGSRangerWolf** [comment]
yeah but it isnt managed by rocket

**Comment by Ejraiel** [comment]
...what?

Sounds like you're talking to someone else.

Didn't answer the question, and responded to something different. xD

Here, have more :beers:!

**Comment by WGSRangerWolf** [comment]
spawning lol.

**Comment by Ejraiel** [comment]
Hmm.

So are you wanting a command to spawn all possible vehicles near your location, or a command to respawn vehicles from map spawnpoints?

If the latter, he added https://github.com/uEssentials/uEssentials/issues/101 =]

**Comment by WGSRangerWolf** [comment]
noooooooo the command would be like the rocketmod vehicle command.




*Have a amazing day,*

*Derrick McLean* (formaly known as waspgod, Rangerwolf)
