### ISSUE TITLE
LPX

### ISSUE THREAD

**Issue by JustOneMoreBlock** [uEssentials/uEssentials#96]
I remember you guys added support for LPX. However, there maybe still an issue.

Currently, I don't use LPX permissions and prefer the WebPermissions system. Therefore, I believe I disabled that portion. However, they're maybe a bug on that point and I've already reached out over on their GitHub in regards to that issue.

Now when Adding LPX to my server and disabled their permissions. The web permissions seem to work fine for the most part.

After adding uEssentials, the WebPermissions are completely disabled. However, I'm not using LPX permissions either. At this point, they're no permissions.

Removing: LPX fixes this issue.
or
Removing: uEssentials fixes this issue.

Kind Regards,
Cory

**Comment by leonardosnt** [comment]
How work this "WebPermissions"?

**Comment by JustOneMoreBlock** [comment]
It's Rockets built-in WebPermissions system. You provide a URL in the Rocket config and updates. My URL connects to my website which automatically provides permissions for staff and donators.

I would like to use LPX because of the Vehicle Lock System. However, if this was added #97 and likely if your kits then I could remove LPX altogether.

Although, there might be still some underlying issues in regards to my previous post.

Testing LPX with no uEssentials - WebPermissions Work.
Testing uEssentials with no LPX - WebPermissions Work.
Testing uEssentials with LPX - WebPermissions Break.

However, LPX permissions are disabled. This could be an issue on their end.
https://github.com/lightphoenix2/LPX/issues/11

**Comment by axiomaticTwist** [comment]
I would HIGHLY recommend switching all to just LPX. I don't understand why you wouldn't use LPX without using its permission plugin.

**Comment by JustOneMoreBlock** [comment]
Simply because I automate ranks using the WebPermissions system that connects from my forums.

Website -> Forums -> Upgrade System -> Custom Script, I wrote to output XML -> Rocket WebPermissions System uses a URL and automatically updates.

I mean likely the same could be done, but this works.

**Comment by WGSRangerWolf** [comment]
Is this still an issue? or does OP have anything else about this before i close this?

**Comment by JustOneMoreBlock** [comment]
Basically, with uEssentials and LPX it causes my Web Permissions to be disabled.
http://i.imgur.com/efzWr8d.jpg

- If I have just LPX the Web Permissions work fine.
- If I have just uEssentials the Web Permissions work fine.

In LPX they do have this option:
`  <LPXEnabled>true</LPXEnabled>`

Which I disable as I don't want to use their permissions.
`  <LPXEnabled>false</LPXEnabled>`

I'm sure there might be an issue on someones plugin.

**Comment by WGSRangerWolf** [comment]
ok

**Comment by leonardosnt** [comment]
@JustOneMoreBlock You having this issue yet?

**Comment by JustOneMoreBlock** [comment]
@leonardosnt Well, I've been testing on a test server and I cannot migrate over until it's fixed. :(

Confirmed it still happens on latest builds.
