### ISSUE TITLE
Vehicle Lock

### ISSUE THREAD

**Issue by JustOneMoreBlock** [uEssentials/uEssentials#97]
Pretty much want the same thing in LIGHT (LPX).

Car Commands:

```
/buyv <Car No>
/car refuel <amount or full>
/car repair
/car lock
/car unlock
/car key <Car No> <Player Name>
/car locate <Car No>
```

```
“/car lock”  Locks your car preventing people from entering. You must be in your vehicle to use this.
“/car unlock” Unlocks your vehicle, allowing people to enter and drive. You must be in your vehicle to use this.
“/car key <car no> <player name> Gives the player access to your vehicle
“/car locate <car no> Give you the X, Y Z location of the vehicle. And if it is in Water or Driven.
FuelPrice – Default: 1.3, 0 = Disable. It is calculated per Liters, it is not calculated by percentage. A full tank from 0% to 100% will cost around 180 Credit.
RepairPrice - Default: 2 0 = Disable. It is calculated based damage and will repair in full and remove that amount from your account.
```

^Same Features

Source: https://dev.rocketmod.net/?rplugin=light

**Missing:**
Configuration option to make vehicle licenses not required in order to drive a non-owned/non-licensed vehicle.
So that the license is optional if the player wants their vehicle protected from theft.

Granted there plugin is fine and if this isn't added. Then I'll use there's, after all the issues have been resolved from permission issues.

Using WebPermissions

**Comment by JustOneMoreBlock** [comment]
This should also be noted of issues of the current Car plugin:
https://github.com/lightphoenix2/LPX/issues/23

**Comment by leonardosnt** [comment]
I'll close this, since Unturned has this feature.
