### ISSUE TITLE
Database Support

### ISSUE THREAD

**Issue by JustOneMoreBlock** [uEssentials/uEssentials#98]
Hello,

Are you planning for MySQL Database support? As it would a great feature added specifically for like kits and global settings as uEssentials would be used globally.

If so, could add a few things, to this or create individual options for the plugin.

Also, great job so far on the plugin! and you're using JSON! Good I hate XML! :)

Kind Regards,
Cory

**Comment by WGSRangerWolf** [comment]
Add an option to use web permissions or MySQL Cause my servers don't run MySQL.
But have it disabled by default

**Comment by JustOneMoreBlock** [comment]
That's actually completely opposite of what I want.

I want to continue using WebPermissions as I have it connected with my forums an easy and automated upgrades.

However, certain aspects of the plugin should have database support.

- Global Settings (Maybe)
- Kits
- Mute (Users Muted)

New Additions:
- Vehicle Lock System
- Ban System
- Warning System
- Whitelist System

**Comment by leonardosnt** [comment]
Database for kids, configuration? I do not think it's necessary.

**Comment by JustOneMoreBlock** [comment]
When I have 22 servers for Unturned and maybe necessary. However, I did say maybe. It's not required specifically. However, things that are are the same for all servers and won't change should have database support.

For example, If a player is being unruly in chat and should be muted. They should be muted on all servers and the specific server, a way to do this is with MySQL support.

**Comment by leonardosnt** [comment]
I've add the webConfig & webKits, I will not add mysql for kit/config since i added webConfig/Kits
