### ISSUE TITLE
when you hold a umbrella with /if autorepair on, on it spams console with errors

### ISSUE THREAD

**Issue by sharkbound** [uEssentials/uEssentials#99]
if you equip a umbrella when you have the item autorepair in it spams console with errors while its in hand. with autorepair disabled its doesnt do this

**Comment by leonardosnt** [comment]
update

**Comment by leonardosnt** [comment]
i already fixed this, it will be added in next release, stay tuned.

**Comment by leonardosnt** [comment]
#93

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/releases/tag/1.1.2.1

If you like this project do not forget to leave your star :D
